### ISSUE TITLE
bug: Schedule Scan Not Working

### ISSUE THREAD

**Issue by bagialuudan** [yogeshojha/rengine#1013]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Funtion: Schedule Scan is error 500

**Comment by AnonymousWP** [comment]
Update reNgine (a lot of error 500's got fixed by Psyray). If that doesn't help, use my [fork](https://github.com/AnonymousWP/rengine).

**Comment by S3ntago** [comment]
Schedule scan is not working even with your fork, the page is loading yes without error 500, but the scan engine it self doesn't work @AnonymousWP

**Comment by psyray** [comment]
I'll close this, as 500 error have been fixed, we continue on #1015
