### ISSUE TITLE
Some help in fixing that error in Mac would be appreciated

### ISSUE THREAD

**Issue by Teicu** [yogeshojha/rengine#1014]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml build db web proxy redis celery celery-beat
[+] Building 0.5s (2/3)                                                                                                 docker:desktop-linux
[+] Building 0.6s (3/3) FINISHED                                                                                        docker:desktop-linux
 => [celery internal] load .dockerignore                                                                                                0.0s
 => => transferring context: 2B                                                                                                         0.0s
 => [celery internal] load build definition from Dockerfile                                                                             0.0s
 => => transferring dockerfile: 3.43kB                                                                                                  0.0s
 => ERROR [celery internal] load metadata for docker.io/library/ubuntu:22.04                                                            0.6s
------
 > [celery internal] load metadata for docker.io/library/ubuntu:22.04:
------
failed to solve: ubuntu:22.04: error getting credentials - err: exit status 1, out: ``
make: *** [build] Error 17

reNgine installation failed!!

### Expected Behavior

Some help in fixing that error in Mac would be appreciated

### Steps To Reproduce

sudo make build

### Environment

```markdown
- reNgine: v2.0.0-jasper
- OS: Apple M2 Max
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

no

**Comment by AnonymousWP** [comment]
So you create an issue, just so that you can close it again? 🤨

**Comment by Teicu** [comment]
already fixed that one, sorry. But now I have another one  

sudo make up
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml up -d --build db web proxy redis celery celery-beat
2023/10/24 11:17:44 must use ASL logging (which requires CGO) if running as root
2023/10/24 11:17:44 must use ASL logging (which requires CGO) if running as root
2023/10/24 11:17:44 must use ASL logging (which requires CGO) if running as root
[+] Running 0/0
 ⠋ proxy Pulling                                                                                                                                     0.0s 
 ⠋ redis Pulling                                                                                                                                     0.0s 
 ⠋ db Pulling                                                                                                                                        0.0s 
error getting credentials - err: exit status 1, out: ``
make: *** [up] Error 1

**Comment by Teicu** [comment]
> So you create an issue, just so that you can close it again? 🤨

do you think you can help me? thank you
