### ISSUE TITLE
bug: Subdomain Scan Fails with [Error: AttributeError("'NoneType' object has no attribute 'name'")]

### ISSUE THREAD

**Issue by S3ntago** [yogeshojha/rengine#1016]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I have noticed that during a Subdomain Enumeration only scan I get for many times Scan Failed with error: `AttributeError("'NoneType' object has no attribute 'name'")` as shown below:
![image](https://github.com/yogeshojha/rengine/assets/48615614/e50ddbc2-2fb7-49c6-9a4e-fc1dfe52871a)

Kindly note that this error happens randomly, so I can have multiple successful scans, then I get this error for specific domains.

### Expected Behavior

-

### Steps To Reproduce

-

### Environment

```markdown
- reNgine: 2.0.1
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by S3ntago** [comment]
More screenshots for troubleshooting:
![image](https://github.com/yogeshojha/rengine/assets/48615614/de8ab04c-ac3c-48fd-80af-bf85b7d7cae4)

![image](https://github.com/yogeshojha/rengine/assets/48615614/eeec1743-6e2e-495e-84ed-96f230cec9fb)

**Comment by psyray** [comment]
Your subdomain is not good : **TRAVELOCITY.COM LP**
