### ISSUE TITLE
Feature - Github Subdomains/Endpoints

### ISSUE THREAD

**Issue by uBadRequest** [yogeshojha/rengine#102]
**Is your feature request related to a problem? Please describe.**
Github can contain subdomains and endpoints that can't be found anywhere else.

**Describe the solution you'd like**
There are a number of tools that implement the ability to search Github for endpoints/subdomains such as https://github.com/gwen001/github-search

Also, you may need to provide the ability to add github tokens/API keys to other tools from the GUI.

**Comment by thezoomerhacker** [comment]
The nuclei team has recently implemented @gwen001 tools into their pipeline. Since this tool uses subfinder, subdomains are already being pulled from github if the `~/.config/subfinder/config.yaml` file is correctly set up

**Comment by attacker007** [comment]
Hi @thezoomerhacker there are tools like which needs to be integrated. 

```
https://github.com/Edu4rdSHL/findomain
https://github.com/Screetsec/Sudomy

```

**Comment by thezoomerhacker** [comment]
Hi @attacker007 , I think I missed the point of your reply. This thread is requesting github implementation for subdomain enum + endpoint discovery.

**Comment by attacker007** [comment]
Hi @thezoomerhacker  I've just given information about subdomain enum tools which need to be integrated...

**Comment by thezoomerhacker** [comment]
Got it. I think for that you can open a new thread on the issues page and mark it as "feature"

**Comment by yogeshojha** [comment]
@attacker007 Oneforall is implemented!

**Comment by yogeshojha** [comment]
I have announced bounty for finddomain and given instructions on how to implement. Let's wait until somebody sends a PR :smile:

**Comment by psyray** [comment]
@yogeshojha 
Does this tools still relevant ?
