### ISSUE TITLE
bug: Security Reporting not working

### ISSUE THREAD

**Issue by sectheops** [yogeshojha/rengine#1024]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Not able to submit security report on huntr.dev.

![issue](https://github.com/yogeshojha/rengine/assets/139357653/ae3ed937-7fe2-4ac6-909c-0805b753ebb6)

### Expected Behavior

Should be able to submit security report.

### Steps To Reproduce

Go to huntr.dev for the page for this repo and notice it is not loading.

### Environment

```markdown
- reNgine: N/a
- OS: N/a
- Python: N/a
- Docker Engine: N/a
- Docker Compose: N/a
- Browser: N/a
```

**Comment by psyray** [comment]
@yogeshojha Why is it not working ?

**Comment by Xistens** [comment]
Any updates on this? It is still not possible to report security related issues

**Comment by psyray** [comment]
> Any updates on this? It is still not possible to report security related issues

No update, sorry, only @yogeshojha could do this

**Comment by yogeshojha** [comment]
This is been updated now with github security.
