### ISSUE TITLE
feat: <added api key telegram impossible 500 error>

### ISSUE THREAD

**Issue by ByteNight60** [yogeshojha/rengine#1025]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

hello guys,
when i added api key telegram i get un error 500 i dont not why can you help me please thanks.

**Comment by yogeshojha** [comment]
Hi @ByteNight60 I added a telegram key just now on v2.0.1 and works as expected. 
![image](https://github.com/yogeshojha/rengine/assets/17223002/3960510f-b861-41da-9d39-13cc956b9c09)


Please provide more info

**Comment by psyray** [comment]
@ByteNight60 
Check again and open a new issue if it persists
