### ISSUE TITLE
bug: Server Error (500) after updating to version 2.

### ISSUE THREAD

**Issue by UbaidAhmed2803** [yogeshojha/rengine#1026]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I have started to get Server Error (500) after updating to version v2.0.1 

After updating my rengine, I was asked to create a project. A new URL was created for me in the following format:

https://{IP}/myproject/dashboard

Since then after login, I am redirected to the above URL where I get to see Server Error(500). I also checked the logs and I observed the following:

```
tpasm-db-1           | 2023-10-31 04:34:12.221 UTC [59] ERROR:  column targetApp_domain.project_id does not exist at character 60
tpasm-db-1           | 2023-10-31 04:34:12.221 UTC [59] STATEMENT:  SELECT COUNT(*) AS "__count" FROM "targetApp_domain" WHERE "targetApp_domain"."project_id" = 1
```

### Expected Behavior

I should be able to access the dashboard

### Steps To Reproduce

No specific steps as such. I just updated the rengine version to v2.0.1

### Environment

```markdown
- reNgine: v2.0.1
- OS: Ubuntu 20.04.4 LTS
- Python: 3.8.10
- Docker Engine: 20.10.17, build 100c701
- Docker Compose: v2.6.0
- Browser: Google Chrome [Version 118.0.5993.117 (Official Build) (arm64)]
```

**Comment by ved009** [comment]
I am also facing the same issue. Did you came up with any work around?

**Comment by foozzi** [comment]
it's just as bad as it was before,
I really don't know why you are using it :)

**Comment by yogeshojha** [comment]
@UbaidAhmed2803 This is weird, because if you had just updated, you shouldn't have been asked to create project because I assume project was already there. 

this is the code from dashboard redirection

```python
projects = Project.objects.all()

    if len(projects):
        slug = projects[0].slug
        return HttpResponseRedirect(reverse('dashboardIndex', kwargs={'slug': slug}))

    return render(request, 'dashboard/onboarding.html', context)
```

If you see project if exists then will be redirected to dashboardIndex otherwise onboarding page.
