### ISSUE TITLE
bug: Interesting Lookup do not accept new values

### ISSUE THREAD

**Issue by carboncrystal** [yogeshojha/rengine#1027]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Menu Scan Engine > Interesting Lookup > do not accept new values.
Error is: Press comma , to separate the keywords.

### Expected Behavior

Add new desired values in Interesting Lookup

### Steps To Reproduce

Try to add new values in menu: Scan Engine > Interesting Lookup

### Environment

```markdown
- reNgine: 2.01
- OS: Ubuntu 22.04.3 LTS
- Python: 3.10.12
- Docker Engine: 24.0.7, build afdd53b
- Docker Compose: v2.5.0
- Browser: Firefox
```

### Anything else?

![Screenshot from 2023-10-31 08-00-54](https://github.com/yogeshojha/rengine/assets/106466414/e031efb3-2250-4598-9933-d1db8815a387)

**Comment by yogeshojha** [comment]
Hi @carboncrystal oops sorry :D that is not an error, I changed the font color to gray. that was just an message. Your interesting lookup keyword is saved already.
