### ISSUE TITLE
bug: Server Error 500 when a user is created using the Admin Settings feature (web interface) tries to access a Target Summary page.

### ISSUE THREAD

**Issue by bry-n** [yogeshojha/rengine#1030]
Server Error 500 when a user is created using the Admin Settings feature (web interface) tries to access a Target Summary page from Targets -> Target Summary.

Rengine build environment: Digital Ocean VPS

Steps to reproduce:

1. Using the main account (first account created) created during the build process (rengine cmdline tool).  Create a new user in Admin Settings. 
2. Give this user "sys admin" role.
3. Log into VPS Rengine instance using this new test user.
4. Access Targets -> Target Summary.  Add a target if there are none. Does not need to be previously scanned.
5. A Server Error 500 is displayed instead of the Target Summary page.

This activity appears to only occur  when using accounts created using Admin Settings. When using the main or first created account the Server Error 500 does not occur.

Logs reflect the server error 500.
![image](https://github.com/yogeshojha/rengine/assets/6549522/3fe382c9-05db-4a40-8f97-aee986adb901)

**Comment by bry-n** [comment]
added bug:

**Comment by psyray** [comment]
Use this https://github.com/yogeshojha/rengine/pull/994#issue-1949670614 and update with a more detailed error

**Comment by bry-n** [comment]
As requested:

Using the URLconf defined in reNgine.urls, Django tried these URL patterns, in this order:

^swagger(?P<format>\.json|\.yaml)$ [name='schema-json']
^swagger/$ [name='schema-swagger-ui']
admin/
[name='onboarding']
<slug:slug>/dashboard/ [name='dashboardIndex']
<slug:slug>/profile/ [name='profile']
<slug:slug>/admin_interface/ [name='admin_interface']
<slug:slug>/admin_interface/update [name='admin_interface_update']
<slug:slug>/search [name='search']
404/ [name='four_oh_four']
<slug:slug>/projects/ [name='list_projects']
delete/project/<int:id> [name='delete_project']
target/ [name='targetIndex']
target/ <slug:slug>/add/target [name='add_target']
target/ <slug:slug>/add/organization [name='add_organization']
target/ <slug:slug>/update/target/<int:id> [name='update_target']
target/ <slug:slug>/update/organization/<int:id> [name='update_organization']
target/ <slug:slug>/list/target [name='list_target']
target/ <slug:slug>/list/organization [name='list_organization']
target/ delete/target/<int:id> [name='delete_target']
target/ delete/organization/<int:id> [name='delete_organization']
target/ <slug:slug>/delete/multiple [name='delete_multiple_targets']
target/ <slug:slug>/summary/<int:id> [name='target_summary']
scanEngine/
scan/
recon_note/
login/ [name='login']
logout/ [name='logout']
api/
^media/(?P<path>.*)$
^staticfiles/(?P<path>.*)$
The current path, target/summary/18, didn’t match any of these.
![rengine_redacted](https://github.com/yogeshojha/rengine/assets/6549522/db9fc263-ad50-4f0d-8d31-ef6495c91435)

**Comment by bry-n** [comment]
Using the URLconf defined in reNgine.urls, Django tried these URL patterns, in this order:

^swagger(?P<format>\.json|\.yaml)$ [name='schema-json']
^swagger/$ [name='schema-swagger-ui']
admin/
[name='onboarding']
<slug:slug>/dashboard/ [name='dashboardIndex']
<slug:slug>/profile/ [name='profile']
<slug:slug>/admin_interface/ [name='admin_interface']
<slug:slug>/admin_interface/update [name='admin_interface_update']
<slug:slug>/search [name='search']
404/ [name='four_oh_four']
<slug:slug>/projects/ [name='list_projects']
delete/project/<int:id> [name='delete_project']
target/ [name='targetIndex']
target/ <slug:slug>/add/target [name='add_target']
target/ <slug:slug>/add/organization [name='add_organization']
target/ <slug:slug>/update/target/<int:id> [name='update_target']
target/ <slug:slug>/update/organization/<int:id> [name='update_organization']
target/ <slug:slug>/list/target [name='list_target']
target/ <slug:slug>/list/organization [name='list_organization']
target/ delete/target/<int:id> [name='delete_target']
target/ delete/organization/<int:id> [name='delete_organization']
target/ <slug:slug>/delete/multiple [name='delete_multiple_targets']
target/ <slug:slug>/summary/<int:id> [name='target_summary']
scanEngine/
scan/
recon_note/
login/ [name='login']
logout/ [name='logout']
api/
^media/(?P<path>.*)$
^staticfiles/(?P<path>.*)$
The current path, target/summary/18, didn’t match any of these.
![rengine_redacted](https://github.com/yogeshojha/rengine/assets/6549522/f5cb8dd2-47a4-4ae5-bc7c-40a5361336f3)

**Comment by ved009** [comment]
I am almost facing the same error on my Raspberry pi instance. I updated it from 1.1 , the initial interface came up where we have to enter the keys, after doing that it is showing 500 error.

**Comment by yogeshojha** [comment]
@ved009 rengine 1.1 is not compatible with 2.0! You will need to fresh install as with every major release.

**Comment by yogeshojha** [comment]
@bry-n likely there is missing slug in my code, mind sharing the logs?

**Comment by bry-n** [comment]
@yogeshojha sure no problem.  Let me know if you need anything else.
![rengine_debug_logs](https://github.com/yogeshojha/rengine/assets/6549522/b9f3f0e5-69ce-446f-a6c9-63be42544c94)

**Comment by psyray** [comment]
@bry-n Thanks for your quality issue 👍 
Fixed with #1123
