### ISSUE TITLE
./install.sh error. - [Makefile:25: build] Error 17  reNgine installation failed!!

### ISSUE THREAD

**Issue by TofuWand** [yogeshojha/rengine#1033]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I get this while doing the ./install.sh script:
failed to solve: executor failed running [/bin/sh -c go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 1
make: *** [Makefile:25: build] Error 17

reNgine installation failed!!

### Expected Behavior

To install correctly. lolol

### Steps To Reproduce

cd rengine
./install.sh

### Environment

```markdown
- reNgine: Latest.
- OS: Kali.
- Python: Latest.
- Docker Engine: Last.
- Docker Compose: Latest.
- Browser: N/A.
```

**Comment by ved009** [comment]
In your Docker file, make nuclei installation url from v2 to v3, it will work

**Comment by TofuWand** [comment]
> In your Docker file, make nuclei installation url from v2 to v3, it will work

Thanks a bunch! I'll try it tomorrow. :3 <3

**Comment by TofuWand** [comment]
> In your Docker file, make nuclei installation url from v2 to v3, it will work

I didn't see Nuclei with any versions in any Docker file, but I did change the Docker Compose from 2.5.0 to 3, and that fixed the issue. However, it said to fix issues by running Manage.py for it to work properly, but that file doesn't exist. It loaded up in the browser, but I didn't see to add domains/subdomains, etc. I'll continue working on it tomorrow.
