### ISSUE TITLE
Scanning Issue

### ISSUE THREAD

**Issue by ShakeelPK** [yogeshojha/rengine#1034]
Dear whenever I run the full it's discover the subdomain rest of other scan is rejected not complete.

I already try to update the tools which you add but still not work.

Kindly let me know how to fix this issue.

**Comment by iwm911** [comment]
Same here

**Comment by smaranchand** [comment]
Same here, looking for the solution.

**Comment by yogeshojha** [comment]
Hi @smaranchand @ShakeelPK can you plz attach screenshot, or in which module it is stuck?

**Comment by ShakeelPK** [comment]
Here is the screenshot
![image-2.png](https://github.com/yogeshojha/rengine/assets/83941561/0147b5b3-05fa-4722-85fc-a599a0b24e6b)

Unapplied migration

After running the python & python3 manage.py then this:
![image-3.png](https://github.com/yogeshojha/rengine/assets/83941561/83d2a25a-dcf8-4042-8049-6737efc3f4a4)

But still scanning the sub domain not endpoint or other scan..

OS: Ubuntu 20:04LTS
Digital Ocean

**Comment by psyray** [comment]
Update httpx in Tools Arsenal.
I'll have the same problem yesterday.
It's always good to look at the make logs output when running reNgine.
And to debug, you could launch command given by the log output directly inside the celery container to look for error.

**Comment by psyray** [comment]
I'll close this issue, we can continue on this one #1037
