### ISSUE TITLE
bug: Scan doesn't completes.

### ISSUE THREAD

**Issue by smaranchand** [yogeshojha/rengine#1037]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

The scan never yields any results like live URLs, screenshots, vulnerability scan, etc.
I suspect it is due to an update in the httpx tool.

### Expected Behavior

The scan should complete and provide results.

### Steps To Reproduce

1. Deploy ReNgine 
2. Scan any domain
3. You will receive information about discovered subdomains only in the full scan.
4. Other scan results like live subdomain discovery, URLs, Vulnerability scans, and screenshots will not appear in the dashboard.

### Environment

```markdown
- reNgine: reNgine 2.0-jasper
- OS: amzn2023.x86_6
- Python: Python 3.9.16
- Docker Engine: Docker version 24.0.5, build ced0996
- Docker Compose: Docker Compose version v2.5.0
- Browser: Firefox
```

**Comment by psyray** [comment]
I have the same problem on a fresh install.
Did you have update httpx to 1.3.7 (look for version in Tool Arsenal) ?
Because it seems the `-asn` parameter is causing problem.
And scan couldn't start if there is no endpoints.
And it's httpx that is the source of endpoints findings

**Comment by smaranchand** [comment]
I just did a fresh installation, The issue still persists, I cannot complete the scan.

Regards,
Smaran

**Comment by psyray** [comment]
> I just did a fresh installation, The issue still persists, I cannot complete the scan.
> 
> Regards, Smaran

A fresh install put buggy HTTPx 1.3.6 again.
You need to update.
A [PR](https://github.com/yogeshojha/rengine/pull/1055) is on his way for this bug and fix will be available in the next release
