### ISSUE TITLE
bug: <Not found IP after scan>

### ISSUE THREAD

**Issue by bagialuudan** [yogeshojha/rengine#1057]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

- After scan,  in Detail Scan will display list IP Address
-  Two weeks ago in the detail scan there were some Vulnerabilities about Low and Unknown

### Expected Behavior

- Now, after scan, not see list IP Address and some Vulnerabilities about Low and Unknown, Although I haven't fixed these vuls yet
- Time scan so fast, Normally the test will take more than 1 hour but now it only takes 6 minutes

### Steps To Reproduce

1h...

### Environment

```markdown
- reNgine: 2.0.1
- OS: Ubuntu
- Python: 3.8
- Docker Engine:  20.10.2
- Docker Compose: 1.25
- Browser: ..
```

**Comment by psyray** [comment]
Upgrade HTTPx in the tools arsenal, PR is on his way
https://github.com/yogeshojha/rengine/issues/1057

**Comment by bagialuudan** [comment]
> Upgrade HTTPx

I updated, but it not change

**Comment by AnonymousWP** [comment]
I think this is fixed by this specific PR: https://github.com/yogeshojha/rengine/pull/1058

**Comment by psyray** [comment]
> > Upgrade HTTPx
> 
> I updated, but it not change

We need more information (screenshot, console log ...)

**Comment by psyray** [comment]
@bagialuudan Feedback ?

**Comment by psyray** [comment]
@bagialuudan 
No feedback for 2 month closing issue
Feel free to open a new issue if problem persist
