### ISSUE TITLE
Feature - Amass config, Subdomainizer & ParamSpider

### ISSUE THREAD

**Issue by JoshuaMart** [yogeshojha/rengine#106]
Hi,
Thanks for your tool, great job, I had started something similar but what you have done is really clean / functional.

I offer you some suggestions in addition to what others have already asked for (especially GF & Nuclei & github-subdomains.py)

- The ability to add an Amass config file, the detection power of the tool lies in the use of this file which allows to search for subdomains on services requiring API keys (like SecurityTrails which is a musthave).
  - The file in question : [https://raw.githubusercontent.com/OWASP/Amass/master/examples/config.ini](https://raw.githubusercontent.com/OWASP/Amass/master/examples/config.ini)
  -  Also used the possibility of bruteforce subdomains with Amass via `-brute` options
  - Possibly, via Amass (`-dir` options) or manually by coupling the output of the different tools, to have alerts on sub-domain differences between two scans

All these things can be done with the following command from Amass  : 
`amass enum -active -o results.txt -d domain.tld -brute -w wordlist.txt -config config.ini -dir aDirectory`

The difference between two scans via Amass can then be found with the following command: 
```bash
amass track -d $DOMAIN -dir aDirectory | grep 'Found:')
```
In addition, I suggest you add [Subdomainizer](https://github.com/nsonaniya2010/SubDomainizer) or something similar and [ParamSpider](https://github.com/devanshbatham/ParamSpider) Which is a good complement to [hakrawler](https://github.com/hakluke/hakrawler) (I found it more convenient to use GF on ParamSpider instead of the hakrawler output.)

Regards,
Jomar

**Comment by yogeshojha** [comment]
Awesome @JoshuaMart 

I am working on this 🚀

**Comment by pappan9100** [comment]
Yes, need a provision for providing word-list option for subdomain discovery

**Comment by yogeshojha** [comment]
Thank you very much @JoshuaMart for the detailed Feature request, ability to perform amass-active and amass passive scan or both are ready to be merged. 

All thanks to @Serizao! 

the config feature, I will be working tommorow and we can close this Feature request.

**Comment by JoshuaMart** [comment]
Hi, guys,
No worries, it's the least you can do to make a correct request :)

Looking forward to these new features, thank's @serizao :)

It would be nice to make a short guide (when you have time) on how to add a tool properly or make some modifications. (A PR contribution guide with which files we need to modify).

Regards,
Jomar

**Comment by yogeshojha** [comment]
Hello @JoshuaMart 

I have merged the changes. I will close this feature request as of now. For Paramspider, there's another feature request and for better tracking, I will be closing this. 

Thank you
