### ISSUE TITLE
Bug - Showing too many urls/directories in Subdomains Discovered

### ISSUE THREAD

**Issue by lucy9x** [yogeshojha/rengine#107]
### Issue Summary

The results of  Subdomains Discovered have shown too many urls/directory. This caused the interface to be broken. 
Below is a picture of my experience
![](https://i.imgur.com/own2S2Y.png)

**Comment by yogeshojha** [comment]
Hi @lucy9x ,

This is happening because the website is responding 200 Ok status for every files dirsearch is brute forcing. 
This is not directly related to reNgine, but related to the website itself.

**Comment by lucy9x** [comment]
Hi @yogeshojha 
Yes, the website is responding 200 Ok status for every files dirsearch is brute forcing. So I think this page should only show a summary of the scan results and need another page to display details scan results of domain
