### ISSUE TITLE
bug: error 500 after authentication for a fresh installation

### ISSUE THREAD

**Issue by batbast** [yogeshojha/rengine#1073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Immediatly after authentication, when there is no project, error 500 produce by the web container.
To fix it, repove the s char on word projects at the line 376 of the file web/dasboard/views.py

### Expected Behavior

The projects variable is not defined, it's a typo error

### Steps To Reproduce

Fresh install
No docker volumes
Authent

### Environment

```markdown
- reNgine: latest source code
- OS: Debian stable
- Python: 3.10
- Docker Engine: latest Debian stable
- Docker Compose: latest Debian stable
- Browser: latest Firefox
```

**Comment by AnonymousWP** [comment]
Please post advanced logs, see [here](https://github.com/yogeshojha/rengine/issues/1030) how.

**Comment by Vijayragha1** [comment]
if projects:
        slug = project.slug
        return HttpResponseRedirect(reverse('dashboardIndex', kwargs={'slug': slug}))

change  to "if project"

**Comment by psyray** [comment]
@yogeshojha you made a modification pushed yesterday
https://github.com/yogeshojha/rengine/commit/b190060d07e6ed4d6bfd969481ab6d54779c09a0
I will fix this immediately

**Comment by psyray** [comment]
PR submitted
 Thanks for the finding @Vijayragha1 👍

**Comment by AnonymousWP** [comment]
Fixed in https://github.com/yogeshojha/rengine/pull/1074.
