### ISSUE TITLE
bug: Web UI doesn't load CSS and JS 

### ISSUE THREAD

**Issue by namdodayne** [yogeshojha/rengine#1087]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/yogeshojha/rengine/assets/57885184/00befc9b-2136-414b-a2ad-6e060c33c1fe)

### Expected Behavior

Error code 500 with .css and .js file

### Steps To Reproduce

1. git clone https://github.com/yogeshojha/rengine.git
2. cd rengine
3. make certs
4. make build
5. make up

### Environment

```markdown
- reNgine: docker.pkg.github.com/yogeshojha/rengine/rengine:lastest
- OS: Linux kali 6.3.0-kali1-amd64 + Windows 10 22H2
- Python: 3.11.4
- Docker Engine: 20.10.25
- Docker Compose: 2.21.0
- Browser: 119.0.6045.160 (Official Build) (64-bit)
```

**Comment by AnonymousWP** [comment]
You're supposed to install it, so after cloning, run `install.sh`. Then, you don't need to run any other command like `make certs`, `make build` or `make up` anymore.

**Comment by psyray** [comment]
And SSL
https://127.0.0.1

**Comment by AnonymousWP** [comment]
Don't close this until the user confirms it's working again, unless this is open for many weeks.

**Comment by namdodayne** [comment]
Thanks, I got it

**Comment by manishavalecha** [comment]
Was this resolved for anyone?
If yes, how did it got resolved?

**Comment by tonyd1313** [comment]
Need help also what's the way to resolve the web gui

**Comment by psyray** [comment]
Please read the issue before asking for help
https://github.com/yogeshojha/rengine/issues/1087#issuecomment-1830166009

**Comment by calejandroateitis** [comment]
Hi! I am having the same problem...specially using in windows environment. @AnonymousWP for example, i dont have any ./install.sh for windows (for example) like a bat or something like that.
