### ISSUE TITLE
reNgine installation failed!!    

### ISSUE THREAD

**Issue by sasholy** [yogeshojha/rengine#1088]
What's the problem, there used to be a link, now it's 404.
`
.637 Get:10 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [78.3 kB]
5.444 Reading package lists...
6.098 E: Release file for http://security.ubuntu.com/ubuntu/dists/jammy-security/InRelease is not valid yet (invalid for another 8h 18min 45s). Updates for this repository will not be applied.
6.098 E: Release file for http://archive.ubuntu.com/ubuntu/dists/jammy-updates/InRelease is not valid yet (invalid for another 8h 19min 29s). Updates for this repository will not be applied.
failed to solve: executor failed running [/bin/sh -c apt update -y &&     apt update -y &&     apt install -y     python3.10     python3-dev     python3-pip]: exit code: 100
make: *** [Makefile:25: build] Error 17
`
reNgine installation failed!!     

    
thanks

**Comment by sasholy** [comment]
https://rengine.wiki/install/detailed/

**Comment by AnonymousWP** [comment]
Try again. See the error:

> invalid for another 8h 18min 45s

Tell us whether the issue still persists or not.

**Comment by sasholy** [comment]
> Try again. See the error:
> 
> > invalid for another 8h 18min 45s
> 
> Tell us whether the issue still persists or not.

working!
sudo bash ./update.sh
thx.
