### ISSUE TITLE
For Port Scan use this tool

### ISSUE THREAD

**Issue by attacker007** [yogeshojha/rengine#109]
**Is your feature request related to a problem? Please describe.**

Nmap takes a lot of time to scan the ports as well as with masscan etc.

**Describe the solution you'd like**

Add this tool 

```
https://github.com/brandonskerritt/RustScan

```

**Describe alternatives you've considered**

Scans all 65k ports in 8 seconds (on 10k batch size).

**Additional context**

https://github.com/brandonskerritt/RustScan/blob/master/pictures/with_rustscan.gif

https://github.com/brandonskerritt/RustScan/blob/master/pictures/without_rustscan.gif

**Comment by HackerOnTwoWheels** [comment]
I second this!

**Comment by yogeshojha** [comment]
Let's keep this open, I will be working on this.

**Comment by attacker007** [comment]
Hi @yogeshojha  I've just checked that same thing can be achieved via nmap with following Command:

```
nmap -p- scanme.nmap.org --min-rate 40000 -T4 --max-retries 2

```

So, That's why i closed it. I also thought that other suggestions in queues are better to be implemented first than this. Its not worth to open... :) 

You've only added your Paypal address for funding .. Add Crypto Addresses too.. 


Sincerely,

**Comment by aoprea1982** [comment]
Can masscan be an option? 

[https://github.com/robertdavidgraham/masscan](url)
