### ISSUE TITLE
when i'm starting a scan the response is 500 server error

### ISSUE THREAD

**Issue by Ghost00Shell** [yogeshojha/rengine#1094]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**Help when i'm starting a scanning the response is 500 server error**

### Expected Behavior

200 OK

### Steps To Reproduce

**when i'm starting a scanning the response is 500 server error**

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by AnonymousWP** [comment]
You need to fill in the information, otherwise we can't know. Also, post logs. Make sure you ran the `update.sh` file and then try again.
