### ISSUE TITLE
Error While Opening "/usr/src/github/Infoga/infoga.py" File

### ISSUE THREAD

**Issue by Deathpoolxrs** [yogeshojha/rengine#1097]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Recently, I ran a scan and observed the following error message.

```
python3 /usr/src/github/Infoga/infoga.py --domain oneweb.net --source all --report /usr/src/scan_results/oneweb.net_32/emails_tmp.txt


python3: can't open file '/usr/src/github/Infoga/infoga.py': [Errno 2] No such file or directory
```

### Expected Behavior

/usr/src/github/Infoga/infoga.py -- This file should exist, so the OS Intelligence module can run properly.

### Steps To Reproduce

Just scan any target, you will get this error target

### Environment

```markdown
reNgine: latest version
OS: Ubuntu 20.04
Python: 3.11.0
Docker: 20.10.22
Docker compose: 2.15.1
Browser: Microsoft Edge 112.0.1722.58
```

**Comment by psyray** [comment]
The original repository seems to be deleted
https://github.com/GiJ03/Infoga

Anyway this project seems old and not maintained.
I will fix the path, but we need to know if this tool is working again.
@AnonymousWP What's your advice ?

**Comment by psyray** [comment]
Fixed, Thanks for reporting this issue.
If you want to test it before released, update link in `celery-entrypoint.sh` and restart celery container `docker-compose restart celery`

**Comment by AnonymousWP** [comment]
> The original repository seems to be deleted in favor of this one https://github.com/GiJ03/Infoga
> 
> Anyway this project seems old and not maintained. I will fix the path, but we need to know if this tool is working again. @AnonymousWP What's your advice ?

I think we should drop it, as it's old anyway and only adds longer scanning time. We have h8mail anyway that does a similar job: https://github.com/khast3x/h8mail

**Comment by yogeshojha** [comment]
Yes I agree, infoga can be dropped. h8mail is there anyways.

**Comment by psyray** [comment]
Infoga dropped in PR #1099

**Comment by Talanor** [comment]
This has been merged in master, should close.
