### ISSUE TITLE
installation crash 

### ISSUE THREAD

**Issue by selomoscar2** [yogeshojha/rengine#112]
I follow the setup steps (docker and docker-compose are working well) but the installation crash on rengine_web_1 process and say that it cannot find  "docker-entrypoint.sh" for container_linux.go. I delete the folder, clone it and restart installation but the same error is still display. 

### Technical details
My OS is windows 10.

**Comment by selomoscar2** [comment]
![ren1](https://user-images.githubusercontent.com/56925898/88308513-06277080-cd05-11ea-9403-fe356c3ca3f5.PNG)

**Comment by atikrahman1** [comment]
is there any update/solution? I am fetching the same error on windows based docker @selomoscar2 @yogeshojha
