### ISSUE TITLE
bug: error: prompted update instructions are outdated - traditional upgrade not detected in Firefox

### ISSUE THREAD

**Issue by carboncrystal** [yogeshojha/rengine#1121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rengine prompted to upgrade to 2.0.2

The Upgrade Instructions button will redirect you to https://rengine.wiki/update/
Here everything is outdated (cd script is now cd scripts, but the scripts did not include `update.sh`).

I tried suggesting an edit (click the pen icon), but it redirects you to https://github.com/yogeshojha/rengine/edit/master/docs/update/index.md which is 404 Not Found.

So I upgraded in the traditional way: `make down && git pull && make build && make up`.

After the upgrade was successful in the Rengine menu the logo display Rengine 2.0.2, but in Username (menu) I am notified that Update is Available. 
On clicking the notification I get the following message:
  
![Screenshot from 2023-12-09 05-49-05](https://github.com/yogeshojha/rengine/assets/106466414/fcbc507a-b4e5-4e2c-8edc-c6035968bf3e)

**Error persist only in Firefox, with Chrome everything works OK.**
YES, I've cleared the cache in Firefox!
YES, I've try `make restart`.

### Expected Behavior

To detect the upgrade in Firefox.

### Steps To Reproduce

1. Upgrade Rengine in the traditional way (as long as upgrade instructions are outdated).
2. Access Rengine in Firefox.

### Environment

```markdown
Ubuntu 22.04.3 LTS
Rengine 2.0.2
Docker, Python etc latest version for Ubuntu.
Browser: Firefox (error),Chrome (OK).
```

**Comment by psyray** [comment]
What's your FF version ?
I did an upgrade yesterday and no problem on FF for dev (121) and FF classic (120)
We need more details, like the web console with the XHR request/response that check version

**Comment by carboncrystal** [comment]
> What's your FF version ? I did an upgrade yesterday and no problem on FF for dev (121) and FF classic (120) We need more details, like the web console with the XHR request/response that check version

Mozilla Firefox Snap for Ubuntu 119.0.1 (64-bit)

**Comment by psyray** [comment]
> > What's your FF version ? I did an upgrade yesterday and no problem on FF for dev (121) and FF classic (120) We need more details, like the web console with the XHR request/response that check version
> 
> Mozilla Firefox Snap for Ubuntu 119.0.1 (64-bit)

XHR request from the dev console please

**Comment by carboncrystal** [comment]
After updating Firefox (by snap) or after updating the latest changes to Rengine 2.0.2 (git pull), this error is gone, now Firefox detects the correct version and doesn't ask you to update!
