### ISSUE TITLE
bug: port not correctly recognized

### ISSUE THREAD

**Issue by psyray** [yogeshojha/rengine#1122]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After a port scan, ports are identified with `unknown`
![image](https://github.com/yogeshojha/rengine/assets/1230954/a2e29536-edd2-4192-9228-05c3a2c10d93)

It comes from the **whatportis** command and is also related with #984 

**Whatportis** rely on the  [IANA database](http://www.iana.org/assignments/port-numbers) and this is the root cause of this problem.
If download failed, whatportis is useless and no port are recognized

And there's no way to update the IANA DB from GUI, only a `docker-compose restart celery` triggers the script update and maybe it download the db or maybe not, it depends on the IANA server.

Then you'll have to launch a port scan again to correctly displayed ports

But, and there is a but, while scan is finished, ports are correctly recognized, but duplicated, for ex. You will have `80/http` and `80/unknown`

Collateral damage for this is that when you do another port scan on the same target and same port is found (eg. 80), now reNgine task will fail with the **MultipleObjectsReturned** error

![image](https://github.com/yogeshojha/rengine/assets/1230954/0113cbc0-2491-4307-ae6e-a5a908caaffd)

There are several solutions for this problem :
- Integrate **whatportis** and the **IANA** database directly into the docker
- **Whatportis** seems to be old, maybe an other project could fit
- Rely on **nmap** to identify port

The quickest solution is the first one, and the better is the third one, as **nmap** is more effective in service port recognition.

To enable **nmap** we need some additional work, as **nmap** recognize the service by querying it, the same port could have more than one label. So we need to rework this part in the db, the logic...

@yogeshojha @AnonymousWP 
Your advice ?

### Expected Behavior

Port should be identified

### Steps To Reproduce

1. Check in the make logs at celery container start that IANA db download failed
2. Connect to reNgine and launch a port scan

### Environment

```markdown
- reNgine: 2.0.2
- OS: Ubuntu 22.04.3
- Python: 3.10
- Docker Engine: 
- Docker Compose: 
- Browser: FF 120
```

**Comment by yogeshojha** [comment]
@psyray this is unrelated to whatportis. port 80 is stored in db with two instances. .get() in django fetches only one. And there are two, can you please go to `http://ip:8000/admin/` and open `Ports` and then show us here what two port 80 has descriptions?

**Comment by psyray** [comment]
@yogeshojha 
Whatportis does not return the correct port description, so two records are added because comparison to find existing record failed.

And later the get does not accept tow records returned, and raise an exception

**Comment by psyray** [comment]
@yogeshojha Strange ...
So what could have been cause this duplicate record ?
I can't give you the record as I've deleted the bad one.
I only see 2 places where port is saved
- In port scan
https://github.com/yogeshojha/rengine/blob/fd5a5e5faa1e289cbf421e8aaf6014452efaef1f/web/reNgine/tasks.py#L1353-L1363
- In target add (in this section only port is used to get a record)
https://github.com/yogeshojha/rengine/blob/fd5a5e5faa1e289cbf421e8aaf6014452efaef1f/web/targetApp/views.py#L142-L145

**Comment by AnonymousWP** [comment]
In my opinion we should go for NMAP as we already added it to reNgine a while ago and second, because it's a better solution. Sure, it might take time, but then at least we can drop one tool (`whatportis`) and keep NMAP.

**Comment by psyray** [comment]
Completely agree with you @AnonymousWP 
Service recognition on port is way better with nmap
And there is a start of implementation here (commented section)
https://github.com/yogeshojha/rengine/blob/fd5a5e5faa1e289cbf421e8aaf6014452efaef1f/web/reNgine/tasks.py#L3199-L3231

**Comment by AnonymousWP** [comment]
@yogeshojha Let me know what you think about the above. If you agree, one of us can open a PR.

**Comment by psyray** [comment]
@yogeshojha Your advice ?
