### ISSUE TITLE
feat: Ruff linter

### ISSUE THREAD

**Issue by jxdv** [yogeshojha/rengine#1134]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Currently the styling of the python codebase is inconsistent. Some examples:
- Mixing up naming conventions (some functions use snake case / camel case etc.)
- Some files follow the PEP8 spacing between functions / classes / constants etc. and some don't.

Proposed solution:
Writing a GitHub action for [Ruff linter](https://github.com/astral-sh/ruff). Of course this would take quite a while to refactor the whole codebase, but I can see the project benefitting from it.

**Comment by psyray** [comment]
Totally agree with that
Some file have spaces indent, some tabs ...
We need some refactoring jobs

**Comment by AnonymousWP** [comment]
> Totally agree with that Some file have spaces indent, some tabs ... We need some refactoring jobs

Do you have experience with that? I don't, but I could look into it when I have more time.

**Comment by psyray** [comment]
Yes,

For example, in the same folder `web/reNgine` 

**tasks.py** have tabs
![image](https://github.com/yogeshojha/rengine/assets/1230954/3c788681-f059-42d0-812d-f73b929fcd57)

**common_serializers.py** have spaces
![image](https://github.com/yogeshojha/rengine/assets/1230954/97568fea-7f6a-47d7-b475-802ea70c8192)

**Comment by jxdv** [comment]
I can create a PR for this if you're interested, but the refactoring obviously would have to be a team effort. It's gonna take quite some time.

**Comment by AnonymousWP** [comment]
If you can, yes please. Don't forget to use the closing keywords for this issue. The refactoring can be done in a new issue.

**Comment by jxdv** [comment]
Yes, Ruff can fix some stuff by itself using `--fix`, but there are also unsafe fixes which I prefer the devs look at as these could cause some troubles and break some backend stuff.

**Comment by jxdv** [comment]
@AnonymousWP I am wondering how would you like to see the linked PRs to this..1 PR just for the implementation of Ruff itself, and the second one for the big python cleanup?

**Comment by AnonymousWP** [comment]
> @AnonymousWP I am wondering how would you like to see the linked PRs to this..1 PR just for the implementation of Ruff itself, and the second one for the big python cleanup?

Yep, correct. Maybe a separate issue to refactor the code and then link the PR of the big Python cleanup to it.
