### ISSUE TITLE
rengine stop working properly after setting DEBUG=0

### ISSUE THREAD

**Issue by Mubspatel** [yogeshojha/rengine#114]
Hi, 

Thank you so much for making this tool publicly available. I encountered some errors when uploading a wordlist, And the error was disclosing many sensitive information as we know. As I am also running this tool on my server (Public IP). So, leaving DEBUG as True might be a problem in the future. So, Please make this little change in this tool. 

Best regards,
Mubassir

**Comment by yogeshojha** [comment]
In the latest update, you should be able to turn off the debug mode
