### ISSUE TITLE
bug: With proxies, no dir, vuln, osint, screenshot, etc. Only subdomains.

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With proxies, no dir, vuln, osint, screenshot, etc. Only subdomains.

### Expected Behavior

All scan.

### Steps To Reproduce

Add proxy list and full scan

### Environment

```markdown
- reNgine: 2.0.2
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by psyray** [comment]
Does your proxy list is good ?
And do the same thing while running `make logs | grep celery`  and check if there are errosr in the console

**Comment by zinwelzl** [comment]
New proxy works, for now.
