### ISSUE TITLE
feat: Codebase refactor

### ISSUE THREAD

**Issue by jxdv** [yogeshojha/rengine#1146]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Creating this issue based on the discussion held in #1134.
The code style should be unified in the whole codebase to make it more readable and prevent code smells.
PR will be linked for this once I have it ready.

### Alternative solutions

n/a

### Anything else?

n/a

**Comment by jxdv** [comment]
Feel free 2 assign me.

**Comment by AnonymousWP** [comment]
Thanks for the PR and this issue! Looking forward to more of your contributions.
