### ISSUE TITLE
feat: Setup run time

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1150]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

When add URL, also add how long scan will last.
In days, hours, etc.

If I need to scan URL for one day (or any time period), and what I found is enough.

**Comment by AnonymousWP** [comment]
I don't think this will be accurate at all, and I don't think it's worth it either. Just imagine that reNgine won't know how many subdomains, endpoints, ports etc. it will find, so I can only assume that as a scan is being performed, the 'progress bar' (or any other implementation) will be all over the place.
