### ISSUE TITLE
bug:  href link with HTML ID does not link to the expected URL

### ISSUE THREAD

**Issue by carboncrystal** [yogeshojha/rengine#1155]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. **Go to Scan Findings (Menu: Scan History > Select your project > View Results).**

2. **Here are the menus:** 

- Home
- Subdomains
- S3 Buckets
- Interesting Recon
- Screenshots
- Directories
- URLs 
- Vulnerabilities
- OSINT
- Visualization

3. For example, if you hover over the Directories menu **you will see that the ID is listed in the URL** (#directories-tab), something like: https://127.0.0.1/scan/myprojectname/detail/15#directories-tab.

4. Let's go deeper with the above example: After you access the Directories menu you can see something like: https://127.0.0.1/scan/myprojectname/detail/11#dir_Jan_01_2024_14_24_54

### What is the problem?
href link with HTML ID does not link to the expected URL.  **Trying to open the above links in a new tab will not work**, you will always be redirected to Home!

So you won't be able to send these HTML ID links to Jira (to your colleagues), or by email.  So you can't map Attack Surface or Vulnerability Assessment in a clear way!

This bug is annoying as hell!

### Expected Behavior

href link with HTML ID to link to the expected URL

### Steps To Reproduce

Explained at Current Behavior field.

### Environment

```markdown
- reNgine: 2.0.2
- OS: Ubuntu 22.04.3 LTS
- Python: Python 3.10.12
- Docker Engine: latest
- Docker Compose: latest
- Browser: Firefox, Chrome
```

**Comment by psyray** [comment]
Thanks for reporting
I will have a look

**Comment by yogeshojha** [comment]
Hey @carboncrystal 

Thank you for reporting this.

>A new feature has been added when clicked on the tabs inside scan results, will append the url hash on the browser. When the URL is accessed, the tab will be automatically clicked, which can be useful for navigation.

> Also, navigation inside tabs is added, for example when clicked on Subdomains tab, and then Screenshot tab, you can use back button to go back to Subdomains tab, earlier it would go back to the previous page and not previous tab.
