### ISSUE TITLE
bug: Fetch GPT Vulnerability Details always blank dates

### ISSUE THREAD

**Issue by carboncrystal** [yogeshojha/rengine#1156]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. I have OpenAI API Key & Netlas API Key set in Rengine.

2. At OpenAI I have premium API plan and sufficient credits, at Netlas I have plan with 2000 API calls/month.

3. At Subdomains menu (for example: https://127.0.0.1/scan/myprojectname/detail/15#subdomain-tab) > clicking on Eye Icon (Show Attack Surface) **everything works perfectly**, you get data (Attack Surface recommendations).

4. But on the Vulnerabilities menu (e.g. https://127.0.0.1/scan/myprojectname/detail/15#vulnerabilities-tab) > click on 3 dots (...), under the menu in the Action table and selecting Fetch GPT Vulnerability Details, **you GET ALWAYS BLANK RESULTS**. 

**Whether Critical, High, Medium, Low, Info, Unknown vulnerabilities are identified in Rengine, you always get the same result:  EMPTY BLANK DATES when Fetch GPT Vulnerability Details!**

### Screenshots 
![Screenshot from 2024-01-02 09-24-01](https://github.com/yogeshojha/rengine/assets/106466414/2cf0e69d-c8a8-433d-a0d1-80434837181d)

![Screenshot from 2024-01-02 09-24-38](https://github.com/yogeshojha/rengine/assets/106466414/d8a9d913-6fa4-4513-9e0e-0a21f34e3572)

### Expected Behavior

Fetch GPT Vulnerability Details to get data from the OpenAI GPT API.

### Steps To Reproduce

Specified above!

### Environment

```markdown
- reNgine: 2.0.2
- OS: Ubuntu 22.04.3 LTS
- Python: Python 3.10.12
- Docker Engine: latest for Ubuntu
- Docker Compose: latest for Ubuntu
- Browser: Firefox, Chrome
```

**Comment by psyray** [comment]
Strange, I didn't use chatGPT yet, but maybe someone else who's using it can help ?
@yogeshojha @AnonymousWP

**Comment by Ondjultomte** [comment]
I experience the same

Vulnerability detail for GeoServer OGC Filter - SQL Injection

Description
null

Impact
null

Remediation
null

References

openAI reports no usage of the API.

running a new install or 2.0.3

**Comment by psyray** [comment]
> I can add that after alittle more testing it only happends on critical and high vulns, not medium. medium and info works just fine to get text from chatgpt. its only critical and high that doesnt wortk for me.

Thanks for your feedback.
I will have a look at this, no ETA

**Comment by yogeshojha** [comment]
Hi @Ondjultomte @carboncrystal 

This was likely due to the issue in prompt. I have tested it now with 2.1.1

We had to do some refactoring for llm report in 2.1.X, issues with LLM/GPT should have fixed.

I tested and works fine for now.

![image](https://github.com/user-attachments/assets/7f963683-3b63-4342-9dc9-7b0e4687f6ee)

If it doesn't work feel free to open a new issue.
