### ISSUE TITLE
feat: Is it possible to integrate Copilot, because it have free GPT-4 model?

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1159]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Is it possible to integrate Copilot, because it have free GPT-4 model?

https://copilot.microsoft.com/

Microsoft’s Copilot is very similar to ChatGPT, with access to chatbot capabilities, image generation through DALL-E 3, and the ability to draft text for emails and documents. It also includes free access to OpenAI’s latest GPT-4 model, something you have to pay for if you’re using ChatGPT.

**Comment by psyray** [comment]
Maybe this one could help ?
https://github.com/yogeshojha/rengine/pull/1118

**Comment by psyray** [comment]
According to the @SubGlitch1 response on #1118 comment, this integration is not possible
