### ISSUE TITLE
Is it possible to set up the server accessible from public ip?

### ISSUE THREAD

**Issue by marcelo321** [yogeshojha/rengine#116]
I would love to run this in my VPS but I'm not sure if i would be able to access it from anywhere I want.

What should i modify to do it correctly?

**Comment by yogeshojha** [comment]
Yes it works right out of the box, your_ip:8000 should work, however, debug should be turned off in django 

But there are some problems with django debug as 0, let ne figure it out.

**Comment by pager5Cx415Cx415Cx69** [comment]
Why we need domain name if we are accessing over vps with only ip it is possible?
