### ISSUE TITLE
bug: Navbar Link Names too big

### ISSUE THREAD

**Issue by serrapa** [yogeshojha/rengine#1160]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The text fo the navbar links is too big and wrap, as shown in the figure below:
<img width="959" alt="image" src="https://github.com/yogeshojha/rengine/assets/26407305/12550d63-bf49-475b-bc07-b51b37bfae70">

### Expected Behavior

The text should not wraps.

### Steps To Reproduce

Open rengine in a 1280 x 551 browser window.

### Environment

```markdown
- reNgine: 2.0.2
- OS: Windows
```

### Anything else?

Change the size of the _.topnav .navbar-nav .nav-link_ from  0.95rem to 0.85rem inside app-dark.min.css and app.min.css

**Comment by psyray** [comment]
Fixed in #1167
