### ISSUE TITLE
feat: LDAP Integration

### ISSUE THREAD

**Issue by LoriSchochWIT** [yogeshojha/rengine#1164]
### Is there an existing feature or issue for this?

- [x] I have searched the existing issues

### Expected feature

Hi all

I am writing to request a new feature that I believe would greatly enhance the tool's functionality and usability. It would be incredibly beneficial if rengine could be integrated with LDAP (Lightweight Directory Access Protocol). This would allow users to authenticate with their existing LDAP credentials, providing a seamless experience and simplifying the management of user access.

Benefits:

1. **User Management**: LDAP integration would simplify the process of managing users, as it would allow administrators to control access through a centralized system.
2. **Security**: LDAP is a proven and widely adopted protocol for user authentication, which would enhance the security of rengine.
3. **Convenience**: Users would not need to remember an additional set of credentials, improving the user experience.

Thank you for your time and consideration.

Best regards,
Lori

**Comment by psyray** [comment]
It could be a really good feature.
Could you work on it ?
Or someone else ?

**Comment by LoriSchochWIT** [comment]
Hi @psyray , unfortunately I can't work on this feature because I'm an employee. Could someone else help with the integration of this important feature?

**Comment by AnonymousWP** [comment]
I don't think this will be used too often. It's rather complicated to implement and not worth the time it costs. Also, most companies usually run this on a VM and it's available for only a handful of pentesters in a team, so it's not like every employee will need access to this.
