### ISSUE TITLE
Feature - Instead of dirsearch use meg tool to remediate 429 status error

### ISSUE THREAD

**Issue by secureITmania** [yogeshojha/rengine#117]
The application is using dirsearch tool to brute-force the directories but this will give **429 status code** because most of the website implementing the rate-limiting. So instead of the dirsearch use meg tool on all subdomains with a custom wordlist. 

Please have a look at this tool.

https://github.com/tomnomnom/meg

**Comment by maverickNerd** [comment]
No, I don't agree, ffuf or dirsearch are good for directory bruteforcing, meg is good when you have many hosts and you want to search for a some particular endpoints, as meg captures the full response.

**Comment by securITymania** [comment]
Lol! You found interesting stuff using dirsearch on the Bugcrowd or hackerone targets 🤔

Happy hunting

**Comment by maverickNerd** [comment]
Ofcourse I found, I use ffuf most of the time though.

**Comment by g33kyshivam** [comment]
Meg is different than dirsearch/fuff. Meg should be used for certain endpoints which you want to spray against multiple targets.

**Comment by secureITmania** [comment]
Ok, I am not downgrading the dirsearch tool but here the problem is the most of the bug bounty programs have rate limiting. If I ran the dirsearch tool or fuff finally the scan end-up with 429 status code and my IP is blocked. So finally, I shifted to meg tool and the data saved from this tool help me to further analysis about the target. Hope all you understand

**Comment by maverickNerd** [comment]
I hardly found any website till now which has directly bruteforce limit, most of them does not have, and even if they have you can delay your requests. As told by Shivam too, meg is good for spraying multiple hosts multiple endpoints which you know are vulnerable, but not for directory bruteforcing, look at ffuf, everyone is using it, it is so fast still I never got blocked by waf and got 429. May be the websites you hunt on have really strict WAF.

**Comment by attacker007** [comment]
Hi there,

In my opinion Dirble is better than dirsearch .. moreover ffuf is faster :)

**Comment by yogeshojha** [comment]
ffuf is coming for directory search after a lot of ask form community. Stay tuned :rocket:

**Comment by yogeshojha** [comment]
Please follow #146 for any updated on ffuf.
