### ISSUE TITLE
bug: error 500 when try to initiate scan

### ISSUE THREAD

**Issue by the-jojo-jj** [yogeshojha/rengine#1170]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

error 500 when try to initiate scan

### Expected Behavior

scan started

### Steps To Reproduce

System check identified 1 issue (0 silenced).
January 13, 2024 - 14:23:52
Django version 3.2.4, using settings 'reNgine.settings'
Starting development server at http://0.0.0.0:8000/
Quit the server with CONTROL-C.
celery.backends.redis | Connection to Redis lost: Retry (0/20) now.
celery.backends.redis | Connection to Redis lost: Retry (1/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (2/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (3/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (4/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (5/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (6/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (7/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (8/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (9/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (10/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (11/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (12/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (13/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (14/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (15/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (16/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (17/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (18/20) in 1.00 second.
celery.backends.redis | Connection to Redis lost: Retry (19/20) in 1.00 second.
celery.backends.redis | 
Retry limit exceeded while trying to reconnect to the Celery redis result store backend. The Celery application must be restarted.

django.server | "POST /scan/default/start/1 HTTP/1.0" 500 145

### Environment

```markdown
- reNgine: 2.0.2
- OS: debian 10
- Python: 2.7.16
- Docker Engine: version 24.0.7, build afdd53b 
- Docker Compose: v2.23.0 
- Browser: Chrome 120 on iOS 17.1
```

**Comment by psyray** [comment]
Restart redis container and it should work
From the cloned rengine directory
`docker compose restart redis`

**Comment by psyray** [comment]
@the-jojo-jj News ?
Issue with no feedback will be closed next week
You can come to the discord channel to discuss about it.
