### ISSUE TITLE
bug: stuck at py.warnings | /usr/local/lib/python3.10/dist-packages/celery/canvas.py:2283: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery. Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final decision regarding how errbacks should behave when used with chords.   warnings.warn(

### ISSUE THREAD

**Issue by the-jojo-jj** [yogeshojha/rengine#1175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

got stuck with this celery docker logs: 
py.warnings | /usr/local/lib/python3.10/dist-packages/celery/canvas.py:2283: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery.
Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final decision regarding how errbacks should behave when used with chords.
  warnings.warn(

### Expected Behavior

continue scanning.

### Steps To Reproduce

py.warnings | /usr/local/lib/python3.10/dist-packages/celery/canvas.py:2283: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery.
Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final decision regarding how errbacks should behave when used with chords.
  warnings.warn(

### Environment

```markdown
- reNgine: 2.0.2
- OS: Ubuntu 22.04
- Python: 3.10.12
- Docker Engine: 24.0.7
- Docker Compose: 2.23.0
- Browser: chrome 120
```

### Anything else?

py.warnings | /usr/local/lib/python3.10/dist-packages/celery/canvas.py:2283: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery.
Please test the new behavior by setting task_allow_error_cb_on_chord_header to True and report any concerns you might have in our issue tracker before we make a final decision regarding how errbacks should behave when used with chords.
  warnings.warn(

**Comment by psyray** [comment]
Title is little long/not readable no ?
Could you set a proper title with the issue topic and put stack trace into markdown tag.

Keep in mind that we read the issue, and your issue does not make you want to be read
Thanks

**Comment by psyray** [comment]
No feedback, no step to reproduce
Feel to reopen issue with complete details.
We can't help you if we can't reproduce

**Comment by ipsecc** [comment]
I got the same error.
`
celery-1       | py.warnings | /usr/local/lib/python3.10/dist-packages/celery/canvas.py:2303: CPendingDeprecationWarning: task_allow_error_cb_on_chord_header=False is pending deprecation in a future release of Celery.
`
Environment
`
- reNgine: 2.1.3
- OS: Ubuntu 24.04
- Python: 3.12.3
- Docker Engine: 24.0.7
- Docker Compose: 2.29.2
`
