### ISSUE TITLE
ERROR: Service 'celery' failed to build : Build failed

### ISSUE THREAD

**Issue by forme9** [yogeshojha/rengine#1178]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When doing make build, wget https://golang.org/dl/go1.21.4.linux-amd64.tar.gz will be connected, but the connection cannot be made until this step: Connecting to golang.org (golang.org)| |:443... failed: Connection refused.
eventually leading to failure
Excuse me , why is this?

### Expected Behavior

full installation

### Steps To Reproduce

fresh install of rengine using the official documentation

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by AnonymousWP** [comment]
Perhaps it was a network issue on Golang's side. Try again.

**Comment by psyray** [comment]
@forme9 Could you give us feedback ?
Without your feedback next week we will close this issue

**Comment by Ovi3** [comment]
在国内大陆访问不到golang.org跟github.com，要挂代理
