### ISSUE TITLE
bug: v 2.1.0, ./update.sh don't work

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1179]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sudo ./update.sh 
Do you want to apply your local changes after updating? (y/n)
y
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml down
Stopping rengine_proxy_1       ... done
Stopping rengine_web_1         ... done
Stopping rengine_celery-beat_1 ... done
Stopping rengine_celery_1      ... done
Stopping rengine_redis_1       ... done
Stopping rengine_db_1          ... done
Removing rengine_proxy_1       ... done
Removing rengine_web_1         ... done
Removing rengine_celery-beat_1 ... done
Removing rengine_celery_1      ... done
Removing rengine_redis_1       ... done
Removing rengine_db_1          ... done
Removing network rengine_rengine_network
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).

### Expected Behavior

v 2.0.2 works

### Steps To Reproduce

sudo make up
sudo ./update.sh

### Environment

```markdown
- reNgine: 2.1.0
- OS: Debian
```

**Comment by AnonymousWP** [comment]
Did you clone it or did you download the ZIP with source code?

**Comment by zinwelzl** [comment]
ZIP

**Comment by AnonymousWP** [comment]
> ZIP

Yeah that's not how it works. The documentation clearly states that you should clone the repo, right? 😅
