### ISSUE TITLE
feat: Doc on how to update the docker compose version.

### ISSUE THREAD

**Issue by cocoonkid** [yogeshojha/rengine#1181]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

A doc explaining how the upgrade process works for docker as the latest tag doesn't seem to be the 2.0.3 right now?

**Comment by cocoonkid** [comment]
https://github.com/yogeshojha/rengine/pull/655   I found this thread & yogeshojha/rengine:latest worked but now the Postgres user postgres and password as set in .env does not work. 

I customized it and it worked with the image build but not with the latest docker hub image.

Not sure right now. I will investigate further tomorrow.

**Comment by AnonymousWP** [comment]
Awesome. Let us know if you found anything and feel free to open a PR. 🙂
