### ISSUE TITLE
bug: Broken "download configuration from here" link in the Scan Engine view

### ISSUE THREAD

**Issue by NadgobKhan** [yogeshojha/rengine#1183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello, great tool! When creating or editing a scan engine, you have the option to download the default YAML configuration. The link to that configuration seems to be broken, as it gives a 404. 
Link in question: https://raw.githubusercontent.com/yogeshojha/rengine/master/default_yaml_config.yaml

Find attached an image of the context.
![image](https://github.com/yogeshojha/rengine/assets/70964231/2ada0cf7-999c-4b79-9b12-87da987bcb1e)

### Expected Behavior

The hyperlink from "download configuration from here" should lead to an actual helpful YAML configuration.

### Steps To Reproduce

1. Deploy reNgine
2. Go to "Scan Engines"
3. Click the "Edit" button
4. Click the hyperlink "download configuration from here"

### Environment

```markdown
- reNgine: 2.0.2
- OS: Ubuntu 22.04 (LTS) x64
- Python: Python 3.10.6
- Docker Engine: 25.0.1
- Docker Compose: v2.24.2
- Browser: Brave
```

**Comment by psyray** [comment]
Fixed in #1200
