### ISSUE TITLE
bug: [celery  4/43] RUN add-apt-repository ppa:mozillateam/ppa

### ISSUE THREAD

**Issue by jeanpaulvanhamond** [yogeshojha/rengine#1186]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After running sudo ./install.sh from a clean install.

At step 4/43 while running add-apt-repository ppa:mozillateam/ppa the follow error message shows up:

> [celery  4/43] RUN add-apt-repository ppa:mozillateam/ppa:                                                                      
184.3 Traceback (most recent call last):                                                                                           
184.3   File "/usr/bin/add-apt-repository", line 364, in <module>                                                                  
184.3     sys.exit(0 if addaptrepo.main() else 1)                                                                                  
184.3   File "/usr/bin/add-apt-repository", line 347, in main                                                                      
184.3     shortcut = handler(source, **shortcut_params)
184.3   File "/usr/lib/python3/dist-packages/softwareproperties/shortcuts.py", line 40, in shortcut_handler
184.3     return handler(shortcut, **kwargs)
184.3   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 82, in __init__
184.3     if self.lpppa.publish_debug_symbols:
184.3   File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 120, in lpppa
184.3     self._lpppa = self.lpteam.getPPAByName(name=self.ppaname)
184.3   File "/usr/lib/python3/dist-packages/lazr/restfulclient/resource.py", line 592, in __call__
184.3     response, content = self.root._browser._request(
184.3   File "/usr/lib/python3/dist-packages/lazr/restfulclient/_browser.py", line 429, in _request
184.3     raise error
184.3 lazr.restfulclient.errors.ServerError: HTTP Error 503: Service Unavailable
184.3 Response headers:
184.3 ---
184.3 -content-encoding: gzip
184.3 connection: close
184.3 content-length: 2155
184.3 content-type: text/html
184.3 date: Mon, 05 Feb 2024 15:34:22 GMT
184.3 server: Apache/2.4.41 (Ubuntu)
184.3 status: 503
184.3 vary: Accept-Encoding
184.3 ---
184.3 Response body:
184.3 ---
184.3 b'<!DOCTYPE html>\n<html\n  xmlns="http://www.w3.org/1999/xhtml"\n  xml:lang="en"\n  lang="en"\n>\n<head>\n  <title>Launchpad is temporarily unavailable</title>\n  <link\n    type="text/css" rel="stylesheet" media="screen, print"\n    href="https://launchpad.net/+icing/basic-error.css" />\n</head>\n<body>\n  <div class="page-center-wrap">\n    <div class="page-center">\n      <div class="page-center-content">\n        <div id="header">\n          <div class="graphic">\n            :(\n          </div>\n          <div class="content">\n            \n            <h1>Uh oh!</h1>\n            <h2>Something has gone wrong. We\'re sorry!</h2>\n            <p>\n              If we are in the middle of an update, Launchpad will be\n              back in a couple of minutes.  Otherwise, we are working to\n              fix the unexpected problems. Check\n              <a href="https://twitter.com/launchpadstatus">@launchpadstatus</a>\n              on Twitter or\n              <a href="https://ubuntu.social/@launchpadstatus">@launchpadstatus@ubuntu.social</a>\n              on Mastodon for updates.\n            </p>\n            <p>\n              If the problem persists, let us know in\n              <a href="irc://irc.libera.chat/#launchpad"\n              >the #launchpad IRC channel on libera.chat</a>.\n            </p>\n            <p class="sub">\n              Technically, the load balancer took too long to connect to\n              an application server.\n            </p>\n            <p><a href="javascript:window.location.reload()">Reload</a>\n              this page or try again in a few minutes</p>\n          </div>\n        </div>\n        <div id="footer">\n          <a href="https://launchpad.net/">\n            <img src="https://launchpad.net/@@/launchpad-logo-and-name.png"\n            width="100"\n            alt="Launchpad" />\n          </a>\n        </div>\n      </div>\n    </div>\n  </div>\n</body>\n</html>\n'
184.3 ---
184.3 
------
failed to solve: process "/bin/sh -c add-apt-repository ppa:mozillateam/ppa" did not complete successfully: exit code: 1
make: *** [Makefile:25: build] Error 17

### Expected Behavior

Finishing step 4 and move on to step 5

### Steps To Reproduce

sudo ./install.sh

### Environment

```markdown
- reNgine: v2.0.2-jasper
- OS: Rocky Linux release 8.9 (Green Obsidian)
- Python: 3.6
- Docker Engine: 25.0.2, build 29cf629
- Docker Compose: v2.24.5
- Browser: -
```

**Comment by AnonymousWP** [comment]
It's probably down, see the message you also posted. Also, check https://ubuntu.social/@launchpadstatus/111879418793860513. Closing this.
