### ISSUE TITLE
bug: Getting error while launching rengine through docker desktop

### ISSUE THREAD

**Issue by vinda-parab** [yogeshojha/rengine#1190]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hello,

I am trying to install the Rengine on Windows machine using docker desktop.
The documentation does not specify any special instructions for Windows installation I assume, we have to just pull and run the Rengine docker image.
When I tried this, I am getting an error:

2024-02-09 11:39:51 Waiting for postgres...
2024-02-09 11:39:56 nc: getaddrinfo: Try again
2024-02-09 11:40:01 nc: getaddrinfo: Try again
2024-02-09 11:40:06 nc: getaddrinfo: Try again

I tried to start the postgres container separately and then run the Rengine, but no success.

Need help - to get Rengine installed on Windows.

Regards,
VP

Regards,
Vinda

### Expected Behavior

Successful installation of Rengine on Windows machine

### Steps To Reproduce

Windows - Docker Desktop

### Environment

```markdown
- reNgine: Latest
- OS: Win
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser: IE
```

**Comment by AnonymousWP** [comment]
I use the same combination and it works totally fine. Just use WSL 2 with Ubuntu. Clone reNgine and start Docker Desktop, and don't forget to use WSL 2 as backend within Docker Desktop.

**Comment by psyray** [comment]
@vinda-parab Could you reply ?
Without reply next week we will close the issue as we can't reproduce
And fill the **Environment** part more seriously.

**Comment by Redteamer0101** [comment]
hi @AnonymousWP , Is it still working in your wsl2 as backend?? I tried same it worked but after some time like few minutes everything got crashed. Docker stopped working and got blue screen on error in windows. that happed 2-3 times back to back.
