### ISSUE TITLE
bug: Risk of leaking the scan result files

### ISSUE THREAD

**Issue by confd0** [yogeshojha/rengine#1202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The [huntr.com](http://huntr.com/) link for reNgine is down, and email is not responsed. so I put it here.
![image](https://github.com/yogeshojha/rengine/assets/60614211/4e274851-4dc1-4911-8363-5e06ed8f2b9f)

I just install reNgine v2.0.3 and find a nginx config file: https://github.com/yogeshojha/rengine/blob/f362189c9b253fd38c7c17c08e5cfc87aee0bfaf/config/nginx/rengine.conf

![image](https://github.com/yogeshojha/rengine/assets/60614211/c9177606-e176-4e98-8579-3a860cb63875)

look like I can read any scan results file from other rengine site if I know the file names, and the files names can be brute force:

![image](https://github.com/yogeshojha/rengine/assets/60614211/f1f789bd-6d23-43b6-b813-8f6ca72897e2)

### Expected Behavior

non-login user should not have privilege to read scan result files

### Steps To Reproduce

brute force `https://rengine_example.com/media/<domain>_<int>/subdomains_sublister.txt` , change `<domain>` and `<int>` to fuzz. 

### Environment

```markdown
- reNgine: 2.0.3
- OS: Linux
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by 0xtejas** [comment]
Maybe `x-accel-redirect` from Nginx helps?

**Comment by yogeshojha** [comment]
@confd0 Excellent one, thank you for reporting this.

@0xtejas Thanks for X-Accel-Redirect

@confd0 Feel free to test these changes and let me know if you need any help disclosing this or filing CVE. Thanks
