### ISSUE TITLE
run "docker exec -it rengine_web_1 /bin/bash" get error

### ISSUE THREAD

**Issue by briefcasehi** [yogeshojha/rengine#121]
I want to add $HOME/.config/subfinder/config.yaml file , but i get error when execute the command 

```
docker exec -it rengine_web_1 /bin/bash
```

**Comment by secureITmania** [comment]
try below this will work

sudo docker exec -it rengine_web_1 /bin/sh

**Comment by briefcasehi** [comment]
Thanks a lot!
