### ISSUE TITLE
bug: AttributeError: 'NoneType' object has no attribute 'name' subdomain scan

### ISSUE THREAD

**Issue by DanyAssuid** [yogeshojha/rengine#1217]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It's resolved the error : 
``` AttributeError: 'NoneType' object has no attribute 'name' ```

### Expected Behavior

The file task.py have a bug in line 545 
Need to change 
`urls.append(subdomain.name)`
to
`urls.append(subdomain_name)`

### Steps To Reproduce

go to task.py in line 545 
change the line above 

### Environment

```markdown
- reNgine: 
- OS: mac
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
This is been fixed in https://github.com/yogeshojha/rengine/pull/1147/commits/35f5380ebdfccb3b42d38ef5f2a9f805dd180908
