### ISSUE TITLE
Starting rengine-master_db_1 ... error

### ISSUE THREAD

**Issue by cehbikramrock** [yogeshojha/rengine#123]
docker-compose up -d this is not worked

Starting rengine-master_db_1 ... 
Starting rengine-master_db_1 ... error

ERROR: for rengine-master_db_1  Cannot start service db: driver failed programming external connectivity on endpoint rengine-master_db_1 (2df8216f6d26811d173c9e0471534928e41f890996067b9ec2481727b64228ea): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

ERROR: for db  Cannot start service db: driver failed programming external connectivity on endpoint rengine-master_db_1 (2df8216f6d26811d173c9e0471534928e41f890996067b9ec2481727b64228ea): Error starting userland proxy: listen tcp 0.0.0.0:5432: bind: address already in use

**Comment by jensecjensec** [comment]
@cehbikramrock How did you fix this bro?

**Comment by Kennydoneit** [comment]
With you :)

**Comment by jenish-sojitra** [comment]
@Kennydoneit Bro, I patched it via specifying different port in docker-compose.yaml file
