### ISSUE TITLE
bug: <Progress button stuck>

### ISSUE THREAD

**Issue by Razerdx** [yogeshojha/rengine#1236]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://github.com/yogeshojha/rengine/assets/56918000/0b6b0e68-ea0f-4d35-b56f-82dbc928ea6b)
Stuck with not much progress after 16 hours of scan

### Expected Behavior

Scan to show results and progress bar to move

### Steps To Reproduce

Happens after initiating scan

### Environment

```markdown
- reNgine: 2.0.5
- OS: Kali linux 2023.4 
- Python: -
- Docker Engine: -
- Docker Compose: -
- Browser: Firefox 115.7.0 esr
```

**Comment by estebanramos** [comment]
Same thing here. rengine ver 2.0.5

**Comment by 2004gixxer600** [comment]
Me as well.  Very frustrating.

**Comment by Talanor** [comment]
It means one of the first tool launched failed / hanged. Can you provide logs ?

**Comment by estebanramos** [comment]
> It means one of the first tool launched failed / hanged. Can you provide logs ?

For me it stucks in "Subdomain discovery" last command is amass and the output is null
` amass enum -active -d mydomain.com -o /usr/src/scan_results/ mydomain.com_20/subdomains_amass_active.txt -brute -w /usr/src/wordlist/deepmagic.com-prefixes-top50000.txt `

**Comment by Talanor** [comment]
What's the error ?
If you do `docker compose exec celery amass enum -active -d mydomain.com -o /usr/src/scan_results/ mydomain.com_20/subdomains_amass_active.txt -brute -w /usr/src/wordlist/deepmagic.com-prefixes-top50000.txt`, does it work ?
If not, does it work from your host ?
```bash
export DOMAIN=mydomain.com
wget https://raw.githubusercontent.com/danielmiessler/SecLists/master/Discovery/DNS/deepmagic.com-prefixes-top50000.txt
go install -v github.com/owasp-amass/amass/v4/...@v4.2.0
mkdir amass-results
amass enum -active -d $DOMAIN -o ./amass-results/subdomains_amass_active.txt
amass enum -active -d $DOMAIN -o ./amass-results ./amass-results/subdomains_amass_active.txt -brute -w deepmagic.com-prefixes-top50000.txt
```
