### ISSUE TITLE
Hi Can I add One-liners for this tool mainly for Scanning Specific Vulnerabilities ?

### ISSUE THREAD

**Issue by loyality7** [yogeshojha/rengine#1240]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Adding One-liners Can Help to detect exact Vulnerability 

### Anything else?

Help me with this admin

**Comment by yogeshojha** [comment]
Hi @loyality7 

Can you elaborate this more? What type of one liners you wish to add and which specific module?

**Comment by yogeshojha** [comment]
Closed due to inactivity
