### ISSUE TITLE
bug: Scans pending caused by broken celery

### ISSUE THREAD

**Issue by metehan-arslan** [yogeshojha/rengine#1241]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Rengine scans stuck at pending, whois doesn't works. make logs shows celery loop.

Thanks to Talanor from discord we were able to identify the issue. Running pip as root causing to crash existing system dependencies. 

Removing the following line fixed the loop:
https://github.com/yogeshojha/rengine/blob/master/web/celery-entrypoint.sh#L81

### Expected Behavior

Scans to work, loops in celery shouldn't happen.
```sh
celery-1       | Error: Invalid value for '-A' / '--app':
celery-1       | Unable to load celery application.
celery-1       | Module 'select' has no attribute 'epoll'
celery-1       | Usage: celery [OPTIONS] COMMAND [ARGS]...
celery-1       | Try 'celery --help' for help.
celery-1       | 
celery-1       | Error: Invalid value for '-A' / '--app':
celery-1       | Unable to load celery application.
celery-1       | Module 'select' has no attribute 'epoll'
celery-1       | Usage: celery [OPTIONS] COMMAND [ARGS]...
celery-1       | Try 'celery --help' for help.
celery-1       | 
celery-1       | Error: Invalid value for '-A' / '--app':
celery-1       | Unable to load celery application.
celery-1       | Module 'select' has no attribute 'epoll'
celery-1       | Usage: celery [OPTIONS] COMMAND [ARGS]...
celery-1       | Try 'celery --help' for help.
celery-1       | 
celery-1       | Error: Invalid value for '-A' / '--app':
celery-1       | Unable to load celery application.
celery-1       | Module 'select' has no attribute 'epoll'
celery-1       | Usage: celery [OPTIONS] COMMAND [ARGS]...
celery-1       | Try 'celery --help' for help.
```

### Steps To Reproduce

git clone https://github.com/yogeshojha/rengine.git
sudo ./install

### Environment

```markdown
- reNgine: 2.0.5
- OS: Raspberry Pi OS (bookworm), Fedora 40
- Python: 3.11.2
- Docker Engine: 26.1.1
- Docker Compose: 2.27.0
- Browser: Firefox, Chrome, Ungoogled Chromium
```

### Anything else?

see also: https://github.com/yogeshojha/rengine/issues/1234

**Comment by Talanor** [comment]
To add a bit more context here:
A modification from the default Dockerfile was made: arch is arm64 (for OS and go)

Probably one of this lib install breaks celery : https://github.com/laramies/theHarvester/blob/master/requirements/base.txt

Generally:
- pip (or any non os mainter supported package manager) as root should be avoided.
- virtual environments (venv, poetry, pipx, pick your poison) should be used for every python tool, including celery.
- Performing pull / clone every entrypoint call gives us a bleeding edge version of every tool that will inevitably break every so often, having premade docker image with known-to-work tools with versions bumbed every so often would help on that front

**Comment by shubhamvashist11** [comment]
```
_Removing the following line fixed the loop:
https://github.com/yogeshojha/rengine/blob/master/web/celery-entrypoint.sh#L81_
```

It didn't fix this for me. Any other workaround? @Talanor @metehan-arslan

**Comment by Talanor** [comment]
> ```
> _Removing the following line fixed the loop:
> https://github.com/yogeshojha/rengine/blob/master/web/celery-entrypoint.sh#L81_
> ```
> 
> It didn't fix this for me. Any other workaround? @Talanor @metehan-arslan

If you have initialized your container once, edit your celery-entrypoint.sh to keep only the celery workers launch lines at the end.
Then down and up the celery container.
If the issue persits, it is due to something else.

If it works, some pip install breaks celery.
add back lines you deleted slowly and down/up the celery container until it breaks to figure out which one.

I'm working on a container with venvs & pipx, but in the meantime that'll get you running.

**Comment by OffS3c** [comment]
[v](https://github.com/yogeshojha/rengine/issues/1248) This issue seems to be related.

**Comment by Talanor** [comment]
> #1248 This issue seems to be related. I was having the same output.

Unlikely, Infoga isn't cloned since it doesn't exist, so it can't make celery fail.
More likely, infoga wasn't cloned, hence the error, AND you had a broken install due to this issue.

**Comment by yogeshojha** [comment]
Hi, this looks very familiar to me. 
Which branch did you clone, is it master or release/2.1.0?

I had this exact issue when I tried to use ollama with celery and it has known issues. 

But on master this is very strange.

**Comment by Talanor** [comment]
This is on master, the discord is full of people with clean install having that bug.

**Comment by OffS3c** [comment]
Hey, I’ll share my working code in a bit.

[image: facebook] <https://www.facebook.com/jahanzaib.durrani.31>
[image: twitter] <https://twitter.com/OffS3c>
[image: linkedin] <https://www.linkedin.com/in/jakd/>
Jahanzaib Durrani

Founder

OffS3c LLC
+1 302 387 0024 <+1+302+387+0024> | + 92 343 206 2048 <++92+343+206+2048>
***@***.***
https://offs3c.com
16192 Coastal Hwy, Lewes, DE 19958, United States

**Comment by Nandolorian** [comment]
> If you have initialized your container once, edit your `./web/celery-entrypoint.sh` to keep only the celery workers launch lines at the end, which look something like:

I have the same behaviour in a fresh install of Ubuntu Server 240.4, I follow your advise and comment the lines in `./web/celery-entrypoint.sh`. I found that the error was generated by theHarvester in this line:

`python3 -m pip install -r /usr/src/github/theHarvester/requirements/base.txt`

In the file `base.txt` the library `fastapi==0.111.0` is the culprit.
I hope that this helps

**Comment by yogeshojha** [comment]
@Nandolorian Thank you! I am downgrading fastapi and let me try doing the installation!

**Comment by yogeshojha** [comment]
@Nandolorian I tired with downgraded fastapi, sadly it doesnt work. Do you mind sharing with me all the requirements version?

You can do this by 

`docker exec -it rengine-celery-1 bash`

and then

`pip freeze`

**Comment by yogeshojha** [comment]
Okay I think `httpcore` is the culprit here. 

https://github.com/python-trio/trio/issues/2848 

I had this exact same issue when using ollama-python because it uses `httpcore` library and our celery workers are gevent based. I guess finding which tool uses httpcore and removing them would solve this.

**Comment by Talanor** [comment]
Or, installing tools in venvs ;)

**Comment by yogeshojha** [comment]
@Talanor yeah venv would be better, but either ways when any of the tools reNgine uses httpcore it wont be able to work with gevent and celery. We might have to change the way these tools run outside celery or use another event pool.
But I am open to hearing how you think venv will help us solve this?

**Comment by Nandolorian** [comment]
> @Nandolorian I tired with downgraded fastapi, sadly it doesnt work. Do you mind sharing with me all the requirements version?
> 
> You can do this by
> 
> `docker exec -it rengine-celery-1 bash`
> 
> and then
> 
> `pip freeze`

I see you have discovered that `httpcore` is the problem. Anyway, I am posting the list for your reference in case it is still useful.

<details><summary>Requirements </summary>
aiofiles==23.2.1</br>
aiodns==3.2.0</br>
aiohttp==3.9.5</br>
aiomultiprocess==0.9.1</br>
aiosignal==1.3.1</br>
aiosqlite==0.20.0</br>
amqp==5.2.0</br>
annotated-types==0.6.0</br>
anyio==4.3.0</br>
appdirs==1.4.4</br>
argcomplete==3.3.0</br>
argh==0.26.2</br>
asgiref==3.8.1</br>
async-timeout==4.0.3</br>
attrs==23.2.0</br>
backoff==2.2.1</br>
beautifulsoup4==4.12.3</br>
billiard==4.2.0</br>
blinker==1.4</br>
Brotli==1.1.0</br>
bs4==0.0.1</br>
celery==5.4.0</br>
censys==2.2.12</br>
certifi==2024.2.2</br>
cffi==1.16.0</br>
chardet==5.0.0</br>
charset-normalizer==2.1.1</br>
click==8.1.7</br>
click-didyoumean==0.3.1</br>
click-plugins==1.1.1</br>
click-repl==0.3.0</br>
colorama==0.4.4</br>
coreapi==2.3.3</br>
coreschema==0.0.4</br>
cron-descriptor==1.4.3</br>
cryptography==3.4.8</br>
cssselect2==0.7.0</br>
dbus-python==1.2.18</br>
decorator==5.1.1</br>
Deprecated==1.2.14</br>
discord-webhook==1.3.0</br>
distro==1.7.0</br>
Django==3.2.4</br>
django-ace==1.0.11</br>
django-celery-beat==2.6.0</br>
django-login-required-middleware==0.6.1</br>
django-mathfilters==1.0.0</br>
django-role-permissions==3.2.0</br>
django-timezone-field==6.1.0</br>
djangorestframework==3.12.4</br>
djangorestframework-datatables==0.6.0</br>
dnspython==2.6.1</br>
dotted-dict==1.1.3</br>
drf-yasg==1.21.3</br>
et-xmlfile==1.1.0</br>
exceptiongroup==1.2.1</br>
exrex==0.10.5</br>
fastapi==0.110.3</br>
filelock==3.14.0</br>
fire==0.4.0</br>
fonttools==4.51.0</br>
frozenlist==1.4.1</br>
future==0.18.2</br>
fuzzywuzzy==0.18.0</br>
gevent==24.2.1</br>
greenlet==3.0.3</br>
gunicorn==22.0.0</br>
h11==0.14.0</br>
h8mail==2.5.6</br>
html5lib==1.1</br>
httplib2==0.20.2</br>
humanize==4.3.0</br>
idna==3.3</br>
importlib-metadata==4.6.4</br>
importlib_resources==6.4.0</br>
inflection==0.5.1</br>
itypes==1.2.0</br>
jeepney==0.7.1</br>
Jinja2==3.1.4</br>
keyring==23.5.0</br>
kombu==5.3.7</br>
launchpadlib==1.10.16</br>
lazr.restfulclient==0.14.4</br>
lazr.uri==1.0.6</br>
Levenshtein==0.25.1</br>
limits==3.11.0</br>
loguru==0.6.0</br>
lxml==5.2.1</br>
Markdown==3.3.4</br>
markdown-it-py==3.0.0</br>
MarkupSafe==2.1.5</br>
mdurl==0.1.2</br>
metafinder==1.2</br>
more-itertools==8.10.0</br>
multidict==6.0.5</br>
netaddr==1.2.1</br>
netlas==0.4.1</br>
oauthlib==3.2.0</br>
openai==0.28.0</br>
openpyxl==3.1.2</br>
orjson==3.9.0</br>
outcome==1.3.0.post0</br>
packaging==24.0</br>
pikepdf==8.15.1</br>
pillow==10.3.0</br>
playwright==1.43.0</br>
pluginbase==1.0.1</br>
prettytable==3.10.0</br>
prompt-toolkit==3.0.43</br>
psycopg2==2.9.7</br>
pycares==4.4.0</br>
pycparser==2.22</br>
pycvesearch==1.0</br>
pydantic==2.7.1</br>
pydantic_core==2.18.2</br>
pydyf==0.10.0</br>
pyee==11.1.0</br>
Pygments==2.18.0</br>
PyGObject==3.42.1</br>
PyJWT==2.3.0</br>
pyparsing==2.4.7</br>
pyphen==0.15.0</br>
PySocks==1.7.1</br>
python-apt==2.4.0+ubuntu3</br>
python-crontab==3.0.0</br>
python-dateutil==2.9.0.post0</br>
python-docx==1.1.2</br>
python-Levenshtein==0.25.1</br>
python-pptx==0.6.23</br>
pytz==2024.1</br>
PyVirtualDisplay==3.0</br>
PyYAML==6.0.1</br>
rapidfuzz==3.9.0</br>
redis==5.0.3</br>
requests==2.31.0</br>
requests-file==2.0.0</br>
retrying==1.3.4</br>
rich==13.7.1</br>
ruamel.yaml==0.18.6</br>
ruamel.yaml.clib==0.2.8</br>
scapy==2.4.3</br>
SecretStorage==3.3.1</br>
selenium==4.9.1</br>
shodan==1.31.0</br>
simplejson==3.19.2</br>
six==1.16.0</br>
slowapi==0.1.9</br>
sniffio==1.3.1</br>
sortedcontainers==2.4.0</br>
soupsieve==2.3.2</br>
SQLAlchemy==1.3.22</br>
sqlparse==0.5.0</br>
starlette==0.37.2</br>
tenacity==8.0.1</br>
termcolor==1.1.0</br>
tinycss2==1.3.0</br>
tinydb==4.8.0</br>
tldextract==3.5.0</br>
tqdm==4.64.0</br>
treelib==1.6.1</br>
trio==0.25.0</br>
trio-websocket==0.11.1</br>
typing_extensions==4.11.0</br>
tzdata==2024.1</br>
ujson==5.9.0</br>
uritemplate==4.1.1</br>
urllib3==1.26.9</br>
uro==1.0.0</br>
uvicorn==0.29.0</br>
uvloop==0.19.0</br>
validators==0.18.2</br>
vine==5.1.0</br>
wadllib==1.3.6</br>
wafw00f==2.2.0</br>
watchdog==4.0.0</br>
wcwidth==0.2.13</br>
weasyprint==53.3</br>
webencodings==0.5.1</br>
whatportis==0.8</br>
win32-setctime==1.1.0</br>
wrapt==1.16.0</br>
wsproto==1.2.0</br>
XlsxWriter==3.2.0</br>
xmltodict==0.13.0</br>
yarl==1.9.4</br>
zipp==1.0.0</br>
zope.event==5.0</br>
zope.interface==6.3</br>
zopfli==0.2.3</br>
</details>

**Comment by Talanor** [comment]
> @Talanor yeah venv would be better, but either ways when any of the tools reNgine uses httpcore it wont be able to work with gevent and celery. We might have to change the way these tools run outside celery or use another event pool. But I am open to hearing how you think venv will help us solve this?

Please see my PR #1250 that adresses the issue

**Comment by yogeshojha** [comment]
@Talanor your PR looks great, I liked the usage of poetry.

The problem is not conflicting versions of httcore or having multiple versions in same environment

> and our celery workers are gevent based, httpcore which is a coroutine-based networking library and uses blocking I/O, which conflicts with gevent's cooperative multitasking model as per my understanding.

**Comment by Talanor** [comment]
> @Talanor your PR looks great, I liked the usage of poetry.
> 
> The problem is not conflicting versions of httcore or having multiple versions in same environment
> 
> > and our celery workers are gevent based, httpcore which is a coroutine-based networking library and uses blocking I/O, which conflicts with gevent's cooperative multitasking model as per my understanding.

I must be missing something. I don't see httpcore in their pip freeze list?

@Nandolorian can you confirm newest master works on a fresh install for you?

**Comment by Talanor** [comment]
Upon further investigation:
The celery workers from my PR do not install httpcore (as seen in my venv):
```bash
talanor@pentest:~/containers/reNgine-CaRE$ docker run --entrypoint /bin/bash -it talanor/rengine-celery:v0.3 
rengine@909fc90322cc:~/rengine$ ls
rengine@909fc90322cc:~/rengine$ cd
rengine@909fc90322cc:~$ ls
nuclei-templates  poetry.lock  pyproject.toml  rengine  results  scan_results  tools  wordlists
rengine@909fc90322cc:~$ poetry -C . shell
Spawning shell within /home/rengine/.cache/pypoetry/virtualenvs/celery-rengine-HmEJnPQT-py3.10
rengine@909fc90322cc:~$ . /home/rengine/.cache/pypoetry/virtualenvs/celery-rengine-HmEJnPQT-py3.10/bin/activate
(celery-rengine-py3.10) rengine@909fc90322cc:~$ pip list
Package                          Version
-------------------------------- -----------
aiodns                           3.0.0
aiohttp                          3.9.5
aiosignal                        1.3.1
amqp                             5.2.0
appdirs                          1.4.4
argh                             0.26.2
asgiref                          3.8.1
async-timeout                    4.0.3
attrs                            23.2.0
beautifulsoup4                   4.9.3
billiard                         4.2.0
Brotli                           1.1.0
celery                           5.4.0
certifi                          2024.2.2
cffi                             1.16.0
charset-normalizer               3.3.2
click                            8.1.7
click-didyoumean                 0.3.1
click-plugins                    1.1.1
click-repl                       0.3.0
coreapi                          2.3.3
coreschema                       0.0.4
cron-descriptor                  1.4.3
cssselect2                       0.7.0
decorator                        5.1.1
Deprecated                       1.2.14
discord-webhook                  1.3.0
Django                           3.2.4
django-ace                       1.0.11
django-celery-beat               2.6.0
django-login-required-middleware 0.6.1
django-mathfilters               1.0.0
django-role-permissions          3.2.0
django-timezone-field            6.1.0
djangorestframework              3.12.4
djangorestframework-datatables   0.6.0
dotted-dict                      1.1.3
drf-yasg                         1.21.3
et-xmlfile                       1.1.0
filelock                         3.14.0
fonttools                        4.51.0
frozenlist                       1.4.1
gevent                           24.2.1
greenlet                         3.0.3
gunicorn                         22.0.0
html5lib                         1.1
humanize                         4.3.0
idna                             3.7
inflection                       0.5.1
itypes                           1.2.0
Jinja2                           3.1.4
kombu                            5.3.7
lxml                             5.2.1
Markdown                         3.3.4
MarkupSafe                       2.1.5
metafinder                       1.2
multidict                        6.0.5
netaddr                          0.8.0
netlas                           0.4.1
openai                           0.28.0
openpyxl                         3.1.2
orjson                           3.9.0
packaging                        24.0
pikepdf                          8.15.1
pillow                           10.3.0
pip                              24.0
prettytable                      2.1.0
prompt-toolkit                   3.0.43
psycopg2                         2.9.7
pycares                          4.4.0
pycparser                        2.22
pycvesearch                      1.0
pydyf                            0.10.0
Pygments                         2.18.0
pyphen                           0.15.0
PySocks                          1.7.1
python-crontab                   3.0.0
python-dateutil                  2.9.0.post0
python-docx                      1.1.2
python-pptx                      0.6.23
pytz                             2024.1
PyYAML                           6.0.1
redis                            5.0.3
requests                         2.31.0
requests-file                    2.0.0
ruamel.yaml                      0.18.6
ruamel.yaml.clib                 0.2.8
scapy                            2.4.3
setuptools                       69.5.1
simplejson                       3.17.2
six                              1.16.0
soupsieve                        2.5
sqlparse                         0.5.0
tinycss2                         1.3.0
tinydb                           4.4.0
tldextract                       3.5.0
tqdm                             4.66.4
typing_extensions                4.11.0
tzdata                           2024.1
uritemplate                      4.1.1
urllib3                          2.2.1
uro                              1.0.0
validators                       0.18.2
vine                             5.1.0
watchdog                         4.0.0
wcwidth                          0.2.13
weasyprint                       53.3
webencodings                     0.5.1
whatportis                       0.8.2
wrapt                            1.16.0
XlsxWriter                       3.2.0
xmltodict                        0.13.0
yarl                             1.9.4
zope.event                       5.0
zope.interface                   6.3
zopfli                           0.2.3
```
However, it is installed as a fastapi dependency from theHarvester.
Installing theHarvester via venv do not install httpcore in the celery environment, and does not introduce conflict.

Basically, if you can fix it by hot removing a package via pip, its something that can (should) be solved with venvs.
