### ISSUE TITLE
error login panel 

### ISSUE THREAD

**Issue by cehbikramrock** [yogeshojha/rengine#125]
`docker exec -it rengine_web_1 python manage.py createsuperuser`
not work !!

''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''''
┌─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #sudo docker exec -it rengine_web_1 python3 manage.py createsuperuser
Error: No such container: rengine_web_1

**Comment by Creased** [comment]
The Docker containers must be created and started before trying to setup users. Can you show us the output of the following command:

```bash
docker ps -a
```

**Comment by cehbikramrock** [comment]
sure sir !!


─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker ps -a
CONTAINER ID        IMAGE                  COMMAND                  CREATED             STATUS                     PORTS                              NAMES
2292be712d0f        rengine-master_web     "/app/docker-entrypo…"   6 hours ago         Up 2 minutes               0.0.0.0:8000->8000/tcp             rengine-master_web_1
534db44e7301        postgres:12.3-alpine   "docker-entrypoint.s…"   6 hours ago         Up 2 minutes               5432/tcp, 0.0.0.0:5433->5433/tcp   rengine-master_db_1
796fddb6e8d1        hello-world            "/hello"                 7 hours ago         Exited (0) 7 hours ago                                        agitated_antonelli
3a8573d4a52a        ubuntu                 "bash"                   7 hours ago         Exited (130) 7 hours ago                                      loving_nash
02737056881b        hello-world            "/hello"                 7 hours ago         Exited (0) 7 hours ago                                        peaceful_swanson

**Comment by JoshuaMart** [comment]
Hi,
Maybe try to stop all your containers & relaunch rengine.

```
docker stop $(docker ps -a -q)
#Inside rengine directory 
docker-compose up -d
```

Regards

**Comment by Creased** [comment]
The container namespace ID for docker-compose services is defined based on the current working directory name ("rengine-master" here).

Here is a quick fix:

```bash
docker-compose down
cat <<-'EOF' >.env
COMPOSE_PROJECT_NAME=rengine

EOF
docker-compose up -d
docker exec -it rengine_web_1 python manage.py createsuperuser
```

**Comment by cehbikramrock** [comment]
Dear sir !
i still found same problems.
┌─[✗]─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker-compose up -d
rengine-master_db_1 is up-to-date
rengine-master_web_1 is up-to-date
┌─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker ps -a -q
985fdff16b3f
59adf89bd2c3
796fddb6e8d1
3a8573d4a52a
02737056881b
┌─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker-compose down 
Stopping rengine-master_web_1 ... done
Stopping rengine-master_db_1  ... done
Removing rengine-master_web_1 ... done
Removing rengine-master_db_1  ... done
Removing network rengine-master_rengine_network
┌─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker exec -it rengine_web_1 python manage.py createsuperuser
Error: No such container: rengine_web_1
