### ISSUE TITLE
For Request Smuggling Identification - Add this Tool

### ISSUE THREAD

**Issue by danzee1** [yogeshojha/rengine#126]
**Is your feature request related to a problem? Please describe.**

Tool need to be powered with http request smuggling identification mechanism. 

**Describe the solution you'd like**

Adding this tool will 

```
https://github.com/defparam/smuggler

```

**Comment by aoprea1982** [comment]
Thank you for the great application. 

Also this script is interesting 

[https://github.com/gwen001/pentest-tools/blob/master/smuggler.py](url)
