### ISSUE TITLE
feat: Need a way to exclude Url paths

### ISSUE THREAD

**Issue by Kuldran** [yogeshojha/rengine#1264]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

when initiating a scan I would need a way to exclude certain URLs paths. This would require wildcard support as well.

example.com/api/somerandomapi/*
example.com/img/*.jpeg

This way the scanners don't waste time on URLs that we are not interested in or can have endless link-backs.

**Comment by yogeshojha** [comment]
This has been implemented in 2.2.0 :partying_face:
