### ISSUE TITLE
Stop All Scans KillSwitch

### ISSUE THREAD

**Issue by tHeStRyNg** [yogeshojha/rengine#1270]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Would be interesting to have a kill switch in which in large asset scannings, we would be able to stop all scans on one click or by organization if defined as at the moment if we have 200 assets we have to go one by one to stop them which isnt useful.

**Comment by yogeshojha** [comment]
@tHeStRyNg Thank you for the feature request.

This has been added and will be available in next release. 

https://github.com/yogeshojha/rengine/pull/1321

**Comment by yogeshojha** [comment]
This is released in reNgine 2.2.0, checkout: [What's new in 2.2.0](https://rengine.wiki/whats-new/2_2_0/)
