### ISSUE TITLE
UI CSS files rendering

### ISSUE THREAD

**Issue by sar12332111** [yogeshojha/rengine#1271]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

http://localhost:8000/path/to/css/file.css
The CSS is not getting rendered ( 500 server error)
<img width="263" alt="Screenshot 2024-05-28 at 2 58 28 PM" src="https://github.com/yogeshojha/rengine/assets/160210068/9d2aea68-0dc9-4cdd-ab9e-61b503b1b7b0">

### Expected Behavior

Proper UI rendering

### Steps To Reproduce

NA

### Environment

```markdown
Mac OS
```

**Comment by yogeshojha** [comment]
Please read documentation carefully, port 8000 is to be used only when you are using local development. You can access UI from https://127.0.0.1
