### ISSUE TITLE
bug:The vulnerability scan does not finish its execution.

### ISSUE THREAD

**Issue by lucasRivas19** [yogeshojha/rengine#1273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The vulnerability scan does not complete its execution. 
Previously it threw an exception for null when running the scan for low vulnerabilities. To fix this, add a condition in the function: record_exists(model, data, exclusion_keys=[]):
	"""
	Check if a record already exists in the database based on the data provided.

	Arguments:
		model (django.db.models.Model) – The Django model to compare against.
		data (dict): Data dictionary containing fields and values.
		exclude_keys (list) – List of keys to exclude from the search.

	Returns:
		bool: True if the record exists, False otherwise.
	"""

	# Extract the keys to be used for the search.
	lookup_fields = {key: data[key] to enter data if key is not in exclude_keys}
	if search_fields:
    	return model.objects.filter(**lookup_fields).exists()
	the rest:
    	false return
but once I fix this, it doesn't finish my core scans.

### Expected Behavior

I want the vulnerability scan to be completed

### Steps To Reproduce

1- perform recommended scan

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
@lucasRivas19 But,

`return model.objects.filter(**lookup_fields).exists()`

this returns True or False otherwise.

what do you mean by "Previously it threw an exception for null when running the scan for low vulnerabilities."

I don't see any problem here.

**Comment by yogeshojha** [comment]
closed dur to inactivity and could not reproduce
