### ISSUE TITLE
bug: Redis Cache Container does not restart after server reboot

### ISSUE THREAD

**Issue by null-ref-0000** [yogeshojha/rengine#1274]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After restarting a server with rengine installed, the redis cache container does not restart. 

### Expected Behavior

After restarting a server with rengine installed, the redis cache container restarts. 

### Steps To Reproduce

1. Restart server
2. observe that redis cache is not restarted automatically

### Environment

```markdown
- reNgine: 2.0.6
- OS: Debian 6.1.90-1
- Browser: Chrome
```

**Comment by yogeshojha** [comment]
This is fixed in 2.1.0
