### ISSUE TITLE
bug: screenshot fails with error

### ISSUE THREAD

**Issue by Rho-9-Official** [yogeshojha/rengine#1279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="208" alt="image" src="https://github.com/yogeshojha/rengine/assets/132458958/93dc43db-7075-484d-b257-3f0b13e6ae86">

### Expected Behavior

Well, we all expect a screenshot of the site,lol

### Steps To Reproduce

rengine was installed on Kali linux, following the instructions exactly. installation went perfectly as far as I could tell.
how to reproduce: well it appears that the issue crops up on all sites I've scanned so far, so pick one, I guess.

running latest version of kali, using python 3.11.8 and docker version 20.10.25
<img width="206" alt="image" src="https://github.com/yogeshojha/rengine/assets/132458958/a9596fe9-3932-49d8-a5e8-84ebb8fe0f61">

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
Hi @Rho-9-Official This is fixed in reNgine 2.1.0
