### ISSUE TITLE
bug: clocked scan and Periodic Scan is not working 

### ISSUE THREAD

**Issue by vamshivaran1** [yogeshojha/rengine#1287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've configured both clocked and periodic scans for a target. Despite the scan run count indicating 1, no results are appearing in the results tab or anywhere else. Has anyone else encountered this issue? Any suggestions or solutions?
<img width="1385" alt="Screenshot 2024-06-25 at 11 07 32 AM" src="https://github.com/yogeshojha/rengine/assets/40388956/ed483ae0-e650-47c9-a9a9-43d1044e58d5">

### Expected Behavior

Once the scheduled scan runs it should show the results in the "scan history".

### Steps To Reproduce

mk

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by Who-AmI** [comment]
I'm also having the same issue

**Comment by yogeshojha** [comment]
@vamshivaran1 @Who-AmI 

Thank you for reporting this guys, a lot of things were missed during the last refactoring. Now it's been fixed. 

Once merged, you can pull the latest changes.

Thank you
