### ISSUE TITLE
bug: Unable to Download Endpoints with Specific Pattern

### ISSUE THREAD

**Issue by ya3raj** [yogeshojha/rengine#1288]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi, rengine currently doesn't download the  Endpoints with Specific Pattern that falls under  Scan Findings > URLs > Download
Suppose if i click on Download Endpoints with Pattern XSS. It downloads "ALL Endpoints" instead of the XSS Patterns.

### Expected Behavior

After Selecting the Download Endpoints with Pattern XSS. The tool should sort out the file with only possible XSS URLs and download them.

### Steps To Reproduce

1. Login to the tool
2. Perform a scan on your domain
3. Go to scan findings > URLs > Download
4. Click on Download Endpoints with Pattern XSS
5. Check the downloaded files, which has ALL ENDPOINTS instead of XSS ENDPOINTS.

![image](https://github.com/yogeshojha/rengine/assets/59885197/50f69016-dc42-4bc2-919e-7106905efc25)

### Environment

```markdown
- reNgine: 2.1.0
- OS: Ubuntu
- Python: 3
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
Closed due to inactivity
