### ISSUE TITLE
bug: reNgine Installation failed: "sudo ./install.sh -n" | "unknown shorthand flag: 'f' in -f" | make: *** [Makefile:17: certs] Error 125

### ISSUE THREAD

**Issue by 0xKayala** [yogeshojha/rengine#1291]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After cloning the rengine repo and changing the "POSTGRES_PASSWORD" password and giving the execution permissions with the command: "chmod +x install.sh". I have executed the following command: sudo ./install.sh -n, but I got an error at "unknown shorthand flag: 'f' in -f" and "make: *** [Makefile:17: certs] Error 125".

I have attached the screenshots for reference, please kindly look into it and let me know the possible resolution so that I can work on it to fix the issue from my end.

Reference Screenshots:

![rengine 001](https://github.com/yogeshojha/rengine/assets/16838353/cd47d1a2-ce07-49a7-ad4f-b6bfecfe266b)
![rengine 002](https://github.com/yogeshojha/rengine/assets/16838353/1a43a979-b932-44dd-a693-2df645858ccb)
![rengine 003](https://github.com/yogeshojha/rengine/assets/16838353/5304f2a5-0131-4f56-a48d-e99e20f1affd)

### Expected Behavior

It needs to be executed without any issues.

### Steps To Reproduce

Followed the required steps:
1. git clone https://github.com/yogeshojha/rengine && cd rengine
2. nano .env
3. chmod +x install.sh
4. sudo ./install.sh or sudo ./install.sh -n

### Environment

```markdown
- reNgine: 2.1.0
- OS: Linux kali 6.8.11-amd64
- Python: 3.11.9
- Docker Engine: 
- Docker Compose: 20.10.25+dfsg1
```

**Comment by purpleracc00n** [comment]
Had this issue myself, it appeared to be caused by the "docker compose" command in make.bat and Makefile. I changed it to docker-compose and it worked for me. Think it has to do with the docker compose versions.

**Comment by yogeshojha** [comment]
Hi @0xKayala @purpleracc00n which version of docker compose you have?

**Comment by purpleracc00n** [comment]
─$ docker version
Client:
 Version:           20.10.25+dfsg1
 API version:       1.41
 Go version:        go1.21.3
 Git commit:        b82b9f3
 Built:             Wed Oct 18 17:36:27 2023
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.21.3
  Git commit:       5df983c
  Built:            Wed Oct 18 17:36:27 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24~ds1
  GitCommit:        1.6.24~ds1-1
 runc:
  Version:          1.1.10+ds1
  GitCommit:        1.1.10+ds1-1
 docker-init:
  Version:          0.19.0
  GitCommit:        


Docker Compose version v2.5.0

**Comment by sunyyer** [comment]
My solution is to modify the -f configurations in the Makefile and replace them with docker-compose. Because the new version is no longer needed, but the earlier version is still needed.

**Comment by calincoj** [comment]
Had this issue  too, just replace all "docker compose" in make.bat and Makefile with docker-compose

**Comment by Rho-9-Official** [comment]
> Had this issue too, just replace all "docker compose" in make.bat and Makefile with docker-compose

just tried that, looks like it's working.

**Comment by yogeshojha** [comment]
Thank you @0xKayala for reporting this. Yes we should make this available for both v1 and v2 versions of docker compose. While it is recommended to update to v2 of docker compose but supporting both versions makes sense.

As suggested by @calincoj and @Rho-9-Official I have made changes to makefile, to check for version and use apt command.

I would appreciate if someone of you could test this https://github.com/yogeshojha/rengine/pull/1302

**Comment by hetvaishnav1106** [comment]
Checking Docker status                                                                             
#########################################################################                          
Docker is running.                                                                                 
                                                                                                   
#########################################################################                          
Installing reNgine                                                                                 
#########################################################################                          
.env:38: *** missing separator.  Stop.                                                             
                                                                                                   
reNgine installation failed!! 



i am getting this error during installation . what should i do?
