### ISSUE TITLE
DataTables warning: table id=list_target_table - Ajax error

### ISSUE THREAD

**Issue by m0ng3sh3ll** [yogeshojha/rengine#1295]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When invoking the function to list targets, this error is shown:

DataTables warning: table id=list_target_table - Ajax error

This happened after updating to the new version 2.1.0 using update.sh.

### Expected Behavior

List targets from project

### Steps To Reproduce

1. Run update.sh;
2. Create new project;
3. Insert new target;
4. When invoking the function to list targets, this error is shown.

### Environment

```markdown
- reNgine: 2.1.0
- OS: Ubuntu 24.04 LTS
- Python: 3.12.3
- Docker Engine: 26.1.2 
- Docker Compose: v2.27.0
- Browser: Chrome and Firefox
```

**Comment by haimtoledano** [comment]
same here

**Comment by yogeshojha** [comment]
@haimtoledano @m0ng3sh3ll When does this happen? I am trying to replicate and do not see this happening on my local instance.

If I understand correctly when you go to targets section `/target/project_name/list/target` is this where datatable warning pops up?

**Comment by m0ng3sh3ll** [comment]
Hi, it's correct.

I try install from zero, create a new project, add one target and the problem continues.

**Comment by yogeshojha** [comment]
Thank you for the prompt update @m0ng3sh3ll 

Do you mind pasting console logs here?

Go as usual where error is there, right click, inspect and go to console tab. Thsi will help me debug the issue.

Thanks

**Comment by m0ng3sh3ll** [comment]
Following the console log:

First error 500:

GET
scheme
	https
host
	localhost
filename
	/api/scan_status/
project
	recon
Address
	127.0.0.1:443
Status
500
VersionHTTP/2
Transferred400 B (145 B size)
Referrer Policysame-origin
DNS ResolutionSystem

And the second error 500:

scheme
	https
host
	localhost
filename
	/api/listTargets/
format
	datatables
slug
	recon
draw
	1
columns[0][data]
	id
columns[0][name]
	
columns[0][searchable]
	true
columns[0][orderable]
	false
columns[0][search][value]
	
columns[0][search][regex]
	false
columns[1][data]
	id
columns[1][name]
	
columns[1][searchable]
	true
columns[1][orderable]
	true
columns[1][search][value]
	
columns[1][search][regex]
	false
columns[2][data]
	name
columns[2][name]
	
columns[2][searchable]
	true
columns[2][orderable]
	true
columns[2][search][value]
	
columns[2][search][regex]
	false
columns[3][data]
	description
columns[3][name]
	
columns[3][searchable]
	true
columns[3][orderable]
	false
columns[3][search][value]
	
columns[3][search][regex]
	false
columns[4][data]
	id
columns[4][name]
	
columns[4][searchable]
	true
columns[4][orderable]
	true
columns[4][search][value]
	
columns[4][search][regex]
	false
columns[5][data]
	start_scan_date
columns[5][name]
	
columns[5][searchable]
	true
columns[5][orderable]
	true
columns[5][search][value]
	
columns[5][search][regex]
	false
columns[6][data]
	id
columns[6][name]
	
columns[6][searchable]
	true
columns[6][orderable]
	false
columns[6][search][value]
	
columns[6][search][regex]
	false
columns[7][data]
	organization
columns[7][name]
	
columns[7][searchable]
	true
columns[7][orderable]
	true
columns[7][search][value]
	
columns[7][search][regex]
	false
columns[8][data]
	most_recent_scan
columns[8][name]
	
columns[8][searchable]
	true
columns[8][orderable]
	true
columns[8][search][value]
	
columns[8][search][regex]
	false
columns[9][data]
	insert_date
columns[9][name]
	
columns[9][searchable]
	true
columns[9][orderable]
	true
columns[9][search][value]
	
columns[9][search][regex]
	false
columns[10][data]
	insert_date_humanized
columns[10][name]
	
columns[10][searchable]
	true
columns[10][orderable]
	true
columns[10][search][value]
	
columns[10][search][regex]
	false
columns[11][data]
	start_scan_date_humanized
columns[11][name]
	
columns[11][searchable]
	true
columns[11][orderable]
	true
columns[11][search][value]
	
columns[11][search][regex]
	false
order[0][column]
	1
order[0][dir]
	desc
start
	0
length
	20
search[value]
	
search[regex]
	false
_
	1720147897509
Address
	127.0.0.1:443
Status
500
VersionHTTP/2
Transferred400 B (145 B size)
Referrer Policysame-origin
DNS ResolutionSystem

**Comment by yogeshojha** [comment]
@m0ng3sh3ll is this from console tab? Very weird to have so

I am trying to see the logs from this console tab.
![image](https://github.com/yogeshojha/rengine/assets/17223002/1bd2d4f4-34d0-4af0-95c0-0d480d2b6661)

**Comment by m0ng3sh3ll** [comment]
Following the screenshot from console for better visualization:

![image](https://github.com/yogeshojha/rengine/assets/71721343/c286756c-2f40-4740-85e3-02d0861a82b7)

**Comment by yogeshojha** [comment]
@m0ng3sh3ll Thank you for the screenshot.

There are two things going wrong here, your scan_status endpoint also has 500 error. weird to have.

I believe issue isnt directly with datatable, rather scan_status api, when you click on GET /api/scan_status what does it show?

**Comment by m0ng3sh3ll** [comment]
For both cases, the return is 500:

![image](https://github.com/yogeshojha/rengine/assets/71721343/566fb7c8-764f-414d-9da9-dd75382f269d)

![image](https://github.com/yogeshojha/rengine/assets/71721343/ce511426-1367-47e4-b577-d264942d04b6)

**Comment by yogeshojha** [comment]
@m0ng3sh3ll Thank you for verifying.

looks like #1297 and this are related. Let me try to debug update as you said from 2.0.X to 2.1.0

**Comment by m0ng3sh3ll** [comment]
The solution show in the #1297 resolved the problem. 

Thank you very much for your support.
