### ISSUE TITLE
Server Error 500

### ISSUE THREAD

**Issue by bagialuudan** [yogeshojha/rengine#1297]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When i update ver 2.0.6 -> 2.1, I cannot access web because this is server error 500 

### Expected Behavior

log:
django.server | "GET /favicon.ico HTTP/1.0" 302 0
django.server | "GET /login/?next=/favicon.ico HTTP/1.0" 200 4516
django.server | "POST /login/?next=/default/dashboard/ HTTP/1.0" 200 4884
django.server | "GET /favicon.ico HTTP/1.0" 302 0
django.server | "GET /login/?next=/favicon.ico HTTP/1.0" 200 4516
django.server | "POST /login/?next=/default/dashboard/ HTTP/1.0" 200 4884
django.server | "GET /favicon.ico HTTP/1.0" 302 0
django.server | "GET /login/?next=/favicon.ico HTTP/1.0" 200 4516
django.server | "POST /login/?next=/default/dashboard/ HTTP/1.0" 302 0
django.server | "GET /default/dashboard/ HTTP/1.0" 500 145
django.server | "GET /favicon.ico HTTP/1.0" 500 145
django.server | "GET /default/dashboard/ HTTP/1.0" 500 145
django.server | "GET /favicon.ico HTTP/1.0" 500 145
django.server | "GET /default/dashboard/ HTTP/1.0" 500 145
django.server | "GET /favicon.ico HTTP/1.0" 500 145
django.server | "GET / HTTP/1.1" 302 0
django.server | "GET /favicon.ico HTTP/1.1" 302 0
django.server | "GET /favicon.ico HTTP/1.1" 302 0
django.server | "GET /favicon.ico HTTP/1.1" 302 0
django.server | "GET /favicon.ico HTTP/1.1" 302 0
django.server | "GET /login/?next=/default/dashboard/ HTTP/1.1" 200 4516
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "GET /default/dashboard/ HTTP/1.1" 302 0
django.server | "POST /login/?next=/default/dashboard/ HTTP/1.0" 403 1019
django.server | "GET /favicon.ico HTTP/1.0" 500 145
django.server | "GET /login/?next=/default/dashboard/ HTTP/1.0" 200 4940
django.server | "GET /favicon.ico HTTP/1.0" 500 145
django.server | "POST /login/?next=/default/dashboard/ HTTP/1.0" 200 4884
django.server | "GET /favicon.ico HTTP/1.0" 500 145
django.server | "POST /login/?next=/default/dashboard/ HTTP/1.0" 200 4884
django.server | "GET /favicon.ico HTTP/1.0" 500 145
django.server | "POST /login/?next=/default/dashboard/ HTTP/1.0" 302 0
django.server | "GET /default/dashboard/ HTTP/1.0" 500 145
django.server | "GET /favicon.ico HTTP/1.0" 500 145

### Steps To Reproduce

1. update new version
2. down all service
3. restart service
4. web error 500 when i login

### Environment

```markdown
- reNgine: 2.1.0
- OS: Ubuntu
- Python: 3.8.10
- Docker Engine: 20.10.21
- Docker Compose: 2.5
- Browser: Chrome Version 126.0.6478.127 (Official Build) (64-bit)
```

**Comment by bagialuudan** [comment]
I tried but it did not run

**Comment by bagialuudan** [comment]
I think rengine-web has encountered an error. I set it to debug mode but still couldn't find the log. I forwarded the port to my machine without going through a proxy and still experienced a login error

**Comment by yogeshojha** [comment]
@bagialuudan @null-ref-0000 @m0ng3sh3ll

I found the root cause for both of these issues but far from finding a solution for it. The problem is that in 2.1.0 we introduced this field in Scans called `initiated_by`, meaning its a field to show who has initiated the scan. 
That was not there in previous versions and there's been issue in django migration that the table schema does not have `initiated_by`.

I have tried everything to resolve this, but looks like no chance.

The only option would be to flush out all scan history, that means you will loose all the scans but targets will remain as it is.

you can use this command 

`sudo docker exec -it rengine-web-1 python3 manage.py migrate startScan zero`

**Please note that while targets will remain as it is, but the scan history will be flushed out, and app will continue to work**

**Comment by bagialuudan** [comment]
> @bagialuudan @null-ref-0000 @m0ng3sh3ll
> 
> I found the root cause for both of these issues but far from finding a solution for it. The problem is that in 2.1.0 we introduced this field in Scans called `initiated_by`, meaning its a field to show who has initiated the scan. That was not there in previous versions and there's been issue in django migration that the table schema does not have `initiated_by`.
> 
> I have tried everything to resolve this, but looks like no chance.
> 
> The only option would be to flush out all scan history, that means you will loose all the scans but targets will remain as it is.
> 
> you can use this command
> 
> `sudo docker exec -it rengine-web-1 python3 manage.py migrate startScan zero`
> 
> **Please note that while targets will remain as it is, but the scan history will be flushed out, and app will continue to work**

**Comment by bagialuudan** [comment]
@yogeshojha  @null-ref-0000  @m0ng3sh3ll  I found the root, because the database was too old, something might have been added to the database during the update, so when setting up the web, it mount the old database which caused the web to not load data. I have deleted and reinstalled the database and everything is fine now, you can try it
