### ISSUE TITLE
feat: <i have upgraded to 2.1.0, im facing issue when i start for scanning after sometime it gets failed>

### ISSUE THREAD

**Issue by Naina1723** [yogeshojha/rengine#1304]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

last week i have created an issue here, you have suggested me to share the yml file and redeploy again i did that but still it is not working, i'm unable to find that issue we discussed here.i am reopening this issue again "we have upgraded to  2.1.0, i'm facing  issue when i start for scanning after sometime it gets failed.

**Comment by yogeshojha** [comment]
Can you share your logs? Without sharing logs how can we identify the issue?

**Comment by Naina1723** [comment]
i have attached the screenshot.
*Thanks & Regards,*
Naina Shaik
DevOps Engineer
E:* ***@***.*** ***@***.***>*

**Comment by yogeshojha** [comment]
Where is the screenshot?

**Comment by Naina1723** [comment]
*Thanks & Regards,*
Naina Shaik
DevOps Engineer
E:* ***@***.*** ***@***.***>*

**Comment by Naina1723** [comment]
PFA

*Thanks & Regards,*
Naina Shaik
DevOps Engineer
E:* ***@***.*** ***@***.***>*

**Comment by yogeshojha** [comment]
closing as spam. no screenshots attached even after multiple request
