### ISSUE TITLE
bug: release 2.1.0 error on install

### ISSUE THREAD

**Issue by x81kilo** [yogeshojha/rengine#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

failed to solve: executor failed running [/bin/sh -c printf "    github.com/jaeles-project/gospider@latest\n    github.com/tomnomnom/gf@latest\n    github.com/tomnomnom/unfurl@latest\n    github.com/tomnomnom/waybackurls@latest\n    github.com/projectdiscovery/httpx/cmd/httpx@latest\n    github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest\n    github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest\n    github.com/projectdiscovery/naabu/v2/cmd/naabu@latest\n    github.com/hakluke/hakrawler@latest\n    github.com/lc/gau/v2/cmd/gau@latest\n    github.com/owasp-amass/amass/v3/...@latest\n    github.com/ffuf/ffuf@latest\n    github.com/projectdiscovery/tlsx/cmd/tlsx@latest\n    github.com/hahwul/dalfox/v2@latest\n    github.com/projectdiscovery/katana/cmd/katana@latest\n    github.com/dwisiswant0/crlfuzz/cmd/crlfuzz@latest\n    github.com/sa7mon/s3scanner@latest\n" |     xargs -L1 go install -ldflags="-s -w" -v &&     rm -rf /go/pkg/* && rm -rf /root/.cache/go-build]: exit code: 123
make: *** [Makefile:30: build] Error 17

### Expected Behavior

work?

### Steps To Reproduce

use current release to clone and run sudo install.sh

### Environment

```markdown
- reNgine: 
- OS: kali linux release 2023.3 on virtualbox
- Python: 3.11.8
- Browser: didnt get that far, but firefox latest version

Docker version:
sudo docker version 
Client:
 Version:           20.10.25+dfsg1
 API version:       1.41
 Go version:        go1.22.3
 Git commit:        b82b9f3
 Built:             Tue May  7 10:33:18 2024
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.25+dfsg1
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.22.3
  Git commit:       5df983c
  Built:            Tue May  7 10:33:18 2024
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.24~ds1
  GitCommit:        1.6.24~ds1-2
 runc:
  Version:          1.1.12+ds1
  GitCommit:        1.1.12+ds1-2
 docker-init:
  Version:          0.19.0
  GitCommit:
```

### Anything else?

please be gentle, I am fresh to linux, git and docker especially.  I really want to test out your software and looking forward to supportive comments to resolve.

Thank you in advance for taking the time to assist me.

**Comment by yogeshojha** [comment]
Hey @x81kilo 

It looks like that was a temporary network issue, I just installed reNgine on a fresh digital ocean droplet, the master branch, and works perfectly fine

![image](https://github.com/user-attachments/assets/e18e2101-b597-40ad-aac9-7936ed97b510)


After installation

![image](https://github.com/user-attachments/assets/a2c2f24c-ff3e-4d07-a8e0-3ddb161f5fab)

**Comment by x81kilo** [comment]
Thanks will retry again.
