### ISSUE TITLE
Can' use Note

### ISSUE THREAD

**Issue by bagialuudan** [yogeshojha/rengine#1310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I use the note feature in 'Add Recon todo/note' in All Subdomain." But it not running.

### Expected Behavior

Bottom Add Recon/Todo not working

### Steps To Reproduce

1. Enter Scan History
2. Click All Subdomain
3. Use Todo/note (It's not working)

### Environment

```markdown
- reNgine: 2.1
- OS: Ubuntu 20.04.6 LTS
- Python: Python 3.8.10doe
- Docker Engine: Docker version 24.0.7
- Docker Compose: Docker version 24.0.7
- Browser: Version 126.0.6478.127
```

**Comment by yogeshojha** [comment]
Hi @bagialuudan Thank you for reporting. 

There was indeed issue, it has now been fixed.
