### ISSUE TITLE
bug: <title>

### ISSUE THREAD

**Issue by meetgyn** [yogeshojha/rengine#1312]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I am using the last Rengine Docker Version
I am trying to add the Dirsearch and WPSCAN in Rengine, but to no avail.
Another problem I am finding and how to edit the scans engines? it is possible ?

### Expected Behavior

Botao de Editar Scan Engines does not appear

### Steps To Reproduce

1 I installed WPSCAN and DIRSEARCH IN CONTAINER
2 I added in plugins
3 I configured the line of commands for execution
Is not working.

### Environment

```markdown
- reNgine: 2.1.0
- OS: Docker
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
wpscan isnt currently supported.
