### ISSUE TITLE
Feature - Add Pause Option

### ISSUE THREAD

**Issue by moriarity9211** [yogeshojha/rengine#132]
If possible please add Pause option to Stop Scan for one domain and being active for others 
.

**Comment by maverickNerd** [comment]
Pause is not possible I guess, as it utilizes other tools and runs those commands. Interrupting them in between will mess results.

**Comment by attacker007** [comment]
Hi @maverickNerd  I think a sudden pause may not be possible.. But a slow Pause process is possible... Many tools have that function.

**Comment by maverickNerd** [comment]
Yes once the current threads/process is over, it can be done. Agree with you.

**Comment by yogeshojha** [comment]
Hi All, yes this feature is coming soon. I am working on migrating threads to Celery. Celery will allow you to schedule scans periodically in the future,  retry auto when scan fails, and many more..

I will keep you updated on the progress.
