### ISSUE TITLE
bug: Error 500 when creating a "Periodic Scan" or "Cloaked Scan"

### ISSUE THREAD

**Issue by gabrielss4ntos** [yogeshojha/rengine#1322]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I'm trying to set up timed and periodic scans for a target. However, I receive error 500 and cannot create. Any suggestions on how to get workaround this?
![error_scheduling](https://github.com/user-attachments/assets/5f9eddb3-9715-4a9a-a060-f3f549baa4f4)
![error-creating-scheduling](https://github.com/user-attachments/assets/b186e9a5-9cbe-4041-822c-7c3e1f83e2dd)

I even enabled debugging, but I can't understand the problem, see screenshots.

Server side logs 

web-1          | django.request | Internal Server Error: /scan/bugbounty/schedule/organization/4
web-1          | Traceback (most recent call last):
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 47, in inner
web-1          |     response = get_response(request)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 181, in _get_response
web-1          |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/rolepermissions/decorators.py", line 21, in wrapper
web-1          |     return dispatch(request, *args, **kwargs)
web-1          |   File "/usr/src/app/startScan/views.py", line 800, in schedule_organization_scan
web-1          |     return HttpResponseRedirect(reverse('scheduled_scan_view', kwargs={'slug': slug, 'id': id}))
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/urls/base.py", line 86, in reverse
web-1          |     return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
web-1          |   File "/usr/local/lib/python3.10/dist-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
web-1          |     raise NoReverseMatch(msg)
web-1          | django.urls.exceptions.NoReverseMatch: Reverse for 'scheduled_scan_view' with keyword arguments '{'slug': 'bugbounty', 'id': 4}' not found. 1 pattern(s) tried: ['scan/(?P<slug>[-a-zA-Z0-9_]+)/scheduled/\\Z']
web-1          | django.server | "POST /scan/bugbounty/schedule/organization/4 HTTP/1.0" 500 96254
proxy-1        | 172.30.15.206 - - [22/Jul/2024:21:15:05 +0000] "POST /scan/bugbounty/schedule/organization/4 HTTP/1.1" 500 96254 "https://localhost/scan/bugbounty/schedule/organization/4" "Mozilla/5.0 

### Expected Behavior

Be able to create periodic scans.

### Steps To Reproduce

Try creating a "Periodic Scan" or "Cloaked Scan".

### Environment

```markdown
- reNgine:2.1.1
- OS: Ubuntu 22.04.3 LTS
- Python: 3.10.12
- Docker Engine: 25.0.4
- Docker Compose: 1.29.2
- Browser: Chrome 126.0.6478.183
```

**Comment by luca-regne** [comment]
+1

**Comment by cerontrustly** [comment]
+1

**Comment by yogeshojha** [comment]
Hi @luca-regne @gabrielss4ntos @cerontrustly 

Thank you guys for reporting, looks like a typo. I have fixed in above MR. Once pipeline passes I will merge this.

Feel free to `git pull`

Thanks :heart:
