### ISSUE TITLE
[Bug] Subdomains Discovered - are not showing after scan is complete.

### ISSUE THREAD

**Issue by virenpawar** [yogeshojha/rengine#133]
### Issue Summary

While scan was in progress, subdomains discovered was showing and after scan is completed, subdomains discovered are not visible anymore. They are available to export but aren't displayed from dashboard.

### Steps to Reproduce

1. Started scanning "droom.in".
2. Used full scan configuration.
3. After scan is completed, subdomains discovered aren't visible.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: YES

### Technical details

Please list out any technical details such as operating environment.
OS: Ubuntu 16.04.6 LTS (GNU/Linux 4.15.0-1080-gcp x86_64)

Docker: 
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:49 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:20 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

Docker-Compose:
docker-compose version 1.26.2, build eefe0d31
docker-py version: 4.2.2
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019

**Comment by yogeshojha** [comment]
Hi Viren, is this happening only for the domain you mentioned, or happens with every other domain?

**Comment by virenpawar** [comment]
I think this issue is on this target only.
