### ISSUE TITLE
make: *** [Makefile:21: certs] Error 1

### ISSUE THREAD

**Issue by sasholy** [yogeshojha/rengine#1359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Cannot connect to the Docker daemon at unix:///run/podman/podman.sock. Is the docker daemon running?                   
Error: executing /usr/local/bin/docker-compose -f docker-compose.setup.yml run --rm certs: exit status 1
make: *** [Makefile:21: certs] Error 1

reNgine installation failed!!  

### Expected Behavior

I don't know

### Steps To Reproduce

Quick Setup for Ubuntu/VPS

### Environment

```markdown
- reNgine: 2.1.0
- OS: kali 
- Python: 3
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
Hi @sasholy you need to run the make file as sudo, try make commands with sudo

And as per logs docker deamon doesn't seem to be running

Did you try running install script?

**Comment by sasholy** [comment]
Yeah, it's as instructed, I put it on a clean kali

**Comment by zinwelzl** [comment]
use sudo and try run it few times.
works for me, slow vps.

**Comment by sasholy** [comment]
`┌──(kali㉿kali)-[~/rengine]
└─$ sudo ./install.sh
           _   _       _
          | \ | |     (_)                                                                                              
  _ __ ___|  \| | __ _ _ _ __   ___                                                                                    
 | '__/ _ \ . ` |/ _` | | '_ \ / _ \                                                                                   
 | | |  __/ |\  | (_| | | | | |  __/                                                                                   
 |_|  \___|_| \_|\__, |_|_| |_|\___| v2.1.1                                                                            
                  __/ |                                                                                                
                 |___/                                                                                                 
Before running this script, please make sure Docker is running and you have made changes to .env file.                 
Changing the postgres username & password from .env is highly recommended.                                             
Are you sure, you made changes to .env file (y/n)? y                                                                   
Continiuing Installation!                                                                                              
                                                                                                                       
#########################################################################                                              
Please note that, this installation script is only intended for Linux                                                  
For Mac and Windows, refer to the official guide https://rengine.wiki                                                  
#########################################################################                                              
                                                                                                                       
Installing reNgine and its dependencies                                                                                
                                                                                                                       
                                                                                                                       
#########################################################################                                              
Installing curl...                                                                                                     
#########################################################################                                              
CURL already installed, skipping.                                                                                      
                                                                                                                       
#########################################################################                                              
Installing Docker...                                                                                                   
#########################################################################                                              
Docker already installed, skipping.                                                                                    
                                                                                                                       
#########################################################################                                              
Installing Docker Compose                                                                                              
#########################################################################                                              
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current                                        
                                 Dload  Upload   Total   Spent    Left  Speed                                          
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0                                         
100 25.2M  100 25.2M    0     0  7820k      0  0:00:03  0:00:03 --:--:-- 9211k                                         
ln: failed to create symbolic link '/usr/bin/docker-compose': File exists                                              
Docker Compose installed!!!                                                                                            
                                                                                                                       
#########################################################################                                              
Installing make                                                                                                        
#########################################################################                                              
make already installed, skipping.                                                                                      
                                                                                                                       
#########################################################################                                              
Checking Docker status                                                                                                 
#########################################################################                                              
Docker is running.                                                                                                     
                                                                                                                       
#########################################################################                                              
Installing reNgine                                                                                                     
#########################################################################                                              
Using: docker compose                                                                                                  
Emulate Docker CLI using podman. Create /etc/containers/nodocker to quiet msg.                                         
>>>> Executing external compose provider "/usr/local/bin/docker-compose". Please refer to the documentation for details. <<<<                                                                                                                 
                                                                                                                       
Cannot connect to the Docker daemon at unix:///run/podman/podman.sock. Is the docker daemon running?                   
Error: executing /usr/local/bin/docker-compose -f docker-compose.setup.yml run --rm certs: exit status 1
make: *** [Makefile:21: certs] Error 1

reNgine installation failed!!      `

**Comment by breaker01** [comment]
I encountered this issue with the error the input device is not a TTY while running the install.sh script. After some troubleshooting, I found that adding the -T flag to the docker-compose run command resolves this problem. The -T flag disables pseudo-TTY allocation, which is necessary for non-interactive environments.
what you have to do is in Makefile just change this line (27) :
`${COMPOSE_PREFIX_CMD} ${DOCKER_COMPOSE} ${COMPOSE_ALL_FILES} up -d --build ${SERVICES}` 
to 
`${COMPOSE_PREFIX_CMD} ${DOCKER_COMPOSE} -f docker-compose.setup.yml run --rm -T certs`
