### ISSUE TITLE
cmd not worked to create username and pswd

### ISSUE THREAD

**Issue by cehbikramrock** [yogeshojha/rengine#138]
Dear sir !
i still found same problems.
┌─[✗]─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker-compose up -d
rengine-master_db_1 is up-to-date
rengine-master_web_1 is up-to-date
┌─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker ps -a -q
985fdff16b3f
59adf89bd2c3
796fddb6e8d1
3a8573d4a52a
02737056881b
┌─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker-compose down
Stopping rengine-master_web_1 ... done
Stopping rengine-master_db_1 ... done
Removing rengine-master_web_1 ... done
Removing rengine-master_db_1 ... done
Removing network rengine-master_rengine_network
┌─[root@parrot]─[/home/bikram/Downloads/rengine-master]
└──╼ #docker exec -it rengine_web_1 python manage.py createsuperuser
Error: No such container: rengine_web_1

**Comment by yogeshojha** [comment]
Hi @cehbikramrock 

Please read the instructions carefully before creating an issue. We are all working hard to resolve all the issues and bring new features, and it's difficult if you keep on raising the issue without reading the manual.

## From readme.md

```
Register Account

Once the application is up and running, you need an account for reNgine. This can be easily created using createsuperuser from Django. Open a new terminal tab, and run the following command:

docker exec -it rengine_web_1 python manage.py createsuperuser

You may now enter your username and password. Remember to keep a secure password.
```

Looking at what you have done, you haven't started the container. Start the container, open the new tab and run the command for superuser creation.
