### ISSUE TITLE
feat: Did you try ClaudeDev for feature development?

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1388]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

i'm trying to use ClaudeDev to help, but can't make it work.

did you try ClaudeDev, or any other AI programming help tool with rengine?

https://www.youtube.com/watch?v=ic9905SMPzk&ab_channel=WorldofAI

**Comment by yogeshojha** [comment]
Hi @zinwelzl

Yes I have used claude, looks promising.

Since this is unrelated to reNgine, I am closing this, please send me an email I will be able to guide you.

Thanks
