### ISSUE TITLE
feat: Enable Bug Bounty mode to separate bug bounty related features

### ISSUE THREAD

**Issue by yogeshojha** [yogeshojha/rengine#1411]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

We need to separate bug bounty related features such as reporting hackerone, importing assets from hackerone etc

For example @null-ref-0000 most recent PR is an excellent feature addition for bug hunters, but reNgine also has corporate users that may not use this feature at all, or even for those users that do recon for their own purpose, they may not need this.

And in future we may bring more of bug bounty features for example, integration with intigriti or bugcrowd and these may not be useful for non bug bounty users.

We need to provide an option during onboarding if these features have to be enabled, and inside reNgine settings as well if the user wants to enable bug bounty related features, a button/checkbox may be provided for user's to enable this.

**Comment by null-ref-0000** [comment]
The [Django-flag](https://cfpb.github.io/django-flags/) modules would likely be useful for this feature. Could create a variable in the .env and then pass that to the settings.py.

**Comment by yogeshojha** [comment]
@null-ref-0000 this library is good, but in future we might as well have such more options to enable or disable so I believe the best is to create a Model called UserPreference model, specific to that user, and store all configs there, and use that in middleware.

**Comment by null-ref-0000** [comment]
@yogeshojha Yeah good points, a user preference section is a more robust feature.
