### ISSUE TITLE
bug: MaxRetryError for checkip.amazonaws.com

### ISSUE THREAD

**Issue by null-ref-0000** [yogeshojha/rengine#1413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Homepage does not load 

### Expected Behavior

Homepage should load without error

### Steps To Reproduce

Unclear steps at this time how to reproduce, but I believe it occurs when the homepage is loaded to often. 

### Environment

```markdown
- reNgine: 2.1.3
- OS: Debian 12
- Python: 3.11
- Docker Engine: 26.1.2, build 211e74b
- Docker Compose: v2.5.0
- Browser: Chrome
```

### Anything else?

externalIp = requests.get('https://checkip.amazonaws.com').text.strip()
web-1          | urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f3992fee290>, 'Connection to checkip.amazonaws.com timed out. (connect timeout=None)')
web-1          | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='checkip.amazonaws.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f3992fee290>, 'Connection to checkip.amazonaws.com timed out. (connect timeout=None)'))

**Comment by null-ref-0000** [comment]
I believe this can be resolved by caching the footer.html. Perhaps should be cache ttl should be one hour? 


https://docs.djangoproject.com/en/5.1/topics/cache/#template-fragment-caching

**Comment by yogeshojha** [comment]
Hi @null-ref-0000 I have removed this ip check in reNgine 2.2.0. I don't see any benefit of having an IP check or even showing external IP on page, so I had removed. Once 2.2.0 is released I will close this
