### ISSUE TITLE
bug: XSS test creates links that trigger XSS

### ISSUE THREAD

**Issue by Rho-9-Official** [yogeshojha/rengine#1415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="960" alt="image" src="https://github.com/user-attachments/assets/551a5795-542b-4777-9155-434ecbf35e3b">
Honestly this one explains it all, but I was scanning a site upon request, and found they're vulnerable to XSS....and so is Rengine

### Expected Behavior

Expected behavior would be to display the URLs, with extra handling to account for the links having XSS payloads

### Steps To Reproduce

scan an XSS vulnerable site like this one
<img width="960" alt="image" src="https://github.com/user-attachments/assets/16e8a72b-b207-4ef9-98f9-87fa551eab5b">
when you go to view the vulnerabilities....have fun clicking out of several pop up boxes that got injected

### Environment

```markdown
- reNgine: 
- OS: 
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

**Comment by yogeshojha** [comment]
Hi @Rho-9-Official do you mind submitting this via https://github.com/yogeshojha/rengine/security
It will be easier for me to manage security reports from there and maybe we could assign you a CVE ID as well.

Thanks

**Comment by yogeshojha** [comment]
Reported as security report
