### ISSUE TITLE
500 Error after update

### ISSUE THREAD

**Issue by shubhamvpandey** [yogeshojha/rengine#1427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used https://rengine.wiki/install/quick/ install steps also I tried using following cmd as well - make cert, make build, make up, make username, make logs 
still, the issues remain the same. 
I am using wsl, docker-compose version v2.26.1 

### Expected Behavior

I am attaching logs for review.
thanks for the amazing tool 

[root@Blank mntcKaliRed-Teamrengine.txt](https://github.com/user-attachments/files/16920036/root%40Blank.mntcKaliRed-Teamrengine.txt)

### Steps To Reproduce

updating or reinstall the tool

### Environment

```markdown
- reNgine: 2.20
- OS: Windows 11 WSL
- Python: 3.119
- Docker Engine: 20.10.25 build b82b9f3
- Docker Compose:  v2.26.1 
- Browser: IE, Google chrome
```

**Comment by yogeshojha** [comment]
Hi @shubhamvpandey 
I have fixed this now, please pull the latest master branch.

Thank you!
