### ISSUE TITLE
bug: Server Error (500)

### ISSUE THREAD

**Issue by doreno39** [yogeshojha/rengine#1431]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I got the "Server Error (500)" error when updating to version v2.2.0 from v2.1.3.

The error logs in the container show as below, the dashboard_userpreferences table does not exist in the Postgres database.
```
db-1           | 2024-09-10 09:43:25.751 UTC [20550] ERROR:  relation "dashboard_userpreferences" does not exist at character 132
db-1           | 2024-09-10 09:43:25.751 UTC [20550] STATEMENT:  SELECT "dashboard_userpreferences"."id", "dashboard_userpreferences"."user_id", "dashboard_userpreferences"."bug_bounty_mode" FROM "dashboard_userpreferences" WHERE "dashboard_userpreferences"."user_id" = 1 LIMIT 21
web-1          | django.server | "GET / HTTP/1.0" 500 145
proxy-1        | 103.245.252.19 - - [10/Sep/2024:09:43:25 +0000] "GET / HTTP/2.0" 500 145 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "-"
db-1           | 2024-09-10 09:43:26.141 UTC [20551] ERROR:  relation "dashboard_userpreferences" does not exist at character 132
db-1           | 2024-09-10 09:43:26.141 UTC [20551] STATEMENT:  SELECT "dashboard_userpreferences"."id", "dashboard_userpreferences"."user_id", "dashboard_userpreferences"."bug_bounty_mode" FROM "dashboard_userpreferences" WHERE "dashboard_userpreferences"."user_id" = 1 LIMIT 21
proxy-1        | 103.245.252.19 - - [10/Sep/2024:09:43:26 +0000] "GET /favicon.ico HTTP/2.0" 500 145 "https://58.84.2.235/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36" "-"
web-1          | django.server | "GET /favicon.ico HTTP/1.0" 500 145
```
<img width="307" alt="image" src="https://github.com/user-attachments/assets/bd1e2589-05cd-44e3-b2df-fe2ae3b8b173">

### Expected Behavior

It should have worked correctly.

### Steps To Reproduce

1. Install Rengine with version v2.1.3.
2. Using update.sh script to update version to v2.2.0
3. Open the browser, then access to https://{IP address}
4. Got the "Server Error (500)" error.

### Environment

```markdown
- reNgine: v2.2.0
- OS: Ubuntu 20.04.6 LTS (Focal Fossa)
- Python: 3.10.14
- Docker Engine: 26.1.0
- Docker Compose: v2.26.1
- Browser: Chrome Version 128.0.6613.120
```

**Comment by sanyam2602** [comment]
@yogeshojha why is this so and how we can fix this?

**Comment by sanyam2602** [comment]
Same issue coming on ubuntu 20.04 as well.

**Comment by vipul-soman** [comment]
Everytime I try to use rengine theres always something breaking, i feel devs could prioritize pending issues and then focus on features , just a suggestion, thanks for the tool

**Comment by yogeshojha** [comment]
@vipul-soman I take in your feedback, next few releases will focus on stability and ease of install/upgrade etc
Thank you!

**Comment by yogeshojha** [comment]
@sanyam2602 please follow the discussion on #1430

**Comment by sanyam2602** [comment]
@yogeshojha it is working now.

**Comment by yogeshojha** [comment]
Hi @doreno39 as comfirmed by @sanyam2602  I have merged the changes, please `git pull` the latest changes on master and hopefully everything works as expected.

I will close this but keep open #1430 if you have any issues please continue the conversation there.

Thank you

**Comment by doreno39** [comment]
> Hi @doreno39 as comfirmed by @sanyam2602 I have merged the changes, please `git pull` the latest changes on master and hopefully everything works as expected.
> 
> I will close this but keep open #1430 if you have any issues please continue the conversation there.
> 
> Thank you

Hi @sanyam2602, it worked correctly, thanks for your support!

**Comment by ethanlacerenza** [comment]
@yogeshojha Excuse me, but why is this issue closed when there are people on Discord, including myself, who are experiencing this problem with the latest published version? An issue shouldn't be closed just because there's a workaround, should it?
