### ISSUE TITLE
bug: <title>Observing issue in rendering the ui in browser.

### ISSUE THREAD

**Issue by rajrathod-code** [yogeshojha/rengine#1433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After successful instantiation of the rengine  latest version i am observing that the login page is there but the ui is not there.

### Expected Behavior

Login page is supposed to be looks with proposer CSS and HTML rendering.

### Steps To Reproduce

Just setup and try to access 127.0.0.1:8000 url.

### Environment

```markdown
- reNgine: reNgine 2.2.0
- OS: Windows wsl and tried on kali also
- Python: Python 3.10.12
- Docker Engine: Docker version 24.0.7
- Docker Compose: v2.29.2
- Browser: Firefox/ Chrome/ Edge
```

### Anything else?

![after_login](https://github.com/user-attachments/assets/4f4307fe-718b-471d-8b09-b0c0dde52522)
![login_page](https://github.com/user-attachments/assets/b338b804-0e62-4b51-b8eb-8e5720b09783)

**Comment by yogeshojha** [comment]
Hey @rajrathod-code you are supposed to access from https://localhost or https://127.0.0.1
