### ISSUE TITLE
bug: Full Scan Stuck on OS Intelligence

### ISSUE THREAD

**Issue by vipul-soman** [yogeshojha/rengine#1436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
Scan Stuck on OS intelligence

### Expected Behavior

Should complete the scan

### Steps To Reproduce

install rengine 
1. Add a target
2. Initiate Scan
3. Full Scan

### Environment

```markdown
- reNgine: 2.2.0
- OS: MacOS
- Python: 
- Docker Engine: 
- Docker Compose: 
- Browser:
```

### Anything else?

Attaching OS inteliigence logs, it says no targets in user input
<img width="1131" alt="Screenshot 2024-09-12 at 10 12 56 AM" src="https://github.com/user-attachments/assets/f3c5c063-ba9b-488c-9bc8-74cb67c34e5a">

**Comment by yogeshojha** [comment]
@vipul-soman do you have the docker logs? If so please attach

**Comment by vipul-soman** [comment]
Not able to exactly reproduce, maybe target issue but if I come across I'll reopen
