### ISSUE TITLE
bug: local LLM dont't work

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#1439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

local LLM dont't work for subdomains and vulns

### Expected Behavior

local LLM

### Steps To Reproduce

local LLM dont't work for subdomains and vulns

### Environment

```markdown
- reNgine: 2.2.0
```

**Comment by yogeshojha** [comment]
Hey @zinwelzl do you mind attaching the logs? Is it the problem with 'httpcore' module as I guess?

**Comment by zinwelzl** [comment]
I'll when new scan end.
It run for 10h...

**Comment by sinaudjango** [comment]
same error with me, also unable configure LLM toolkit when return 500 internal server error
![image](https://github.com/user-attachments/assets/e9eced7e-f6cd-4db9-9634-3361f74353ff)

``` bash
django.server | "GET /scanEngine/redacted/llm_toolkit HTTP/1.0" 500 145
api.views  | Using Ollama for Attack Suggestion Generation

```

**Comment by yogeshojha** [comment]
Looks like httpcore library issue, I'm looking into this
