### ISSUE TITLE
Feature - Mark subdomain for Done/In-progress to track the progress for each subdomain

### ISSUE THREAD

**Issue by S3ntago** [yogeshojha/rengine#153]
Can you please add a mark on each subdomain so we can mark which subdomain was tested and which is not so we can keep track each subdomain progress

I suggest:

1. Done with green highlight color (Test completed)
2. In-progress with orange highlight color (Testing in progress)

Regards,
s3ntago

**Comment by yogeshojha** [comment]
This is awesome! We will make sure this is implemented!

**Comment by S3ntago** [comment]
Thanks bro @yogeshojha this will really help in tracking the progress

**Comment by sasokyleader** [comment]
Could you add the current percentage of the overall task?

**Comment by yogeshojha** [comment]
Good news, I have worked on this. Waiting to merge for v0.5.
