### ISSUE TITLE
Feature - Add timeout option for aquatone

### ISSUE THREAD

**Issue by 0xShin** [yogeshojha/rengine#156]
**Is your feature request related to a problem? Please describe.**
I have encountered a problem whereas aquatone was giving request timeout due to the default option which resulted for the empty screenshots tab after scanning the target and this problem also rises when a server has a slow network connection. 
https://github.com/yogeshojha/rengine/blob/1e29204160b584c8915e18f3cf190c98a32b1936/startScan/views.py#L316

**Describe the solution you'd like**
I would like to suggest to add an option to put how many seconds it should be before giving out a timeout error, for instance 
` /app/tools/aquatone --threads 10 -http-timeout 10000 -screenshot-timeout 10000 -scan-timeout 10000`. Please note that we have to put in milliseconds as the option input as aquatone's docs said.

**Comment by yogeshojha** [comment]
Okay @0xShin I will provide yaml setting for this.

**Comment by yogeshojha** [comment]
Implemented in the latest release. Waiting to be merged.
