### ISSUE TITLE
Scan all selected targets?

### ISSUE THREAD

**Issue by jhaddix** [yogeshojha/rengine#158]
Hey All =)

I was just playing around with this awesome framework. Thank you.

I imported a target txt file. I assumed when I selected all the targets on the left I could scan them all but I couldn't find that functionality. Did I miss it?

![2020-07-26_03-26-34](https://user-images.githubusercontent.com/3488554/88475809-78a87400-cef0-11ea-8efe-37d89fc9706f.png)

**Comment by yogeshojha** [comment]
Hi @jhaddix 

Currently reNgine uses threads to run the scans in the backgrounds. I am on my way to migrate threads to celery and Redis queue, which will then bring in features like multiple scans, stopping the scans, scheduling scans in future.


I will keep this issue open until I work on it.

Thank you once again for using reNgine.

**Comment by RapidEU** [comment]
I think RabbitMQ would be a better choice mate!
However, create a branch for it, I'll try to spare some time and contribute when you are starting.

**Comment by yogeshojha** [comment]
Hi @jhaddix This is Fixed in V0.4. 🎉 Please check 🎉
