### ISSUE TITLE
subdomain/domain hyperlink header in screenshot frame 

### ISSUE THREAD

**Issue by bugdisclose** [yogeshojha/rengine#159]
![improvement](https://user-images.githubusercontent.com/33686367/88478274-90214480-cf64-11ea-8c1a-91291384dc1c.png)
I've noticed that when we open a screenshot there is no direct hyperlink to visit a particular subdomain/domain. We need to come back and then search for a related subdomain with the screenshot then we can visit.

I would recommend adding a small header above screenshot with a little subdomain related information like:

- subdomain hyperlink (Open in new tab), Page title, etc.

This feature can improve the user experience.

**Comment by yogeshojha** [comment]
This will be a simple PR, it will be done @bugdisclose

**Comment by tarunn-1** [comment]
Hi, @yogeshojha I want to work on this. Please assign it to me.

**Comment by yogeshojha** [comment]
Fixed in V0.4. 🎉
