### ISSUE TITLE
Feature - Your Awesome feature title

### ISSUE THREAD

**Issue by saberzaid** [yogeshojha/rengine#161]
hello 

thanks for this great tool 

the only instllation is via duckers? is there away to install it in my kali linux for example without ducker? it take so long to install and alot of space ,

thank you again

**Comment by yogeshojha** [comment]
CUrrently there is no way to install other than docker. We do not officially support, but you can play with the django settings, maybe you could make it work. Since there are a lot of shell scripts, recommend you to run on linux
