### ISSUE TITLE
Feature - Add OneForAll for subdomain find

### ISSUE THREAD

**Issue by zer0yu** [yogeshojha/rengine#162]
Can you integrate [oneforall](https://github.com/shmilylty/OneForAll)  tool for directory discovery? that would be better option.

**Comment by yogeshojha** [comment]
The documentation is in Chinese, as far as I can see it's subdomain discovery tool. oneforall has directory scan module as well?

**Comment by zer0yu** [comment]
> The documentation is in Chinese, as far as I can see it's subdomain discovery tool. oneforall has directory scan module as well?

it does not has directory scan module, but it's subdomain discovery module is very well.

**Comment by d1pakda5** [comment]
> 
> 
> The documentation is in Chinese, as far as I can see it's subdomain discovery tool. oneforall has directory scan module as well?

You can get the English Version here https://github.com/shmilylty/OneForAll/blob/master/docs/en-us/README.md

**Comment by abdilahrf** [comment]
IMHO, the tools is using so many all other tools together and it will making the project harder to mantain for the long term
how about we choose only which sources that we need to add, its more efficient

**Comment by abdilahrf** [comment]
adding for subdomain discovery is quite good i think, but not for directory discovery.

**Comment by alph4byt3** [comment]
Tried this tool out, it works great. I second adding it to rengine, it would help a lot with whatever the four already existing tools(subfinder, amass etc) can't find

**Comment by yogeshojha** [comment]
This has been implemented ❤️
