### ISSUE TITLE
Bug - httpx task 

### ISSUE THREAD

**Issue by saberzaid** [yogeshojha/rengine#163]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
web_1_f73dce40ca96 | 
web_1_f73dce40ca96 |     __    __  __       _  __
web_1_f73dce40ca96 |    / /_  / /_/ /_____ | |/ /
web_1_f73dce40ca96 |   / __ \/ __/ __/ __ \|   / 
web_1_f73dce40ca96 |  / / / / /_/ /_/ /_/ /   |  
web_1_f73dce40ca96 | /_/ /_/\__/\__/ .___/_/|_|  
web_1_f73dce40ca96 |              /_/            
web_1_f73dce40ca96 | 
web_1_f73dce40ca96 |            projectdiscovery.io
web_1_f73dce40ca96 | 
web_1_f73dce40ca96 | [WRN] Use with caution. You are responsible for your actions
web_1_f73dce40ca96 | [WRN] Developers assume no liability and are not responsible for any misuse or damage.
web_1_f73dce40ca96 | aquatone v1.7.0 started at 2020-07-27T14:40:10+05:30
web_1_f73dce40ca96 | 
web_1_f73dce40ca96 | No targets found in input.
web_1_f73dce40ca96 | Traceback (most recent call last):
web_1_f73dce40ca96 |   File "/app/startScan/views.py", line 321, in doScan
web_1_f73dce40ca96 |     with open(aqua_json_path, 'r') as json_file:
web_1_f73dce40ca96 | FileNotFoundError: [Errno 2] No such file or directory: '/app/tools/scan_results/
A summary of the issue.

### Steps to Reproduce

1. When I am scanning the domains, this happens
as soon as httpx start the task , the scanner failed 

### Technical details

using kali linux updated as of today

**Comment by yogeshojha** [comment]
Please re run the scan, looks like https could not grab any live URL
