### ISSUE TITLE
Installation crash ScanEngine

### ISSUE THREAD

**Issue by Ahsan-x** [yogeshojha/rengine#164]
### Issue Summary

A summary of the issue.
After Installing Getting this issue scan engine not working for me 
![image](https://user-images.githubusercontent.com/46222314/88532918-cde2a380-d01e-11ea-80cc-98fa7078aa4e.png)

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
Yes

### Technical details

Please list out any technical details such as operating environment.
Ubuntu 20.04 LTS
Docker version 19.03.8, build afacb8b7f0

**Comment by bugdisclose** [comment]
Remove your old docker image and do a fresh install.

Reference: https://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks/

**Comment by yogeshojha** [comment]
removing the volume is enough.

docker volume ls

and docker volume rm rengine_volume_name

**Comment by Ahsan-x** [comment]
Thankyou! resolved know
