### ISSUE TITLE
Error in install

### ISSUE THREAD

**Issue by MMrhassel** [yogeshojha/rengine#166]
musl-dev     && apk add postgresql-dev chromium git netcat-openbsd     && pip install psycopg2     && apk del build-deps
 ---> Running in 2e7b4de8f730
ERROR: Unable to read database state: No such file or directory
ERROR: Failed to open apk database: No such file or directory
ERROR: Service 'web' failed to build: The command '/bin/sh -c apk update     && apk add --virtual build-deps gcc python3-dev musl-dev     && apk add postgresql-dev chromium git netcat-openbsd     && pip install psycopg2     && apk del build-deps' returned a non-zero code: 99

**Comment by Serizao** [comment]
Hello,

What is your environnement ? Have you try CLI command one by one ? Like :

```shell
apk add postgresql-dev chromium git netcat-openbsd
pip install psycopg2
apk del build-deps
```
If not try it for locate the problem with more precision

**Comment by 0xspade** [comment]
apk command not found :(
