### ISSUE TITLE
Feature - Use project discovery subdomain takeover nuclie script

### ISSUE THREAD

**Issue by pager5Cx415Cx415Cx69** [yogeshojha/rengine#167]
Use project discovery subdomain takeover nuclie script haccer is not maintaining now collectively maintain nuclie subdomain script.

**Comment by attacker007** [comment]
Hi @pager5Cx415Cx415Cx69 this is already in pipeline as complete nuclei project will be implemented. Please close this as its open in another ticket. 

Thanks !!
