### ISSUE TITLE
Cant delete a list of target

### ISSUE THREAD

**Issue by 0xWise64** [yogeshojha/rengine#168]
Hello, Firstly thank you for this awsome reconnaissance framework.

When I import a list of domains (targets) above 1000 domains, the delete button doesn't work with me, but I think it is crashed, I suggest creating a button to select all targets and delete them all at once, and also button for scanning all targets.

Regards

**Comment by 0xWise64** [comment]
Also, I noticed that the `Never Scanned Before` target could not be deleted from "List Targets".

Regards

**Comment by pager5Cx415Cx415Cx69** [comment]
Till now is their any ways to delete list of target. Like the scan which are finished stored in rengine/tools/scan_results . But the targets which are on list and has never been scan before where they has been stored by default?

**Comment by yogeshojha** [comment]
Yay, this is available V0.4. 🎉 Please update the reNgine :)
