### ISSUE TITLE
Feature - Grabbing subdomains also with chaos project discovery

### ISSUE THREAD

**Issue by pager5Cx415Cx415Cx69** [yogeshojha/rengine#173]
Grabbing subdomains also with chaos project discovery.
Fetching subdomains using simple python script like chaospy or with wget they mention on their twitter.
Chaos would we better also it does not required heavy resources.
Thanks

**Comment by yogeshojha** [comment]
Perfect, I need to see if I have chaos invitation. I will surely Integrate it.

**Comment by yogeshojha** [comment]
Hey @pager5Cx415Cx415Cx69 thank you for this feature request. Chaos is now a part of reNgine's subdomain enum process! 

releasing in 2.2.0!

🚀

**Comment by yogeshojha** [comment]
This is released in reNgine 2.2.0, checkout: [What's new in 2.2.0](https://rengine.wiki/whats-new/2_2_0/)
