### ISSUE TITLE
Feature - Dark Theme

### ISSUE THREAD

**Issue by alph4byt3** [yogeshojha/rengine#175]
As requested in Twitter, just moving it over to Github for keeping track.

**Comment by micr0seft** [comment]
I went ahead and implemented this, after we spoke on twitter yesterday.
[dark_mode.zip](https://github.com/yogeshojha/rengine/files/6951982/dark_mode.zip)

I altered base.html, index.html, notification index, and top_nav. 2 js files were added to assest/js/, theme-switcher and darkreader.js. If you have any questions let me know. This was all tested working on Firefox 90.0.2 on Ubuntu 20.04

**Comment by yogeshojha** [comment]
Thanks Guys, this is released in 1.0. <3 

![dark](https://user-images.githubusercontent.com/17223002/129470525-5d40d795-9ffe-4d7d-9c60-186f9a6d89c3.gif)
