### ISSUE TITLE
Bug - Title of Bug

### ISSUE THREAD

**Issue by adik69** [yogeshojha/rengine#177]
Hey,
This Happened with me second time this error came up , It was running smooth for 3-4 days suddenly the database password is changed.
I didn't mess with the script . How can it forget its own database password??

![Screenshot_2020-07-30 OperationalError at ](https://user-images.githubusercontent.com/25083418/88840234-c9261700-d1f9-11ea-9be2-70b513cbb2cc.png)

Only reason I think of is maybe there are too many processes/scans running.

**Comment by Hacker22o2** [comment]
@adik69 the reason for this error is you have utilised 100% CPU memory, either you need to increase the CPU memory or stop the docker and restart it. giving many parallel scans could lead you this error.
