### ISSUE TITLE
Found XSS Bug On TITLE while scanning (Security Bug)

### ISSUE THREAD

**Issue by omemishra** [yogeshojha/rengine#178]
Hello Brother,

first of all nice tool and we done,

i was looking into the application  and i find that there is a security issue on your tool,

i mean if a website title is "><img/src=x onmouseover=alert(11)> it will execute ...

Means there is xss..

Take Care

**Comment by omemishra** [comment]
![Screenshot-20200730032901-1865x987](https://user-images.githubusercontent.com/25466820/88857810-8de51180-d214-11ea-9111-7b72856c6531.png)

**Comment by yogeshojha** [comment]
Thank you so much for bringing this to the attention. This will be fixed

**Comment by omemishra** [comment]
You are welcome brother ..... 

Tc

**Comment by yogeshojha** [comment]
Thank you very much for reporting this!

https://github.com/yogeshojha/rengine/blob/master/.github/SECURITY.md

**Comment by yogeshojha** [comment]
If you find any other instances of XSS, feel free to report them on separate issue.

**Comment by omemishra** [comment]
Thanks bro .... 

Sure will do that.... 

Tc
