### ISSUE TITLE
Feature - Remote Database

### ISSUE THREAD

**Issue by Regala** [yogeshojha/rengine#180]
**Is your feature request related to a problem? Please describe.**
Increased segregation allow us to deploy the application in a more elastic architecture. Supporting a remote database, one could deploy it in the cloud using e.g. AWS which can take care of resizing, backups and other serverless benefits. 

**Describe the solution you'd like**
Support local and remote database. Preferable configuring using the UI under an "Application settings".

**Comment by yogeshojha** [comment]
This is documented on how to implement, thanks @Regala <3

https://rengine.wiki/install/remotedb/

**Comment by Regala** [comment]
Woop woop!!! 🤩

**Comment by Regala** [comment]
p.s. completely unrelated @yogeshojha , but does Rengine support any sort of API I can use to push recon data? (e.g. push urls -> trigger screenshots)

Awesome work with v1.0 btw ;)

**Comment by abdolzx** [comment]
Docker is not running. Please run docker and try again.
You can run docker service using sudo systemctl start docker

**Comment by ByteNight60** [comment]
hello guys,
when i added api key telegram i get un error 500 i dont not why can you help me please thanks.
