### ISSUE TITLE
Server won't fire up again

### ISSUE THREAD

**Issue by P1nkBug** [yogeshojha/rengine#183]
Hello,
so after installing everything was working fine, then I used Ctrl + C to terminate the server, fired it up again after few minutes and then used   sudo lsof -iTCP:8080 -sTCP:LISTEN and kill -ID to terminate it once I was done. Now whenever I use sudo docker-compose up -d to start it again I get:
rengine_db_1 is up-to-date
rengine_web_1 is up-to-date
But localhost:8000 does not load
Any help?

**Comment by yogeshojha** [comment]
Can you try 127.0.0.1:8000?

**Comment by P1nkBug** [comment]
hi @yogeshojha thanks for the reply!
I tried 127.0.0.1:8000. I managed to temporarily fix the issue by rebooting not when I use docker-compose up -d the server starts normally but after I terminate it with sudo kill PID and try to start it up again I get the same message: 
rengine_db_1 is up-to-date
rengine_web_1 is up-to-date
and I'm still unable to access anything at localhost,127.0.0.1 or 127.1

**Comment by P1nkBug** [comment]
@yogeshojha  I fixed the issue by running docker-compose kill to terminate the service instead of kill PID, now everything works fine. Another issue if it's not so much trouble, I must have found the old installation instructions and didn't use Makefile, how do I register a user now that make username does not work? Thank you
