### ISSUE TITLE
Feature - Make default screenshots size bigger

### ISSUE THREAD

**Issue by Regala** [yogeshojha/rengine#185]
**Is your feature request related to a problem? Please describe.**
Currently the main view of a scan renders the screenshots as a default size which is quite small. 

**Describe the solution you'd like**
It would be nice if we could personalize the size of the screenshot images in that view. e.g. small (like it is right now), medium, large.

Additionally, it would be nice if we could access the report of aquatone directly within the UI.

**Comment by yogeshojha** [comment]
Regala, first of all, thank you so much for sponsoring this project! 

This suggestion will be definitely worked upon. Currently, I am super busy with migrating threads based scan to celery, which will then allow you to schedule scan, cancel the scans, and many more. Once that is over, I will surely update this.


Thank you and Stay Healthy.

**Comment by Regala** [comment]
Awesome stuff my dude, keep up the good work 🙏

**Comment by yogeshojha** [comment]
This has been implemented, waiting to be merged in the newer major release!

![Screenshot 2020-11-24 at 11 57 53 PM](https://user-images.githubusercontent.com/17223002/100136294-e077c700-2eb0-11eb-8441-a8950ae8d9ab.png)

**Comment by yogeshojha** [comment]
Merged in v0.5
