### ISSUE TITLE
Feature - Improve the UI of content discovery results

### ISSUE THREAD

**Issue by Regala** [yogeshojha/rengine#186]
**Is your feature request related to a problem? Please describe.**
In the main scan view, where we have the domain, status, screenshot we also have the directories found from content discovery. It just so happens that this view works well when we have a few found paths, but not as good with lots of results. This is often the case when:
- The application responds to 200/3xx to every request
- The application responds to 4xx to non existing request

This will pollute that view, increase the scrolling by an order of magnitude and overall make it very difficult to distinguish and/or pinpoint interesting paths. 

**Describe the solution you'd like**
Two initial solutions are:
- After more than e.g. 50 entries, make it so that they are collapsable. So by default it would only show up to that many entries, and to see all of the others we'd need to expand.
- Make that column a DataTable itself, where by default the results would be ordered by status code (e.g. 2xx first, then 3xx).  

**Describe alternatives you've considered**
Alternatively, by clicking a row in this view we could have a more detailed view of the subdomain - including a new view containing more information of the paths discovered (as a DataTable), akin to the Endpoints view look like.

**Comment by Regala** [comment]
In regards to the last paragraph: basically that view could be the existing "endpoints" view but filtered to just that particular domain you've clicked.

**Comment by yogeshojha** [comment]
Thank you so much for the detailed feature request. We will work on this as well. <3

**Comment by yogeshojha** [comment]
This is implemented, you should be able to see a small badge right next to subdomains that will have count for vulnerability, and endpoints, upon clicking, you can see more details about either vuln or endpoints.
