### ISSUE TITLE
How to update

### ISSUE THREAD

**Issue by iamRjarpan** [yogeshojha/rengine#191]
Hi, sorry to ask this qusion but I am stuggling to update the tool. I tried everything but getting this error

```
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml images db web proxy
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
make: *** [Makefile:50: images] Error 1
```

**Comment by xlaruen** [comment]
> COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml images db web proxy
> ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
> For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
> make: *** [Makefile:50: images] Error 1

What's the version of your docker-compose? Run `$ docker-compose --version` to find out. If it's lower than 1.25.5, try lowering the version of docker-compose.yml document (very first line) from 3.8 to e.g. 3.7 and see if it works fine, like this:
`version: '3.7'`

I have 1.25.0 installed and I was able to work around that as described above.
