### ISSUE TITLE
Nginx proxy Keep Restaring 

### ISSUE THREAD

**Issue by BitThr3at** [yogeshojha/rengine#198]
### Issue Summary

I am trying to set up it via WSL 2 and docker-desktop and followed all the `make` steps but the Nginx proxy container keep restarting in a loop.

#logs
![image](https://user-images.githubusercontent.com/45028933/89124646-400f2880-d4f6-11ea-8880-944b3bee5645.png)

#other container working
![image](https://user-images.githubusercontent.com/45028933/89124674-6a60e600-d4f6-11ea-8552-f542c34f0239.png)

**Comment by RapidEU** [comment]
Did u `make certs` ?

**Comment by BitThr3at** [comment]
Yes i DID with this `.env`
![image](https://user-images.githubusercontent.com/45028933/89151914-97a5a680-d57f-11ea-9f57-3feaa983b2d8.png)

**Comment by BitThr3at** [comment]
is there any way it to run on simple http?

**Comment by BitThr3at** [comment]
hey can anybody help?

**Comment by alirezamdp** [comment]
i have same logs on rocky linux9 

`nginx: [emerg] host not found in upstream "rengine" in /etc/nginx/conf.d/rengine.conf:28
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2023/03/26 14:47:19 [emerg] 1#1: host not found in upstream "rengine" in /etc/nginx/conf.d/rengine.conf:28`

**Comment by tej0402** [comment]
Yes @alirezamdp same issue persists in Ubuntu 20 version too. Is there any work around for the above error?

**Comment by alirezamdp** [comment]
> Yes @alirezamdp same issue persists in Ubuntu 20 version too. Is there any work around for the above error?

I didn't come up with a special idea, I just managed to run another branch and it worked fine
