### ISSUE TITLE
[localhost] https is being blocked by chrome

### ISSUE THREAD

**Issue by x72hoor** [yogeshojha/rengine#199]
It's also can't forward to site.

Screenshot -

![image](https://user-images.githubusercontent.com/48919542/89147824-b0ab5900-d579-11ea-8b2a-15495b539f2f.png)

**Comment by yogeshojha** [comment]
You have to regenerate the certificate. AFAIK you had another instance of rengine already and did reinstallation. In that case please change dotenv file, Authority Name, Domain, and company.
