### ISSUE TITLE
Feature - Expanding the Target concept

### ISSUE THREAD

**Issue by Regala** [yogeshojha/rengine#200]
**Is your feature request related to a problem? Please describe.**
At the moment a "Target" is just a domain (can be a root domain or subdomain). However, most of the times a Target (a big company) has a multitude of root domains (say, Verizon or Yahoo). We should be able to add them all in one Target.

**Describe the solution you'd like**
When creating a new Target, we should be able to add any number of root domains and not only one. 
By doing this we can also **improve** the import target feature: say I found 100 domains using my own private tools. I could then import these directly to that target (preferably even before issuing a scan). 

(I think I might've mentioned this somewhere, just don't know where lol)

**Comment by hiddengearz** [comment]
This is one of the main reasons I don't use rengine very often tbh, It becomes very tedious to deal with ~50 domains manually. Great project otherwsise.

**Comment by ad0nis** [comment]
It would be great if the concept of targets were expanded even further to include IP addresses and subnets so that basic port scans, directory mapping, and screenshots could be run over an IP scope instead of only a domain name.

**Comment by yogeshojha** [comment]
Related to #89 . I am currently working on this, so that you can easily import subdomain results from other tools.

**Comment by Regala** [comment]
@yogeshojha wonder how this is coming along? 😛

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:
