### ISSUE TITLE
SSL files not present

### ISSUE THREAD

**Issue by dinosn** [yogeshojha/rengine#201]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

By executing a git pull to get the last update the docker is not starting after build with an error on the nginx certs. 

### Steps to Reproduce

Simply git clone the latest release, issue docker-compose build and after that docker-compose up. 

The certs are not present and either should be generated manually or config should on nginx conf not to include the ssl certs.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
yes

### Technical details

Please list out any technical details such as operating environment.
any ...

**Comment by alph4byt3** [comment]
You need to create the certs with `make certs`

**Comment by dinosn** [comment]
Many thanks, it's something that can be added also to be done directly.
