### ISSUE TITLE
Feature: extract all the queryStrings,parameters from the endpoints 

### ISSUE THREAD

**Issue by aoprea1982** [yogeshojha/rengine#203]
**Describe the solution you'd like**
To be able to get a list of the parameters in the endpoints 

Example:
https://github.com/tomnomnom/unfurl

Query String Key/Value Pairs

 cat urls.txt | unfurl keypairs
id=123
name=Sam
org=ExCo

Thank you! 

Tsubasa

**Comment by yogeshojha** [comment]
Not sure, if this is overkill, but reNgine 1.0 supports GF. You can download all the URLs with matched patterns
