### ISSUE TITLE
Crawler not following 307 redirects

### ISSUE THREAD

**Issue by aoprea1982** [yogeshojha/rengine#206]
HTTP Crawler not crawling the 307 redirected URL . 

The domain result:  statusCode  is "307"
"Recent Activities" shows HTTP Crawler completed  but no endpoints are discovered in "Endpoints"

 Is this expected? 

Can the redirect be followed 
to retrieve the endpoints? 

Thank you!

**Comment by yogeshojha** [comment]
Redirect option is not supported by reNgine as of now, but I can implement it. No worries.
