### ISSUE TITLE
make build command giving this error.

### ISSUE THREAD

**Issue by 007divyachawla** [yogeshojha/rengine#207]
Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

Please help me out in this.

**Comment by JoshuaMart** [comment]
Hi,
Try to change the version of the dockerfile for 2.2 or update docker-compose.

You can delete it & reinstall it with :
```
curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose
```
