### ISSUE TITLE
How to access Postgres using PgAdmin? 

### ISSUE THREAD

**Issue by Narendra-Modi** [yogeshojha/rengine#211]
Hi @yogeshojha ,

Nice work! Can you please tell me how i can access Postgres DB from my PgAdmin local setup? I tried entering host (My EC2 Public IP) and used username, password and db as postgres, postgres, postgres respectively.

I was getting connection refused error everytime, i also enabled port 5432 from my firewalls. Can you please tell me why it is different or hard to access postgres here?

There are lot of changes need to be made in ReEngine, and hopefully i would be able to add some PR if everything works good. Can you please help me accessing Postgres from External machine (My PC)?

**Comment by JoshuaMart** [comment]
Hi,
However, if you still want to expose your base, you need to modify the docker compose and add the directive for the `db' container:
```
ports:
  - 5432:5432
```

Don't forget that anyone will be able to access it from outside with the default credentials.

**Comment by Narendra-Modi** [comment]
@JoshuaMart ,

Still not accessible
![Screenshot 2020-08-17 at 10 36 23 AM](https://user-images.githubusercontent.com/69027716/90359107-9b542580-e075-11ea-8961-ad4ded5e8a32.png)
![Screenshot 2020-08-17 at 10 37 42 AM](https://user-images.githubusercontent.com/69027716/90359146-b1fa7c80-e075-11ea-886a-af0226d01485.png)

Getting this error in PgAdmin

Unable to connect to server:

could not connect to server: Connection refused
Is the server running on host "XX.XX.XX.XX" and accepting
TCP/IP connections on port 5432?

I also allowed 5432 port from my firewall in EC2

**Comment by Narendra-Modi** [comment]
Now, this is working as expected, i'd to add these ports before running ``make build`` and i was doing it after making it
