### ISSUE TITLE
Out of Scope options

### ISSUE THREAD

**Issue by Darth-Ginger** [yogeshojha/rengine#213]
There are times when you don't want to scan certain domains/subdomains as they are specified Out of Scope. It would be nice to have the option to add this.

In designating a new target, offer an option for a list of domains/subdomains to be skipped. Regex here would be nice but not necessary.

**Comment by r3dC4prica** [comment]
I also came here to request this feature!

**Comment by yogeshojha** [comment]
Yay, the PR from @valbrux solves this. Waiting to merge in v0.5.
