### ISSUE TITLE
Could not resolve host: github.com

### ISSUE THREAD

**Issue by tushRana** [yogeshojha/rengine#216]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

While doing make build, it gets stuck on the steps where the tools are installed from github using 'go get'. Throws an error that github.com could not be resolved. Please see screenshot attached.

<img width="680" alt="Capture" src="https://user-images.githubusercontent.com/25536846/90218069-89c61000-de20-11ea-9ab9-8c8e175a5172.PNG">

Previously, it got stuck at the same step but gave an SSL certificate error while installing from github. But I was able to solve that by adding the line 'RUN git config --global http.sslVerify false' in the Dockerfile. Now it is giving the error in the screenshot.

**Comment by attacker007** [comment]
Hi @tushRana it only can happen due to slow internet. Try to not use internet for other commands or devices. before running do this  "export GO111MODULE=on"

**Comment by tushRana** [comment]
Hi @attacker007 , I was able to solve it. There was a network connection issue for the docker daemon, had to reconfigure the DNS. Installed the tool and working perfectly. Amazing tool btw great work

**Comment by Vikas92155** [comment]
Hey i was also having similar kind of issue can we discuss it over private chat or mail . Or on slack. 
https://twitter.com/_vikas_gupta_

**Comment by tushRana** [comment]
Hi @Vikas92155 , let me post my solution here might help others as well:

Configured the DNS settings of Docker in file /etc/default/docker and added address to Google servers and restart docker service-
DOCKER_OPTS="--dns 8.8.8.8 --dns 8.8.4.4 --dns 192.168.1.1"

Refer this thread-
https://stackoverflow.com/questions/24151129/network-calls-fail-during-image-build-on-corporate-network
