### ISSUE TITLE
Feature - IP Addresses & Masscan

### ISSUE THREAD

**Issue by uBadRequest** [yogeshojha/rengine#220]
**Is your feature request related to a problem? Please describe.**
Wanting to have a list of the IP addresses that all the subdomains resolved to.

**Describe the solution you'd like**
Maybe, another tab that displays the subdomains and what IP address they resolved and an option to download just the IP addresses. It would be really cool if you also implement running masscan on them all.

**Comment by yogeshojha** [comment]
Yay, this is available V0.4. 🎉 

IP Address and CNAME is being displayed in a separate column. Please check the lastest version
