### ISSUE TITLE
Bug - Unable to build on DigitalOcean 

### ISSUE THREAD

**Issue by b0tzone** [yogeshojha/rengine#221]
Hi Team,

I was trying to build the docker image with "make build" command on DigitalOcean's machine (Ubuntu 18.04) , but facing out of memory issue.

Please refer the below screenshots,

![image](https://user-images.githubusercontent.com/39560492/90784359-ce6d1200-e31e-11ea-8b26-0d5204e96b5b.png)

![image](https://user-images.githubusercontent.com/39560492/90784469-ed6ba400-e31e-11ea-9d24-92fe363d9f9c.png)

Thanks.

**Comment by goodrookie** [comment]
I had the same problem and I upgraded to 2GB, and there it's working!

**Comment by b0tzone** [comment]
Thank You! @goodrookie 

After upgrade to 2GP machine, it's working fine. Thanks again 👍
