### ISSUE TITLE
[IP]/start_scan/export/endpoints/2 --->> 502 Bad Gateway

### ISSUE THREAD

**Issue by goodrookie** [yogeshojha/rengine#222]
### Issue Summary
ss
When I want to export endpoints from the dedicated green button, it gives 502 error.
Subs and URL exports work perfectly.

OS: Ubuntu 18
VPS: Digital Ocean, plenty free disk space, I've alredy gone to 8vCPUs and 8GB RAM.

Diagnostics:
gunicorn process go nuts when exporting several thousands of endpoint TXT (see attached). I have 2 examples from a couple of big domains:
1) +/- 57000 endpoints.
2) +/- 24000 endpoints.

Maybe there's some way to fine tune gunicorn process.
Thanks!

<img width="326" alt="gunicorn process" src="https://user-images.githubusercontent.com/43944006/90839557-2cedbc80-e32e-11ea-950a-4d21d4e2d963.png">

**Comment by r3dC4prica** [comment]
I also experience issue every time I start a new scan
