### ISSUE TITLE
ERROR: for proxy  Cannot create container for service proxy with rengine_chain.pem

### ISSUE THREAD

**Issue by fre3vil** [yogeshojha/rengine#227]
### Issue Summary

The error show as below
ERROR: for proxy  Cannot create container for service proxy: invalid mount config for type "bind": bind source path does not exist: /root/git/rengine/secrets/certs/rengine_chain.pem

### Steps to Reproduce

1. when I use docker-compose up -d, it can't create rengine_proxy_1 instance.
2. How can I to solve this problem, it can't generate rengine_chain.pem automatically.

**Comment by fre3vil** [comment]
I had forget to use make certs generate certs

**Comment by Gp9633** [comment]
how to fix this i got similar error

**Comment by dirtycoder0124** [comment]
I am also facing the same problem. Any solution?

**Comment by 5m477** [comment]
i am facing the same error. Any fix to this?

**Comment by dirtycoder0124** [comment]
Download latest rengine and follow the new installation instructions.

**Comment by moeyass8** [comment]
Just run the $ sudo ./install.sh 
before composing the docker up with: 
$ sudo docker-compose up

**Comment by mdaxido** [comment]
> Just run the $ sudo ./install.sh before composing the docker up with: $ sudo docker-compose up

That does not work, rengine_chain.pem is not created.

**Comment by mdaxido** [comment]
> > Just run the $ sudo ./install.sh before composing the docker up with: $ sudo docker-compose up
> That does not work, rengine_chain.pem is not created.
Next run it is rengine.pem missing (but still no rengine_chain.pem)

Needs a bit more of that "heavily tested" thing, Debian 12

**Comment by mdaxido** [comment]
openssl req -x509 -newkey rsa:4096 -sha256 -days 3650 -nodes \
  -keyout docker/secrets/certs/rengine_rsa.key \
  -out    docker/secrets/certs/rengine.pem \
  -subj "/CN=localhost"

cp docker/secrets/certs/rengine.pem docker/secrets/certs/rengine_chain.pem
