### ISSUE TITLE
Failed to Scan

### ISSUE THREAD

**Issue by random-robbie** [yogeshojha/rengine#228]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

add twitter and do a passive scan.

### Steps to Reproduce

```
Running migrations:
  No migrations to apply.
Installed 3 object(s) from 1 fixture(s)
[2020-09-07 09:47:08 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-09-07 09:47:08 +0000] [1] [INFO] Listening at: http://0.0.0.0:8000 (1)
[2020-09-07 09:47:08 +0000] [1] [INFO] Using worker: sync
[2020-09-07 09:47:08 +0000] [12] [INFO] Booting worker with pid: 12
cat: can't open '/*.txt': No such file or directory
sh: twitter.com: not found
sh: _2020_09_07_09_47_35: not found
Traceback (most recent call last):
  File "/app/startScan/views.py", line 184, in doScan
    with open(subdomain_scan_results_file) as subdomain_list:
FileNotFoundError: [Errno 2] No such file or directory: '/app/tools/scan_results/twitter.com\n_2020_09_07_09_47_35/sorted_subdomain_collection.txt'
```

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes )

**Comment by random-robbie** [comment]
Bug appears to happen when the domain has been imported via text file.

**Comment by ptrk01** [comment]
@random-robbie I faced the same problem. When importing domains via txt file then all domain scan are failing. If I add the domains manually (domain by domain) the scan works.

**Comment by yogeshojha** [comment]
Oops this was a problem when imported targets had trailing "\n".

This has been fixed now

**Comment by yogeshojha** [comment]
Thanks @random-robbie for reporting this!
