### ISSUE TITLE
ERROR: Encountered errors while bringing up the project.

### ISSUE THREAD

**Issue by Gp9633** [yogeshojha/rengine#238]
when i was setting up , it crashed like the below what to do now?

Successfully built 4b9ac47907f8
Successfully tagged docker.pkg.github.com/yogeshojha/rengine/rengine:latest
rengine_db_1 is up-to-date
rengine_web_1 is up-to-date
Creating rengine_proxy_1 ... error
ERROR: for rengine_proxy_1  Cannot create container for service proxy: invalid mount config for type "bind": bind source path does not exist: /home/d3lt4/rengine/secrets/certs/rengine_chain.pem

ERROR: for proxy  Cannot create container for service proxy: invalid mount config for type "bind": bind source path does not exist: /home/d3lt4/rengine/secrets/certs/rengine_chain.pem
ERROR: Encountered errors while bringing up the project.

![Screenshot (3)](https://user-images.githubusercontent.com/37683369/95108844-b6691a80-0733-11eb-9489-245a83381331.png)

**Comment by yogeshojha** [comment]
You haven't generated certificates. Please read the documentation available at rengine.wiki

**Comment by vpsfree13** [comment]
how i can solve this error i dont have any process work on port 80 i install everything but proxy problem :( i cant up tool on gcp
help me please this error 

ERROR: for proxy  Cannot start service proxy: driver failed programming external connectivity on endpoint rengine_proxy_1 (0c7be04d28979132bdba34ebf2f27bb16008e7137c904a6524f32a4d755089c5): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use

**Comment by ludbaziza** [comment]
hello i have error like this, how should i [do?[](url)](url)
![Screenshot 2023-09-01 230714](https://github.com/yogeshojha/rengine/assets/100133942/a0ae190e-25f7-4b51-bb0f-d50b379d971e)

**Comment by ludbaziza** [comment]
> enerated

sir i have sam issue, i have create certs but still have this problem:
Creating rengine_proxy_1 ... error

ERROR: for rengine_proxy_1  Cannot create container for service proxy: invalid mount config for type "bind": bind source path does not exist: /home/kali/Hunting/rengine/secrets/certs/rengine_chain.pem

ERROR: for proxy  Cannot create container for service proxy: invalid mount config for type "bind": bind source path does not exist: /home/kali/Hunting/rengine/secrets/certs/rengine_chain.pem
ERROR: Encountered errors while bringing up the project.
make: *** [Makefile:22: up] Error 1

**Comment by ludbaziza** [comment]
> You haven't generated certificates. Please read the documentation available at rengine.wiki

upps after i  check it again i have error in make certs like this:
Unable to load certificate request input
mv: can't rename 'rengine.crt': No such file or directory
cp: can't stat 'ca.crt': No such file or directory
rm: can't remove 'rengine.csr': No such file or directory

how to fix this?
