### ISSUE TITLE
Bug - More than one ip, and not alligned

### ISSUE THREAD

**Issue by jaykumarjp** [yogeshojha/rengine#241]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

New feature added in v4 which show ip addresses but more than one ip also not alligned.

### Steps to Reproduce

1. scan a bigscope target and look in result, see ip address column

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)

![image](https://user-images.githubusercontent.com/42172283/95472756-0993d500-09a1-11eb-8111-5c3096241711.png)

- [ ]

**Comment by yogeshojha** [comment]
I guess this happens with the older scans, can you please run a new scan and confirm if this happens?

Earlier we were capturing as many IP as we could from aquatone, now we are using data provided by HTTPX and have a single IP. Could you please confirm?

**Comment by jaykumarjp** [comment]
Yes you right sir.. these were in old scan not happening with new one
