### ISSUE TITLE
Service 'web' failed to build

### ISSUE THREAD

**Issue by Slingx** [yogeshojha/rengine#242]
Step 13/24 : RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx     github.com/projectdiscovery/naabu/cmd/naabu     github.com/projectdiscovery/subfinder/cmd/subfinder     github.com/lc/gau
 ---> Running in ddf41f63849d
go: finding github.com/lc/gau v1.0.5
go: finding github.com/projectdiscovery/subfinder v2.4.5+incompatible
go: finding github.com/projectdiscovery/httpx v1.0.2
go: finding github.com/projectdiscovery/naabu v2.0.2+incompatible
go: downloading github.com/lc/gau v1.0.5
go: downloading github.com/projectdiscovery/httpx v1.0.2
go: downloading github.com/projectdiscovery/subfinder v2.4.5+incompatible
go: downloading github.com/projectdiscovery/naabu v2.0.2+incompatible
go: extracting github.com/projectdiscovery/naabu v2.0.2+incompatible
go get github.com/projectdiscovery/naabu/cmd/naabu: module github.com/projectdiscovery/naabu@upgrade found (v2.0.2+incompatible), but does not contain package github.com/projectdiscovery/naabu/cmd/naabu
go: extracting github.com/lc/gau v1.0.5
go: extracting github.com/projectdiscovery/subfinder v2.4.5+incompatible
go get github.com/projectdiscovery/subfinder/cmd/subfinder: module github.com/projectdiscovery/subfinder@upgrade found (v2.4.5+incompatible), but does not contain package github.com/projectdiscovery/subfinder/cmd/subfinder
go: extracting github.com/projectdiscovery/httpx v1.0.2
The command '/bin/sh -c GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx     github.com/projectdiscovery/naabu/cmd/naabu     github.com/projectdiscovery/subfinder/cmd/subfinder     github.com/lc/gau' returned a non-zero code: 1
ERROR: Service 'web' failed to build
Makefile:25: recipe for target 'build' failed
make: *** [build] Error 1

:/

**Comment by Slingx** [comment]
I get this when i try to use "make build"

**Comment by jaykumarjp** [comment]
same i recieved when installing in kali linux

**Comment by Jacoppy** [comment]
I am using kali 2020.3 and after many tries it worked out, I had to recreate the certificates and then the build worked

**Comment by Anne272732** [comment]
Hi @yogeshojha,

I get the same error today:

Step 13/25 : RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx
 ---> Running in d8c05673d917
go: downloading github.com/projectdiscovery/httpx v1.0.3
go: found github.com/projectdiscovery/httpx/cmd/httpx in github.com/projectdiscovery/httpx v1.0.3
go: downloading github.com/projectdiscovery/fdmax v0.0.2
go: downloading github.com/projectdiscovery/rawhttp v0.0.4
go: downloading golang.org/x/text v0.3.4
go: downloading github.com/projectdiscovery/mapcidr v0.0.4
go: downloading github.com/projectdiscovery/hmap v0.0.1
go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
go: downloading github.com/projectdiscovery/gologger v1.0.1
go: downloading github.com/microcosm-cc/bluemonday v1.0.4
go: downloading github.com/remeh/sizedwaitgroup v1.0.0
go: downloading golang.org/x/net v0.0.0-20201110031124-69a78807bb2b
go: downloading github.com/projectdiscovery/retryablehttp-go v1.0.1
go: downloading github.com/projectdiscovery/cdncheck v0.0.1
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading github.com/projectdiscovery/clistats v0.0.5
go: downloading github.com/hbakhtiyor/strsim v0.0.0-20190107154042-4d2bbb273edf
go: downloading github.com/yl2chen/cidranger v1.0.0
go: downloading github.com/rs/xid v1.2.1
go: downloading go.uber.org/atomic v1.7.0
go: downloading github.com/chris-ramon/douceur v0.2.0
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
go: downloading github.com/projectdiscovery/fastdialer v0.0.1
go: downloading github.com/gorilla/css v1.0.0
go: downloading github.com/projectdiscovery/retryabledns v1.0.5
go: downloading github.com/aymerick/douceur v0.2.0
go: downloading github.com/miekg/dns v1.1.29
go: downloading golang.org/x/crypto v0.0.0-20201112155050-0c6587e931a9
go: downloading golang.org/x/sys v0.0.0-20201113233024-12cec1faf1ba
go: github.com/projectdiscovery/clistats upgrade => v0.0.7
go: github.com/miekg/dns upgrade => v1.1.35
go: golang.org/x/crypto upgrade => v0.0.0-20201221181555-eec23a3978ad
go: github.com/yl2chen/cidranger upgrade => v1.0.2
go: github.com/projectdiscovery/fastdialer upgrade => v0.0.2
go: golang.org/x/sys upgrade => v0.0.0-20201223074533-0d417f636930
go: golang.org/x/text upgrade => v0.3.4
go: golang.org/x/net upgrade => v0.0.0-20201224014010-6772e930b67b
go: github.com/projectdiscovery/gologger upgrade => v1.1.2
go: github.com/logrusorgru/aurora upgrade => v2.0.3+incompatible
go: github.com/golang/snappy upgrade => v0.0.2
go: github.com/projectdiscovery/fdmax upgrade => v0.0.3
go: downloading github.com/projectdiscovery/gologger v1.1.2
go: downloading github.com/projectdiscovery/fdmax v0.0.3
go: downloading golang.org/x/sys v0.0.0-20201223074533-0d417f636930
go: downloading github.com/golang/snappy v0.0.2
go: downloading golang.org/x/net v0.0.0-20201224014010-6772e930b67b
go: downloading github.com/projectdiscovery/clistats v0.0.7
go: downloading github.com/yl2chen/cidranger v1.0.2
go: downloading github.com/projectdiscovery/fastdialer v0.0.2
go: downloading github.com/json-iterator/go v1.1.10
go: downloading github.com/dimchansky/utfbom v1.1.1
go: downloading github.com/miekg/dns v1.1.35
go: downloading github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
go: downloading github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: downloading golang.org/x/crypto v0.0.0-20201221181555-eec23a3978ad
go: github.com/modern-go/reflect2 upgrade => v1.0.1
go: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading github.com/modern-go/reflect2 v1.0.1
github.com/modern-go/concurrent
github.com/modern-go/reflect2
github.com/json-iterator/go
github.com/logrusorgru/aurora
github.com/projectdiscovery/gologger/levels
github.com/projectdiscovery/gologger/formatter
github.com/projectdiscovery/gologger/writer
github.com/projectdiscovery/gologger
go.uber.org/atomic
github.com/projectdiscovery/clistats
golang.org/x/sys/internal/unsafeheader
golang.org/x/sys/unix
github.com/projectdiscovery/fdmax
github.com/projectdiscovery/fdmax/autofdmax
github.com/projectdiscovery/hmap/store/cache
github.com/syndtr/goleveldb/leveldb/util
github.com/syndtr/goleveldb/leveldb/cache
github.com/syndtr/goleveldb/leveldb/comparer
github.com/syndtr/goleveldb/leveldb/storage
github.com/syndtr/goleveldb/leveldb/errors
github.com/syndtr/goleveldb/leveldb/filter
github.com/syndtr/goleveldb/leveldb/iterator
github.com/syndtr/goleveldb/leveldb/journal
github.com/syndtr/goleveldb/leveldb/memdb
github.com/syndtr/goleveldb/leveldb/opt
github.com/golang/snappy
github.com/syndtr/goleveldb/leveldb/table
github.com/syndtr/goleveldb/leveldb
github.com/projectdiscovery/hmap/store/disk
github.com/projectdiscovery/hmap/store/hybrid
github.com/projectdiscovery/httpx/common/customheader
github.com/hbakhtiyor/strsim
github.com/aymerick/douceur/css
github.com/gorilla/css/scanner
github.com/chris-ramon/douceur/parser
golang.org/x/net/html/atom
golang.org/x/net/html
github.com/microcosm-cc/bluemonday
github.com/yl2chen/cidranger/net
github.com/yl2chen/cidranger
github.com/projectdiscovery/cdncheck
github.com/dimchansky/utfbom
golang.org/x/crypto/ed25519
golang.org/x/net/bpf
golang.org/x/net/internal/iana
golang.org/x/net/internal/socket
golang.org/x/net/ipv4
golang.org/x/net/ipv6
github.com/miekg/dns
github.com/projectdiscovery/retryabledns
github.com/projectdiscovery/fastdialer/fastdialer
github.com/projectdiscovery/retryablehttp-go
github.com/projectdiscovery/httpx/common/httputilz
github.com/projectdiscovery/httpx/common/slice
github.com/projectdiscovery/rawhttp/client
github.com/projectdiscovery/rawhttp/clientpipeline
github.com/projectdiscovery/rawhttp
github.com/rs/xid
golang.org/x/text/transform
golang.org/x/text/unicode/bidi
golang.org/x/text/secure/bidirule
golang.org/x/text/unicode/norm
golang.org/x/net/idna
golang.org/x/net/http/httpguts
golang.org/x/net/http2/hpack
golang.org/x/net/http2
golang.org/x/text/encoding/internal/identifier
golang.org/x/text/encoding
golang.org/x/text/encoding/internal
golang.org/x/text/encoding/simplifiedchinese
golang.org/x/text/encoding/traditionalchinese
github.com/projectdiscovery/httpx/common/httpx
# github.com/projectdiscovery/httpx/common/httpx
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:41:4: undefined: gologger.Errorf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:61:3: undefined: gologger.Errorf
github.com/projectdiscovery/httpx/common/fileutil
github.com/projectdiscovery/httpx/common/iputil
github.com/projectdiscovery/httpx/common/stringz
github.com/projectdiscovery/mapcidr
github.com/remeh/sizedwaitgroup
The command '/bin/sh -c GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx' returned a non-zero code: 2
ERROR: Service 'web' failed to build
make: *** [Makefile:25: build] Error 1

I try to install in a fresh digital ocean droplet (Ubuntu 20.04 (LTS) x64) and try to execute make build several times and always the same error...any idea  to solve it?

Regards,

Anne

**Comment by InfoSec4Fun** [comment]
Hi @yogeshojha,
I'm also facing the same issue

Step 13/25 : RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx
 ---> Running in 48adbd3f64d0
go: downloading github.com/projectdiscovery/httpx v1.0.3
go: found github.com/projectdiscovery/httpx/cmd/httpx in github.com/projectdiscovery/httpx v1.0.3
go: downloading github.com/projectdiscovery/gologger v1.0.1
go: downloading github.com/projectdiscovery/clistats v0.0.5
go: downloading github.com/remeh/sizedwaitgroup v1.0.0
go: downloading github.com/projectdiscovery/fdmax v0.0.2
go: downloading github.com/projectdiscovery/mapcidr v0.0.4
go: downloading github.com/microcosm-cc/bluemonday v1.0.4
go: downloading github.com/projectdiscovery/fastdialer v0.0.1
go: downloading github.com/projectdiscovery/hmap v0.0.1
go: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
go: downloading github.com/hbakhtiyor/strsim v0.0.0-20190107154042-4d2bbb273edf
go: downloading golang.org/x/net v0.0.0-20201110031124-69a78807bb2b
go: downloading github.com/projectdiscovery/cdncheck v0.0.1
go: downloading golang.org/x/text v0.3.4
go: downloading github.com/projectdiscovery/retryablehttp-go v1.0.1
go: downloading github.com/syndtr/goleveldb v1.0.0
go: downloading github.com/chris-ramon/douceur v0.2.0
go: downloading github.com/projectdiscovery/retryabledns v1.0.5
go: downloading github.com/rs/xid v1.2.1
go: downloading github.com/projectdiscovery/rawhttp v0.0.4
go: downloading go.uber.org/atomic v1.7.0
go: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
.
.
.
github.com/projectdiscovery/httpx/common/httpx
#github.com/projectdiscovery/httpx/common/httpx
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:41:4: undefined: gologger.Errorf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:61:3: undefined: gologger.Errorf
The command '/bin/sh -c GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx' returned a non-zero code: 2
**ERROR: Service 'web' failed to build
Makefile:25: recipe for target 'build' failed
make: *** [build] Error 1**


Regards,
Amar

**Comment by abundov** [comment]
Just a heads up for this error: My fix was to **"make certs" again** and try "make build" after. I
t completed successfully.

**Comment by sidh104** [comment]
> [rengine_celery 25/31] RUN nuclei -update:
#0 0.624 
#0 0.624                      __     _
#0 0.624    ____  __  _______/ /__  (_)
#0 0.624   / __ \/ / / / ___/ / _ \/ /
#0 0.624  / / / / /_/ / /__/ /  __/ /
#0 0.624 /_/ /_/\__,_/\___/_/\___/_/   2.7.5
#0 0.624 
#0 0.624                projectdiscovery.io
#0 0.624 
#0 0.625 [WRN] Use with caution. You are responsible for your actions.
#0 0.625 [WRN] Developers assume no liability and are not responsible for any misuse or damage.
#0 5.675 [FTL] Could not create runner: could not fetch latest release: context deadline exceeded
------
failed to solve: executor failed running [/bin/sh -c nuclei -update]: exit code: 1
make: *** [Makefile:25: build] Error 17

after make cert and make build still getting error!
