### ISSUE TITLE
Unable to delete or turnoff Scheduled Scans

### ISSUE THREAD

**Issue by VaibhavNagariya** [yogeshojha/rengine#243]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

On "https://x.x.x.x/start_scan/scheduled/" page, scheduled scans can't be deleted or turned off. 

### Steps to Reproduce

1. Setup a scheduled scan.
2. Go to "https://x.x.x.x/start_scan/scheduled/" page
3. Try to delete or turn off any scheduled scan.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

Please list out any technical details such as the operating environment.

I am running reNgine on Ubuntu 18.08

**Comment by yogeshojha** [comment]
There was a known issue in the older version of celery. This is now fixed in v0.5.
