### ISSUE TITLE
Feature - separated page for directory scanning

### ISSUE THREAD

**Issue by miaochiahao** [yogeshojha/rengine#244]
Mixing directory scanning results in subdomain page may not be the best idea, directory results breaks the table. If rengine creates another page for directory listing, the whole dashboard will be more clear.

**Comment by yogeshojha** [comment]
You'll now see a separate page for Directory
![Screenshot from 2021-08-15 12-48-06](https://user-images.githubusercontent.com/17223002/129470393-b777e30b-ed64-43ca-a220-68add39551c7.png)
