### ISSUE TITLE
Scan Goes on Loop

### ISSUE THREAD

**Issue by adik69** [yogeshojha/rengine#245]
###Summary
I see you have upgraded the rengine with more new features. But this issue wasn't there before.

After the scan is being completed It restarts the scan again . It goes on loop.
And I'm really unsure what is causing this.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

![Screenshot_2020-10-19 Scan history](https://user-images.githubusercontent.com/25083418/96503982-b3ad1000-1271-11eb-86c0-3334eddb4510.png)

### Technical details
Debian (Docker installed)

**Comment by ptrk01** [comment]
I faced this problem as well. It scanned the same target again and again. This problem arises from time to time and happens since scheduled scans were implemented.

**Comment by yogeshojha** [comment]
Is this still occurring? Please attach the logs 

`make logs`
