### ISSUE TITLE
Bug - Passive scan makes active connections to identified domains.

### ISSUE THREAD

**Issue by ad0nis** [yogeshojha/rengine#246]
### Issue Summary

When performing a "passive scan" of a domain, I noticed that it had actually requested every path that it had identified on a webserver, and even hit rate-limiting. Clearly not "passive" behavior.

### Steps to Reproduce

1. Create a new passive scan
2. Scan a domain
3. Observe "Endpoints" section.

Passive implies that no connections are made to identified sites, and should be "safe" to run without alerting the target to your investigation. I can see a single connection being made to screenshot a website as one thing. Retrieving every resource on that site is noisy as hell, and well beyond any definition of passive.

### Technical details

Ubuntu 20.04 Server, installed using setup instructions.

**Comment by yogeshojha** [comment]
You are right @ad0nis, I need to remove httpx from passive.
