### ISSUE TITLE
Error Logs & Resume Scan button

### ISSUE THREAD

**Issue by ad0nis** [yogeshojha/rengine#252]
**Is your feature request related to a problem? Please describe.**
Ran a scan of a bugbounty domain, and it just shows "failed". Some hosts appear to have been scanned, but no reason identified in the UI for the failure. No way to resume a failed scan where it gave up.

**Describe the solution you'd like**
Would be great to have a logging tab that shows what's going on in the server's back-end, and shows why something may have failed for troubleshooting purposes.

Additionally, it would be great to have a way to resume a failed scan wherever it failed, so as to not lose scan progress.

**Describe alternatives you've considered**
Hadn't thought about it too much, but open to other ideas. :)

**Comment by yogeshojha** [comment]
You can get the logs using `make logs`.
