### ISSUE TITLE
Bug - Title of Bug

### ISSUE THREAD

**Issue by E-R-R-O-R-404** [yogeshojha/rengine#253]
Found a bug? Please fill out the sections below. 👍
remove number of limit
### Issue Summary
some times the targets are not scanning even only 2 scans are running so please remove the no of limits in scan or create a button for setting number of scans
A summary of the issue.

### Steps to Reproduce

1. When I am scanning the domains, this happens
2. ...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)

### Technical details

Please list out any technical details such as operating environment.

**Comment by yogeshojha** [comment]
The scans are based on the number of threads available on your CPU. Celery divides the task based on the number of available free threads. There should be a workaround to increase the number of scans, but at this point, this is not in priority. However, I will come back to this issue in future, if there's more community request on this.
