### ISSUE TITLE
Stuck On Dirsearch

### ISSUE THREAD

**Issue by hackingguy** [yogeshojha/rengine#258]
### Issue Summary
From previous three days on a simple website it get stuck on get_dirs.sh, I tried to abort the scans and restart them, but every effort nonetheless. I just 
I am also not able to import txt or csv file, getting error invalid file format, is there any issue related to "\r\n" and "\n" ?

### Steps to Reproduce

N/A

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes (Using Nuclei Version)

### Technical details

N/A

**Comment by yogeshojha** [comment]
Please attach logs.

`make logs`

**Comment by hackingguy** [comment]
May be issue with VPS, I was using it in ec2 instance 1 GB RAM t2 micro!

**Comment by hackingguy** [comment]
Please update in README Section about minimum requirements
