### ISSUE TITLE
Feature - Add Option to Import IP's As Targets

### ISSUE THREAD

**Issue by meridian0x01** [yogeshojha/rengine#260]
Just like importing domains as targets, it would be great to also import ip's as a .txt file!
It could be useful especially when doing internal network recon!

**Comment by meridian0x01** [comment]
Hi there.
Any updates, regarding this issue or any ETA?
Thanks

**Comment by moshealon76** [comment]
Hi 
Any update +1?

**Comment by meridian0x01** [comment]
Hi any updates regarding this issue!??

**Comment by yogeshojha** [comment]
This is available in reNgine 1.1. Thank you for the feature request.

**Comment by SkinAir** [comment]
Hello, I didn't see the update of ip.txt in the latest version 1.3.6 of engine

> This is available in reNgine 1.1. Thank you for the feature request.这在 reNgine 1.1 中可用。感谢您的功能请求。

Hello, I didn't see the update of ip.txt in the latest version 1.3.6 of engine
