### ISSUE TITLE
Global/Target Blacklist

### ISSUE THREAD

**Issue by uBadRequest** [yogeshojha/rengine#267]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i've been told im scanning out of scope assets.

**Describe the solution you'd like**
When creating a target, we should be able to define subdomains on that target that are out of scope.

It may also be nice to have a blacklist that can be uploaded, then I can easily collect all of the out of scope assets across a number of targets and upload them.

**Comment by yogeshojha** [comment]
Hi @uBadRequest, happy to tell you that v0.5 is coming up with out of scope options 😉 

Please wait until this weekend.
