### ISSUE TITLE
unknown flag: --iidfile

### ISSUE THREAD

**Issue by flag-KKK** [yogeshojha/rengine#268]
**make crets：**

WARNING: Native build is an experimental feature and could change at any time
Building certs
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'certs' failed to build
make: *** [certs] Error 1

**make build：**

WARNING: Native build is an experimental feature and could change at any time
Building web
unknown flag: --iidfile
See 'docker build --help'.
ERROR: Service 'web' failed to build
make: *** [build] Error 1

**Comment by yogeshojha** [comment]
Did you make any changes to makefile?

**Comment by flag-KKK** [comment]
No,I never did it

**Comment by atikrahman1** [comment]
did you find any solution for this? I am facing the same issue @flag-KKK

**Comment by atikrahman1** [comment]
I have solved the issue by updating my old docker version to the latest one
