### ISSUE TITLE
Please Help! 0 Endpoints Discovered!

### ISSUE THREAD

**Issue by oumeirsaifedeen** [yogeshojha/rengine#270]
Hello, I have installed reNgine correctly on Ubuntu VPS, version Ubuntu 20.04 (LTS) x64 and I get a problem that the tool is not using the Endpoints Discovered tools like "Diresearch" and at the end of the search it says this error 
![image](https://user-images.githubusercontent.com/75129663/100518553-21890900-3147-11eb-9ef8-f6e6d89548ac.png)
![image](https://user-images.githubusercontent.com/75129663/100518643-9bb98d80-3147-11eb-914e-5aea83c5b5e0.png)

**And this my Engine settings**
![image](https://user-images.githubusercontent.com/75129663/100518515-d53dc900-3146-11eb-9b8f-7a03a4124b29.png)
![image](https://user-images.githubusercontent.com/75129663/100518524-e1298b00-3146-11eb-94cd-bc19a2c8e590.png)

So I had to check "Dirsearch" if it was running alone on my VPS and was running without problems
And I have checked the logs and this result was not able to know where the problem is, can you help me?

**Screenshot for the logs**
![image](https://user-images.githubusercontent.com/75129663/100518820-e12a8a80-3148-11eb-9d15-ef034d9b18f3.png)

**Comment by yogeshojha** [comment]
The log doesn't show anything as such. Can you attach another log?
