### ISSUE TITLE
Feature - safe and vulnerable file differentiation 

### ISSUE THREAD

**Issue by Rpal1315** [yogeshojha/rengine#271]
**Is your feature request related to a problem? Please describe.**
If there are vulnerable files in a website 
 then  the computer may be attacked by malwares

**Describe the solution you'd like**
I want a feature that will filter safe and malware affected files

@yogeshojha

**Comment by Rpal1315** [comment]
@yogeshojha please respond to the issue

**Comment by yogeshojha** [comment]
Rengine doesn't perform anything related to malware.
