### ISSUE TITLE
Feature - Progress precentage

### ISSUE THREAD

**Issue by sasokyleader** [yogeshojha/rengine#272]
**Is your feature request related to a problem? Please describe.**
When i close my pc and reopen it, the tool i cant know weather it is still working or not it shows in progress but is taking a lot of time (about 4 days know)  so i suggest adding a progress percentage to know the state of the tool

**Describe the solution you'd like**
adding a progress percentage

**Comment by yogeshojha** [comment]
This is coming 😉 Please wait for the v0.5 release.
