### ISSUE TITLE
Bug - missing module mathfilters on web container

### ISSUE THREAD

**Issue by 0xShin** [yogeshojha/rengine#274]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
A missing module has been found on a web container in the new update which stops the web container to be launched.

### Steps to Reproduce

1. When, I launch rengine I use `docker-compose -f docker.compose.dev.yml` for dev purposes.
2. When I try to run it, it seems the web container doesn't launch up due to module error.
![image](https://user-images.githubusercontent.com/50789123/100572765-4204bf00-3311-11eb-8017-c6324c17d3d1.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I expected the web container to run properly.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
Yes

### Technical details

- Ubuntu 18.04.4 LTS

**Comment by yogeshojha** [comment]
This is strange. Let me look at the requirements file.

**Comment by yogeshojha** [comment]
Can you please attach your requirements.txt file?

**Comment by 0xShin** [comment]
Yeah, sure <3 
[requirements.txt](https://github.com/yogeshojha/rengine/files/5614000/requirements.txt)

**Comment by 0xShin** [comment]
I have checked my requirements.txt to your repository's requirements.txt and they both seems the same.

**Comment by 0xShin** [comment]
Hi yoge, we can close this now, I fixed it through changing the Django version in requirements.txt to 3.1.4
