### ISSUE TITLE
Feature - Ability to do a Nuclei Vuln scan on alive endpoints

### ISSUE THREAD

**Issue by alph4byt3** [yogeshojha/rengine#275]
If possible, implement a way for nuclei to scan the list of alive endpoints as well. Some of nucleis templates such as the XSS prober rely on GET parameters(iirc) and what would be especially useful with this is the tokens templates which can scan all JS endpoints that are found.

**Comment by yogeshojha** [comment]
I did this infact. But the problem was, when nuclei received approx 20k+ endpoints, it crashed. I need to talk to nuclei guys, and see if it actually is a problem with my implementation or Nuclei. 

But thanks for pointing this out.

**Comment by alph4byt3** [comment]
Interesting, I wonder if that's the same for just the domains/ subdomains. If theoretically you have 20k working subdomains, would nuclei misbehave as well. Anyway, I know a lot of people run the tokens template on a list of js endpoints because it's good at finding secret keys so having it implemented would add this functionality. But yeah, check up with PD, sounds like a limitation on their end but I can't say for sure

**Comment by yogeshojha** [comment]
I have tried for 50k+ subdomains, and I had no issues. It could be one reason that, your http URL contains many params and also sometimes URL maybe too long for nuclei to parse. Can't say for sure, I ran scan multiple times and it failed, so I dropped the plan of using URLs. Neverthless, in future we have to find a way for this. This will surely increase reNgine capabilities.

**Comment by yogeshojha** [comment]
This is now working in 1.0
