### ISSUE TITLE
docker issue

### ISSUE THREAD

**Issue by sakyb7** [yogeshojha/rengine#284]
when i install i it from docker hub or build with docker compose it errorin 
```
getaddrinfo: Name does not resolve
getaddrinfo: Name does not resolve

**Comment by FlaviuPopescu** [comment]
This may help your situation,

You need to install **bind-tools** in Dockerfile-dev for Name does not resolve problem:

**apk add bind-tools** 

Test:

/usr/src/app # **nslookup users-db**
nslookup: can't resolve '(null)': Name does not resolve

Name:      users-db
Address 1: 172.20.0.2 stc_users-db_1_f435854a8c88.stc_default

/usr/src/app # **apk add bind-tools**
(1/4) Installing json-c (0.13.1-r0)
(2/4) Installing libxml2 (2.9.8-r1)
(3/4) Installing bind-libs (9.12.3-r0)
(4/4) Installing bind-tools (9.12.3-r0)
Executing busybox-1.28.4-r3.trigger
OK: 188 MiB in 62 packages

/usr/src/app # **nslookup users-db**
Server:         127.0.0.11
Address:        127.0.0.11#53

Non-authoritative answer:
Name:   users-db
Address: 172.20.0.2

**Comment by yogeshojha** [comment]
@FlaviuPopescu Thank you ❤️ 

I hope this would have solve this issue
