### ISSUE TITLE
How can I add a custom subdomain list

### ISSUE THREAD

**Issue by M1k0er** [yogeshojha/rengine#285]
How can I add a custom subdomain list

**Comment by FlaviuPopescu** [comment]
Go into Targets > Import Targets > 
In there you can import via .txt file or .csv file

**Supported txt Format**
hackerone.com
docs.hackerone.com
nepal.gov.np
**UnSupported txt Format**
https://hackerone.com
https://docs.hackerone.com
nepal.gov.np/docs
**Supported CSV Format**
hackerone.com
docs.hackerone.com, Hackerone Docs
nepal.gov.np, Nepal Government Bug Bounty
**UnSupported CSV Format**
https://hackerone.com, Hackerone, Target
https://docs.hackerone.com

**Comment by nijats11** [comment]
The same question, tried to put config in scan engine like:
wordlist: new_wordlist, but did not work.

**Comment by yogeshojha** [comment]
@FlaviuPopescu Thank you for helping them out.

@nijats11 can you please attach the logs? Without logs, its impossible to tell what could have gone wrong

**Comment by kcnewb1e** [comment]
should i using protocol to input site list?
like https:// or http:// ? 
cant i input without protocol?
