### ISSUE TITLE
cdncheck

### ISSUE THREAD

**Issue by zer0yu** [yogeshojha/rengine#287]
**Is your feature request related to a problem? Please describe.**

Generally, after discovering the IP corresponding to a domain name, it is necessary to determine whether the corresponding IP is CDN in the first place, so as to avoid useless scanning

**Describe the solution you'd like**
Suggest to add  [cdncheck](https://github.com/projectdiscovery/cdncheck) to determine the IP for the probe

**Comment by yogeshojha** [comment]
reNgine now does CDN check.
