### ISSUE TITLE
Feature - Able to select some notifications

### ISSUE THREAD

**Issue by Anne272732** [yogeshojha/rengine#289]
Thanks for the tool, is awesome..

It would be good in the notifications section, to be able to select which notifications you want to receive, for example, only the start and end of the scan, or only receive vulnerabilities high and/or criticals.

This way you would avoid receiving hundreds of info-type notifications

Best Regards,

Anne

**Comment by matthernet** [comment]
This could be really really helpful in order to receive and read the vulnerabilities in an organized way, avoiding the start/end scene of each target
There is a date for this?

**Comment by yogeshojha** [comment]
Yes, this is done in reNgine 1.0 Thanks, 
![notification](https://user-images.githubusercontent.com/17223002/129470756-577702e0-7da3-4860-95d2-6f239999c694.png)
