### ISSUE TITLE
Feature Request - Discord Webhook for updates.

### ISSUE THREAD

**Issue by FlaviuPopescu** [yogeshojha/rengine#294]
I noticed you use rengine uses webhook for Slack, it would be very useful and easily implementable to do the same concept for Discord, there are many people like myself who are on Discord more often than Slack and would find a lot of value from this. To summarize I think it would be a great addition to your tool. Regards, Flaviu

**Comment by yogeshojha** [comment]
Hi @FlaviuPopescu ,

@EQW99 finally implemented this. I am super proud of him. Much appreciated. Thank you once again.

Also, I awarded him $20 bounty for this feature request, if you would like to support him, please feel free to offer him any bounty.
This will inspire him to implement more feature requests.

Thank you

**Comment by yogeshojha** [comment]
![Screenshot from 2021-02-19 23-55-40](https://user-images.githubusercontent.com/17223002/108545622-07a62f00-730e-11eb-881e-6b6c4e8360ac.png)
