### ISSUE TITLE
How to set the time properly? 

### ISSUE THREAD

**Issue by spazbg** [yogeshojha/rengine#297]
Тhe clock is two hours behind - now is 6:44pm
![image](https://user-images.githubusercontent.com/22222777/102018057-6f228a00-3d73-11eb-8061-3856e3904b38.png)

**Comment by yogeshojha** [comment]
This is a good question though, I have been thinking about this lately.

The clock is currently UTC, I haven't checked with localized time. AFAIK Server time is always on UTC, correct me if I am wrong.


https://github.com/yogeshojha/rengine/blob/a7a1faa44aad72b616d96e1a5565b65d386c05b6/reNgine/settings.py#L129


can you change this to your timezone and see if celery scheduled tasks and normal scan works?


Thanks
