### ISSUE TITLE
Can't stop scan

### ISSUE THREAD

**Issue by spazbg** [yogeshojha/rengine#298]
After the new scan haven't started because there was a massage Pending to finish the previous scan (witch in fact is finished) I tried to stop it but got this message 

![image](https://user-images.githubusercontent.com/22222777/102084680-2f64ac80-3e1e-11eb-8473-ca85d3c46ef5.png)

**Comment by yogeshojha** [comment]
Logically, the scans that have never started cannot be stopped, because celery task id isn't genereted yet.

A good UX would be to remove the stop button for pending scan, what do you think?

**Comment by ptrk01** [comment]
@yogeshojha I would recommend to remove the stop button and add something like "delete from pending list".

However, I have the same problem with a target in scanning mode. The target has found over 40k live domains and it has been running for days now. I wanted to stop it but I get the same message as above.

![github_1](https://user-images.githubusercontent.com/26350416/103893225-3913c400-50ed-11eb-87c9-54970a86f748.png)
![github_2](https://user-images.githubusercontent.com/26350416/103893236-3e710e80-50ed-11eb-8841-bc7bd8286f6b.png)

Any idea how I can stop the scan anyway (for example manually via the console)?
