### ISSUE TITLE
Bug - OneForAll Is not all merging results

### ISSUE THREAD

**Issue by sherlocksecurity** [yogeshojha/rengine#300]
After the final roundup of subdomains, the overall shows exporting results in .csv files in the app directory but no files found there or shown, Logs shows no file found after the process.

Thanks,

**Comment by yogeshojha** [comment]
Yes because once the scan is completed, after the parsing is done, to save up some diskspace, we thought of removing the csv or any other generated files

https://github.com/yogeshojha/rengine/blob/a7a1faa44aad72b616d96e1a5565b65d386c05b6/reNgine/tasks.py#L224
