### ISSUE TITLE
web can not build

### ISSUE THREAD

**Issue by n00B-ToT** [yogeshojha/rengine#301]
root@ubuntu:~/rengine#>> docker-compose up -d --build web
# github.com/projectdiscovery/httpx/cmd/httpx
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/banner.go:19:2: undefined: gologger.Printf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/banner.go:20:2: undefined: gologger.Printf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/banner.go:22:2: undefined: gologger.Labelf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/banner.go:23:2: undefined: gologger.Labelf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/httpx.go:47:3: undefined: gologger.Fatalf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/httpx.go:67:4: undefined: gologger.Fatalf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/httpx.go:83:5: undefined: gologger.Fatalf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/httpx.go:110:4: undefined: gologger.Fatalf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/httpx.go:117:3: undefined: gologger.Fatalf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/httpx.go:301:4: undefined: gologger.Fatalf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.2/cmd/httpx/httpx.go:301:4: too many errors
ERROR: Service 'web' failed to build: The command '/bin/sh -c GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx@v1.0.2' returned a non-zero code: 2

**Comment by puzanov** [comment]
how did u solve the issue? I am facing the same.

**Comment by TerickJojo** [comment]
same

**Comment by n00B-ToT** [comment]
u can modify Dockerfile remove  '-u -v' where line startwith go get 952695313 邮箱：952695313@qq.com 签名由 网易邮箱大师 定制 On 12/23/2020 10:46, TerickJojo wrote: same — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TerickJojo** [comment]
> u can modify Dockerfile remove  '-u -v' where line startwith go get 952695313 邮箱：952695313@qq.com 签名由 网易邮箱大师 定制 On 12/23/2020 10:46, TerickJojo wrote: same — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

搞定了，牛逼牛逼

**Comment by n00B-ToT** [comment]
🐮 952695313 邮箱：952695313@qq.com 签名由 网易邮箱大师 定制 On 12/23/2020 15:09, TerickJojo wrote: u can modify Dockerfile remove  '-u -v' where line startwith go get 952695313 邮箱：952695313@qq.com 签名由 网易邮箱大师 定制 On 12/23/2020 10:46, TerickJojo wrote: same — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 搞定了，牛逼牛逼 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by puzanov** [comment]
https://github.com/yogeshojha/rengine/issues/303
