### ISSUE TITLE
Error on command make build

### ISSUE THREAD

**Issue by sappi13** [yogeshojha/rengine#304]
When I run command `make build` getting the below error.

![Screenshot 2020-12-23 at 12 54 02 PM](https://user-images.githubusercontent.com/7771468/102970799-2f4f6580-451e-11eb-806b-7804204ff92d.png)

**Comment by AlTahish** [comment]
Same with me in kali 2020.4 with the latest updated tools

**Comment by Seif-AW** [comment]
same with me in ubuntu 18.04
