### ISSUE TITLE
make build error 

### ISSUE THREAD

**Issue by uzza1hossain** [yogeshojha/rengine#305]
Step 13/25 : RUN GO111MODULE=on go get -u -v github.com/projectdiscovery/httpx/cmd/httpx
 ---> Running in c6fa5ba4ca9d
[91mgo: downloading github.com/projectdiscovery/httpx v1.0.3
[0m[91mgo: found github.com/projectdiscovery/httpx/cmd/httpx in github.com/projectdiscovery/httpx v1.0.3
[0m[91mgo: downloading github.com/projectdiscovery/gologger v1.0.1
[0m[91mgo: downloading github.com/logrusorgru/aurora v2.0.3+incompatible
[0m[91mgo: downloading github.com/projectdiscovery/fdmax v0.0.2
go: downloading github.com/projectdiscovery/rawhttp v0.0.4
[0m[91mgo: downloading github.com/projectdiscovery/hmap v0.0.1
[0m[91mgo: downloading github.com/projectdiscovery/mapcidr v0.0.4
[0m[91mgo: downloading github.com/projectdiscovery/retryablehttp-go v1.0.1
[0m[91mgo: downloading golang.org/x/net v0.0.0-20201110031124-69a78807bb2b
[0m[91mgo: downloading github.com/projectdiscovery/cdncheck v0.0.1
[0m[91mgo: downloading golang.org/x/text v0.3.4
[0m[91mgo: downloading github.com/projectdiscovery/clistats v0.0.5
[0m[91mgo: downloading github.com/projectdiscovery/fastdialer v0.0.1
[0m[91mgo: downloading github.com/rs/xid v1.2.1
[0m[91mgo: downloading github.com/microcosm-cc/bluemonday v1.0.4
[0m[91mgo: downloading github.com/syndtr/goleveldb v1.0.0
[0m[91mgo: downloading github.com/remeh/sizedwaitgroup v1.0.0
[0m[91mgo: downloading github.com/hbakhtiyor/strsim v0.0.0-20190107154042-4d2bbb273edf
[0m[91mgo: downloading github.com/yl2chen/cidranger v1.0.0
[0m[91mgo: downloading github.com/projectdiscovery/retryabledns v1.0.5
[0m[91mgo: downloading github.com/golang/snappy v0.0.0-20180518054509-2e65f85255db
[0m[91mgo: downloading go.uber.org/atomic v1.7.0
[0m[91mgo: downloading github.com/chris-ramon/douceur v0.2.0
[0m[91mgo: downloading github.com/miekg/dns v1.1.29
[0m[91mgo: downloading github.com/gorilla/css v1.0.0
[0m[91mgo: downloading github.com/aymerick/douceur v0.2.0
[0m[91mgo: downloading golang.org/x/crypto v0.0.0-20201112155050-0c6587e931a9
[0m[91mgo: downloading golang.org/x/sys v0.0.0-20201113233024-12cec1faf1ba
[0m[91mgo: github.com/projectdiscovery/fdmax upgrade => v0.0.3
[0m[91mgo: github.com/golang/snappy upgrade => v0.0.2
[0m[91mgo: golang.org/x/sys upgrade => v0.0.0-20201223074533-0d417f636930
[0m[91mgo: golang.org/x/crypto upgrade => v0.0.0-20201221181555-eec23a3978ad
[0m[91mgo: golang.org/x/text upgrade => v0.3.4
go: github.com/yl2chen/cidranger upgrade => v1.0.2
[0m[91mgo: github.com/projectdiscovery/clistats upgrade => v0.0.7
[0m[91mgo: github.com/projectdiscovery/gologger upgrade => v1.1.2
[0m[91mgo: github.com/projectdiscovery/fastdialer upgrade => v0.0.2
[0m[91mgo: golang.org/x/net upgrade => v0.0.0-20201216054612-986b41b23924
[0m[91mgo: github.com/logrusorgru/aurora upgrade => v2.0.3+incompatible
[0m[91mgo: github.com/miekg/dns upgrade => v1.1.35
[0m[91mgo: downloading github.com/projectdiscovery/fdmax v0.0.3
[0m[91mgo: downloading github.com/projectdiscovery/gologger v1.1.2
[0m[91mgo: downloading github.com/projectdiscovery/fastdialer v0.0.2
[0m[91mgo: downloading github.com/yl2chen/cidranger v1.0.2
[0m[91mgo: downloading golang.org/x/net v0.0.0-20201216054612-986b41b23924
[0m[91mgo: downloading github.com/projectdiscovery/clistats v0.0.7
[0m[91mgo: downloading github.com/golang/snappy v0.0.2
[0m[91mgo: downloading golang.org/x/sys v0.0.0-20201223074533-0d417f636930
[0m[91mgo: downloading github.com/json-iterator/go v1.1.10
[0m[91mgo: downloading github.com/dimchansky/utfbom v1.1.1
[0m[91mgo: downloading github.com/miekg/dns v1.1.35
[0m[91mgo: downloading github.com/modern-go/concurrent v0.0.0-20180228061459-e0a39a4cb421
go: downloading github.com/modern-go/reflect2 v0.0.0-20180701023420-4b7aa43c6742
[0m[91mgo: downloading golang.org/x/crypto v0.0.0-20201221181555-eec23a3978ad
[0m[91mgo: github.com/modern-go/reflect2 upgrade => v1.0.1
[0m[91mgo: github.com/modern-go/concurrent upgrade => v0.0.0-20180306012644-bacd9c7ef1dd
[0m[91mgo: downloading github.com/modern-go/reflect2 v1.0.1
[0m[91mgo: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
[0m[91mgithub.com/projectdiscovery/gologger/levels
[0m[91mgolang.org/x/sys/internal/unsafeheader
[0m[91mgithub.com/projectdiscovery/httpx/common/customheader
[0m[91mgolang.org/x/net/html/atom
[0m[91mgolang.org/x/net/internal/iana
[0m[91mgithub.com/projectdiscovery/httpx/common/slice
[0m[91mgolang.org/x/text/encoding/internal/identifier
[0m[91mgithub.com/syndtr/goleveldb/leveldb/comparer
[0m[91mgithub.com/golang/snappy
[0m[91mgithub.com/dimchansky/utfbom
[0m[91mgithub.com/projectdiscovery/hmap/store/cache
[0m[91mgolang.org/x/text/transform
[0m[91mgolang.org/x/sys/unix
[0m[91mgithub.com/modern-go/concurrent
[0m[91mgithub.com/logrusorgru/aurora
[0m[91mgithub.com/projectdiscovery/gologger/writer
[0m[91mgo.uber.org/atomic
[0m[91mgithub.com/syndtr/goleveldb/leveldb/util
[0m[91mgithub.com/syndtr/goleveldb/leveldb/storage
[0m[91mgithub.com/hbakhtiyor/strsim
[0m[91mgithub.com/syndtr/goleveldb/leveldb/cache
[0m[91mgithub.com/projectdiscovery/clistats
[0m[91mgithub.com/modern-go/reflect2
[0m[91mgithub.com/syndtr/goleveldb/leveldb/filter
[0m[91mgithub.com/aymerick/douceur/css
[0m[91mgithub.com/gorilla/css/scanner
[0m[91mgithub.com/syndtr/goleveldb/leveldb/opt
[0m[91mgithub.com/yl2chen/cidranger/net
[0m[91mgolang.org/x/net/html
[0m[91mgolang.org/x/crypto/ed25519
[0m[91mgithub.com/chris-ramon/douceur/parser
[0m[91mgithub.com/syndtr/goleveldb/leveldb/errors
[0m[91mgolang.org/x/net/bpf
[0m[91mgithub.com/yl2chen/cidranger
[0m[91mgithub.com/projectdiscovery/retryablehttp-go
[0m[91mgithub.com/projectdiscovery/rawhttp/client
[0m[91mgithub.com/syndtr/goleveldb/leveldb/iterator
[0m[91mgithub.com/syndtr/goleveldb/leveldb/journal
[0m[91mgithub.com/projectdiscovery/cdncheck
[0m[91mgithub.com/syndtr/goleveldb/leveldb/memdb
[0m[91mgithub.com/syndtr/goleveldb/leveldb/table
[0m[91mgithub.com/projectdiscovery/httpx/common/httputilz
[0m[91mgithub.com/projectdiscovery/rawhttp/clientpipeline
[0m[91mgithub.com/rs/xid
[0m[91mgolang.org/x/text/unicode/bidi
[0m[91mgolang.org/x/text/unicode/norm
[0m[91mgolang.org/x/net/http2/hpack
[0m[91mgithub.com/projectdiscovery/rawhttp
[0m[91mgithub.com/microcosm-cc/bluemonday
[0m[91mgolang.org/x/text/secure/bidirule
[0m[91mgithub.com/json-iterator/go
[0m[91mgithub.com/syndtr/goleveldb/leveldb
[0m[91mgithub.com/projectdiscovery/fdmax
[0m[91mgolang.org/x/net/internal/socket
[0m[91mgolang.org/x/text/encoding
[0m[91mgithub.com/projectdiscovery/fdmax/autofdmax
[0m[91mgolang.org/x/text/encoding/internal
[0m[91mgolang.org/x/text/encoding/simplifiedchinese
[0m[91mgolang.org/x/text/encoding/traditionalchinese
[0m[91mgithub.com/projectdiscovery/httpx/common/fileutil
[0m[91mgolang.org/x/net/ipv4
[0m[91mgolang.org/x/net/ipv6
[0m[91mgolang.org/x/net/idna
[0m[91mgithub.com/projectdiscovery/httpx/common/iputil
[0m[91mgithub.com/projectdiscovery/httpx/common/stringz
[0m[91mgithub.com/projectdiscovery/mapcidr
[0m[91mgithub.com/remeh/sizedwaitgroup
[0m[91mgolang.org/x/net/http/httpguts
[0m[91mgithub.com/miekg/dns
[0m[91mgolang.org/x/net/http2
[0m[91mgithub.com/projectdiscovery/hmap/store/disk
[0m[91mgithub.com/projectdiscovery/hmap/store/hybrid
[0m[91mgithub.com/projectdiscovery/gologger/formatter
[0m[91mgithub.com/projectdiscovery/gologger
[0m[91mgithub.com/projectdiscovery/retryabledns
[0m[91mgithub.com/projectdiscovery/fastdialer/fastdialer
[0m[91mgithub.com/projectdiscovery/httpx/common/httpx
[0m[91m# github.com/projectdiscovery/httpx/common/httpx
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:41:4: undefined: gologger.Errorf
root/go/pkg/mod/github.com/projectdiscovery/httpx@v1.0.3/common/httpx/http2.go:61:3: undefined: gologger.Errorf
[0m

**Comment by uzza1hossain** [comment]
Help

**Comment by puzanov** [comment]
https://github.com/yogeshojha/rengine/issues/303

**Comment by Seif-AW** [comment]
i have the same error

**Comment by cheetah12-tech** [comment]
same error
