### ISSUE TITLE
Eliminate other files in endpoint discovery

### ISSUE THREAD

**Issue by 0xspade** [yogeshojha/rengine#308]
Hi,

Just wanted to eliminate (if possible) the other file extensions like css, png, eot, woff,woff2, svg, ico, jpg,jpeg, tiff,tiff2, ttf2, ttf, eot2, etc.

**Comment by micha3lb3n** [comment]
Hi @0xspade , you can make use of queries to seperate them.

`content_type!image/png`

will remove all the PNG images. This can be coupled with `&` operator to achieve the desired result!

**Comment by yogeshojha** [comment]
i guess, we can work on this, just like how we exclude subdomains, we can exclude the file extensions. I will keep you updated

**Comment by yogeshojha** [comment]
This is coming 🚀 

https://github.com/yogeshojha/rengine/commit/457a194f4e96eea1fa1a236ab768cf48ce9a766e

**Comment by yogeshojha** [comment]
https://rengine.wiki/usage/scan_engine/#fetch_url
