### ISSUE TITLE
Bug - Multiple Scan Issue

### ISSUE THREAD

**Issue by PrajwalKhante** [yogeshojha/rengine#312]
### Issue Summary

While creating and Initiating multiple scans it doesn't start concurrently and also the Freezes on the first scan itself

I have confirmed that this issue can be reproduced as described on the latest version/pull of reNgine: (yes)

### Technical details

Kali Linux on VPS

**Comment by yogeshojha** [comment]
I can confirm multiple scan works on latest build. Can you please attach some logs atleast when the scan initiates?
