### ISSUE TITLE
Feature - Add Resume and Pause features 

### ISSUE THREAD

**Issue by harshtya9i** [yogeshojha/rengine#314]
We can add Pause and Resume functionality buttons which give better flexibility to the users.

**Comment by yogeshojha** [comment]
Unfortunately, not sure if celery supports this. But any scans, that could not be completed are anyways resumed by celery. So adding pause and resume is currently not in the pipeline.

**Comment by harshtya9i** [comment]
Hi, Yogesh
I have one query also can we implement multiple scan (2-3 scan) at simultaneoulsy on different targets. 
Thanks

**Comment by yogeshojha** [comment]
Yes reNgine already supports this, it depends on your CPU threads though, this is handled by Celery, celery will lool for the free threads and depending on the numbers will run simultaneous scans. You can try on VPS though, to unleash the power of reNgine, install on VPS with atleast 4 CPU. You can run 4 simultaneous scans. 

If you're looking for VPS, use dogitalocean, use this referral link and you get $100 for 3 months and I will also get $25 credit.

https://m.do.co/c/e353502d19fc
