### ISSUE TITLE
Add Instructions for Updating rengine after major updates in the wiki

### ISSUE THREAD

**Issue by r3dC4prica** [yogeshojha/rengine#319]
I keep forgetting how to do this and it would be super nice if this was included in the wiki instructions. After a major update, how do I update my existing installation? 
Do I do this?:

1. Make stop
2. Make Build
3. Make Up

And that will update the engine?

**Comment by yogeshojha** [comment]
Thank you, this has been updated - https://rengine.wiki/pentester/update/

**Comment by rakesh6927** [comment]
https://rengine.wiki/pentester/update/ shows 404 NOT Found
