### ISSUE TITLE
dirsearch - Efficiency vs Stability

### ISSUE THREAD

**Issue by ShayShwartz** [yogeshojha/rengine#321]
### Issue Summary

When get_dirs.sh runs dirsearch module, it requesting pages using IP to make the scanning faster.
Many websites require requests to be by hostname, otherwise, you receive SSL Error.
"SSL Error connecting to server. Try the -b flag to connect by hostname"
In order to make it stable, you should add to get_dirs.sh the flag -b when running dirsearch to request pages by hostname.

### Steps to Reproduce

1. When I'm scanning a domain that requires requests by hostname it returns SSL Error
2. When I add -b flag to dirsearch.py , it works!

I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

tested from provided celery docker - latest version.

**Comment by yogeshojha** [comment]
I had never thought of this. Thanks

**Comment by yogeshojha** [comment]
This has been replaced by ffuf.
