### ISSUE TITLE
Feature - HTTP/Socks proxy support

### ISSUE THREAD

**Issue by ShayShwartz** [yogeshojha/rengine#322]
**Is your feature request related to a problem? Please describe.**
I need to make the pentest via the company https proxy, so I had to use transparent to  HTTP Proxy docker and edit the docker-compose in order to make it happen.

**Describe the solution you'd like**
An option to mention proxy protocol, address and port and make all the plugins to use this proxy.

**Describe alternatives you've considered**
I created a docker with redsocks and added it to the docker-compose setup.
Created a new network with my redsocks docker as the network driver.
Then, all traffic was tunneled to redsocks docker interface and thanks to transparent to HTTP Proxy capabilities it tunneled through the HTTP proxy of the company.

**Comment by yogeshojha** [comment]
Yes, reNgine 1.0 features proxy support!

https://rengine.wiki/usage/proxy/

![proxy](https://user-images.githubusercontent.com/17223002/129470332-355c1421-57be-4f24-a303-811f241cc632.png)
