### ISSUE TITLE
Bug - ERROR: Service 'web' failed to build

### ISSUE THREAD

**Issue by sidjad** [yogeshojha/rengine#327]
Found a bug? Please fill out the sections below. 👍

### Issue Summary
error checking context: 'no permission to read from '/home/lab/rengine/secrets/certs/ca.key''.
ERROR: Service 'web' failed to build

### Steps to Reproduce

1. During installation of rengine { make build } It was showing "
ERROR: Service 'web' failed to build
"

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
yes

### Technical details

Linux lab 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.1 LTS
Release:        20.04
Codename:       focal

**Comment by AhmedOzil10** [comment]
same here
