### ISSUE TITLE
[info] Google’s Safe Browsing blocks this Repo

### ISSUE THREAD

**Issue by 6uhrmittag** [yogeshojha/rengine#328]
Hi!

Sorry if this doesn't belong here - I just want to inform... someone?!

Google's Safe Browsing currently blocks the URL of this repo because:

````
Current status
warning
This site is unsafe
The site https://github.com/yogeshojha/rengine contains harmful content, including pages that:

Install unwanted or malicious software on visitors’ computers
````
Report: https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Fgithub.com%2Fyogeshojha%2Frengine&hl=en

Happened in Brave browser when browsing through Github.
I know, probably a stupid feature anyway - I've just never seen this warning before...

<img width="1103" alt="2021-01-23 19_40_44-Issues · yogeshojha_rengine · GitHub - Firefox Developer Edition" src="https://user-images.githubusercontent.com/5658838/105611098-a09b6600-5db3-11eb-8128-473948720f94.png">
It looks quite dramatic(text in German):
<img width="711" alt="2021-01-23 19_41_21-Sicherheitsfehler - Brave" src="https://user-images.githubusercontent.com/5658838/105611097-9f6a3900-5db3-11eb-9dd4-e88c3e548aa6.png">

**Comment by rohitcoder** [comment]
Now this error is also popping on chromes not only brave...

**Comment by yogeshojha** [comment]
Can you please confirm if this is fixed?

**Comment by yogeshojha** [comment]
Looks like now it's fixed, it was a mistake from Google.

![Screenshot from 2021-02-19 23-54-25](https://user-images.githubusercontent.com/17223002/108545446-cf9eec00-730d-11eb-8099-97eb53a81a56.png)

**Comment by yogeshojha** [comment]
Feel free to self close this issue ❤️
