### ISSUE TITLE
Feature - Vulners to check services having cve's

### ISSUE THREAD

**Issue by thecybermanhunter** [yogeshojha/rengine#330]
**Is your feature request related to a problem? Please describe.**
As we perform port scan , is that possible to check Vulners as well ,similar to [MassVulnScan](https://github.com/choupit0/MassVulScan) ?
Also is that possible to perform scans using ip's as target as we can see elastic ip's and lb ip's are also being used by many organizations.
**Describe the solution you'd like**
So once the port scans gets done we can make use of nmap + vulners.nse to detect services which have cve's .
This will help with Rengine being more helpful as we already have nuclei.

**Comment by psyray** [comment]
Vulners and vulscan already added
You could set it up in the Scan Engine
Look at for details #1004
