### ISSUE TITLE
Feature - Dir bruteforce ignoring custom 404 page which is picked up as 200

### ISSUE THREAD

**Issue by demon1k** [yogeshojha/rengine#334]
Most of the times webapps have custom error page so when dirbruteforce shows result it will show everything as a hit cause of that. but the result/hit all would have same response size for ex: 0.60kb. is there a way to filter that out? Thanks

Kindly check the attached screenshot to see what i mean. Thanks
![rengine-dir-prob](https://user-images.githubusercontent.com/26355801/106393575-b941f680-6419-11eb-82c8-fd6013407fe4.png)

**Comment by demon1k** [comment]
Also if we could pass custom header to include our bugbounty username or a string... while doing dirbruteforce... as this is required by some programs. Otherwise the ip would get banned/blacklisted.

**Comment by yogeshojha** [comment]
This is now filtered, 404, 403 like status are now filtered
