### ISSUE TITLE
[QUESTION] Backup Whole Rengine

### ISSUE THREAD

**Issue by c4nh0t0** [yogeshojha/rengine#335]
Is there a way to backup the whole rEngine system (finished scans, configurations and so on)?
I mean, I need transfer all the rEngine stuff from one machine to other. What's the best way to do it?

Thanks.

**Comment by goodrookie** [comment]
Hey there c4nh0t0, did you find at least an informal way to do this? I need it too! Thanks!

**Comment by yogeshojha** [comment]
I guess, the best way would be to backup your entire postgre database
