### ISSUE TITLE
cant import .csv list target

### ISSUE THREAD

**Issue by kcnewb1e** [yogeshojha/rengine#338]
### Issue Summary

i cant import list domain target.

### Steps to Reproduce

1. When i am import list with .csv file, gotten error invalid type

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
* yes

### Technical details

im import file .csv : 
```
arkoselabs.com,bounty
arlo.com,bounty
```

and i uploaded and import in reengine, error shown "Invalid Type"...
i dnt know what happen, i check the log, but it's not written in logs..

**Comment by ansidorov** [comment]
Hello.

Could you please tell me what version of reNgine you are using, what file name are you importing?
I have not been able to reproduce the problem.

**Comment by kcnewb1e** [comment]
Lastest version sir..

**Comment by kcnewb1e** [comment]
![image](https://user-images.githubusercontent.com/53884802/108651068-96c06c00-74f3-11eb-82d5-0f3b6e055fd7.png)

i using .csv import, and after i upload, i got error and redirected to form upload .txt

**Comment by 2502151499** [comment]
UnsucrableOn Feb. 19, 2021 11:11, kcnewb1e <notifications@github.com> wrote:
Lastest version sir..

**Comment by mido1677** [comment]
i have same issue, is there are any fix?

**Comment by yogeshojha** [comment]
Hi, this has been fixed. There was a content type issue on Windows. Please pull the latest changes.
