### ISSUE TITLE
502 Bad Gateway when listing targets (can't scan!!)

### ISSUE THREAD

**Issue by goodrookie** [yogeshojha/rengine#345]
Every other funtionality seems working fine, but when I list targets (in order to scan an old target o to scan a newly added target) I get this error: **502 Bad Gateway - nginx/1.19.6**

**_Fragment of make logs:_**
web_1          | [2021-02-20 02:35:38 +0000] [1] [CRITICAL] WORKER TIMEOUT (pid:48)
web_1          | [2021-02-20 02:35:38 +0000] [48] [INFO] Worker exiting (pid: 48)
proxy_1        | 2021/02/20 02:35:38 [error] 24#24: *418 upstream prematurely closed connection while reading response header from upstream, client: XXX.XXX.XXX.XXX, server: rengine, request: "GET /target/list/ HTTP/2.0", upstream: "http://XXX.XXX.XXX.XXX:8000/target/list/", host: "XXX.XXX.XXX.XXX", referrer: "https://XXX.XXX.XXX.XXX/start_scan/history/"
proxy_1        | XXX.XXX.XXX.XXX - - [20/Feb/2021:02:35:38 +0000] "GET /target/list/ HTTP/2.0" 502 559 "https://XXX.XXX.XXX.XXX/start_scan/history/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36" "-"
web_1          | [2021-02-20 02:35:39 +0000] [49] [INFO] Booting worker with pid: 49

**_I've tried:_**
- make stop, make up.
- make stop, make restart.
- Cloning git again and installing as the 1st time.
**_Results_**: keeps giving this error and I can't scan any more!! :(

**Comment by goodrookie** [comment]
I guess the problems comes after I imported by mistake a large number of **targets, approximately 30000**, and I think that the list targets web page can't handle that. From time to time, I refresh the page and by surprise it appears and let me delete 50 targets at most and then I enter a new cycle of 502 errors. I've been playing with **nginx config file**, modifying its parameters and values with no success. I'm open to suggestions specific for this situation with reNgine or if someone has knowledge about how to fix this with the right nginx parameters/values. Or maybe if someone knows how to **delete targets directly from reNgine database** (maintaining integrity, of course). Thanks!

**Comment by 0xcrypto** [comment]
Same happened to me. Had to remove all those domains from within the database.
