### ISSUE TITLE
Feature - Ability to kill a task, or, delete a specific task's results

### ISSUE THREAD

**Issue by payloadartist** [yogeshojha/rengine#349]
**Is your feature request related to a problem? Please describe.**
Sometimes ```dirsearch``` and ```endpoint``` extraction doesn't work as expected, and that leads to a lot of useless data being collected.

An example: dirsearch logs endpoints with ```200 status``` but sometimes backends respond with custom error page skipping out the status code (404). In such cases, dirsearch returns too many false positives.

**Describe the solution you'd like**
 - Kill the ```dirsearch``` or  gau/hakrawler task
 - Also be able to delete unwanted results

**Describe alternatives you've considered**
stopping the scan midway
killing the celery task in the docker container manually (?)

**Additional context**
Sometimes, dirsearch took too long, I tried checking out the logs ```make logs``` to find that dirsearch is logging all paths even though they are error pages, which results in too many false positives.

I couldn't find a way to kill the celery task from the docker container, and hence this feature request

**Comment by yogeshojha** [comment]
Sorry forgot to close this, this has been since 1.0. You have an option to delete scan data.
