### ISSUE TITLE
Stored XSS at Notification Section 

### ISSUE THREAD

**Issue by omemishra** [yogeshojha/rengine#354]
Hello Yogesh,

How are you i have again found a xss 

#Your Slack channel

Now save it and click on delete [

https://0.0.0.0/notification/#

**Comment by omemishra** [comment]
![stored-xss-notification](https://user-images.githubusercontent.com/25466820/109051067-220e4d00-7700-11eb-89cb-1481aae1af75.png)

payload 
"><><><><img src=x onmouseover=alert(1)>

**Comment by omemishra** [comment]
`"><><><><img src=x onmouseover=alert(1)>`

**Comment by omemishra** [comment]
`https://0.0.0.0/scanEngine/wordlist/#`


same here also

**Comment by yogeshojha** [comment]
Oops, Thank you for reporting.
Nice finding.

Whenever you're free can you please check all the instances of XSS and report it to the same issue? I will try to close all of them.

**Comment by omemishra** [comment]
Hello Bro,

sure i will and let you know.

Take care bro
