### ISSUE TITLE
Failing Scan - rEngine Failing Finishing Scan

### ISSUE THREAD

**Issue by c4nh0t0** [yogeshojha/rengine#357]
### Issue Summary

I was running rEngine normally, yesterday after git pulling new version of rEngine the scans fails every time. Don't know how to give more technical details because I just git pull a previous version already running in  my VPS and then crashed all the scans that I've made.

### Steps to Reproduce

1. git pull
2. make build
3. make up
4. run a test scan and check that it fails

![image](https://user-images.githubusercontent.com/8462973/109416792-142a2780-799f-11eb-85a5-31f9b9b3b34a.png)

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes)

### Technical details

Running in an Ubuntu 18.04.5 with kernel in 4.15.0-134-generic.

**Comment by yogeshojha** [comment]
Can you please attach the logs

**Comment by ad0nis** [comment]
I was able to reproduce this. I also had a previously-running rengine instance, did the same steps, and ended up with naabu port scans that had been running for over 17 hours, and appearing to be hung up.

**Comment by c4nh0t0** [comment]
Problem solved after git pull latest updates.
