### ISSUE TITLE
Naabu holding CPU at 100% - scans never complete

### ISSUE THREAD

**Issue by ad0nis** [yogeshojha/rengine#361]
### Issue Summary

When launching a scan against a list of domains, naabu hangs the CPU up and never completes.

### Steps to Reproduce

1. Import list of domains
2. select them all and launch Full Scan
3. Wait, and observe that it never passes port scan step.
4. Screenshots are said to be complete, but never show up either.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

ubuntu 20.04 VM with 4c/8gb

**Comment by foozzi** [comment]
same problem

**Comment by yogeshojha** [comment]
Fixed
