### ISSUE TITLE
import only one domain from the txt list + can't upload csv list "Invalid File type!"

### ISSUE THREAD

**Issue by Mebrahem1** [yogeshojha/rengine#362]
### Issue Summary

When try to import txt list of subdomains or domains only one domain uploaded!

#####test.txt

```
hackerone.com
docs.hackerone.com
nepal.gov.np
```

also when i try to import csv list i see this error `Invalid File type!`

#####test.csv

```
hackerone.com
docs.hackerone.com, Hackerone Docs
nepal.gov.np, Nepal Government Bug Bounty
```

i tried the examples from your wiki and it's not working!

### Steps to Reproduce

1. Go to https://yourserver/target/import/
2. upload your txt list you will see alert that told you only one target added, then go to https://yourserver/target/list/ you will find only one domain or subdomain added!
3. for csv Go to https://yourserver/target/import/ click on ` .csv import` upload your csv file you will see error says `Invalid File type!`

Thanks.

**Comment by moshealon76** [comment]
Same issue

**Comment by yogeshojha** [comment]
Can you please attach the logs, make logs? Because I am not able to replicate this. I just imported using csv and works

**Comment by ad0nis** [comment]
For me, txt uploads work just fine, but CSV uploads give the same error.

**Comment by mido1677** [comment]
Hi @yogeshojha ,

Thanks for your reply,


for txt:

![Screenshot 2021-03-09 003209](https://user-images.githubusercontent.com/20936471/110390729-18290a00-806f-11eb-9b44-b7c976462b16.png)


for csv:

![Screenshot 2021-03-09 003258](https://user-images.githubusercontent.com/20936471/110390764-2414cc00-806f-11eb-9d3f-db3eccfb6629.png)


Thanks.

**Comment by mido1677** [comment]
@yogeshojha 

??

**Comment by mido1677** [comment]
for txt file i found the problem it's `\r` should the file not have this in the lines!
But for CSV still can't import it and i see `Invalid File type!` every time!

Thanks.

**Comment by lootfinder** [comment]
> for txt file i found the problem it's `\r` should the file not have this in the lines!
> But for CSV still can't import it and i see `Invalid File type!` every time!
> 
> Thanks.

I have only spent a second skimming this issue but I can assure you that the comma in the (KHTML, Like Gecko) will cause issues if it isn't being escaped in the code. Can you try removing that user-agent and trying again?

**Comment by yogeshojha** [comment]
Hi, this has been fixed. There was a content type issue on Windows. Please pull the latest changes.
