### ISSUE TITLE
make certs error during complet install 

### ISSUE THREAD

**Issue by ringawy** [yogeshojha/rengine#365]
WARNING: Native build is an experimental feature and could change at any time
Building certs
Sending build context to Docker daemon  4.608kB

Step 1/6 : FROM alpine:latest
 ---> 28f6e2705743
Step 2/6 : RUN apk update &&     apk add --no-cache openssl &&     rm -rf /var/cache/apk/*
 ---> Running in f0506ed97550
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.13/community/x86_64/APKINDEX.tar.gz
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/main: temporary error (try again later)
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/main: No such file or directory         
ERROR: https://dl-cdn.alpinelinux.org/alpine/v3.13/community: temporary error (try again later)       
WARNING: Ignoring https://dl-cdn.alpinelinux.org/alpine/v3.13/community: No such file or directory    
2 errors; 14 distinct packages available                                                              
The command '/bin/sh -c apk update &&     apk add --no-cache openssl &&     rm -rf /var/cache/apk/*' returned a non-zero code: 2
ERROR: Service 'certs' failed to build
make: *** [Makefile:16: certs] Error 1

**Comment by crmassociates** [comment]
sudo make certs

**Comment by ringawy** [comment]
same error with sudo

**Comment by lootfinder** [comment]
> same error with sudo

Ok. I had the error as well earlier. I believe it's a DNS issue.

Can you try editing:  `/etc/docker/daemon.json` and using Googles public DNS?

```
{
  "dns": ["8.8.8.8"]
}
```

Then afterwards: `sudo service docker restart`
