### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by cybertricks** [yogeshojha/rengine#369]
=> ERROR [stage-0  6/19] RUN GO111MODULE=on go get -v github.com/project  7.7s
------
 > [stage-0  6/19] RUN GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder:
#10 0.785 go: downloading github.com/projectdiscovery/subfinder v0.1.1
#10 1.742 go: downloading github.com/projectdiscovery/subfinder v2.4.6+incompatible
#10 7.683 go get github.com/projectdiscovery/subfinder/v2/cmd/subfinder: module github.com/projectdiscovery/subfinder@upgrade found (v2.4.6+incompatible), but does not contain package github.com/projectdiscovery/subfinder/v2/cmd/subfinder
------
ERROR: Service 'web' failed to build

**Comment by cybertricks** [comment]
all the git urls are showing 404

RUN go get -u github.com/tomnomnom/assetfinder github.com/hakluke/hakrawler

RUN GO111MODULE=on go get -v github.com/projectdiscovery/httpx/cmd/httpx

RUN GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/tree/master/v2/cmd/subfinder
RUN GO111MODULE=on go get -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei
RUN GO111MODULE=on go get -v github.com/lc/gau
RUN GO111MODULE=on go get -v github.com/projectdiscovery/naabu/v2/cmd/naabu

**Comment by smaranchand** [comment]
Hi @cybertricks  Just encountered the same issue, For now subfinder build error can be fixed by replacing the below lines in Dockerfile as mentioned in subfinder repo. https://github.com/projectdiscovery/subfinder/issues/405
```
RUN GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@221eee8e0891c1bdae1228eb7068aa7b033d8483
```
Regards,
Smaran

**Comment by cybertricks** [comment]
Thank you
