### ISSUE TITLE
Can't see vulnerability scan results.

### ISSUE THREAD

**Issue by MelonMusk4** [yogeshojha/rengine#371]
Hello :)

While running a scan on a target, that uses the vulnerability scanner (Full scan, custom scan, vulnerability scan - obviously)

unfortunately, I see no results on the dashboard even though I know the target is vulnerable (also checked on logs and the target is vulnerable + no errors as well!!).

I am not sure why it happened, I cloned rengine AGAIN from GitHub and it's still not showing me the results :(

Attached a few pics as well.

![Screen Shot 2021-03-25 at 15 49 46](https://user-images.githubusercontent.com/81370965/112485813-fd030d80-8d83-11eb-9ee6-dba251560b6e.png)

![Screen Shot 2021-03-25 at 16 12 18](https://user-images.githubusercontent.com/81370965/112486832-e9a47200-8d84-11eb-9bf2-85e6dcdb915e.png)

![Screen Shot 2021-03-25 at 16 10 18](https://user-images.githubusercontent.com/81370965/112486642-be218780-8d84-11eb-9a9f-7561194d12bb.png)

**Comment by yogeshojha** [comment]
Can you please attach the complete log? Looks like exception has occured

**Comment by MelonMusk4** [comment]
Of course.

I just did a new scan with another target for demo purposes.

2 files are attached -

1). rengine_start_vuln_scan.log - all the logs from starting the scan.

2). restart_rengine.log - all the logs from just restarting rengine.

[restart_rengine.log](https://github.com/yogeshojha/rengine/files/6205587/restart_rengine.log)

[rengine_start_vuln_scan.log](https://github.com/yogeshojha/rengine/files/6205586/rengine_start_vuln_scan.log)

**Comment by MelonMusk4** [comment]
Any updates?

**Comment by TheSerialiZator** [comment]
@yogeshojha

**Comment by YuraveON** [comment]
i'm having this issue too.

i just reinstall my vps several days ago, and now cant see any vulnerabilities. before reinstall everything went perfectly fine.

**Comment by smaranchand** [comment]
Hi @yogeshojha ,  Hope you are having a great time, Just encountered the same issue. Tried looking for the root cause but no luck. The vulnerability scan is working for sure but the results are not getting populated to the database. 

![Screen Shot 2021-04-01 at 7 24 44 AM](https://user-images.githubusercontent.com/36672015/113231651-6ff81100-92bb-11eb-94a5-c1c1dc132bf4.png)
Regards,
Smaran

**Comment by DhiyaneshGeek** [comment]
@yogeshojha i'm also facing the same issue

![image](https://user-images.githubusercontent.com/24750220/113468830-51824900-9466-11eb-9050-edc9a46caa9a.png)

**Comment by chestervdb** [comment]
I am encountering the same issue as well. Have deployed rEngine following the steps
on wiki, but no success yet. 
![0AC87CD7-C6A4-4D13-B363-2144E1CE7B69](https://user-images.githubusercontent.com/12883493/113556396-b374b700-95fc-11eb-93b1-82916c0f2aa6.jpeg)

**Comment by TheSerialiZator** [comment]
There might be issues with docker.pkg.github.com/yogeshojha/rengine/rengine:latest ?

**Comment by OnePlus-Sec** [comment]
I faced same issue

**Comment by chestervdb** [comment]
yogeshojha?

**Comment by TheSerialiZator** [comment]
Did anyone fix it?

**Comment by chestervdb** [comment]
Don't think so. I couldn't discover the issue myself and the last change was 18 days ago.

**Comment by anggipradana** [comment]
Any update?

**Comment by yogeshojha** [comment]
Thank you for your patience. I was away due to my health issues, apologies for the long due. I have just fixed this.

**Comment by yogeshojha** [comment]
Let me know if you still experience this.

**Comment by chestervdb** [comment]
Hope you are doing well now @yogeshojha! #371 is still present. I've redeployed the git on a fresh digitalocean docker droplet, but after scanning around 1000 subs, still 0 vulnerabilities were discovered.

**Comment by yogeshojha** [comment]
You are right. Thank you for bringing this to my attention. Nuclei JSON output had changed, which caused this issue. Fixed it just now again. Please do a git pull. 
![image](https://user-images.githubusercontent.com/17223002/116004209-4e224d80-a61f-11eb-9c49-a1198b7f4b1b.png)

**Comment by DhiyaneshGeek** [comment]
@yogeshojha Thanks a lot for Fixing the issue :)

**Comment by yogeshojha** [comment]
Cheers mate 🚀 stay tuned for reNgine another major release with Scan Comparision, ability to discover interesting subdomains and endpoints, gf xss, ssrf,....etc. Can't wait to release. 🚀
Stay tuned and enjoy reNgine.

**Comment by chestervdb** [comment]
It is working now, thanks a lot @yogeshojha! Looking forward to the new major release! Any ETA you can disclose?

**Comment by yogeshojha** [comment]
There are a lot of major changes and I am working super hard on it. You can expect it to be released by mid of June. But if things go well, it may well before June mid also.
