### ISSUE TITLE
Feature - Screenshot Gallery

### ISSUE THREAD

**Issue by uBadRequest** [yogeshojha/rengine#374]
This feature would give you the ability to screen all the screenshots that have been taken, looking for interesting sites.

The feature would add an option to the sidebar, which would display a gallery of all the screenshots that have been taken. Text could overlay the image with some info, like if technology on that site was detected... PHP, Apache. With the ability to filter specific target groups or "descriptions", or maybe even technologies that have been detected across all scans. For example, say you want to see screenshots from all the sites that have been detected with PHP or nginx.

**Comment by hims1911** [comment]
I want to work this issue.

**Comment by yogeshojha** [comment]
I can confirm that this is done 🚀 
![image](https://user-images.githubusercontent.com/17223002/119537501-b9d71200-bda7-11eb-90fc-81caf9191c1e.png)

**Comment by yogeshojha** [comment]
Added filtering as well
![image](https://user-images.githubusercontent.com/17223002/119769584-5567a000-bed8-11eb-9763-c700369b72c2.png)

**Comment by Regala** [comment]
Looks great can we have it pushed? 🤩

**Comment by yogeshojha** [comment]
Pushed guys <3

**Comment by Regala** [comment]
🔥🔥🔥🔥🔥
