### ISSUE TITLE
Feature - Run New Nuclei Template on all alive target 

### ISSUE THREAD

**Issue by DhiyaneshGeek** [yogeshojha/rengine#379]
Hi There

Can we have a feature to scan only newly released nuclei template on all the alive targets

**Comment by DhiyaneshGeek** [comment]
@yogeshojha is it possible to have a feature to run custom or private templates ?

**Comment by yogeshojha** [comment]
This would be a nice add-on! I will consider this for the upcoming major release.

**Comment by yogeshojha** [comment]
Both are now in reNgine 1.0! 
![tool](https://user-images.githubusercontent.com/17223002/129470214-e09215cd-1b24-4aa9-9a77-ad355be89321.gif)
