### ISSUE TITLE
Scanner breaks when trying to fetch urls

### ISSUE THREAD

**Issue by demon1k** [yogeshojha/rengine#382]
### Issue Summary

I scanned 4 diff targets and scanner breaks when trying to fetch urls... so it ends at dirsearch. no endpoints and no vuln scan.

### Steps to Reproduce

1. install fresh rengine on debian 10
2. follow ^ the installation manual
2. do a Full scan on a target
3. it will break while trying to fetch urls/endpoinnts

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
yes

### Technical details

part of log from "make logs".
celery_1       |
celery_1       | [2021-04-11 12:26:56,055: ERROR/ForkPoolWorker-1] 'title'
celery_1       | [2021-04-11 12:26:56,057: ERROR/ForkPoolWorker-1] https://xyz.target.com
celery_1       | [2021-04-11 12:26:56,057: ERROR/ForkPoolWorker-1] xyz.target.com
celery_1       |
celery_1       | [2021-04-11 12:26:56,058: ERROR/ForkPoolWorker-1] 'title'
celery_1       | [2021-04-11 12:26:56,059: ERROR/ForkPoolWorker-1] https://xyz.target.com
celery_1       | [2021-04-11 12:26:56,060: ERROR/ForkPoolWorker-1] xyz.target.com
celery_1       |
celery_1       | [2021-04-11 12:26:56,060: ERROR/ForkPoolWorker-1] 'title'
celery_1       | [2021-04-11 12:26:56,062: ERROR/ForkPoolWorker-1] https://xyz.target.com
celery_1       | [2021-04-11 12:26:56,062: ERROR/ForkPoolWorker-1] xyz.target.com
celery_1       |
celery_1       | [2021-04-11 12:26:56,063: ERROR/ForkPoolWorker-1] 'title'
celery_1       | [2021-04-11 12:26:56,064: ERROR/ForkPoolWorker-1] https://xyz.target.com
celery_1       | [2021-04-11 12:26:56,065: ERROR/ForkPoolWorker-1] xyz.target.com
celery_1       |
celery_1       | [2021-04-11 12:26:56,065: ERROR/ForkPoolWorker-1] 'title'
celery_1       | [2021-04-11 12:26:56,310: ERROR/ForkPoolWorker-1] 'fetch_url'
celery_1       | [2021-04-11 12:26:56,337: INFO/ForkPoolWorker-1] Task reNgine.tasks.doScan[f153b985-79ec-41cc-b2e9-f7a8a0a57fd5] succeeded in 335.98428217599576s: {'status': True}

**Comment by demon1k** [comment]
root@genji:~/Fun/rengine# make username
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python manage.py createsuperuser

You have 18 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): startScan, targetApp.
Run 'python manage.py migrate' to apply them.
Username (leave blank to use 'root'):
Email address:
Password:
Password (again):
The password is too similar to the username.
This password is too short. It must contain at least 8 characters.
Bypass password validation and create user anyway? [y/N]: y
Superuser created successfully.
root@genji:~/Fun/rengine# python manage.py migrate
  File "manage.py", line 16
    ) from exc
         ^
SyntaxError: invalid syntax
root@genji:~/Fun/rengine# python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in main
    from django.core.management import execute_from_command_line
ModuleNotFoundError: No module named 'django'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 16, in main
    ) from exc
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?
root@genji:~/Fun/rengine#

**Comment by lur1el** [comment]
Same problem here :(

**Comment by demon1k** [comment]
@yogeshojha could you please look into this when you are free?

**Comment by lur1el** [comment]
@yogeshojha Same problem here!! It looks like the application is having problems with the "Fetch Urls" process... it always returns Failed :(

**Comment by demon1k** [comment]
> @yogeshojha Same problem here!! It looks like the application is having problems with the "Fetch Urls" process... it always returns Failed :(

which os are you running it on?

**Comment by lur1el** [comment]
@demon1k Ubuntu.I tested it on Debian and the problem happens too. :(

**Comment by AlexisGrgs** [comment]
Same here on my VM which worked well two weeks agon, same issue on new kali linux freshly installed and updated

**Comment by yogeshojha** [comment]
Oops, sorry about it guys. I was away due to my health issues. Please be assured, I am working on it. I Will investigate the cause, in the meantime can you attach the scan engine YAML?

**Comment by demon1k** [comment]
@AlexisGrgs and @lur1el  could you guys attach the Scan Engine YAML for @yogeshojha . because i killed my vps after i ran into this issue. @yogeshojha i ran it with default settings when this error showed up. Hope that helps.

**Comment by yogeshojha** [comment]
Fixed. This was due to a JSON object not existing.
