### ISSUE TITLE
Bug - Scan failed

### ISSUE THREAD

**Issue by AlexisGrgs** [yogeshojha/rengine#384]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

I tried this morning to run some discovery scans (subdomain + URL) but all scan failed, it worked perfectly two weeks ago. 
I updated rengine, same problem. I reinstalled a vm kali to start from scratch and still the same problem on a brand new and updated kali and updated rengine, I don't understand what's going on.

The subdomains seem to be found but no URL is found and the scan displays an error

### Steps to Reproduce

1. When I am scanning the domains, this happens

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)

yes

### Technical details

Kali linux

**Comment by anggipradana** [comment]
Yes, I have the same problem, but the display is different. Vulnerability scanner finished but no results. I have tried doing a manual scan and there are some results, but no results in the rengine.

**Comment by yogeshojha** [comment]
Oops, sorry about it guys. I was away due to my health issues. Please be assured, I am working on it. Will investigate the cause, in the mean time can you attach the scan engine yaml?

**Comment by anggipradana** [comment]
Get well soon Mr @yogeshojha , Thank you for your response. We really appreciate you. 🙏

**Comment by anggipradana** [comment]
I think this is same issue with #371 issue, so that you can check logs and scan engine yaml on previous issue

**Comment by Naina1723** [comment]
i have upgraded to 2.1.0, im facing when i start for scanning after sometime it gets failed.
![image](https://github.com/yogeshojha/rengine/assets/137153679/c980c2fd-1a70-47a6-96ce-e228fa8bb4ac)
