### ISSUE TITLE
Axiom integration - Lets go FAST!

### ISSUE THREAD

**Issue by uBadRequest** [yogeshojha/rengine#385]
**Is your feature request related to a problem? Please describe.**
Scanning from one machine is so boring and slow. Lets get distributed and go fast.

**Describe the solution you'd like**

If user enabled use of Axiom in the scan engine, all scans using that engine are distributed among the axiom hosts. 

Also, I wouldn't want a large fleet of hosts created by axiom running with nothing to do for a long time so checking for whether or not there is anything in the queue, or if something is taking way too long to kill it.

https://github.com/pry0cc/axiom

**Describe alternatives you've considered**
Using axiom manually

**Additional context**
This will increase the speed in which people are able to scan, also reduce the effect of being rate-limited/blocked. You could also advertise your referral links for the cloud hosting providers supported by Axiom! :+1:

It's pretty easy to manually add modules to Axiom too!

**Comment by uBadRequest** [comment]
What do you think @yogeshojha?

**Comment by log4works** [comment]
Agree.. [https://github.com/pry0cc/axiom](https://github.com/pry0cc/axiom) rengine+axiom will be awesome

**Comment by anggipradana** [comment]
Agree, this will be faster and solve IP blocking problem @yogeshojha

**Comment by yogeshojha** [comment]
Sounds awesome, give me sometime to think about it as I have never used axiom in the past. Need to see how we can use axiom in reNgine. If you have any ideas, please feel free to give.

**Comment by uBadRequest** [comment]
> Sounds awesome, give me sometime to think about it as I have never used axiom in the past. Need to see how we can use axiom in reNgine. If you have any ideas, please feel free to give.

All the tools ReNgine uses, could be ran distributed across your botnet(linode/digital ocean).You can run ffuf across a fleet of hosts, it would split your dictionary up by the number of hosts you have in your botnet, each one gets a piece of the dictionary.

Or you run Nuclei across 500 subdomains, axiom splits those subdomains up by the number of hosts in your botnet, each host gets their piece to run Nuclei against.

It would also be awesome to have Target Groups, so that all the domains in scope, can be grouped together.

**Comment by uBadRequest** [comment]
I hope so haha!

**Comment by eschultze** [comment]
This would allow rengine to insanely scale up the scans! Also, as axiom machines would be doing all the hard work, rengine would possibly run smoothly while performing like 20 concurrent scans and would only need to store the results back in the local database.

**Comment by uBadRequest** [comment]
Hey @yogeshojha , Here's a video of the developer showing it off at NahamCon 2021. I think he does a good job explaining how it works. [NahamCon 2021 - Introduction to Axiom - The Dynamic Infrastructure Framework for Everybody!](https://www.youtube.com/watch?v=t-FCvQK2Y88&t=848s) 

Another option, although I haven't used it yet, is https://github.com/FleexSecurity/fleex

One thing that anyone who wants to use this will have to do, is create a ticket with the cloud provider requesting the ability to create bigger image sizes. Axiom will ask if you want it to create the ticket for you. I think I had to wait a day for that to happen, but you won't be able to use Axiom until that happens, unless you remove stuff from the image so it meets their default image size limit of like 6Gb. 

They also have limits to the number of droplets/linodes you can deploy, so we should have the ability to configure how many we want Rengine to attempt to deploy, because you can request an increase, which I was able to get to like 50 with Linode. All accounts start off with the ability to only create 20 concurrent active linodes, and 10 for Digital Ocean. 

I'm on discord if you want to chat👋
BadRequests#2053

**Comment by yogeshojha** [comment]
Perfect, I'll add you on Discord, in the meantime I will watch the talk and will get back to you if I have any questions.

**Comment by eschultze** [comment]
@yogeshojha were you able to take a look at the videos? Let me know if you want to schedule a meeting so I can do a small demonstration

**Comment by tpirneci** [comment]
Is this idea still alive?

**Comment by kobs0N** [comment]
Hi @yogeshojha 
Let's talk, I know how to do it. 🥇

**Comment by AmeerAssadi** [comment]
Is this idea still alive?

**Comment by Messerschmidts-Reave** [comment]
Shadowclone could be alternative if axiom too hard to integrate https://github.com/fyoorer/ShadowClone this was faster than axiom and its more flexible too.

**Comment by ktecv2000** [comment]
Is this idea still alive?

**Comment by psyray** [comment]
@yogeshojha 
It could be an awesome improvement.
As said @Messerschmidts-Reave Shadowclone seems more easy to implement

**Comment by psyray** [comment]
We will try to implement ShadowClone when we have time
I'm closing this issue, continue discussion on #961
