### ISSUE TITLE
Bug - Endpoint Scan 

### ISSUE THREAD

**Issue by moshealon76** [yogeshojha/rengine#396]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

A summary of the issue.
 
I scanned some domains. And in all the scans the engine tries to scan the whole site endpoints(ecommerce site) and downloads every file (png,jpg, jss, html) that exists on the site. Also the scan takes a long time (over 14 hours) (in the previous version this did not happen)

### Steps to Reproduce

1. When I am scanning the domains, this happens
2. ...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
yes 

### Technical details

Please list out any technical 
![Rengine](https://user-images.githubusercontent.com/26068105/117150345-ba8c1200-adc0-11eb-9cf3-38446e8e4780.PNG)
details such as operating environment.

**Comment by yogeshojha** [comment]
Did you try cloning the release/1.0 branch? because this UI is currently being developed and is not at all stable. Can you please try cloning the master branch?
