### ISSUE TITLE
Vulnerability Scan Failed 

### ISSUE THREAD

**Issue by d1pakda5** [yogeshojha/rengine#397]
Hi i tried multiple time to scan for vulnerability , one target having 6k+ subdomain but not showing any vulnerability

**Comment by d1pakda5** [comment]
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/17035598/117180004-5afa2a80-adf1-11eb-8823-dc8c02e8d3bc.png">

**Comment by c4nh0t0** [comment]
Yeah I'm also having the same issue after gitting clone new versions of this repo. Same target (that has vulns) now didn't show any vulnerability. Not even information is showing.

Scanned at May 7, 2021, 11:38 p.m.
![image](https://user-images.githubusercontent.com/8462973/117572622-1947d900-b0aa-11eb-8ad0-72c51ed38fa4.png)

Scanned at Jan. 3, 2021, 2:21 a.m.
![image](https://user-images.githubusercontent.com/8462973/117572667-40060f80-b0aa-11eb-95d8-fca5810b61fa.png)

**Comment by c4nh0t0** [comment]
I've cloned the release/major-1.0 and installed from the ground. Still having same issues with Vulnerability module.

**Comment by yogeshojha** [comment]
Please do not clone release/major-1.0, the work is currently in progress and is not at all stable. It will be released only on the week of June 23.

**Comment by T-Virus-443** [comment]
Óla eu também fiz analise de vulnerabilidade em um site de teste http://testphp.vulnweb.com/, 
o reNgine não me trouxe as vulnerabilidades 

![reNgineReporte](https://user-images.githubusercontent.com/33964602/118505946-44ae7180-b703-11eb-84c7-d6245579b3fd.png)



Hi, I also did a vulnerability analysis on a test site http://testphp.vulnweb.com/,
reNgine didn’t bring me the vulnerabilities

**Comment by d1pakda5** [comment]
@yogeshojha Kindly look into it

**Comment by yogeshojha** [comment]
Should be fixed now in 1.0/
