### ISSUE TITLE
[Feature Request] Queue system option for scans

### ISSUE THREAD

**Issue by gprime31** [yogeshojha/rengine#398]
Queue system option for scans so they run one after the other, and not all at once.
The scheduler is great but it's hard to time the scans, sometimes they take longer and overlap and 20 are running at once.
Thanks

**Comment by yogeshojha** [comment]
Currently scans runs on celery queues right? Correct me if I am wrong, suppose there are 5 domains to scan, you initiate all of them, suppose you have 4 core available, this will run 4 scans and 5th is in pending state. When one of the scans is finished, the remaining scans runs. 

Is this what you mean?

**Comment by gprime31** [comment]
Yes, but have the option to just have one run, then queue the rest.

**Comment by k11h-de** [comment]
First: thanks @yogeshojha for all the hard work and effort you put in this project.

I have to admit, I would love to see an improvement in the queue management also. 
An option to define the max. number of concurrent scans would be perfect.

**Comment by AnonymousWP** [comment]
We're considering using another tasking system, but it'll take time to implement.
