### ISSUE TITLE
Duplicated work? Speed improvement?

### ISSUE THREAD

**Issue by uBadRequest** [yogeshojha/rengine#399]
If you don't set it to aggressive, it looks like this happening twice? 

https://github.com/yogeshojha/rengine/blob/b0bf3480bf0b463156d37ff866d49fe34265d23e/reNgine/tasks.py#L565-L570

https://github.com/yogeshojha/rengine/blob/b0bf3480bf0b463156d37ff866d49fe34265d23e/reNgine/tasks.py#L604-L606

And for aggressive, why can't we just pipe the list of subdomains to the tools in get_urls? I would think that would be alot faster then looping through each one.

I tried scanning the main domain for the company I work at, and it was going on for days. We have 1500 subdomains, but most of them redirect back to the homepage.

Do you have a discord man?

**Comment by yogeshojha** [comment]
You're right @uBadRequest, but this is going to be fixed in the release 1.0. Can you please verify in the branch release/major-1.0 and self close - if this no longer is relevant.

Thank you

**Comment by uBadRequest** [comment]
Looks good to me!
