### ISSUE TITLE
IP Rotation/Proxychain Support and Nessus API Integration

### ISSUE THREAD

**Issue by DhiyaneshGeek** [yogeshojha/rengine#401]
**Is your feature request related to a problem? Please describe.**

**IP Blocking/Banned:**
i have installed rengine on VPS and My Ip address is getting blocked during scans. some of the targets are US based which are not accessible from Indian region VPS. likewise for other region as well . 

**Nessus Integration**
i have a set of IP address of a target , where i want to run nessus scan, if it is possible to do it via Rengine , it would be best to have all at one place 

**Describe the solution you'd like**

1. If there is a Tab for Adding Socks5 Proxy that would help me in rotating the IP Address and running the scan smooth
2.  if there is a Tab for supplying my Nessus API Keys and credentials to run nessus scan  would be good (reference : https://github.com/1N3/Sn1per/wiki/Nessus-Integration)

**Comment by techasit14607** [comment]
It's not work. Lost the time.

**Comment by yogeshojha** [comment]
Sure, this is on priority and I am working on it.

**Comment by techasit14607** [comment]
You have to learn Thai language.

**Comment by DhiyaneshGeek** [comment]
@yogeshojha is this feature completed bro ?

**Comment by yogeshojha** [comment]
Proxy support is out now in 1.0!

![proxy](https://user-images.githubusercontent.com/17223002/129470129-6b52b5d3-b505-44e4-9d95-5c13dfe00481.png)

**Comment by DhiyaneshGeek** [comment]
@yogeshojha  Thanks man :)

**Comment by DhiyaneshGeek** [comment]
@yogeshojha  Nessus API Integration seems to be missing .

Let me know if i'm wrong

**Comment by z7701858** [comment]
@yogeshojha Is it support socks5 proxy in 1.0.2 ? Or only http/https ? The example is http.THX man.
