### ISSUE TITLE
Bug - Make File

### ISSUE THREAD

**Issue by FIXERMAN** [yogeshojha/rengine#405]
root@fixer:/home/fixer/tools/rengine# make up
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml up -d --build db web proxy redis celery celery-beat
Building web
Sending build context to Docker daemon  212.3MB
Step 1/28 : FROM python:3-alpine
 ---> 2d64a2341b7c
Step 2/28 : LABEL     name="reNgine"     author="Yogesh Ojha <yogesh.ojha11@gmail.com>"     description="reNgine is a automated pipeline of recon process, useful for information gathering during web application penetration testing."
 ---> Using cache
 ---> 19e0ef1fb833
Step 3/28 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 6d0918cb112b
Step 4/28 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> d77e1e19ff20
Step 5/28 : RUN apk update     && apk add --virtual build-deps gcc python3-dev musl-dev     && apk add postgresql-dev chromium git netcat-openbsd build-base     && pip install psycopg2     && apk del build-deps     && apk add libpcap-dev
 ---> Using cache
 ---> fb2203f4011e
Step 6/28 : COPY --from=golang:1.14-alpine /usr/local/go/ /usr/local/go/
 ---> Using cache
 ---> ffa1bb95b6c5
Step 7/28 : ENV DATABASE="postgres"
 ---> Using cache
 ---> f0c25489f24c
Step 8/28 : ENV GOROOT="/usr/local/go"
 ---> Using cache
 ---> f8bcd31346dd
Step 9/28 : ENV GOPATH="/root/go"
 ---> Using cache
 ---> 0b07fa0f509d
Step 10/28 : ENV PATH="${PATH}:${GOROOT}/bin"
 ---> Using cache
 ---> c3f507a0559f
Step 11/28 : ENV PATH="${PATH}:${GOPATH}/bin"
 ---> Using cache
 ---> 73f94c7abe6f
Step 12/28 : RUN go get -u github.com/tomnomnom/assetfinder github.com/hakluke/hakrawler
 ---> Running in ee5febed604a
# cd .; git clone -- https://github.com/tomnomnom/assetfinder /root/go/src/github.com/tomnomnom/assetfinder
Cloning into '/root/go/src/github.com/tomnomnom/assetfinder'...
fatal: unable to access 'https://github.com/tomnomnom/assetfinder/': Could not resolve host: github.com
package github.com/tomnomnom/assetfinder: exit status 128
# cd .; git clone -- https://github.com/hakluke/hakrawler /root/go/src/github.com/hakluke/hakrawler
Cloning into '/root/go/src/github.com/hakluke/hakrawler'...
fatal: unable to access 'https://github.com/hakluke/hakrawler/': Could not resolve host: github.com
package github.com/hakluke/hakrawler: exit status 128
The command '/bin/sh -c go get -u github.com/tomnomnom/assetfinder github.com/hakluke/hakrawler' returned a non-zero code: 1
ERROR: Service 'web' failed to build : Build failed
make: *** [Makefile:22: up] Ошибка 1
root@fixer:/home/fixer/tools/rengine# 

rкак решить эту проблему ?

**Comment by ohlinge** [comment]
+1

**Comment by Ajatars** [comment]
vim Dockerfile

add
ENV GO111MODULE="on"
ENV GOPROXY="https://goproxy.io,direct"

**Comment by deepcat1337** [comment]
> vim Dockerfile
> 
> add
> ENV GO111MODULE="on"
> ENV GOPROXY="https://goproxy.io,direct"

Thanks Work for me
