### ISSUE TITLE
Feature - Results export

### ISSUE THREAD

**Issue by soufian2017** [yogeshojha/rengine#406]
**Is your feature request related to a problem? Please describe.**
When ever a scan is finished, subdomains and endpoints are listed on there own pages but there is no option to export them and use the output in different tools/reports.

**Describe the solution you'd like**
When you visit subdomains page for example, an export button appears with different options such as txt,csv,json and on click you get a list of subdomains in the specified file format.
This should apply to all the data types including and not limited to subdomains, endpoints, targets, ...

**Describe alternatives you've considered**
manual copy using curl and a few bash tricks.

**Additional context**
![image](https://user-images.githubusercontent.com/26626288/120178941-ec4a9a00-c201-11eb-85f7-1164271b9cc2.png)

**Comment by yogeshojha** [comment]
Implemented in 1.0

![Screenshot from 2021-08-15 12-35-25](https://user-images.githubusercontent.com/17223002/129470087-fc44672f-b2f4-4794-b767-9dfb2fc89c56.png)
![Screenshot from 2021-08-15 12-35-48](https://user-images.githubusercontent.com/17223002/129470098-8f1e9b2c-90a1-4610-b33f-24d53d48a8a0.png)
