### ISSUE TITLE
Scanner dies after fetching endpoints

### ISSUE THREAD

**Issue by demon1k** [yogeshojha/rengine#408]
celery_1       | [2021-05-15 13:39:11,199: ERROR/MainProcess] Process 'ForkPoolWorker-1' pid:12 exited with 'signal 9 (SIGKILL)'
celery_1       | [2021-05-15 13:39:23,392: ERROR/MainProcess] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL).')
celery_1       | Traceback (most recent call last):
celery_1       |   File "/usr/local/lib/python3.9/site-packages/billiard/pool.py", line 1265, in mark_as_worker_lost
celery_1       |     raise WorkerLostError(
celery_1       | billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL).
celery_1       | [2021-05-15 13:39:31,995: INFO/MainProcess] Discarding revoked task: celery.backend_cleanup

i was scanning a target with a large network and the status was stuck at 'fetching endpoints'. when i checked logs. This is what happened.

**Comment by yogeshojha** [comment]
Fixed in 1.0
