### ISSUE TITLE
Feature - need xss scanner 

### ISSUE THREAD

**Issue by PRAZPC** [yogeshojha/rengine#413]
xss is a major bug in any website and it is one of the most common bug adding it in the rengine will be a great to all of us

**Comment by Teicu** [comment]
reNgine is a reconnaissance engine(framework) so wtf?  what does this tool have to do with vulnerability scanning when there are so many other scanners

**Comment by PRAZPC** [comment]
> reNgine is a reconnaissance engine(framework) so wtf? what does this tool have to do with vulnerability scanning when there are so many other scanners

hey you m****rF****r  just shut you mouth , Do you even know what are you saying ? , have you ever use reNgine you son of b***h , reNgine uses other scanner such as (aMass , sublist3r etc) and give you result in better form with an good ui , reNgine is used to find vulnerability you idiot have you ever seen there is an option of vulnerability scanning which search for only subdomain take over vuln and other (not doing directory finding) , just first go and use it .
