### ISSUE TITLE
Unable to import target(s)

### ISSUE THREAD

**Issue by ratpunk2** [yogeshojha/rengine#418]
Whenever I am trying to upload target list, I am getting following error "Oops! File format was invalid, could not import any targets." Target list is already in .txt format.

**Comment by PR3R00T** [comment]
Hey @ratpunk2 
So I encountered this problem, Its to do with Windows and Linux different End of Line finishes. 
first make sure your file is like

test1.example.com
test2.example.com
test3.example.com

Then if you are on a windows computer, open up Notepad ++ : Edit -> EOL Conversions -> Unix (LF) save the file and try again
If you are on a Linux terminal and you have copied the file from a windows PC do : dos2unix filename.txt 

upload the file and it should work now. :)
