### ISSUE TITLE
FTP Service with default credentials	

### ISSUE THREAD

**Issue by foozzi** [yogeshojha/rengine#419]
FTP Service with default credentials	
but it is not known exactly what standard data

**Comment by schniggie** [comment]
same here, cannot find any hint in the source code by searching for ftp, default credentials ....

**Comment by foozzi** [comment]
@yogeshojha why is the status closed? no response received, how does rengine determine the default login details for ftp?

**Comment by schniggie** [comment]
https://github.com/projectdiscovery/nuclei-templates/blob/920255635be0fd02d35751b6672fef558e87598e/network/ftp-default-creds.yaml

Based on that complete crappy nuclei check.
