### ISSUE TITLE
it is impossible to create a scan with multiple targets (404 error)

### ISSUE THREAD

**Issue by foozzi** [yogeshojha/rengine#424]
### Issue Summary

it is impossible to create a scan with multiple targets

### Steps to Reproduce

1. select 1 more targets
2. click "Scan multiple targets"
3. have 404 error...

### Technical details
Linux 5.4.0-29-generic #33-Ubuntu SMP Wed Apr 29 14:32:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
python 3.8.2
rengine 1.0

@yogeshojha

**Comment by yogeshojha** [comment]
Hey, thanks for the heads up, fixed it!
