### ISSUE TITLE
Subdomain enumeration taking 3 hours on small target

### ISSUE THREAD

**Issue by helloreddit** [yogeshojha/rengine#428]
Is there anyway to see whether the tool is running as it should? Been sat discovering subdomains for 3 hours on a target which I know has about 10 subdomains.

**Comment by yogeshojha** [comment]
This should not have happened, can you check where it is stuck?

Into project directory
make logs

Can you also try stopping the scan and rescan them?

**Comment by yogeshojha** [comment]
I just ran a scan on a target on an entirely new machine, works well for me. Please rescan the target

**Comment by helloreddit** [comment]
I did make logs and can see that it was running fine and had found subdomains but nothing was reflected on the UI.

After cancelling and retrying scan I am now seeing results reflected on UI. I ran a quick scan this time and a full scan last time. I will try again on full scan.

**Comment by helloreddit** [comment]
Ok. Here was my issue.

I saw on the right after adding a target ‘quick scan’ so assumed this was some type of lighter faster scan, so had been selecting the target with the toggle on the left and then ‘scan multiple targets’. This was causing the scans not to reflect the results on the UI.

Starting the scan through quick scan works fine.
