### ISSUE TITLE
 NameError("name 'amass_config_path' is not defined")

### ISSUE THREAD

**Issue by big-ppp** [yogeshojha/rengine#429]
### Issue Summary

Subdomain scan does not seem to be progressing, checked the logs using "make logs" and can see error message 
NameError("name 'amass_config_path' is not defined")

### Steps to Reproduce

1. I have added the amass configuration to the tools settings
2. I have modified the engine to include "use_amass_config: true"
3. i also added amass-active to the subdomain discovery

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

Please see error message detail

[2021-08-15 13:32:22,046: ERROR/ForkPoolWorker-4] Task reNgine.tasks.initiate_scan[869f5730-4e7c-41cb-a7dd-9a4281d56500] raised unexpected: NameError("name 'amass_config_path' is not defined")
celery_1       | Traceback (most recent call last):
celery_1       |   File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 450, in trace_task
celery_1       |     R = retval = fun(*args, **kwargs)
celery_1       |   File "/usr/local/lib/python3.8/dist-packages/celery/app/trace.py", line 731, in __protected_call__
celery_1       |     return self.run(*args, **kwargs)
celery_1       |   File "/usr/src/app/reNgine/tasks.py", line 149, in initiate_scan
celery_1       |     subdomain_scan(
celery_1       |   File "/usr/src/app/reNgine/tasks.py", line 392, in subdomain_scan
celery_1       |     if amass_config_path:
celery_1       | NameError: name 'amass_config_path' is not defined

**Comment by yogeshojha** [comment]
That shouldn't be any problem. When config file is not found, you still can double click the text area and update your contents.
