### ISSUE TITLE
Wrong text Color in Darkmode in Visualisation Tab

### ISSUE THREAD

**Issue by TheD3C4Y** [yogeshojha/rengine#430]
First of all Thank you for everyone involved in this Project the new release is awesome. but there is an visual bug with the text Color in the Visualisation tab where the the white panels have white text. if you switch to normal mode the text is fine.

Found a bug? Please fill out the sections below. 👍

### Issue Summary

Wrong text Color in Darkmode in Visualisation Tab

### Steps to Reproduce

1. Run a Scan and go to the Visualtion Tab 
2. ...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes 

The Color of the text in Darkmode is still white so you white panels with white text.

### Technical details

Debian 10
Docker version 20.10.8, build 3967b7d
latest Regine Version from Github

**Comment by yogeshojha** [comment]
The visualisation is changed in 1.1 and should fix this
