### ISSUE TITLE
Add Engine Button not working

### ISSUE THREAD

**Issue by attacker007** [yogeshojha/rengine#435]
Tried many times to add custom Engine but Add Engine button is not working. Anyone noticed?

**Comment by yogeshojha** [comment]
Surprisingly, I just tested and is working. Can you send me a screenshot of which button you're talking about? 
![1](https://user-images.githubusercontent.com/17223002/129512847-8023909b-b974-4cbf-9505-48d32c503d4a.gif)

**Comment by attacker007** [comment]
Not that "Add New Engine" but other one named "Add Engine" ... search it.. its under that box where u can add yaml...

**Comment by yogeshojha** [comment]
It is working!
![1](https://user-images.githubusercontent.com/17223002/129513175-4adc8966-b6b4-44df-94df-36e615f49e2d.gif)

**Comment by attacker007** [comment]
Not working again checked... let me make video and send ...

**Comment by attacker007** [comment]
check:

https://mega.nz/file/7J1GwA6A#8E0K39pqsL9T-bh4GYDn73FdTC5g5S_q4Gp5R_QbBFE

**Comment by yogeshojha** [comment]
Please read the instructions there on the page itself before raising any request, It just isn't worth the time if I spend so much on providing instruction there inside the application and the issue is raised without reading it.

reNgine depends on YAML configurations to build engines for scans. You do not have a YAML configuration. 

This is what is written there: 
```
reNgine YAML Documentation
To learn more about YAML config visit the official documentation at https://rengine.wiki/pentester/scan_engine/
Note: Invalid YAML configuration may crash scans.
PLEASE, DO NOT MODIFY THE CONFIGURATION IF YOU ARE NOT SURE WHAT YOU ARE DOING.
If default YAML configuration doesn't automatically load, download default configuration and paste here https://raw.githubusercontent.com/yogeshojha/rengine/master/tools/default_settings.yaml
```

**Comment by attacker007** [comment]
Hi, sorry my bad.. in ur last update.. there was no such thing and user could add via few clicks ... that's why i was try that...

**Comment by yogeshojha** [comment]
No worries, If default YAML configuration doesn't automatically load, download default configuration and paste here https://raw.githubusercontent.com/yogeshojha/rengine/master/tools/default_settings.yaml
