### ISSUE TITLE
Rengine Already Installed

### ISSUE THREAD

**Issue by DhiyaneshGeek** [yogeshojha/rengine#444]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

We have not installed rengine , but it shows this error message , there is no docker images that is running as well 

### Steps to Reproduce

sudo ./install.sh

![image](https://user-images.githubusercontent.com/24750220/129564192-dad2b90c-b731-46a7-a37c-5d0fea955b81.png)

**Comment by foozzi** [comment]
docker-compose.setup.yml and docker-compose.yml set version 3.7

**Comment by DhiyaneshGeek** [comment]
@foozzi it worked ! thanks
