### ISSUE TITLE
ERROR: Version in docker-compose is unsupported (Ubuntu 20.04)

### ISSUE THREAD

**Issue by notdodo** [yogeshojha/rengine#448]
### Issue Summary

ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/

### Steps to Reproduce

1. Install docker and docker-compose on Ubuntu 20.04
2. run `sudo ./install.sh`

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

- Ubuntu 20.04
- Docker version 20.10.8, build 3967b7d
- docker-compose version 1.25.0, build unknown

**Comment by edoardottt** [comment]
Same error here

**Comment by yogeshojha** [comment]
I think you have an older version of docker-compose. Which version of compose you're running?

```sudo docker-compose --version?```

**Comment by edoardottt** [comment]
`docker-compose --version`: docker-compose version 1.29.2, build unknown  
`sudo docker-compose --version`: docker-compose version 1.25.0, build unknown

After updating following https://docs.docker.com/compose/install/#install-compose-on-linux-systems

I have `1.29.2` version on both my user and root and It works fine.

Sorry for the wasted time, and thank you

## If you're having problems, just update docker-compose https://docs.docker.com/compose/install

I think we can close the issue.

**Comment by yogeshojha** [comment]
No worries guys, it happens, feel free to self close. :heart:

**Comment by Esonhugh** [comment]
Same Error, Thank.
But Notice, If anybody try the document, remember to remove the docker-compose.
Don't apt install it. I stucked on it.
Use the `docker compose` instead (no `-` there).
