### ISSUE TITLE
rengine not running properly

### ISSUE THREAD

**Issue by hridoua** [yogeshojha/rengine#449]
![Screenshot 2021-08-17 06:24:07](https://user-images.githubusercontent.com/47630504/129770968-0f004917-82a7-4fa0-896e-e9c678229639.png)
![Screenshot 2021-08-17 06:44:37](https://user-images.githubusercontent.com/47630504/129770997-cb56f857-9f6c-4fea-b454-1487b871264e.png)
whats the problem?

**Comment by alph4byt3** [comment]
Are you on a Kali virtual machine?

**Comment by dorkerdevil** [comment]
installing it on a fresh ubuntu works without issues

**Comment by alph4byt3** [comment]
if you're on a kali vm though, install docker manually and then rerun the script

**Comment by hridoua** [comment]
im in kali virtualbox

**Comment by alph4byt3** [comment]
> im in kali virtualbox

yeah, install docker manualy by following this article and then rerun the script, it will work.

https://airman604.medium.com/installing-docker-in-kali-linux-2017-1-fbaa4d1447fe

**Comment by hridoua** [comment]
docker also installed now whats the problem?
![Screenshot 2021-08-19 03:53:55](https://user-images.githubusercontent.com/47630504/130114167-f5e9eb2b-6891-4050-934e-d93c63f7dd73.png)

**Comment by alph4byt3** [comment]
did you run script with sudo?

**Comment by hridoua** [comment]
yes

**Comment by alph4byt3** [comment]
> yes

i don't know, it works fine for me on a new kali vm

**Comment by Soukainachr** [comment]
hello, I had the same issue; you should first install docker properly( you can follow this tutorial https://linuxhint.com/install_docker_kali_linux/), then you can follow the instructions explained in the documentation : https://rengine.wiki/install/install/ to install rengine :) (btw, I'm using kali 2021.2)
