### ISSUE TITLE
Widget Cards are not responsive

### ISSUE THREAD

**Issue by yogeshojha** [yogeshojha/rengine#45]
While on the dashboard, either zoom or resize the browser window, the cards do not resize properly. This has something to do with the Bootstrap grid system.

![Screenshot 2020-07-05 at 8 41 49 PM](https://user-images.githubusercontent.com/17223002/86535743-3945c380-bf00-11ea-9adc-4d375b4f72ff.png)

Maybe somebody can work on it, Good first issue!

Code for this should be inside /reNgine/dashboard/templates/dashboard/index.html

**Comment by Aju100** [comment]
@yogeshojha yeah there is a problem out in **Recent Section** too. Have a look
![mobileresponsiveproblem](https://user-images.githubusercontent.com/29862610/86536181-4d3ff400-bf05-11ea-93da-945579adf499.png)

**Comment by Suprita-25** [comment]
@yogeshojha , I am working on it
