### ISSUE TITLE
Changes in amass

### ISSUE THREAD

**Issue by SAGEof6iixPATHS** [yogeshojha/rengine#452]
Hello!

When I run amass it breaks the connection with the ip, can you tell me how to edit the command you used, so I could use less threads and make amass work again?

**Comment by PR3R00T** [comment]
Hey @SAGEof6iixPATHS 
go to web/reNgine/tasks.py Line 366 and/or 376 are the raw amass commands. 
Add your thread flag in there and then make build && make up to rebuild the app.

**Comment by SAGEof6iixPATHS** [comment]
Thank you!
