### ISSUE TITLE
[SECURITY] - Stored Cross-site Scripting before deleting an Organization!

### ISSUE THREAD

**Issue by TheBinitGhimire** [yogeshojha/rengine#456]
### Issue Summary

In reNgine v1.0, there is Stored Cross-site Scripting before deleting an Organization!

Note that this report is different from #454. #454 occurs while displaying the Organization name, but this one occurs for a different reason as I have shown in the attached image.

### Steps to Reproduce

1. Visit your reNgine instance, and login to your account.
2. Add some targets through the Targets page.
2. Head over to the **`/target/list/organization`** endpoint.
3. Click on "Add Organization" and write `');alert(document.domain);//` in the **Organization name** field.
4. Select targets, and add the organization.
5. Click on the Delete icon (cross icon), and the payload will be executed.

Here, the payload will be executed through the values inside the **onclick** attribute, as shown in the image below:

![Stored Cross-site Scripting before deleting an Organization!](https://user-images.githubusercontent.com/20013689/130065193-73dc9159-f926-4410-b09c-92d5a1d48d9f.png)

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: **yes**

### Technical details

* Debian 4.19.181-1

**Comment by yogeshojha** [comment]
Duplicate #454 , fix for #454 is available
