### ISSUE TITLE
Add Instructions for Updating rengine after major updates in the wikiFeature - Your Awesome feature title

### ISSUE THREAD

**Issue by park3ra** [yogeshojha/rengine#458]
I asked for this before and it was done but with the major version 1.0 release the page now goes to a 404 error. Anyway to add this back? Eager to update my build to the new release!

**Comment by alph4byt3** [comment]
If I'm not mistaken, this build is a major overhaul so if you want it to this build you'll need to reinstall it completely.

**Comment by park3ra** [comment]
Yes, I concluded that as well, I ended up rebuilding everything and it works. :)

**Comment by yogeshojha** [comment]
Sorry for the delay, I was working on documentation. You can now find the updated documentation here: https://rengine.wiki/update/
