### ISSUE TITLE
feat: Allow uploading of multiple Nuclei templates

### ISSUE THREAD

**Issue by iamxhunt3r** [yogeshojha/rengine#461]
Is there any way whether manually or by UI to add many custom nuclei templates in rengine?

**Comment by rakesh6927** [comment]
yes you can navigate to https://<your-ip>/scanEngine/tool_settings and find nuclei section.

**Comment by iamxhunt3r** [comment]
> yes you can navigate to https://localhost/scanEngine/tool_settings and find nuclei section.

As mentioned above can we add many ( 2 or more at a time) custom nuclei templates ?

**Comment by iamxhunt3r** [comment]
Well i found a way we can put templates manually on docker

**Comment by innerfirebg** [comment]
> Well i found a way we can put templates manually on docker

How?

**Comment by y0d4a** [comment]
> Well i found a way we can put templates manually on docker

would you like to tell us ?
DId just copy yaml inside /var/lib/docker/volumes/rengine_nuclei_templates/_data/ 
works?

**Comment by Tamirye** [comment]
stupid workaround i found 

```
#!/bin/bash

source_folder="/path/to/nuclei/templates"
destination_folder="/var/lib/docker/volumes/rengine_nuclei_templates/_data/"

# Use find to locate all YAML files inside the source folder
find "$source_folder" -type f -name "*.yaml" -exec cp {} "$destination_folder" \;

```

**Comment by psyray** [comment]
> How have people mass added their new templates to their scanner engine? The documentation states you need to list each file manually?

Yes for the moment.

> Is it a case of creating a new folder within the volume, moving all files there, then formatting all names into yaml friendly formatting for the custom_templates section? Does it need to include the folder name or just name of template?

You can add the templates directly inside the Celery container, via the docker volumes
![image](https://github.com/yogeshojha/rengine/assets/1230954/3b093ec6-7a28-4b1b-99e5-76111b081130)

**Comment by yogeshojha** [comment]
PR #1320
