### ISSUE TITLE
Add Local or ipadress for scanning the locally cloned repos

### ISSUE THREAD

**Issue by chanduaki** [yogeshojha/rengine#463]
When we cloned the repository, for supposing consider `DVWA` running in my VirtualBox, when i am trying to add the VMs IP address as a target, then getting an error
`localhost is not a valid domain Name`
`<ipaddress> is not a valid domain Name`

Solution: 
* Can u allow the <IP Address> along with Domain Name

**Comment by righel** [comment]
I think it would be great to be able to add IP addresses as targets, no matter if public or private.

**Comment by yogeshojha** [comment]
This is available in reNgine 1.1. Thank you for the feature request. IP Address can be added and resolved from target section.
