### ISSUE TITLE
How to turn off the services?

### ISSUE THREAD

**Issue by edoardottt** [yogeshojha/rengine#465]
Sorry to bother you, I will be real quick.

Just installed rengine, executed `sudo ./install.sh` without errors.  
Now I can see the main service on port 80 and all other services on port 8000, 5432 etc..  

How can I turn off everything? Is possible to have a simple way to turn off the services and then re-turn on later?  
Do I have to use docker commands ? 

Thank you and sorry if there is already an answer and I'm not seeing it

**Comment by YuraveON** [comment]
do you mean turn off rengine? if yes, use `make stop` 

full instruction is in https://rengine.wiki/install/install/

**Comment by edoardottt** [comment]
Oh my god. ahaha

Thank you so much :)  
Have a good day
