### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Krosskid12** [yogeshojha/rengine#470]
Hii I would like to know that nuclei-templates doesn't isn't included in the vulnerability scan?. I scanned a target but never got any vulnerability issue.
![image](https://user-images.githubusercontent.com/73221787/130906203-48e1e2c4-ec0d-42e2-8b96-de33a8f15d70.png)

**Comment by yogeshojha** [comment]
I confirmed now, default nuclei templates are working as expected.

**Comment by Krosskid12** [comment]
> I confirmed now, default nuclei templates are working as expected.

should I need do change some setting or it runs default?

**Comment by yogeshojha** [comment]
Hi Guys, I am trying to fix this today, can you please give me the target name (if public) so that I can fix the OSINT scan failure?

**Comment by Soukainachr** [comment]
> Did you use custom template name in yaml config?
> 
> https://rengine.wiki/usage/scan_engine/
> 
> https://rengine.wiki/usage/scan_engine/#:~:text=1%0A%20%20templates%3A%20%5B%20all%20%5D%0A%20%20%23-,custom_templates,-%3A%20%5B%5D%0A%20%20severity%3A%20%5B%20critical%2C%20high

what about the harvester tool, how can we add shodan and censys api ??

**Comment by Mateus-Veras-Tvirus** [comment]
Hi, is everything ok?, the destination I'm trying is cnnbrasil.com.br, I'm using the proxy list that reports reNgine on the site, I'm using the private proxy and I don't have results like Password,  
![renginee](https://user-images.githubusercontent.com/33964602/132445649-07efc0c9-c809-4b11-b207-d1a75f49307b.png) @yogeshojha
