### ISSUE TITLE
merge organization with targets and add unique params, endpoints to scan results

### ISSUE THREAD

**Issue by pichik** [yogeshojha/rengine#472]
Hi, here are few ideas:
1. Be able to scan specific subdomains  directly from scan history/summary/target subdomains
2. Have merged organization and targets, as I feel like organization have not much of purpose:
- You start with creating organization
- You can add domains to this organization, and for every domain you can specify out of scope subdomains (as now you need to specify them every time you want to scan target)
- if you scan subdomains they will be added under domain they belong
So you will be able to open your organization, then open domain and you will see all subdomains of specific domain and you can choose if you want to scan entire organization, domain, or specific subdomain only.
As now you need to add new subdomain to target and every time add it to your organization and your target tab get messy pretty fast if you have lots of domains/subdomains.
3.  Add unique endpoints and params next to urls in scan history

I hope i've explained it well, as this can improve user experience.
Thank you !

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) 
https://rengine.wiki/changelog/#200
