### ISSUE TITLE
Scan fail if we choose vulnerability scan (Normal)

### ISSUE THREAD

**Issue by rakesh6927** [yogeshojha/rengine#474]
### Issue Summary

If we run a vulnerability scan (normal) after some time scanning gets failed.

### Steps to Reproduce

1. Add Target
2. Choose Vulnerability scan (NOrmal)
3. Wait for few minutes, after some time of vulnerability scan it gets failed.

* I have confirmed that this issue can be reproduced as described on the latest version/pull of reNgine: (yes)

I checked the logs, it gets failed after a nuclei scan, find the screenshot which might be useful. Tried multiple times with different domains

![Screenshot 2021-08-28 010519](https://user-images.githubusercontent.com/25160144/131180005-14795d27-408c-488b-8a99-12306520cc3e.png)

![Screenshot 2021-08-28 010934](https://user-images.githubusercontent.com/25160144/131180318-2d5293c0-300d-4398-8a38-5520362dd434.png)

**Comment by yogeshojha** [comment]
This has now been fixed, https://github.com/yogeshojha/rengine/commit/14592877d8409d54b258bfec95fe48b407e1a622 Please check the changelogs :) THank you
