### ISSUE TITLE
OCI runtime exec failed: exec failed: container_linux.go:380: starting container process caused: exec: "python": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by mikesmith12137** [yogeshojha/rengine#475]
Been trying to get ReNgine running in Windows

Everything works up until "make username"

Have uninstalled and reinstalled...

Checked entrypoints and updated to python3 -- same error there as well..

Any ideas or help is greatly appreciated...can't wait to play with the tool if I can get it up and running

**Comment by yogeshojha** [comment]
Please try with fresh installation.

Additionally, try uninstalling rengine https://rengine.wiki/uninstall/ and install again.
