### ISSUE TITLE
Bug - Scanning issues after recent merge/ commits

### ISSUE THREAD

**Issue by alph4byt3** [yogeshojha/rengine#479]
### Issue Description

Scans stop working after subdomain discovery but before probing subdomains for endpoints. It seems to be happening during the HTTPX part of the scan.

Here's a normal vuln scan using the default engine in a newly installed instance.

![image](https://user-images.githubusercontent.com/67894940/131221581-add0990c-5546-482e-a1db-bec624dffa39.png)

![image](https://user-images.githubusercontent.com/67894940/131221628-0496302e-42db-4151-a1e9-ced68d70b2b6.png)

![image](https://user-images.githubusercontent.com/67894940/131221644-1e65a03d-63c8-485f-b55a-77bbc0e97457.png)

The build I was using before Thursday 26th was fine and that was the day new changes were committed, today I reinstalled rengine due to a power outage hence why I'm now here.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)

yes

### Technical details

None

**Comment by yogeshojha** [comment]
Weird! Let me try immediately on my older VPS build. But I don't think any changes has happened in scanning part, which would fail this. anyways let me check

**Comment by yogeshojha** [comment]
How did you update btw? I assume

`make down && git pull && make build && make up`

right?

**Comment by yogeshojha** [comment]
I can confirm everything is working as expected. My build was from Aug 16 and updated to the most recent. It is working as expected.

**Comment by wapwn** [comment]
@alph4byt3 
that's because `httpx` just updated, the returned json data is a bit different
in the `http_crawler` function you just need to change the subdomain query to
```
subdomain = Subdomain.objects.get(scan_history=task, name=json_st['input'])
```
original code
```
subdomain = Subdomain.objects.get(scan_history=task, name=json_st['url'].split("//")[-1])
```

**Comment by alph4byt3** [comment]
> How did you update btw? I assume
> 
> `make down && git pull && make build && make up`
> 
> right?

Hey, I didn't update it. I'm on a VM so I went back to a previous screenshot from a couple of days ago without reNgine installed and reinstalled it from scratch (git clone etc etc)

I'm quite busy at the moment so when I get free time later I'll go check on it again for any other things I can find

**Comment by yogeshojha** [comment]
Hi @wapwn Thank you very much for pointing this out! You're awesome 🌟 

This has been fixed, tested on the most recent version of HTTPX. If this problem still persists, feel free to raise a new GitHub issue, or we can reopen this.

**Comment by yogeshojha** [comment]
Thanks @alph4byt3  for reporting this.
