### ISSUE TITLE
Error while Rengine doing Director Bruteforce

### ISSUE THREAD

**Issue by XDev05** [yogeshojha/rengine#480]
hello rengine team, the tool didn't work well when it's achieve the Directory Bruteforce Point, it's take along time and nothing return, so Please take a look and fix this bug.

![1](https://user-images.githubusercontent.com/55960303/131233587-e1a6287e-b247-4bc4-a26e-7230177094ae.PNG)
![2](https://user-images.githubusercontent.com/55960303/131233588-9af2a7ea-342d-4a6b-81fc-f8474561183b.png)
)

**Comment by Mateus-Veras-Tvirus** [comment]
hello, I have this problem too, I don't know what to do
