### ISSUE TITLE
requirements.txt doesn't have all the required modules

### ISSUE THREAD

**Issue by brenu** [yogeshojha/rengine#486]
# Issue

While trying to install this new version of reNgine, I received a lot of error messages coming from Python about "unknown" modules, then it turned out that these modules were not inside web/requirements.txt and I had to install them one by one. Here's the list of the missing modules:
```
djangorestframework-datatables
django-ace
django-celery-beat
django-mathfilters
drf-yasg
discord_webhook
metafinder
emailfinder
dotted_dict
degoogle
```

**Comment by yogeshojha** [comment]
This is not normal, 

If you check the requirements file: https://github.com/yogeshojha/rengine/blob/master/web/requirements.txt

All those requirements are set. Which OS are you installing in? and please attach the logs as well
