### ISSUE TITLE
Perfomance - low 

### ISSUE THREAD

**Issue by aniruddhmistry** [yogeshojha/rengine#488]
Hi Team,

I used the same configuration (VPS) displayed on Regine.wiki, but still, after start scan after 2 hr Subdomain was not founded. 

as I Used Subfinder or some other passive recon tool, it hardly takes 1-2 min for recon. then I don't know why it's taking that much time.

> Request you to add CLI ( Terminal Log) Scan-wise so We can check the error/Log or status of the scan.
> If I have Subdomain List and I want to perform only Port San and Vulnerability scan for that feature not availabe.

**Comment by yogeshojha** [comment]
Please read the documentation before raising issues as it is not worth the time to repeat same things again and again.

We have an option to check the logs and is well documented.

https://rengine.wiki/install/install/#checking-logs

**Comment by yogeshojha** [comment]
Your subdomain scan may have failed due to misconfiguration in scan engine. Otherwise it is very unlikely that scan gets stuck in subdomain gathering.
