### ISSUE TITLE
Grouping of vulnerabilities

### ISSUE THREAD

**Issue by yogeshojha** [yogeshojha/rengine#491]
Grouping of vulnerabilties using Vulnerability Title or Severity

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) 
https://rengine.wiki/changelog/#200
![image](https://github.com/yogeshojha/rengine/assets/1230954/46866da8-5df1-45fc-bd69-235b768acac3)
