### ISSUE TITLE
Create organization when adding targets

### ISSUE THREAD

**Issue by macesaces** [yogeshojha/rengine#492]
Hej,

It would be awesome when there would be a function to directly create organizations when adding targets.
Right now you need to add the targets - create an organization and add the domains..
It would safe much time when it would be possible to create an org right of the "add target" window.
So when I'm adding domains from a specific program i just can add a Org name and it will create the
Targets, then create an Org and afterwards it will add the domains to the organization.

best

**Comment by yogeshojha** [comment]
This could be a very good addition. Thanks for letting me know. I will do my best to bring it on reNgine 1.1

**Comment by yogeshojha** [comment]
This has been further extended to create new organization while adding quick target.

**Comment by yogeshojha** [comment]
![image](https://github.com/user-attachments/assets/93a3995e-174d-4375-b732-8e49bda831b6)


One can add organization here, if organization already exists, it will tag this target to existing organization

**Comment by yogeshojha** [comment]
This is released in reNgine 2.2.0, checkout: [What's new in 2.2.0](https://rengine.wiki/whats-new/2_2_0/)
