### ISSUE TITLE
Bug - Service 'web' failed to build

### ISSUE THREAD

**Issue by beerMT** [yogeshojha/rengine#493]
### Issue Summary

sudo make build results in an Error: 
The command '/bin/sh -c GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder     github.com/projectdiscovery/nuclei/v2/cmd/nuclei     github.com/lc/gau     github.com/projectdiscovery/naabu/cmd/naabu' returned a non-zero code: 2
ERROR: Service 'web' failed to build : Build failed
make: *** [build] Error 1

### Steps to Reproduce

1. Clone the repo
2. Make certs
3. Sudo make build

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
Yes, recently cloned repo

### Technical details
Mac OS 11.5.2, latest version of Docker

**Comment by yogeshojha** [comment]
Hi @beerMT, please try to rebuild once again. 
`make build && make up`
The builds are passing and I am able to install reNgine on the newly created VPS.

**Comment by yogeshojha** [comment]
https://github.com/yogeshojha/rengine/runs/3540875336?check_suite_focus=true
