### ISSUE TITLE
Feature LXC 

### ISSUE THREAD

**Issue by Reikagilu** [yogeshojha/rengine#496]
I'm using Proxmox, reNgine could easily run in an LXC container, but I currently have to upload a full VM into it to run a docker container inside it for run reNgine

**Comment by psyray** [comment]
I've tested both, LXC and KVM on Proxmox.
KVM is the best choice, with LXC you will face to the docker overlay2 problem
https://forum.proxmox.com/threads/lxc-zfs-docker-overlay2-driver.122621/
