### ISSUE TITLE
Scan Summary -> filter directories by size to find "real" endpoints

### ISSUE THREAD

**Issue by macesaces** [yogeshojha/rengine#500]
Hi there,

it would be awesome if you could add the possibility to filter by size.

I'm having hundreds of positive results with the same filesize because the server is responding always responding with a HTTP 200 status. Even if the requested file/endpoint doesn't exist. No if there is one "real" finding it will be pretty hard to look for it.
Right now I am using the browsers search function for it but it would be nice to have the possibility to sort by filesize.

```
/yaml.bak (0.38 Kb)
/txt.zip (0.38 Kb)
/sql.zip (0.38 Kb)
/conf.php (0.38 Kb)
/bak.bak (0.38 Kb)
/aspx.bak (0.38 Kb)
/php (0.38 Kb)
/db.tgz (0.38 Kb)
/bak (0.38 Kb)
/mysql (0.38 Kb)
/!.gitignore (0.38 Kb)
/aspx.tar (0.38 Kb)
/php.tgz (0.38 Kb)
/sql.php (0.38 Kb)
/aspx.php (0.38 Kb)
/db.old (0.38 Kb)

```

appreciate your work!

best
mace

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:
