### ISSUE TITLE
Feature - Download endpoints based on filter results

### ISSUE THREAD

**Issue by alph4byt3** [yogeshojha/rengine#501]
Unless I missed it, there doesn't seem to be a way to download certain endpoints only based on the filter e.g if I wanted to download all endpoints with a status code of 200.

If possible, it would be nice to have it so that multiple status codes can be included as well e.g if I wanted to download all endpoints with status codes 200,401,403.

**Comment by tejas15802** [comment]
right now unable to download the `subdomains` too.

**Comment by yogeshojha** [comment]
Fixed this in 1.1
