### ISSUE TITLE
Bug - Installation Error on MacOS and Kali Linux

### ISSUE THREAD

**Issue by S3ntago** [yogeshojha/rengine#509]
Hi,

While I was installing the latest version of rengine on my Macbook Pro and my Kali VM I almost got the same errors shown below and appreciate your support:

Mac
![image](https://user-images.githubusercontent.com/48615614/135443109-77262054-db37-462f-9a28-f882cd8b4eed.png)

Kali
![image](https://user-images.githubusercontent.com/48615614/135443184-49a2bd73-db9a-46ac-b26f-ac1e80f27c08.png)

**Comment by BinhMinhptit** [comment]
did you solved this issue? i got the same problem

**Comment by apetroff** [comment]
the issue is caused by your Apple silicon.
you have to add ```--platform=linux/amd64``` to  ```docker build```:
```docker build --platform=linux/amd64```

**Comment by apetroff** [comment]
Well.... the problem is deeper.

```
# Download and install go 1.17
RUN wget https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
RUN tar -xvf go1.17.2.linux-amd64.tar.gz
RUN rm go1.17.2.linux-amd64.tar.gz
RUN mv go /usr/local

# Download geckodriver
RUN wget https://github.com/mozilla/geckodriver/releases/download/v0.26.0/geckodriver-v0.26.0-linux64.tar.gz
RUN tar -xvf geckodriver-v0.26.0-linux64.tar.gz
RUN rm geckodriver-v0.26.0-linux64.tar.gz
RUN mv geckodriver /usr/bin
```

All Dockerfiles are using amd64 packages inside. It's not crossplatform
