### ISSUE TITLE
Bug - Broken UI - Looks like the CSS isn't kicking it?

### ISSUE THREAD

**Issue by Rz-Rz** [yogeshojha/rengine#510]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary
![2021-09-30 16_12_33-Window](https://user-images.githubusercontent.com/52322219/135472234-14e57bb6-592a-4a80-8288-f4584e18f39b.png)
The dashboard is broken rendering the application unusable.

### Steps to Reproduce
1. I git clone the repos
2. The install.sh script tells me that docker is not running, however I am using WSL2 and this command (sudo systemctl start docker) does not work, I have to use this command instead: sudo service docker start. However the install script does not pick up docker running using this way.
3. I use the manual steps to install the project, using the wiki. (make build, make certs...)
4. Then after make up, i check localhost:8000 and this is what I see.
![secondpic](https://user-images.githubusercontent.com/52322219/135474502-afd7f9c9-07f5-4d01-a01b-a56d78f13d4c.png)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
yes

### Technical details
I use WSL2
Please list out any technical details such as operating environment.

**Comment by tejas15802** [comment]
@Rz-Rz please check port 80

**Comment by yogeshojha** [comment]
Hi @Rz-Rz port 8000 should only be accessed if you are in dev mode. Otherwise please access via https://localhost
