### ISSUE TITLE
Param Spider with Dalfox integration for XSS

### ISSUE THREAD

**Issue by aaryan778** [yogeshojha/rengine#511]
Add Param Spider + Dalfox for automating XSS attacks.

Param Spider for extracting parameters from the domain and Dalfox for fuzzing through the parameters( Additional parameters can be added through "Arjun" tool which is commonly used for XSS attacks ).

Something like  below command:

sudo cat /home/<PATH>/<FILE.TXT> | ~/go/bin/dalfox pipe --mining-dict /home/<PATH>/Arjun/arjun/db/params.txt -b https://<XSS_HUNTER_PAYLOAD (.xss.ht ) --output /home/PATH/FINALPOC.TXT

1) We find all the parameters of all domains using "Param Spider" tool.
2) We pass those parameters through "Arjun" for fuzzing and adding additional parameters which, if vulnerable will trigger an XSS and will be passed through XSS HUNTER PAYLOAD.

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0, dalfox has been a part of vuln scanner now.

Thank you :pray:
