### ISSUE TITLE
Feature - Integration through Plesk Docker

### ISSUE THREAD

**Issue by thistehneisen** [yogeshojha/rengine#519]
**Is your feature request related to a problem? Please describe.**
Would be interested in tutorial on how to integrate rEngine via Plesk Docker to specific domain.

**Describe the solution you'd like**
rEngine integrated via https://www.plesk.com/extensions/docker/ ported to a specific domain

**Comment by psyray** [comment]
Seems Plesk supports only image download from docker hub and reNgine use docker compose to customize the docker container.
![image](https://github.com/yogeshojha/rengine/assets/1230954/64098401-c48b-4acb-87f8-6f790c56d819)
