### ISSUE TITLE
Feature - Multiple tenants

### ISSUE THREAD

**Issue by thistehneisen** [yogeshojha/rengine#520]
**Is your feature request related to a problem? Please describe.**
Adding multiple tenants and assigning them to organizations so they can see their information and do their own actions.

**Describe the solution you'd like**
Ability to add multiple users with different access levels and rights.

**Comment by yogeshojha** [comment]
Hi, can you please explain what exactly you mean by tenants?

**Comment by Tink2Hack** [comment]
The access level will allow management ppl to see what the issue is ( Superadmin, Pentester, User). Superadmin - Full access, Pentester - Only Scanning, User - Only view dashboard and scan results.

**Comment by m3hdigh** [comment]
this feature for user management can be useful .👌

**Comment by yogeshojha** [comment]
Yes, we can do this. 
User with roles and permissions is coming <3

**Comment by thistehneisen** [comment]
Hi, is there any updates on this?

**Comment by m3hdigh** [comment]
> Hi, is there any updates on this?

I check the source code of master and 2.0.0 version . Didn't see this feature yet . Multi tenancy required stateless process and separate database ...

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:
