### ISSUE TITLE
Feature - Export all results [Subdomain - IP address - Port - Title - Status - Technologies] in txt and CSV formats

### ISSUE THREAD

**Issue by S3ntago** [yogeshojha/rengine#523]
Dear Yogeshojha,

Thank you for the awesome framework, while I was doing a Pentest, I was not able to download the scans results, I was only able to download the Subdomains in .txt file.

My recommendation to allow us to download all results including subdomain, IP address, ports, title, HTTP status, technologies..etc in .txt and .csv formats.

example:
![image](https://user-images.githubusercontent.com/48615614/137709085-bf5f111e-eaca-44c0-bb4d-994e89ce7a46.png)
![image](https://user-images.githubusercontent.com/48615614/137709503-89464763-fe7d-43b7-a71b-08c373c48130.png)

This feature will be very helpful.

Thank you,
S3ntago

**Comment by yogeshojha** [comment]
This is available in reNgine 1.1. Thank you for the feature request. PDF reports are available and fully customisable
