### ISSUE TITLE
Improper UI placement

### ISSUE THREAD

**Issue by Bawer-Agirman** [yogeshojha/rengine#526]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary.

Cannot access UI elements in the dashboard on my laptop

Example : I don't see the system link in the header

### Steps to Reproduce

1. Installation on vps
2. go to vps ip address
3. Login 

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes 

### Technical details

As I said, I installed rengine on my vps (ubuntu os) and followed every step thoroughly. 
I ran in some issues with "python manage.py migrate" but still carried on as I couldn't resolve the problem even when running the command inside the web folder

![Capture d’écran (86)](https://user-images.githubusercontent.com/59149679/138145957-1c841e5b-651d-485f-9df8-5ed394e778f8.png)

**Comment by yogeshojha** [comment]
Hi, this is not related to reNgine. What do you mean by system link? Do you mean the address bar?

You must be in full-screen mode, press f11 to exit full-screen mode.

If the issue is otherwise, feel free to comment, I will re open this issue

**Comment by Bawer-Agirman** [comment]
Yes exactly in the address bar. I was already in full-screen mode when I made the screenshot. 

Also, when I'm switching in mobile view when resizing the window, i cannot scroll the menu.

It seems like I have responsiveness issue.
