### ISSUE TITLE
Add Custom Header Option

### ISSUE THREAD

**Issue by tejas15802** [yogeshojha/rengine#532]
**Is your feature request related to a problem? Please describe.**
It's is not actually a problem but some H1 and SRT program need either their Username in custom header field or authentication keys

**Describe the solution you'd like**
As all the request needs to have that header specified, maybe have a input field for that such that, it uses the information and adds it into all the request or specified domain maybe

**Comment by yogeshojha** [comment]
https://rengine.wiki/usage/scan_engine/#custom_header

Implemented in rengine 1.1
