### ISSUE TITLE
Bug - Many duplicates on vulnerability section

### ISSUE THREAD

**Issue by thistehneisen** [yogeshojha/rengine#537]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

For some reason same kind of vulnerability to exact same endpoint keeps on duplicating many times.

### Steps to Reproduce

Scan a target that has SSH (22) open with OpenSSH username enumeration < v7.3 vulnerability.
The issue will keep duplicating with the same info:
['SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.8']
OpenSSH before 7.3 is vulnerable to username enumeration and DoS vulnerabilities.

Additionally, the link on "Read more" is "https://127.0.0.1/scan/detail/['http://seclists.org/fulldisclosure/2016/jul/51'," which is invalid (127.0.0.1 is the server IP)

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

Operating latest rEngine version on latest Ubuntu Server.

**Comment by yogeshojha** [comment]
This is caused by Nuclei, reNgine just shows the data generated by nuclei.
