### ISSUE TITLE
Brother, this is a good idea, I hope it can be adopted

### ISSUE THREAD

**Issue by Oldman19** [yogeshojha/rengine#539]
I hope that some separate tools can be directly integrated in a simple way, so that users can simply add the functions they need

**Comment by tejas15802** [comment]
can you describe? @Oldman19

**Comment by Oldman19** [comment]
> 你能描述一下吗？@Oldman19

Of course, for example, you can add a store function: he can download a new tool from github and other places, and integrate this tool into rengine, which is convenient for users to use.

**Comment by yogeshojha** [comment]
This is coming in reNgine 1.1, But, it is difficult to support downloading tools for things like port scan or say vulnerability scan. But yes I am bringing support for the ability to add custom subdomain gathering tools, so you can download right from  UI.

**Comment by yogeshojha** [comment]
Custom tools in 1.1is available under tools arsenal section
