### ISSUE TITLE
Project Option

### ISSUE THREAD

**Issue by 0xtejas** [yogeshojha/rengine#540]
**Is your feature request related to a problem? Please describe.**
All the stats of scans mixes up in dashboard.

**Describe the solution you'd like**
- Maybe have an option to load rengine like a burpsuite where we use it like projects. 
- or make the dashboard stats more precise when there are more number of program being ran simultaneously

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:
