### ISSUE TITLE
Unable to delete scan results

### ISSUE THREAD

**Issue by tejas15802** [yogeshojha/rengine#541]
### Issue Summary

I tried deleting the scan results and it threw an error `Oops! Unable to delete Delete scan results`

#### SCREENSHOT 
![image](https://user-images.githubusercontent.com/47889755/143388096-6398b697-c539-4963-81ee-ccc38ba4c65f.png)

**Comment by quantumburnz** [comment]
I originally posted this in #561 but it probably makes more sense to put it here. I wanted to start fresh so I tried to delete my scan results but this doesn't work either - same issue as @tejas15802 .

![image](https://user-images.githubusercontent.com/26365765/150418171-8b9d0445-28c8-4502-b380-bc63a0a5113e.png)

**Comment by yogeshojha** [comment]
This is fixed in 1.1 Thank you guys for reporting this
