### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by zPrototype** [yogeshojha/rengine#548]
### Issue Summary

Running the install.sh script on my Ubuntu 20.04 VPS gives me the following error:
ERROR: Service 'celery' failed to build : Build failed

It also throws a bunch of other errors, here is the full output:
`#########################################################################
Please note that, this installation script is only intended for Linux
For Mac and Windows, refer to the official guide https://rengine.wiki
#########################################################################

Installing reNgine and it's dependencies

#########################################################################
Installing Docker...
#########################################################################
Docker already installed, skipping.

#########################################################################
Installing docker-compose
#########################################################################
docker-compose already installed, skipping.

#########################################################################
Installing make
#########################################################################
make already installed, skipping.

#########################################################################
Checking Docker status
#########################################################################
Docker is running.

#########################################################################
Installing reNgine
#########################################################################
Creating rengine_certs_run ... done
Creating new certificate for recon.example.com
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................
..................................................................................................................................
......................................++++
..................................................................................++++
e is 65537 (0x010001)
Signature ok
subject=C = US, ST = Georgia, L = Atlanta, O = reNgine, CN = recon.example.com
Getting CA Private Key
total 24
-rw-r--r--    1 root     root          1887 Dec 30 12:22 ca.crt
-rw-------    1 root     root          3247 Dec 30 12:22 ca.key
-rw-r--r--    1 root     root             3 Dec 30 12:24 ca.srl
-rw-r--r--    1 root     root          1801 Dec 30 12:24 rengine.pem
-rw-r--r--    1 root     root          1887 Dec 30 12:24 rengine_chain.pem
-rw-------    1 root     root          3243 Dec 30 12:24 rengine_rsa.key
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml build db web proxy redis celery celery-beat tor
db uses an image, skipping
redis uses an image, skipping
tor uses an image, skipping
proxy uses an image, skipping
Building celery
Sending build context to Docker daemon  7.771MB
Step 1/41 : FROM ubuntu:20.04
 ---> ba6acccedd29
Step 2/41 : LABEL     name="reNgine"     author="Yogesh Ojha <yogesh.ojha11@gmail.com>"     description="reNgine is a automated pipeline of recon process, useful for information gathering during web application penetration testing."
 ---> Using cache
 ---> 5065b1239394
Step 3/41 : ENV DEBIAN_FRONTEND="noninteractive"     DATABASE="postgres"
 ---> Using cache
 ---> 3816e565572b
Step 4/41 : ENV PYTHONDONTWRITEBYTECODE 1
 ---> Using cache
 ---> 364583f2509d
Step 5/41 : ENV PYTHONUNBUFFERED 1
 ---> Using cache
 ---> a18143558743
Step 6/41 : RUN apt update -y && apt install -y  --no-install-recommends     build-essential     cmake     firefox     gcc     git     libpq-dev     libpq-dev     libpcap-dev     netcat     postgresql     python3     python3-dev     python3-pip     python3-netaddr     wget     x11-utils     xvfb
 ---> Running in a3abd183e456

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Err:1 http://archive.ubuntu.com/ubuntu focal InRelease
  At least one invalid signature was encountered.
Err:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease
  At least one invalid signature was encountered.
Err:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease
  At least one invalid signature was encountered.
Err:2 http://security.ubuntu.com/ubuntu focal-security InRelease
  At least one invalid signature was encountered.
Reading package lists...
W: GPG error: http://archive.ubuntu.com/ubuntu focal InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-updates InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-updates InRelease' is not signed.
W: GPG error: http://archive.ubuntu.com/ubuntu focal-backports InRelease: At least one invalid signature was encountered.
E: The repository 'http://archive.ubuntu.com/ubuntu focal-backports InRelease' is not signed.
W: GPG error: http://security.ubuntu.com/ubuntu focal-security InRelease: At least one invalid signature was encountered.
E: The repository 'http://security.ubuntu.com/ubuntu focal-security InRelease' is not signed.
The command '/bin/sh -c apt update -y && apt install -y  --no-install-recommends     build-essential     cmake     firefox     gcc     git     libpq-dev     libpq-dev     libpcap-dev     netcat     postgresql     python3     python3-dev     python3-pip     python3-netaddr     wget     x11-utils     xvfb' returned a non-zero code: 100
ERROR: Service 'celery' failed to build : Build failed
make: *** [Makefile:25: build] Error 1
reNgine is installed!!!

#########################################################################
Creating an account
#########################################################################
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python3 manage.py createsuperuser
make: *** [Makefile:28: username] Error 1
Thank you for installing reNgine, happy recon!!`

Environment:
Ubuntu 20.04 on a VPS
uname -a output:
Linux vortex-server 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by aravindd007** [comment]
ERROR: Service 'celery' failed to build : Build failed

**Comment by climax0x** [comment]
[+] Building 0.0s (0/0)                                                                                                                                                                                            
http: invalid Host header
make: *** [Makefile:16: certs] Error 17

reNgine installation failed!!
