### ISSUE TITLE
vuln - broken keyword tags

### ISSUE THREAD

**Issue by noraj** [yogeshojha/rengine#552]
### Issue Summary

Keyword tags have extra `[` or `'` injected

![image](https://user-images.githubusercontent.com/16578570/147973755-e529d035-bb97-410b-9dfd-5b1c900f35b2.png)

![image](https://user-images.githubusercontent.com/16578570/147973921-cd2449db-cf37-4110-af51-fe835802df72.png)

### Steps to Reproduce

Launch any vulnerability scan and see the results

**Comment by yogeshojha** [comment]
This is fixed in reNgine 1.1. Thank you for reporting
