### ISSUE TITLE
vuln - broken description "Read More" link

### ISSUE THREAD

**Issue by noraj** [yogeshojha/rengine#553]
### Issue Summary

On the vuln list (https://my.host/scan/detail/vuln), some vulnerabilities have a cropped description and a _Read More_ button.

![image](https://user-images.githubusercontent.com/16578570/147974475-84492e43-04de-4457-b49d-90b6ffe2ea36.png)

But the _Read More_ link is totally broken: `https://my.host/scan/detail/['https://book.varnish-software.com/4.0/chapters/cache_invalidation.html',`.

### Steps to Reproduce

1. Launch a vulnerability scan

### Technical details

Docker version

**Comment by ShockwaveNN** [comment]
I think it's a bug so it reported in the right place

For example for vulnerability with title
`OpenSSH Username Enumeration <= v7.7`

I got a link on `Read more`:
`https://my.host/scan/detail/['https://github.com/sakurasamuraii/derailed`

**Comment by AbacusQ** [comment]
Still up.

**Comment by yogeshojha** [comment]
This should be fixed now in 1.1. Thanks for reporting
