### ISSUE TITLE
Delete Wordilst not working

### ISSUE THREAD

**Issue by cosmin91ro** [yogeshojha/rengine#555]
### Issue Summary

Error when trying to delete an wordlist I've previusly created

### Steps to Reproduce

1. Add any wordlist via Engine -> Wordlists menu-> Add New Wordlist button
2. Try to delete the wordlist using the Delete Wordlist button under the Action column
3. Notice the confusing message "Are you sure you want to delete this scanning engine?" and click Delete
4. Error message appear: "Oops! Unable to delete"
5. Wordlist is not deleted

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: Yes

### Technical details

Running rengine in docker on a Linux kali 5.10.0-kali9-amd64 host
<img width="1673" alt="Screenshot 2022-01-05 at 12 21 46" src="https://user-images.githubusercontent.com/13283745/148202054-bc4056cb-5902-4239-ac2b-fee9acb0aa29.png">
<img width="1681" alt="Screenshot 2022-01-05 at 12 22 42" src="https://user-images.githubusercontent.com/13283745/148202077-b998948b-4267-4d83-a1d3-a522aedf093d.png">

**Comment by Oxigen96** [comment]
I'm encountering the same behaviour

**Comment by Oxigen96** [comment]
A temporary workaround could be using the Django Administration Panel at /admin in order to delete wordlist objects.
![image](https://user-images.githubusercontent.com/38695526/153396530-2042c16f-b793-4197-a4b9-1b50782fec33.png)

**Comment by xnl-h4ck3r** [comment]
I was having the same issue too... Thanks @Oxigen96 !
