### ISSUE TITLE
"Server Error (500)" When Starting Scan

### ISSUE THREAD

**Issue by quantumburnz** [yogeshojha/rengine#562]
### Issue Summary

I created a custom scan engine that's the same as "reNgine Recommended" just without the Subdomain Discovery because I used a different tool for that. However, when I attempt to start the scan, I get a "Server Error (500)".  

### Steps to Reproduce

1. "Add New Engine"
2. Uncheck "Subdomain Discovery" and check "Port Scan"
3. Paste YAML from here: https://raw.githubusercontent.com/yogeshojha/rengine/master/web/tools/default_settings.yaml
4. Add Engine
5. "Quick Scan" a target and receive "Server Error (500)" from https://127.0.0.1:444/scan/start/64 (I'm port forwarding)
6. I receive the same "Server Error (500)" if I try to view a summary of the scan from https://127.0.0.1:444/target/summary/64

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
I looked at 'sudo make logs', but I'm not seeing much of interest.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes, I'm using a pull from 30Dec21.

### Technical details

Please list out any technical details such as operating environment.
Ubuntu 20.04.3 LTS
Docker version 20.10.12, build e91ed57

**Comment by quantumburnz** [comment]
I ran a 'sudo make restart' and then I was able to start a scan. Although, I'm still receiving an Error 500 if I try to view the Target Summary (https://127.0.0.1:444/target/summary/64). I can view detailed scan results though (https://127.0.0.1:444/scan/detail/7).

**Comment by quantumburnz** [comment]
I completely uninstalled, rm -rf /usr/share/rengine, re-pulled from git, and re-installed yesterday. I added one target, performed a scan, and I'm getting the same result. I get an Error 500 if I try to view the Target Summary (https://127.0.0.1:444/target/summary/1), but I can view detailed scan results (https://127.0.0.1:444/scan/detail/6).

**Comment by Seif-AW** [comment]
I solved the problem by manually doing `sudo make down` , then `sudo make up` and the scan started successfully

**Comment by harmony00x** [comment]
@Seif-AW I tried that but unfortunately I got the same error 500 when launching scan

**Comment by yogeshojha** [comment]
Hi, can you please attach the log, want to know why 50X occurs, looks like this is an very old issue, if you still face the error, feel free to reopen.

**Comment by HaxBunty** [comment]
![image](https://user-images.githubusercontent.com/113579343/220366986-be20e4de-be65-4cf1-9318-12ccda1a8d01.png)

**Comment by ablito19** [comment]
> I solved the problem by manually doing `sudo make down` , then `sudo make up` and the scan started successfully

It work, but for me , i need to do it every reboot, Otherwise it not working.
How can i fix it once.
