### ISSUE TITLE
How to elimate a single or multiple templates 

### ISSUE THREAD

**Issue by Deku-izuku-dotcom** [yogeshojha/rengine#565]
Hello 

Hope you're doing well 

My question : how to eliminate a single or multiple templates from nuclei ?? 

Best regards

**Comment by quantumburnz** [comment]
@Deku-izuku-dotcom - I'm just another user but have you seen this? https://rengine.wiki/usage/tool_conf/

You should also be able to edit the YAML for your Scan Engine, there's a "templates" parameter.
