### ISSUE TITLE
Old hakrawler Syntax - Needs Update

### ISSUE THREAD

**Issue by quantumburnz** [yogeshojha/rengine#566]
### Issue Summary
rengine/web/tools/get_urls.sh calls `hakrawler -plain -url $1 | grep -Eo $4 > $2/urls_hakrawler.txt`

If you see the https://github.com/hakluke/hakrawler page, the syntax has changed. The new syntax appears to be something like this:

`echo https://DOMAIN | hakrawler`
NOTE: Protocol seems to be required, I get no results if I leave https:// off.

### Steps to Reproduce

1. sudo docker exec -it rengine_celery_1 bash
2. hakrawler -plain -url DOMAIN
flag provided but not defined: -plain
Usage of hakrawler:
  -d int
        Depth to crawl. (default 2)
  -h string
        Custom headers separated by two semi-colons. E.g. -h "Cookie: foo=bar;;Referer: http://example.com/" 
  -insecure
        Disable TLS verification.
  -s    Show the source of URL based on where it was found (href, form, script, etc.)
  -subs
        Include subdomains for crawling.
  -t int
        Number of threads to utilise. (default 8)
  -u    Show only unique urls

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes, latest

### Technical details

Please list out any technical details such as operating environment.

**Comment by yogeshojha** [comment]
Fixed in 1.2.0
