### ISSUE TITLE
Feature - Redirect Std Error to a File

### ISSUE THREAD

**Issue by quantumburnz** [yogeshojha/rengine#567]
**Is your feature request related to a problem? Please describe.**
Tools change over time, which could break reNgine as seen in #566 .

**Describe the solution you'd like**
Perhaps a way to deal with this would be to redirect standard error to a file and notify the user when something was written to it, indicating a possible underlying tool failure. It would be important to annotate in the file while tool is causing the error since this likely wouldn't be in the stderr output. get_urls.sh could also include some command result error checking instead of just piping the results, and assuming the command worked properly.

**Comment by yogeshojha** [comment]
Std error will be now caught by rengine and if scan fails you'll be able to see the reason for error
