### ISSUE TITLE
Feature - Building upon other requests regarding target grouping

### ISSUE THREAD

**Issue by quantumburnz** [yogeshojha/rengine#570]
**Is your feature request related to a problem? Please describe.**
This is somewhat related to #200 submitted by @Regala and #472. However, I thought I should add another feature request as it doesn't align exactly with those.

I'm performing scanning on subdomains like the following:
abc.company.xyz
cde.company.xyz
fgh.company.xyz

However, I don't want to scan company.xyz. Therefore, I can't create a target for company.xyz and add the others as subdomains. I must create individual targets for each of the subdomains.

**Describe the solution you'd like**
It would be nice to have the option to group subdomains but not scan the parent domain. Similar to what @pichik described in #472, perhaps being able to import targets into an organization would provide a good solution. Although, I still think there should be a way for me to group subdomains under one "Target" so I don't have a ton of different targets.

**Describe alternatives you've considered**
I considered creating a target of company.xyz and providing the subdomains I'm interested in to the "Import Subdomains" field and then adding company.xyz to the "Out of Scope Subdomains"; however, I reviewed tasks.py, and it doesn't appear this would work. `out_of_scope_subdomains` is only used for the purposes of `subdomain_scan`.

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) 
https://rengine.wiki/changelog/#200
