### ISSUE TITLE
Bug - Open Ports Not Displayed in Scan Results

### ISSUE THREAD

**Issue by quantumburnz** [yogeshojha/rengine#572]
### Issue Summary
I have a target where Nabuu identified open ports and wrote them to ports.json. However, in the Web UI, no results are displayed for the scan.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?
My target doesn't have 80 or 443 open so I'm not sure if this is a dependency on the results of httpx but if there are open ports discovered, I'd expect this to show up in the scan result.

I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes, I'm using a pull from 30Dec21.

### Technical details

Ubuntu 20.04.3 LTS
Docker version 20.10.12, build e91ed57

**Comment by yogeshojha** [comment]
There was a known issue with naabu output and has now been resolved in 1.1
