### ISSUE TITLE
Feature - Improving Scheduled scan by specifying time and also notifying about the results

### ISSUE THREAD

**Issue by thistehneisen** [yogeshojha/rengine#581]
**Is your feature request related to a problem? Please describe.**
Currently scheduled scan can only be specified to run every X minutes/hours/days etc. It would be great if a time for the scan to run could also be specified, e.g. 5 AM.

**Describe the solution you'd like**
Additional dropdown or input to specify what time the scan should run every X minutes/hours/days.

**Describe alternatives you've considered**
Probably would have to create manual cronjob running the task via CLI.

**Additional context**
Also, it appears that Scheduled Tasks are not being notified via Slack or other specified notification channels. I'd expect for them to be, or at least for the option to be toggleable.

**Comment by thistehneisen** [comment]
@xnl-h4ck3r thank you, much appreciated.

**Comment by psyray** [comment]
Does this function do the job ?
![image](https://github.com/yogeshojha/rengine/assets/1230954/0be32493-3c8c-4c5f-b43c-80163a4e8b15)

Notification message has been fixed in 2.0 with #742 complete scan rewrite
