### ISSUE TITLE
Bug - sorted_subdomain_collection.txt file sent to Discord always contains the string "subdomain" as an entry

### ISSUE THREAD

**Issue by xnl-h4ck3r** [yogeshojha/rengine#582]
### Issue Summary

When a sub domain scan completes and sends the notification to Discord with the `sorted_subdomain_collection.txt` file, this file always contains the line`subdomain` in the list of subs.

### Steps to Reproduce

1. Set up notification for Discord with the `Send Scan Output (e.g. Subdomain gathered file) ` option checked.
2. Add a target and start a Quick Scan
3. When the scan completes, look at the file sent to Discord and see the entry `subdomain`. It seems like it is included the column header or something.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

Installed on Ubuntu 20.04.3 LTS, 64-Bit

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
