### ISSUE TITLE
Bug - dirsearch.py does not recognise the `--recursion-depth` parameter

### ISSUE THREAD

**Issue by xnl-h4ck3r** [yogeshojha/rengine#585]
### Issue Summary

reNgine uses https://github.com/maurosoria/dirsearch and treis to use the parameter `--recursion-depth` whcih does not exists on the latest version of dirsearch.py

### Steps to Reproduce

1. Create a target and engine with **Directory and Files Search** enabled.
2. Run `sudo make logs` and start a scan of the target.
3. The logs show an error `dirsearch.py: error: no such option: --recursion-depth` when it tries to use `dirsearch.py`

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

reNgine calls `python3 /usr/src/github/dirsearch/dirsearch.py -u https://target.com:443 -w /usr/src/github/dirsearch/db/dicc.txt --format json -o /usr/src/scan_results/target.com_372144022254/dirs.json -e php,git,yaml,conf,db,mysql,bak,asp,aspx,txt,conf,sql,json -t 100 --random-agent --follow-redirects --exclude-status 403,401,404 -X jpg,png,jpeg,gif,tiff --recursion-depth 1 --recursion-depth 1` which fails because `--recursion-depth` isn't valid. I'm not sure hwy it passes the paramater twice either.
The latest version of dirsearch.py seems to use `--max-recursion-depth` instead

UPDATE:
The code is in `rengine/web/reNgine/task.py` (duplcated which is why the paramater is added twice). If it's changed from `--recursion-depth` to `--max-recursion-depth` then dirsearch works, but then another error occurs: `/usr/src/scan_results/logs is a file, should be a directory` so still nothing is logged

UPDATE: 
The error `/usr/src/scan_results/logs is a file, should be a directory` is happening because it is default the `--log` parameter to the name `logs` in scan_results directory for some reason. By adding `--log=test` for example, this correctly writes the logs (whcih I assume aren't used anyway) and correctly outputs the dirsearch info in the Directories section of the scan history.

**Comment by s7safe** [comment]
Hi @xnl-h4ck3r,
I also encountered this problem. How can I solve the second problem (log) and modify it in a file

**Comment by xnl-h4ck3r** [comment]
Hi @s7safe 
You just need to add `--log=test` into the command somewhere, so for example in `rengine/web/reNgine/task.py` change the line 
` dirsearch_command += ' --random-agent --follow-redirects --exclude-status 403,401,404'`
to
` dirsearch_command += ' --log=test --random-agent --follow-redirects --exclude-status 403,401,404'`

**Comment by s7safe** [comment]
Thank you, you'vebeen most helpful.

**Comment by 0-0eth0** [comment]
Hi i have issued a pull request [Here](https://github.com/yogeshojha/rengine/pull/564) solution let the @yogeshojha approve & merge into the main branch

**Comment by arthur4ires** [comment]
HI, i hope you are fine :)

@0-0eth0 

You just need to add --log=test for the solution to be complete.

**Comment by yogeshojha** [comment]
This is now replaced with ffuf.
