### ISSUE TITLE
Unable to save subfinder configuration

### ISSUE THREAD

**Issue by Chr1sto-sec** [yogeshojha/rengine#590]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

When I try to save the configuration for Subfinder, Internet 500 is reported
How can I solve this problem

### Steps to Reproduce

![图片](https://user-images.githubusercontent.com/51648173/155195095-25ec5f17-587b-4343-8e6f-f46e007ef9f8.png)
![图片](https://user-images.githubusercontent.com/51648173/155195234-ad65a7ca-4954-4ae6-a0b3-cdd03d95664b.png)

### Technical details

Ubuntu 20.04.3

**Comment by 0-0eth0** [comment]
Hi try this,

sudo mkdir -p /var/lib/docker/volumes/rengine_tool_config/_data/subfinder; touch /var/lib/docker/volumes/rengine_tool_config/_data/subfinder/config.yaml


Regards
