### ISSUE TITLE
ModuleNotFoundError: No module named 'cryptography' - dirsearch 

### ISSUE THREAD

**Issue by arthur4ires** [yogeshojha/rengine#592]
Hi, hope you are well :)

I'm experiencing issues with rengine's docker in the brutforce process, I realized I wasn't getting endpoints.

I went to test the command manually inside docker and got the missing dependency as you can see in the screenshot.

![img](https://i.imgur.com/0ll9btI.png)

**Comment by arthur4ires** [comment]
Access docker manually with:
```
sudo docker exec -it ID_DOCKER /bin/bash
```
Run the following command:
```
pip3 install cryptography
```
Problem solved :)

**Comment by yogeshojha** [comment]
This is now replaced with ffuf so closing this
