### ISSUE TITLE
Feature - Starting a Scan with Acunetix Api

### ISSUE THREAD

**Issue by secfb** [yogeshojha/rengine#596]
First of all, I would like to state that your vehicle is very beautiful. Really good health. Can a scan be started using acunetix api to perform automated vulnerability scanning with this tool? It would be really nice if we could start a scan for the subdomains found.

The two best projects for scanning using the Acunetix api are as follows.
https://github.com/WazeHell/acunetix-python
https://github.com/test502git/awvs14-scan

If something like this is done, the project would be really good.

**Comment by yogeshojha** [comment]
Acunetix is a paid tool and is not in the priority at the moment.
