### ISSUE TITLE
Feature - Add Download Subdomain based on Filters

### ISSUE THREAD

**Issue by serrapa** [yogeshojha/rengine#600]
When dealing with targets that have a ton of subdomains and you have to download them, there's no possibility to download directly those filtered.

It would be nice to add a button to download only those subdomain got from the filters you type on the "search" bar.

For example add a button "Download based on filters" among the other download choices. In the figure below, only subdomains with http_status equal to 200 will be downloaded

![image](https://user-images.githubusercontent.com/26407305/158401519-4bb9b178-72d4-400f-aa03-c8707d52db46.png)

**Comment by yogeshojha** [comment]
Yay, This is available in reNgine 1.1. Thank you for the feature request.
