### ISSUE TITLE
Bug - Badges not working in Target Summary Page

### ISSUE THREAD

**Issue by serrapa** [yogeshojha/rengine#602]
### Issue Summary

When you open a target summary, the Endpoint, Ports and IP Address badges (Subdomain tab) are not working because of the lack of the proper functions defined in the details_scan.js: _get_ip_details_, _get_endpoint_models_ etc...

In fact, after clicking a badge, an error raises in the console:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/26407305/160244646-c634005e-c78f-4621-8f13-9cd7992d6bfa.png">

That doesn't happen while you are reviewing a scan (/scan/details/x) instead. 

### Steps to Reproduce

1. Open a target summary
2. Go in the subdomain tab
3. Click a badge (ie. IP Addresses)

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

The javascript _details_scan.js_ containing all functions for badges is not included in the target summary html, but even when including it, the issue remains because the api calls return nothing, so not showing any errors in console but not open the small window as it happens from a scan summary.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: **yes**

**Comment by yogeshojha** [comment]
fixed in 1.1.
