### ISSUE TITLE
Feature - Uninstall / Reinstall rEngine

### ISSUE THREAD

**Issue by thistehneisen** [yogeshojha/rengine#603]
**Is your feature request related to a problem? Please describe.**
Would like to understand how to properly uninstall and make blank installation of rEngine.

**Describe the solution you'd like**
Due to some issues (https://github.com/yogeshojha/rengine/issues/588) taking long time to resolve, a faster way would be to create a new blank rEngine installation on the same host as before. Would like to understand how the process is done properly.

**Describe alternatives you've considered**
Reinstalling the whole machine, but that's not going to be possible in most cases.

**Additional context**
There's bugs happening in rEngine and that's fine, but would like a way to quickly reinstall it when such occurs.

**Comment by psyray** [comment]
https://rengine.wiki/uninstall/
