### ISSUE TITLE
hakrawler not working on main domain - it must specify protocol

### ISSUE THREAD

**Issue by grittyninja** [yogeshojha/rengine#623]
### Issue Summary

hakrawler not working - it must specify protocol

### Steps to Reproduce

When I am scanning the domains, I track which tools is called and what its output. when rengine doing url discover, it called hakrawler with this command 

`echo [domain_target] | hakrawler | grep -Eo 'https?://([a-z0-9]+[.])*[domain_target].*' > /usr/src/scan_results/[domain_target]_718315682966/urls_hakrawler.txt`

refer to this code
https://github.com/yogeshojha/rengine/blob/master/web/reNgine/tasks.py#L1354

on hakrawler documentation, https://github.com/hakluke/hakrawler you must specify protocol (http or https)

for example

`echo "https://domain.target" | hakrawler`

### Technical details

I think the problem is on this code 
https://github.com/yogeshojha/rengine/blob/master/web/reNgine/tasks.py#L1335-L1341

you don't specify protocol for domain if the domain is MAIN DOMAIN

**Comment by Ph33rr** [comment]
Hello you can use deep mode in config file

  intensity: normal
  # intensity: deep

fast fix:
https://github.com/yogeshojha/rengine/pull/624/commits/274317e11ea84d85ea9398fbd0e75b618b0ceab1

**Comment by yogeshojha** [comment]
Fixed on 1.2.0
