### ISSUE TITLE
Added status code,title,content length via new and interesting subdomains displayed by discord webhook

### ISSUE THREAD

**Issue by z7701858** [yogeshojha/rengine#626]
**Is your feature request related to a problem? Please describe.**
When discord notifies me of new sub-domains I need to copy them and do preliminary scouting through httpx etc. to determine the valuable ones, which is too tedious

**Describe the solution you'd like**
Added status code,title,content length via new and interesting subdomains displayed by discord webhook

**Comment by psyray** [comment]
Fixed by https://github.com/yogeshojha/rengine/pull/963
https://rengine.wiki/changelog/#200
With the new @ocervell PR https://github.com/yogeshojha/rengine/pull/742 httpx is systematic
