### ISSUE TITLE
Bug -scan all web service in a single host #  of Bug

### ISSUE THREAD

**Issue by test502git** [yogeshojha/rengine#629]
It seems that rengine will not perform path discovery on different ports of a single host. For example, port 80 and port 8888 opened on a host, rengine will only perform path discovery on 80, and 8888 will be left.

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
