### ISSUE TITLE
stopping the reengine_web_1 container will create a 502 bad gateway

### ISSUE THREAD

**Issue by melmel27** [yogeshojha/rengine#634]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

when i try to restore the backup sql database from old server to new server via rengine wiki guide it doesn't work. because when rengine_web_1 is stopped and goes to the next step make build && make up server will show 520 bad gateway. I thought it was a problem in the database, it wasn't. this problem occurs due to stop rengine_web_1

### Steps to Reproduce

1. clean rengine and install again
2. go to the dashboard and make sure everything is working
3. run the command sudo docker stop reengine_web_1
4. then run the command sudo docker start reengine_web_1
5. server will show 502 bad gateway

### Technical details

Ubuntu 18 vps 8cpu 32GB ram

**Comment by yogeshojha** [comment]
Fixed on 1.2.0
