### ISSUE TITLE
Feature - Support OIDC/SAML SSO

### ISSUE THREAD

**Issue by rucciva** [yogeshojha/rengine#637]
**Is your feature request related to a problem? Please describe.**
We would love to add reengine to our existing devsecops suite. It would be nice if reengine could integrate with OIDC or SAML SSO so that we could re-use our existing credential to access reengine

**Describe the solution you'd like**
Implement OIDC or SAML client library

**Describe alternatives you've considered**
Plan to disable login in reengine so that we could use reverse-proxy middleware to integrate with OIDC and avoid double login, but can't seem to find the method to do so.

**Additional context**
none

**Comment by yogeshojha** [comment]
Unfortunately We do not have any plans for OIDC or SAML SSO. Thank you for requesting this though.
