### ISSUE TITLE
Feature - vulnerability action

### ISSUE THREAD

**Issue by noraj** [yogeshojha/rengine#642]
It seems the only action available at `/scan/detail/vuln` is **Report to HackerOne**. I may be wrong but I was unable to perform simple actions like remove a vulnerability or change it's status to false positive or fixed.

Also while there is a checkbox to select multiple vulnerabilities there is no batch action to run on multiple vulns.

**Comment by yogeshojha** [comment]
Remove vulnerability is not implemented as of now, this requires a bit of workaround. Targeting Vulnerability actions for 2.0.0

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:
