### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by ubaidahmedIN** [yogeshojha/rengine#654]
**Is your feature request related to a problem? Please describe.**
I have observed that there is no option available to track the users created by us and to revoke the access of any user.

**Describe the solution you'd like**
It will be really nice to have a user management page from where we can create/remove users and mark users as valid/invalid

**Comment by GlitchWitch** [comment]
Is there currently a way to add an additional user? I did not see anything in the documentation, and the link on the login page only goes to the root of the wiki.

**Comment by ocervell** [comment]
Nope, we can only add super users for now. You can create another one with `docker-compose exec python3 manage.py createsuperuser <USERNAME>`

**Comment by GlitchWitch** [comment]
Thanks @ocervell, this is more or less what I ended up doing.

```
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python3 manage.py createsuperuser <USERNAME>
```

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:
