### ISSUE TITLE
Bug -  Repeat scan

### ISSUE THREAD

**Issue by testa010** [yogeshojha/rengine#656]
### Issue Summary

When scanning multiple targets, some targets give errors.

### Steps to Reproduce
Some targets automatically start the next scan after the scan is complete.
<img width="220" alt="aaaaaa" src="https://user-images.githubusercontent.com/64741288/175798394-061f8b55-127a-48bc-9503-571f4b21f262.png">
<img width="218" alt="bbbbb" src="https://user-images.githubusercontent.com/64741288/175798502-0d3c9dcc-4c95-49c6-bded-94ede4c0a80a.png">
<img width="224" alt="cccccccc" src="https://user-images.githubusercontent.com/64741288/175798537-1fa04d1a-4b40-441c-bd5e-f17c19582d5e.png">

**Comment by yogeshojha** [comment]
This is weird @testa010 This problem still exists?

**Comment by testa010** [comment]
hi @yogeshojha sorry for not replying for a long time. I reinstalled rengine v2 today and found that this issue still exists and some scanning tasks will be repeated. Can you reopen this issue?
![image](https://github.com/user-attachments/assets/a2f61008-84a1-4bc9-9d8c-0a5627ca518a)
