### ISSUE TITLE
Feature - Allow IP for scanning

### ISSUE THREAD

**Issue by beerandgin** [yogeshojha/rengine#658]
**Is your feature request related to a problem? Please describe.**
Allow to scan IP and IP prefix, even if there is no DNS records.

**Describe the solution you'd like**
Able to add IP address and its prefix for scanning

**Describe alternatives you've considered**
Manual CLI using same tools used by rengine

**Comment by Rainerhu** [comment]
I also need it....

**Comment by greggel** [comment]
I also need this, many times I want to know details about an IP that may not resolve to a dns/hostname.

**Comment by RoiSec** [comment]
please merge https://github.com/yogeshojha/rengine/issues/678

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
