### ISSUE TITLE
Bug - Port Scanning Failed-Subdomain matching query does not exist

### ISSUE THREAD

**Issue by z7701858** [yogeshojha/rengine#659]
### Issue Summary
Port Scanning Failed
Error: Subdomain matching query does not exist.

### Steps to Reproduce

1. When I am scanning the domains vulnweb.com, this happens
2. I haven't changed anything, the configuration used for scanning is the default configuration for full scan
### Technical details
ubuntu

**Comment by ocervell** [comment]
Should be fixed in https://github.com/ocervell/rengine/pull/1. Please wait for it to be integrated in reNgine.

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
