### ISSUE TITLE
Bug - Screenshots and Subdomains are not loading after scan 

### ISSUE THREAD

**Issue by hailstorm1422** [yogeshojha/rengine#663]
### Issue Summary

After initiating a scan, the Subdomains and Screenshots section is not populating data under the endpoint (/scan/detail/3) 

### Steps to Reproduce

1. Start a scan
2. Click on Scan History > view results >Subdomains/Screenshots

<img width="1403" alt="image" src="https://user-images.githubusercontent.com/6916721/178094905-921c6623-b0c4-4791-a7b9-21b4d677762f.png">

**Comment by tejas15802** [comment]
I'm able to

**Comment by yogeshojha** [comment]
Fixed in 1.3.0
