### ISSUE TITLE
Feature - Sort subdomains by alphabet

### ISSUE THREAD

**Issue by moayadalmalat** [yogeshojha/rengine#673]
If someone has too many subdomains, it could be good to sort them by alphabet [a-z] in order to know if the e.g. ffuf or any other tool still needs time during the processes.

I launch a `ps aux | grep ffuf` command in order to see which URL running on ffuf... and since no alphabet, the recon took too time (until I thought it was doing a loop) then I killed the process after 4 days.

i.e, it's a good idea to sort the subdomains/urls by alphabet in order to see if still in https://a.example.com or https://z.example.com.

My guessing is during collecting the urls/subdomains, just use `| sort -u` this will sort from 0 to z.

**Comment by yogeshojha** [comment]
Hi @moayadalmalat 

I am not sure if I understood this, you mean while running ffuf we need to sort?

I think we do this already, there is a file called sorted_subdomains.txt that is generated once subdomain scanning is done which also has -u flag, and this is further used for all other port or nuclei or ffuf

**Comment by moayadalmalat** [comment]
Hello,

Thank you for your reply!

After more digging, I saw that the ffuf gets the list in alphabet [a..z] thank you again.

I will go ahead and close this issue right now.

Have a nice weekend!
