### ISSUE TITLE
Feature - Adding module for Netlas.io, domainiq.com, builtwith.com and whoisxmlapi.com

### ISSUE THREAD

**Issue by 7onez** [yogeshojha/rengine#676]
These Netlas.io, domainiq.com, builtwith.com and whoisxmlapi.com API modules will help to gather information on a target and good for threat intel.

Thank you

**Comment by yogeshojha** [comment]
Hi @7onez Looks like most of these are paid, can you please help me with free-to-use APIs/service providers so that I can integrate? Paid tools are a problem because not everyone can afford to use them.

**Comment by 7onez** [comment]
Dear Yogeshojha/Rengine,

I think Netlas.io is a great option to be integrated since it's offering
many free options for a free user account. Otherwise, I would love to see
that Dalfox can be also integrated for XSS scan.

Thank you for the great work that you are doing for cybersec society.
Best regards,

Hieu Ngo (Hieupc) - Cybersecurity researcher at Viet Nam's NCSC, APWG,
VirusTotal, URLScan and Scamadviser

**Comment by ocervell** [comment]
We can consider using paid tools that would be enable with an API key in the config.

But before this, let's answer these questions: 

- [ ] Which features do those services bring that we don't already have ?
- [ ] Is there an Open-Source alternative that would fill the same purpose ?

Regarding `dalfox`, it looks pretty good, it seems well-maintained and feature-rich. We are currently using `naabu` for vulnerability scans and it has XSS templates, so we should find out which features dalfox has that naabu doesn't to see if it's a good candidate to be added to reNgine.

**Comment by 7onez** [comment]
For Netlas, it offers to search sensitive secrets or keywords inside HTML
body by using: http.body (I found out the same time the Free account offers
most of tools that a bug hunter needs). As far as I know, there is no
alternative like this for open source. You can contact the owner of Netlas
for more information: Artur Kotylevskiy email at: ***@***.***

To me and many others that I know, Dalfox is way better than many other XSS
scanners.

Please have some considerations.

Thank you,

Hieu Ngo




Best regards,

Hieu Ngo (Hieupc) - Cybersecurity researcher at Viet Nam's NCSC, APWG,
VirusTotal, URLScan and Scamadviser

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:

**Comment by 7onez** [comment]
Thank you for your response
