### ISSUE TITLE
Feature - Support IP's scan without domain

### ISSUE THREAD

**Issue by roisec** [yogeshojha/rengine#678]
Hi 
I would like to scan the range/segment of IPs without an doamins. 
First, scan ports and then, scanning nucleli and other engines

**Comment by italianfrost** [comment]
This would be great to have!!

**Comment by micobal** [comment]
@yogeshojha please also consider the ability to group a list of IPs (csv, json) under the same target, with the ability to fetch the IP list by running a curl or bash command, this is really useful for regular scanning.

**Comment by atolac** [comment]
@yogeshojha please also consider the ability to group a list of IPs (csv, json) under the same target, with the possibility to fetch the IP list by running a curl or bash command. this is especially useful during regular scans.

**Comment by ocervell** [comment]
Implemented in the PR above. You can use mixed lists of IPs, Domains, Subdomains in that version. It should be integrated in the v2 of reNgine planned end of this year.

**Comment by roisec** [comment]
@ocervell , wow it's looks much better. 
Did you opened a pull request?

**Comment by yogeshojha** [comment]
This is now a part of reNgine 2.0

Thank you :pray:
