### ISSUE TITLE
Feature - about add External tool

### ISSUE THREAD

**Issue by ghost** [yogeshojha/rengine#682]
when we add External tool

<img width="837" alt="Snipaste_2022-08-16_04-30-43" src="https://user-images.githubusercontent.com/106905547/184713115-3c1800fc-78b7-4e37-8c3a-79fc47c6c997.png">

I want to know where to check the shell details
Which container shell you need to enter to view?
and How do I check to make sure External tool is installed successfully?

Waiting for a reply:construction:

**Comment by ocervell** [comment]
`docker-compose logs -f web` should give you the info you need. If you are not using docker-compose, you need to find the container id for the web service, and run `docker logs -f <CONTAINER_ID>`
