### ISSUE TITLE
Feature - Nuclei vulnerability not scanned the open ports

### ISSUE THREAD

**Issue by roisec** [yogeshojha/rengine#687]
Hi,
I encouraged a missing vulnerability scan by Rengine.
Nuclei will not scan the endpoints/assets identified by open ports scan.
I would like to scan services other than HTTPS. for example 9090.
There is a JSON file with open ports, all that we need to scan all the endpoints within this JSON during the vuln scan engine.

**Comment by ocervell** [comment]
Fixed in https://github.com/ocervell/rengine/pull/1, you might have to wait until we release v2 end of this year.

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
