### ISSUE TITLE
scans fail frequently

### ISSUE THREAD

**Issue by Killua-Zoldyck-1** [yogeshojha/rengine#689]
Scan Failed due to: [Errno 2] No such file or directory: '/usr/src/scan_results/in-the-dating.com_993012857593/ports.json'

I've done all I can think of to fix the error, but, since the files are in so many different directories, and I have no idea what does what, I'm unable to fix the issue myself,or determine the cause.
I'm using Kali Linux if that helps.

**Comment by Killua-Zoldyck-1** [comment]
> wave Hi @Killua-Zoldyck-1, Issues is only for reporting a bug/feature request. Please read documentation before raising an issue https://rengine.wiki For very limited support, questions, and discussions, please join reNgine Discord channel: https://discord.gg/azv6fzhNCE Please include all the requested and relevant information when opening a bug report. Improper reports will be closed without any response.

Since it seems to be a constant issue occurring on multiple operating systems, I figured it should be reported as a bug.
Sorry if that isn't right.

**Comment by m00tiny** [comment]
> Scan Failed due to: [Errno 2] No such file or directory: '/usr/src/scan_results/in-the-dating.com_993012857593/ports.json'
> 
> I've done all I can think of to fix the error, but, since the files are in so many different directories, and I have no idea what does what, I'm unable to fix the issue myself,or determine the cause. I'm using Kali Linux if that helps.

Looks like your port scanner is not running, or not writing results, as well, another tool is looking for those results. No idea how you got there. But, it doesn't happen if you're using a supported OS and following the documentation..
Need output of the install script, from there we can take a look at your scan engines, etc.. but really.. There's so many things that could go wrong here.. if your only effort to raise an issue is this.. go find one of your linux friends and bother them about it.

Don't be a help vampire on the issues board.

**Comment by industrialarmy** [comment]
Still have the same issue with different versions of ubuntu

**Comment by chosenonehacks** [comment]
This is a bug for sure, got the same error on various targets.

**Comment by JamVayne** [comment]
when i use <screenshot + portscan> ,i got the same error
but when i use <subdomain discovery + screenshot + portscan>, it work fine.
this work for me, hope to help you

**Comment by noraj** [comment]
portscan fail or success on the following situations:

- :x: portscan + screenshot
- ✅ portscan
- :x:  portscan + screenshot + osint
- ✅ portscan + screenshot + subdomain

**Comment by ad0nis** [comment]
This appears to be the same issue as in https://github.com/yogeshojha/rengine/issues/674
