### ISSUE TITLE
Error while installation (hakrawler)

### ISSUE THREAD

**Issue by zwni** [yogeshojha/rengine#691]
### Issue Summary

Error while installing:

<img width="901" alt="image" src="https://user-images.githubusercontent.com/79983467/186895239-b8bb04dd-ce55-483e-9ea7-2121fb5d0862.png">

### Steps to Reproduce

1. sudo ./install.sh
2. getting the error

I also separately installed hakrawler but the installation is still failing

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine

**Comment by Hacker-trademark** [comment]
i got same error in rengine. please help me.

**Comment by iamxhunt3r** [comment]
Hey i got similar issue

best way is to downgrade go version to 1.19

Go to web/Dockerfile
Edit it 

RUN wget https://golang.org/dl/go1.19.linux-amd64.tar.gz
RUN tar -xvf go1.19.linux-amd64.tar.gz
RUN rm go1.19.linux-amd64.tar.gz
RUN mv go /usr/local
