### ISSUE TITLE
Feature - Checks to avoid repeated content

### ISSUE THREAD

**Issue by cbk914** [yogeshojha/rengine#692]
The visualization of the vulnerabilities consumes a lot of resources.
The endpoints counter grows excessively without need.

Checking if the vulnerabilities and endpoints are already present in the database, could avoid the consumption of unnecessary resources.

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742 and #1012 

https://rengine.wiki/changelog/#200
