### ISSUE TITLE
Bug - Unable to retrieve whois data

### ISSUE THREAD

**Issue by therob89** [yogeshojha/rengine#693]
### Issue Summary

Unable to retrieve whois data

### Steps to Reproduce

1. When I am scanning the domains, this happens upon clicking on "View Whois"

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes (Release 1.3.2)

<img width="565" alt="image" src="https://user-images.githubusercontent.com/8765735/186962615-5d98eda6-1b57-4926-a352-9f9bf6dd1a29.png">

### Technical details

The issue is present on the last release (1.3.2) and a Docker Environment (setup as reported in the documentation).

<img width="653" alt="image" src="https://user-images.githubusercontent.com/8765735/186962133-a0b59187-e8d5-462f-b0af-1a3f968be705.png">

To fix this kind of issue I made the following changes on asset -> `/usr/src/app/reNgine/common_func.py`
[common_func.txt](https://github.com/yogeshojha/rengine/files/9435317/common_func.txt)

**Comment by noraj** [comment]
Same on the scan finding page, you have `WHOIS Record Has not been fetched, would you like to fetch it now?` which triggers `javascript: fetch_whois('example.org', true);)` but you get indefinitely ` Fetching WHOIS records, Please wait...`.

**Comment by surajchapagain20** [comment]
Whois is working but in Domain .com.np is not working
