### ISSUE TITLE
amass not executed when performing subdomain scan

### ISSUE THREAD

**Issue by NightRang3r** [yogeshojha/rengine#694]
### Issue Summary

Hi,

I have noticed that amass is not executed when  performing a subdomain scan .

The 'default_subdomain_tools' list contains the value 'amass' where the 'tools" variable contains tools from the yaml file which are 'amass-active' or 'amass-passive'

https://github.com/yogeshojha/rengine/blob/f31e7060dbc2e39442ee6b5f7648fb14137910f6/web/reNgine/tasks.py#L514

https://github.com/yogeshojha/rengine/blob/f31e7060dbc2e39442ee6b5f7648fb14137910f6/web/reNgine/tasks.py#L526

The following if statement will not find 'amass-active' or 'amass-passive' in the 'default_subdomain_tools' list thus it will not execute amass.

https://github.com/yogeshojha/rengine/blob/f31e7060dbc2e39442ee6b5f7648fb14137910f6/web/reNgine/tasks.py#L549

### Steps to Reproduce

1. Start docker logs ``` docker logs --follow rengine_celery_1```
2. Start a subdomain scan 
3. You should notice that amass is not executed

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

**Comment by 3ntr0phy** [comment]
Can you please fix this issue or modify the wiki ?
There is contradictory information and apparently we can only run amass in passive settings?
Could you please clarify it?
Cheers :)

**Comment by 0xb33** [comment]
I found a temp fix for running both amass-passive and amass-active.
it works for me.

Take a look : https://github.com/0xb33/rengine/commit/a6a1f7acab2184a795c2153af1726a89069450e2

Cheers :)

**Comment by psyray** [comment]
Could you try on v2 and reopen issue if problem persists
