### ISSUE TITLE
New features: subdomain S3 bucket and Subdomain takeover

### ISSUE THREAD

**Issue by 7onez** [yogeshojha/rengine#699]
A good tool like https://github.com/nuncan/slurp and also integrate a subdomain takeover tools like: 
https://github.com/thevillagehacker/Bigfoot/blob/main/bigfoot.sh &  https://github.com/mohsinenar/agent_subjack & https://github.com/LukaSikic/subzy

Please consider to integrate. Thanks

**Comment by ocervell** [comment]
`slurp` hasn't been updated for 5 years so I doubt we will add it. Same for `subzy`. However we can consider the others if they provide the features we need.

**Comment by psyray** [comment]
s3 bucket scan implemented in v2
![image](https://github.com/yogeshojha/rengine/assets/1230954/fee9bdb9-7697-471a-a132-2653ca08054f)
