### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by pavanreddi** [yogeshojha/rengine#700]
Thanks, I want to download the full data image for analysis. I am unable to download in clear format of entire image. can you please help. 

![image](https://user-images.githubusercontent.com/23329957/189310085-386287e9-0f03-4558-a606-e8ae232d7519.png)

**Comment by ocervell** [comment]
Not sure if we can render it as an image, would need to check how it works in the frontend plugin that does the visualization. In the meantime, just use greenshot and take the image yourself ?
