### ISSUE TITLE
Option to download IPs, Ports and Technologies as text file

### ISSUE THREAD

**Issue by Adelante10k** [yogeshojha/rengine#703]
When you go to Targets > Target Summary at the bottom you have:
IP Addresses, Discovered Ports, Discovered Technologies.

**There must be an option to download the list of IPs! - Each IP listed on a new row!**

### Case study:
I have a target that has discovered 890 IPs.
Assume the IPs are:
`1.0.0.1`    `1.1.1.1`   ` 8.8.8.8`    ` 8.8.4.4`
If I copy this list of IPs from the mouse and want to put it into a text file (to use in the attack surface stage with another tool), the IPs are literally PASTED (spliced), i.e. IPs are literally glued into one line:
`1.0.0.11.1.1.18.8.8.88.8.4.4`
And copying 890 IPs one by one is madness.

The scenario is so bad that you can't use grep, sed or awk to solve the problem.

This option should also be applied to Technologies and Ports.

A big plus would be to have a checkbox like "Ignore Info", so there should be a checkbox like "Ignore CDN IPs".

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
