### ISSUE TITLE
Bug - Backup Engine documentation needs updating

### ISSUE THREAD

**Issue by IOCsec** [yogeshojha/rengine#704]
### Backup Reingine

In the [official documentation on Backup Reingine](https://rengine.wiki/backup/) it is specified (14 September 2022):
`sudo docker exec -t rengine_db_1 pg_dumpall -c -U {DB_USER} > rengine_dump_.sql`

**It will display the error:**
`Error: No such container: rengine_db_1`

**If you list you Docker containers:**
`docker container ls --all --no-trunc`
you will find that `rengine_db_1` has been renamed to `rengine-db-1`

**Now if you run the backup command:**
`sudo docker exec -t rengine-db-1 pg_dumpall -c -U {DB_USER} > rengine_dump_.sql`
you'll get the error `pg_dumpall: option requires an argument: U` (even if you'll use: `${DB_USER}` as specified in the PostgreSQL documentation in the saved .sql file you'll have the error: `pg_dumpall: option requires an argument: U`).  So you won't be able to backup Rengine this way either.

### Solution:
1. In the installed folder of rengine open the `.env` file:
`nano .env`
2.  Check the name assigned to the database (Line 20):
POSTGRES_DB=rengine (rengine is default unless you specified another name during installation)

**Backup/save Reingine database:**
`docker exec -t rengine-db-1 pg_dumpall -c -U rengine > rengine_dump_.sql`

I hope it helps others who want to back up the Rengine DB. It would be good if the documentation were also updated.

**Comment by psyray** [comment]
@yogeshojha Could you update the doc with @Adelante10k fixed command
