### ISSUE TITLE
502 Bad Gateway

### ISSUE THREAD

**Issue by Biswanath12** [yogeshojha/rengine#708]
![Screenshot 2022-09-22 at 15-53-08 502 Bad Gateway](https://user-images.githubusercontent.com/50658399/191723291-ac62636e-4d89-41f1-ac2a-fb6a55a4d111.png)
Getting this error after trying to run it on my Linux system

**Comment by sunyyer** [comment]
I met the same error when update `V1.3.4`,`make down&make up` still error.

**Comment by Meetzanonymous** [comment]
I am facing the same issue!
