### ISSUE TITLE
DataTables warning: table id=subdomain_scan_results - Ajax error

### ISSUE THREAD

**Issue by ratnadip1998** [yogeshojha/rengine#710]
DataTables warning: table id=subdomain_scan_results - Ajax error. For more information about this error, please see http://datatables.net/tn/7

![re](https://user-images.githubusercontent.com/40835957/191863204-92264ef6-35eb-454e-9225-6c0f14f21320.png)

**Comment by ocervell** [comment]
Please give more context, which subscans show you this error ?

**Comment by vastestoff** [comment]
I have to confirm i have the same issue. 
any domain which i scanned doesn't show anything in subdomains tab. 
I got same error like on screenshot
As a guess - may be there is some limit or critical amount of subdomains to show ? 
by the way - results in text files exist and everything fine

**Comment by psyray** [comment]
Could you check on v2 and open a new issue if problem persists
