### ISSUE TITLE
ERROR: No container found for web_1

### ISSUE THREAD

**Issue by purple-WL** [yogeshojha/rengine#711]
`sudo ./install.sh`

Before running this script, please make sure Docker is running and you have made changes to .env file.
Changing the postgres username & password from .env is highly recommended.
Are you sure, you made changes to .env file (y/n)?

#########################################################################
Please note that, this installation script is only intended for Linux
For Mac and Windows, refer to the official guide https://rengine.wiki
#########################################################################

Installing reNgine and it's dependencies

#########################################################################
Installing curl...
#########################################################################
CURL already installed, skipping.

#########################################################################
Installing Docker...
#########################################################################
Docker already installed, skipping.

#########################################################################
Installing docker-compose
#########################################################################
docker-compose already installed, skipping.

#########################################################################
Installing make
#########################################################################
make already installed, skipping.

#########################################################################
Checking Docker status
#########################################################################
Docker is running.

#########################################################################
Installing reNgine
#########################################################################
Creating new CA...
genrsa: Can't open "ca.key" for writing, Permission denied
Can't open ca.key for reading, No such file or directory
139742672857928:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('ca.key','r')
139742672857928:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load Private Key
/entrypoint.sh: line 48: can't create ca.srl: Permission denied
Creating new certificate for recon.example.com
genrsa: Can't open "rengine.key" for writing, Permission denied
Can't open rengine.key for reading, No such file or directory
139746035641160:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('rengine.key','r')
139746035641160:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
unable to load Private Key
Can't open rengine.csr for reading, No such file or directory
139965736029000:error:02001002:system library:fopen:No such file or directory:crypto/bio/bss_file.c:69:fopen('rengine.csr','r')
139965736029000:error:2006D080:BIO routines:BIO_new_file:no such file:crypto/bio/bss_file.c:76:
mv: can't rename 'rengine.crt': No such file or directory
cp: can't stat 'ca.crt': No such file or directory
mv: can't rename 'rengine.key': No such file or directory
rm: can't remove 'rengine.csr': No such file or directory
ls: can't open '/certs': Permission denied
total 0
make: *** [certs] Error 1
reNgine is installed!!!

#########################################################################
Creating an account
#########################################################################
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python3 manage.py createsuperuser
WARNING: Service "proxy" uses an undefined secret file "/home/rengine-1.3.2/secrets/certs/rengine_chain.pem", the following file should be created "/home/rengine-1.3.2/secrets/certs/rengine_chain.pem"
WARNING: Service "proxy" uses an undefined secret file "/home/rengine-1.3.2/secrets/certs/rengine.pem", the following file should be created "/home/rengine-1.3.2/secrets/certs/rengine.pem"
WARNING: Service "proxy" uses an undefined secret file "/home/rengine-1.3.2/secrets/certs/rengine_rsa.key", the following file should be created "/home/rengine-1.3.2/secrets/certs/rengine_rsa.key"
ERROR: No container found for web_1
make: *** [username] Error 1

**Comment by ocervell** [comment]
Your error is this:

```
genrsa: Can't open "ca.key" for writing, Permission denied
Can't open ca.key for reading, No such file or directory
```

Check that you have permissions to write to the directory where it is creating the keys.
