### ISSUE TITLE
Feature - Need fast recon and good results

### ISSUE THREAD

**Issue by aravindb26** [yogeshojha/rengine#712]
Hi @yogeshojha hope u r doing well :)

I used your tool, really it's a very great tool for all researchers who want to do recon and makes it easy to analyze our recon process.

But one thing is it's taking a long time like days or even a week to complete the whole process.

So, if this recon goes fast, it will be good sir.

ThankYou :)

**Comment by aravindb26** [comment]
> 👋 Hi @aravindb26, Issues is only for reporting a bug/feature request. Please read documentation before raising an issue https://rengine.wiki For very limited support, questions, and discussions, please join reNgine Discord channel: https://discord.gg/azv6fzhNCE Please include all the requested and relevant information when opening a bug report. Improper reports will be closed without any response.

Yeah asked in discord but no one giving the solution. So i raised the issue here. Sorry for that

**Comment by ocervell** [comment]
Which engine are you using ? Which tasks takes a long time ? 

You can tweak settings `rate`, `timeout`, `threads` by creating a new engine (https://rengine.wiki/usage/scan_engine/#default-yaml-config). 

Depending on your server power, if you are scanning a lot of subdomains, or you are not filtering on specific templates in vulnerability_scan it might take forever indeed, but it is not really a reNgine problem, more the underlying tools that it is using.

**Comment by psyray** [comment]
Fixed by [2.0 version](https://github.com/yogeshojha/rengine/pull/963) with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
