### ISSUE TITLE
invalid certificate

### ISSUE THREAD

**Issue by Killua-Zoldyck-1** [yogeshojha/rengine#713]
![image](https://user-images.githubusercontent.com/112053770/192128566-ece93e34-a6ad-42c1-8ce6-778c064992d8.png)

how the heck am I supposed to fix this one?
I've scoured the internet, but it basically has no clue what to do.
it says "delete the certificate in your web browser settings"....yeah? which one?

HEEEEELLLLLLLPPPPPP

**Comment by m00tiny** [comment]
Confirmed
