### ISSUE TITLE
"Scheduled Scans" fail to run after container restart

### ISSUE THREAD

**Issue by atolac** [yogeshojha/rengine#716]
### Issue Summary

Scheduled Scans fail to run after containers are restarted

### Steps to Reproduce

Setup a daily scheduled scan https://127..0.0.1/scan/scheduled/
Let it run a couple of days and enjoy the findings 🐱‍💻
Restart your server or your containers
Now the scheduled scans won't repeat

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

reNgine1.3.2] on Debian 2 CPU 8GB RAM

**Comment by ocervell** [comment]
celery-beat uses a database. If you don't specify the db environment variables in your docker-compose, then every restart of the container might wipe off the sqlite database.

You should connect it to an external Postgres database (or equivalent SQL db). For this I add this to my celery-beat section in `docker-compose.yml`:
```
    environment:
      ...
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
 ```
