### ISSUE TITLE
Why does the network connection fail after successful installation on aws-ec2, is it because the docker environment has changed the network?

### ISSUE THREAD

**Issue by badguy233** [yogeshojha/rengine#719]
Why does the network connection fail after successful installation on aws-ec2 is it because the docker environment has changed the network? and cause me to not be able to connect my aws-ec2 via ssh

**Comment by badguy233** [comment]
<img width="1010" alt="image" src="https://user-images.githubusercontent.com/22237869/193082744-0f66d4e8-da2b-4db1-b59f-cfa64d916143.png">

**Comment by ocervell** [comment]
This looks like an AWS issue, not a reNgine issue. Should close.
