### ISSUE TITLE
No static Files

### ISSUE THREAD

**Issue by 0xmkr24** [yogeshojha/rengine#721]
![image](https://user-images.githubusercontent.com/60741904/193722159-19035288-c485-4ef6-af53-9e8c85d9cc58.png)

there's no static files

**Comment by ocervell** [comment]
Are you using Docker ? In that case you should visit the nginx proxy URL (often https://localhost:443) instead of the local web port since it's Nginx which serves static files.

**Comment by bukeyong** [comment]
I encountered the same problem during the installation process, and port 443 could not be accessed.
