### ISSUE TITLE
rengine tool in error 

### ISSUE THREAD

**Issue by Hacker-trademark** [yogeshojha/rengine#736]
![Screenshot 2022-10-31 8 43 59 PM](https://user-images.githubusercontent.com/47114230/199145307-243b7e9f-5ccd-48d5-8c5b-195df5f55b04.png)
[docker.pkg.github.com/yogeshojha/rengine/rengine:latest 12/31] RUN go install -v github.com/hakluke/hakrawler@latest:
#0 1.589 /bin/sh: 1: go: Exec format error> [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 12/31] RUN go install -v github.com/hakluke/hakrawler@latest:
#0 1.589 /bin/sh: 1: go: Exec format error

failed to solve: executor failed running [/bin/sh -c go install -v github.com/hakluke/hakrawler@latest]: exit code: 2
make: *** [Makefile:25: build] Error 17

Creating an account
#########################################################################
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python3 manage.py createsuperuser
service "web" is not running container #1
make: *** [Makefile:28: username] Error 1
Thank you for installing reNgine, happy recon!!

**Comment by yogeshojha** [comment]
Do you still see this? I did a fresh installation and is working all good.

![image](https://user-images.githubusercontent.com/17223002/199395757-3c799dc7-b9cc-4edf-9e06-309e10f48b94.png)

**Comment by Hacker-trademark** [comment]
Who needs pkg for properly installation rengine framework?

**Comment by yogeshojha** [comment]
You do not need pkg, installation is automated. All you have to do is `./install.sh`

**Comment by Hacker-trademark** [comment]
But in this cmd in one tool not install properly in go language hakrawler
tool in error installation.

**Comment by Hacker-trademark** [comment]
I try it for new process but not install rengine framework please help me.
I need to use this tool for bug hunting.
Please please please please help me

**Comment by iqzer0** [comment]
![image](https://user-images.githubusercontent.com/3487952/200253842-9a65ebb5-2b9c-4b78-b020-b901c72486e3.png)

```
 => [rengine_celery 22/31] RUN GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest         20.5s 
 => ERROR [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 23/31] RUN GO111MODULE=on go install -v github.com/projectdisc  2.8s 
------                                                                                                                                  
 > [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 23/31] RUN GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest:                                                                                                                    
#0 0.743 go: downloading github.com/projectdiscovery/nuclei v1.1.7                                                                      
#0 2.791 go: github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest: module github.com/projectdiscovery/nuclei@latest found (v1.1.7), but does not contain package github.com/projectdiscovery/nuclei/v2/cmd/nuclei
------
failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 1
make: *** [Makefile:25: build] Error 17
reNgine is installed!!!
```

I'm having the same issue.. any idea ?

**Comment by A0WaQ4** [comment]
> ![image](https://user-images.githubusercontent.com/3487952/200253842-9a65ebb5-2b9c-4b78-b020-b901c72486e3.png)
> 
> ```
>  => [rengine_celery 22/31] RUN GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest         20.5s 
>  => ERROR [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 23/31] RUN GO111MODULE=on go install -v github.com/projectdisc  2.8s 
> ------                                                                                                                                  
>  > [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 23/31] RUN GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest:                                                                                                                    
> #0 0.743 go: downloading github.com/projectdiscovery/nuclei v1.1.7                                                                      
> #0 2.791 go: github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest: module github.com/projectdiscovery/nuclei@latest found (v1.1.7), but does not contain package github.com/projectdiscovery/nuclei/v2/cmd/nuclei
> ------
> failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 1
> make: *** [Makefile:25: build] Error 17
> reNgine is installed!!!
> ```
> 
> I'm having the same issue.. any idea ?

I solved it by modifying web/Dockerfile.
change
RUN GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
to
RUN GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@v2.7.7
<img width="680" alt="image" src="https://user-images.githubusercontent.com/117633012/200264785-0252e50c-33c6-407e-8100-74756cbb8d25.png">
