### ISSUE TITLE
Scan issue - Screenshots, http responses not working 

### ISSUE THREAD

**Issue by roisec** [yogeshojha/rengine#738]
Hi,

Screenshots, HTTP responses, and technology detection not working.
These error logs occur after the httpx tool.
![image](https://user-images.githubusercontent.com/68992144/200159794-ec5d9a3f-44c8-44f3-aab6-057bcc3cbc15.png)

I think the issue started when configured with the last commits that support a proxy or something regarding the last commits.
@yogeshojha 
Please help to fix that ASAP.
Thanks

**Comment by kr0no** [comment]
Just made a PR #740. Feel free to test it, should be fixed.

**Comment by yogeshojha** [comment]
Thank you for reporting this, there was an issue with httpx as they changed the output json format. 

This is now fixed in 1.3.4
