### ISSUE TITLE
Nuclei not working

### ISSUE THREAD

**Issue by runvirus** [yogeshojha/rengine#743]
### Issue Summary

Vulnerability Scan is not working or showing any result , rengine old version working fine with me but latest version not working  

### Steps to Reproduce

1. When I am scanning the domains, this happens
2. Vulnerability Scan Completed very fast and not showing any result

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)

### Technical details

OS : ubuntu

**Comment by khanjanny** [comment]
same issue also screenshots not showing

**Comment by kr0no** [comment]
PR #740 solves it.

**Comment by yogeshojha** [comment]
Thank you for reporting this, there was an issue with httpx as they changed the output json format. 

This is now fixed in 1.3.4
