### ISSUE TITLE
Vulnerability Scanning Not Working 

### ISSUE THREAD

**Issue by VarmaKollu** [yogeshojha/rengine#748]
# Issue Summary
Vulnerability Scan is not working or showing any result, rengine old version is working  and the latest version is not working 

# Steps to Reproduce
When I am running rengine recommended scan on domains. it's completed and did not show any progress on vulnerabilities.
its keeps same thing on the latest version 

I have confirmed that this issue can be reproduced as described on the latest version/pull of reNgine
# Technical details
OS : ubuntu 20

**Comment by ad0nis** [comment]
Reproduced this last week. Recommended scan, imported a long list of hostnames. It skipped about 90% of them, found a small list, ran directory brute-force on them, and listed no vulns or screenshots.

**Comment by yogeshojha** [comment]
Thank you for reporting this, there was an issue with httpx as they changed the output json format. 

This is now fixed in 1.3.4
