### ISSUE TITLE
[Makefile:25: build] Error 17 - subfinder - v1.3.4

### ISSUE THREAD

**Issue by MikJagger** [yogeshojha/rengine#750]
### Issue Summary
Update existing v1.3.3 install or fresh install of v1.3.4 on ubuntu 20.04.4 LTS VPS results in 'make: *** [Makefile:25: build] Error 17' error on subfinder

Error message:

```

 => ERROR [rengine_celery-beat 22/31] RUN GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest       2.4s
------
 > [rengine_celery-beat 22/31] RUN GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest:
#0 1.008 go: downloading github.com/projectdiscovery/subfinder v2.5.4+incompatible
#0 1.821 go: github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest: module github.com/projectdiscovery/subfinder@latest found (v2.5.4+incompatible), but does not contain package github.com/projectdiscovery/subfinder/v2/cmd/subfinder
------
failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest]: exit code: 1
make: *** [Makefile:25: build] Error 17
```

### Steps to Reproduce

fresh install:

#git clone https://github.com/yogeshojha/rengine && cd rengine
sudo ./install.sh

#update existing install:
make down && git pull && make build && make up

**Comment by abda11atarek** [comment]
same problem with me

**Comment by MikJagger** [comment]
#751

**Comment by BrotherOfJhonny** [comment]
I'm having the same problem when I follow the installation guidelines.

![image](https://user-images.githubusercontent.com/28454566/213786532-bf018dbb-3f47-4f47-8a7b-794974e571d9.png)

**Comment by BrotherOfJhonny** [comment]
For everyone having the problem with go 1.18
Enter the directory: web/dockerfile
on the line: #Download and install go 1.18
change package : https://go.dev/d1/go1.18.2.linux-amd64.tar.gz
to: https://go.dev/d1/go1.19.linux-amd64.tar.gz

![image](https://user-images.githubusercontent.com/28454566/213799562-af15b8b4-b5ef-4d08-8720-f18216b76303.png)
