### ISSUE TITLE
Update don't work from 1.3.3 to 1.3.4

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#757]
Hi

I have reNgine1.3.3

When I https://rengine.wiki/update/ use Quick Update or Detailed Update Instructions version don't change, still 1.3.3?

And get this
"Update Available!
reNgine's new update undefined is available, please follow the update instructions.
undefined"

What to do?

**Comment by Adelante10k** [comment]
@zinwelzl - I confirm the same issue.

**Comment by ahmedx90T** [comment]
same issue here, tried multiple methods for the update but same result

**Comment by hr00tn** [comment]
Same issue here.

**Comment by abbasrashid** [comment]
Owner didnt update "RENGINE_CURRENT_VERSION" in docker config for recent commit i believe thats issue but everything should work fine.

**Comment by swarogisreal** [comment]
Same over here. Commands do not properly commit new change to origin/master.
