### ISSUE TITLE
Bug - OSINT not discovering any subdomains, nor anything really at all

### ISSUE THREAD

**Issue by thistehneisen** [yogeshojha/rengine#760]
### Issue Summary
Running `OSINT Only` is practically worthless as it discovers nothing:

```
reNgine has initiated recon for target largeTarget.tld with engine type OSINT Only
HTTP Crawler for target largeTarget.tld has been initiated.
HTTP Crawler for target largeTarget.tld has been completed.
 0 subdomains were alive (http status 200).
reNgine has initiated OSINT on target largeTarget.tld
reNgine has completed performing OSINT on target largeTarget.tld
```

Running subdomain gathering minutes before:
```
HTTP Crawler for target largeTarget.tld has been completed.
 19 subdomains were alive (http status 200).
```

So basically the tool / method is not working for some reason.

### Steps to Reproduce

1. Run `OSINT Only` on your target.

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

**Comment by 7onez** [comment]
Same issue with me, vuln scan is not working either. Please help to fix. Thank you

**Comment by psyray** [comment]
Fixed by https://github.com/yogeshojha/rengine/pull/963 with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
Old OSINT program has been dropped
