### ISSUE TITLE
update to 1.3.4 , world-map is missing ????

### ISSUE THREAD

**Issue by nop4LOL** [yogeshojha/rengine#761]
when I update to 1.3.4 , index.html world-map is missing

even I reinstall again and again , the problem is all happen

I open the devtools and find maybe is django problem ,but I dont know how to fix 

this is the screen picture:

![微信截图_20221125192025](https://user-images.githubusercontent.com/117899311/203977896-8401bd3d-1de9-4075-894f-47f1db2628f0.png)

![微信截图_20221125192047](https://user-images.githubusercontent.com/117899311/203977916-e1e63fed-1c18-47cb-84db-3eff53f55583.png)

**Comment by nop4LOL** [comment]
@yogeshojha I have been waitting a week ~

**Comment by yogeshojha** [comment]
Fixed in v1.3.5

Thank you :heart:
