### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by bukeyong** [yogeshojha/rengine#765]
Why can't I access port 443 after installing on the vps? I executed 'netstat - ano' on the vps and found that only 8000 and 5432 are available. I tried to access http://xxxx:8000 , but the static file cannot be loaded. I have tried both ubuntu and centos, both of which have the same problem.

**Comment by 5pokk** [comment]
have the same issue :( help pls

**Comment by 5pokk** [comment]
in Ubuntu/VPS, DigitalOcean

**Comment by testoiubvtc** [comment]
> 在 Ubuntu/VPS 中，DigitalOcean

#766 在这里我给出了解决方法

**Comment by chh2001125** [comment]
have the same issue, please help QAQ

**Comment by 5pokk** [comment]
> have the same issue, help please QAQ

in the issue 766 the solution, you have to install everything normally and then modify rengine.conf and docker-compose.yml... then run sudo ./install.sh again :D

**Comment by chh2001125** [comment]
> > have the same issue, help please QAQ
> 
> in the issue 766 the solution, you have to install everything normally and then modify rengine.conf and docker-compose.yml... then run sudo ./install.sh again :D

thanks,it helps a lot  👍
