### ISSUE TITLE
  Proxy container display certificate error

### ISSUE THREAD

**Issue by testoiubvtc** [yogeshojha/rengine#766]
The proxy container displays certificate error after installation. The installation failed
![1](https://user-images.githubusercontent.com/100524176/208358987-a0a1be3f-a025-438d-b190-d69923f873d7.jpg)

**Comment by testoiubvtc** [comment]
Now you can only remove the https authentication and just change the following configuration to run

rengine/config/nginx/rengine.conf

server {
    listen                                          80 default;
    listen                                          [::]:80 default;
    server_name                                     rengine recon;
    return                                          301 http://$host$request_uri;
}


server {
    listen                                          8090;
    listen                                          [::]:8090;
    server_name                                     rengine recon;

    charset                                         utf-8;
    keepalive_timeout                               70;

    client_max_body_size                            800M;

    location / {
        proxy_read_timeout                          300;
        proxy_connect_timeout                       300;
        proxy_redirect                              off;

        proxy_set_header                            Host $host;
        proxy_set_header                            X-Real-IP $remote_addr;
        proxy_set_header                            X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header                            X-Forwarded-Proto $scheme;
        proxy_pass                                  http://rengine:8000/;
    }

    location /staticfiles/ {
        alias /usr/src/app/staticfiles/;
    }

    location /media/ {
        alias /usr/src/scan_results/;
    }
}







rengine/docker-compose.yml

version: '3.8'

services:
  db:
    restart: always
    image: "postgres:12.3-alpine"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - rengine_network

  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
      - rengine_network

  celery:
    build:
      context: ./web
    restart: always
    entrypoint: /usr/src/app/celery-entrypoint.sh
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine worker --autoscale=${MAX_CONCURRENCY},${MIN_CONCURRENCY} -l INFO
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - scan_results:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
      - static_volume:/usr/src/app/staticfiles/
    environment:
      - DEBUG=0
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - db
      - redis
    networks:
      - rengine_network

  celery-beat:
    build: ./web
    entrypoint: /usr/src/app/beat-entrypoint.sh
    command: celery -A reNgine beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - DEBUG=0
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - celery
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - scan_results:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
    networks:
      - rengine_network

  web:
    build:
      context: ./web
    entrypoint: /usr/src/app/entrypoint.sh
    restart: always
    image: docker.pkg.github.com/yogeshojha/rengine/rengine:latest
    environment:
      - DEBUG=0
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      # THIS IS A MUST FOR CHECKING UPDATE, EVERYTIME A COMMIT IS MERGED INTO
      # MASTER, UPDATE THIS!!! MAJOR.MINOR.PATCH https://semver.org/
      - RENGINE_CURRENT_VERSION='1.3.3'
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - scan_results:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
      - static_volume:/usr/src/app/staticfiles/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - celery-beat
    networks:
      - rengine_network
    networks:
      rengine_network:
        aliases:
          - rengine

  tor:
    image: peterdavehello/tor-socks-proxy
    restart: always
    networks:
      - rengine_network
    depends_on:
      - web

  proxy:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80/tcp
      - 8090:8090/tcp
    depends_on:
      - web
      - db
      - redis
    volumes:
      - ./config/nginx/rengine.conf:/etc/nginx/conf.d/rengine.conf:ro
      - static_volume:/usr/src/app/staticfiles/
      - scan_results:/usr/src/scan_results
    networks:
      - rengine_network

networks:
  rengine_network:

volumes:
  tool_config:
  postgres_data:
  gf_patterns:
  nuclei_templates:
  github_repos:
  wordlist:
  scan_results:
  static_volume:

**Comment by andist15** [comment]
> The proxy container displays certificate error after installation. The installation failed ![1](https://user-images.githubusercontent.com/100524176/208358987-a0a1be3f-a025-438d-b190-d69923f873d7.jpg)

Same issue here :(

**Comment by yogeshojha** [comment]
This has now been fixed in v1.3.5

Thanks you <3

**Comment by soutzis** [comment]
> Now you can only remove the https authentication and just change the following configuration to run
> 
> rengine/config/nginx/rengine.conf
> 
> server { listen 80 default; listen [::]:80 default; server_name rengine recon; return 301 http://$host$request_uri; }
> 
> server { listen 8090; listen [::]:8090; server_name rengine recon;
> 
> ```
> charset                                         utf-8;
> keepalive_timeout                               70;
> 
> client_max_body_size                            800M;
> 
> location / {
>     proxy_read_timeout                          300;
>     proxy_connect_timeout                       300;
>     proxy_redirect                              off;
> 
>     proxy_set_header                            Host $host;
>     proxy_set_header                            X-Real-IP $remote_addr;
>     proxy_set_header                            X-Forwarded-For $proxy_add_x_forwarded_for;
>     proxy_set_header                            X-Forwarded-Proto $scheme;
>     proxy_pass                                  http://rengine:8000/;
> }
> 
> location /staticfiles/ {
>     alias /usr/src/app/staticfiles/;
> }
> 
> location /media/ {
>     alias /usr/src/scan_results/;
> }
> ```
> 
> }
> 
> rengine/docker-compose.yml
> 
> version: '3.8'
> 
> services: db: restart: always image: "postgres:12.3-alpine" environment: - POSTGRES_DB=${POSTGRES_DB} - POSTGRES_USER=${POSTGRES_USER} - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} - POSTGRES_PORT=${POSTGRES_PORT} ports: - "5432:5432" volumes: - postgres_data:/var/lib/postgresql/data/ networks: - rengine_network
> 
> redis: image: "redis:alpine" hostname: redis networks: - rengine_network
> 
> celery: build: context: ./web restart: always entrypoint: /usr/src/app/celery-entrypoint.sh command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine worker --autoscale=${MAX_CONCURRENCY},${MIN_CONCURRENCY} -l INFO volumes: - ./web:/usr/src/app - github_repos:/usr/src/github - wordlist:/usr/src/wordlist - scan_results:/usr/src/scan_results - gf_patterns:/root/.gf - nuclei_templates:/root/nuclei-templates - tool_config:/root/.config - static_volume:/usr/src/app/staticfiles/ environment: - DEBUG=0 - CELERY_BROKER=redis://redis:6379/0 - CELERY_BACKEND=redis://redis:6379/0 - POSTGRES_DB=${POSTGRES_DB} - POSTGRES_USER=${POSTGRES_USER} - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} - POSTGRES_PORT=${POSTGRES_PORT} - POSTGRES_HOST=${POSTGRES_HOST} depends_on: - db - redis networks: - rengine_network
> 
> celery-beat: build: ./web entrypoint: /usr/src/app/beat-entrypoint.sh command: celery -A reNgine beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler environment: - DEBUG=0 - CELERY_BROKER=redis://redis:6379/0 - CELERY_BACKEND=redis://redis:6379/0 - POSTGRES_DB=${POSTGRES_DB} - POSTGRES_USER=${POSTGRES_USER} - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} - POSTGRES_PORT=${POSTGRES_PORT} - POSTGRES_HOST=${POSTGRES_HOST} depends_on: - celery volumes: - ./web:/usr/src/app - github_repos:/usr/src/github - wordlist:/usr/src/wordlist - scan_results:/usr/src/scan_results - gf_patterns:/root/.gf - nuclei_templates:/root/nuclei-templates - tool_config:/root/.config networks: - rengine_network
> 
> web: build: context: ./web entrypoint: /usr/src/app/entrypoint.sh restart: always image: docker.pkg.github.com/yogeshojha/rengine/rengine:latest environment: - DEBUG=0 - CELERY_BROKER=redis://redis:6379/0 - CELERY_BACKEND=redis://redis:6379/0 - POSTGRES_DB=${POSTGRES_DB} - POSTGRES_USER=${POSTGRES_USER} - POSTGRES_PASSWORD=${POSTGRES_PASSWORD} - POSTGRES_PORT=${POSTGRES_PORT} - POSTGRES_HOST=${POSTGRES_HOST} # THIS IS A MUST FOR CHECKING UPDATE, EVERYTIME A COMMIT IS MERGED INTO # MASTER, UPDATE THIS!!! MAJOR.MINOR.PATCH https://semver.org/ - RENGINE_CURRENT_VERSION='1.3.3' volumes: - ./web:/usr/src/app - github_repos:/usr/src/github - wordlist:/usr/src/wordlist - scan_results:/usr/src/scan_results - gf_patterns:/root/.gf - nuclei_templates:/root/nuclei-templates - tool_config:/root/.config - static_volume:/usr/src/app/staticfiles/ ports: - "8000:8000" depends_on: - db - celery - celery-beat networks: - rengine_network networks: rengine_network: aliases: - rengine
> 
> tor: image: peterdavehello/tor-socks-proxy restart: always networks: - rengine_network depends_on: - web
> 
> proxy: restart: always image: nginx:alpine ports: - 80:80/tcp - 8090:8090/tcp depends_on: - web - db - redis volumes: - ./config/nginx/rengine.conf:/etc/nginx/conf.d/rengine.conf:ro - static_volume:/usr/src/app/staticfiles/ - scan_results:/usr/src/scan_results networks: - rengine_network
> 
> networks: rengine_network:
> 
> volumes: tool_config: postgres_data: gf_patterns: nuclei_templates: github_repos: wordlist: scan_results: static_volume:

Using Docker Desktop (4.19.0) with WSL2, Windows 11. Disabling HTTPS completely is the way to go. Thank you

**Comment by gata-bbs** [comment]
Hello,

At date of today here is a quick dirty setup tutoral to make reNgine v2.0 locally work on Windows 11.
The windows tutorial was a bit fuzzy for me.

1. Download & install [Docker Desktop](https://docs.docker.com/desktop/install/windows-install/)
2. Install & Activate [WSL ](https://learn.microsoft.com/en-us/windows/wsl/install)
3. Clone the repo locally via `git clone https://github.com/yogeshojha/rengine.git` 
4. Modify the following files:
- Add in `rengine/docker-compose.yml` the following lines ([see @psyray solution to avoid the rengine_celery-beat_1 bug](https://github.com/yogeshojha/rengine/issues/971#issue-1932574753:)) 
```
# Temporary fix for celery beat crash
# See https://github.com/yogeshojha/rengine/issues/971
DJANGO_CELERY_BEAT_TZ_AWARE = False
```
- Modify `rengine\config\nginx\rengine.conf` as follow:
```
server {
    listen                                          80;
    listen                                          [::]:80;
    server_name                                     rengine recon;
    return                                          301 http://$host$request_uri;
}


server {
    listen                                          8090;
    listen                                          [::]:8090;
    server_name                                     rengine recon;

    charset                                         utf-8;
    keepalive_timeout                               70;

    client_max_body_size                            800M;

    location / {
        proxy_read_timeout                          300;
        proxy_connect_timeout                       300;
        proxy_redirect                              off;

        proxy_set_header                            Host $host;
        proxy_set_header                            X-Real-IP $remote_addr;
        proxy_set_header                            X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header                            X-Forwarded-Proto $scheme;
        proxy_pass                                  http://rengine:8000/;
    }

    location /staticfiles/ {
        alias /usr/src/app/staticfiles/;
    }

    location /media/ {
        alias /usr/src/scan_results/;
    }
}
```
- Modify `rengine\docker-compose.yml` as follow:
```
version: '3.8'

services:
  db:
    restart: always
    image: "postgres:12.3-alpine"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - rengine_network

  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
      - rengine_network

  celery:
    build:
      context: ./web
    restart: always
    entrypoint: /usr/src/app/celery-entrypoint.sh
    command: watchmedo auto-restart --recursive --pattern="*.py" --directory="/usr/src/app/reNgine/" -- celery -A reNgine worker --autoscale=${MAX_CONCURRENCY},${MIN_CONCURRENCY} -l INFO
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - scan_results:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
      - static_volume:/usr/src/app/staticfiles/
    environment:
      - DEBUG=0
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - MAX_CONCURRENCY=${MAX_CONCURRENCY}
      - MIN_CONCURRENCY=${MIN_CONCURRENCY}
    depends_on:
      - db
      - redis
    networks:
      - rengine_network

  celery-beat:
    build: ./web
    entrypoint: /usr/src/app/beat-entrypoint.sh
    command: celery -A reNgine beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
    depends_on:
      - celery
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - scan_results:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
    networks:
      - rengine_network

  web:
    build:
      context: ./web
    entrypoint: /usr/src/app/entrypoint.sh
    restart: always
    image: docker.pkg.github.com/yogeshojha/rengine/rengine:latest
    environment:
      - DEBUG=0
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - DOMAIN_NAME=${DOMAIN_NAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_HOST=${POSTGRES_HOST}
      # THIS IS A MUST FOR CHECKING UPDATE, EVERYTIME A COMMIT IS MERGED INTO
      # MASTER, UPDATE THIS!!! MAJOR.MINOR.PATCH https://semver.org/
      - RENGINE_CURRENT_VERSION='2.0.0'
    volumes:
      - ./web:/usr/src/app
      - github_repos:/usr/src/github
      - wordlist:/usr/src/wordlist
      - scan_results:/usr/src/scan_results
      - gf_patterns:/root/.gf
      - nuclei_templates:/root/nuclei-templates
      - tool_config:/root/.config
      - static_volume:/usr/src/app/staticfiles/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - celery-beat
    networks:
      rengine_network:
        aliases:
          - rengine

  proxy:
    restart: always
    image: nginx:alpine
    ports:
      - 80:80/tcp
      - 8090:8090/tcp
    depends_on:
      - web
      - db
      - redis
    volumes:
      - ./config/nginx/rengine.conf:/etc/nginx/conf.d/rengine.conf:ro
      - static_volume:/usr/src/app/staticfiles/
      - scan_results:/usr/src/scan_results
    networks:
      - rengine_network


networks:
  rengine_network:

volumes:
  tool_config:
  postgres_data:
  gf_patterns:
  nuclei_templates:
  github_repos:
  wordlist:
  scan_results:
  static_volume:

```
- In `rengine` folder run consecutively in a termial:
&emsp; - `make certs`
&emsp; - `make build`
&emsp; - `make up`
&emsp; - `make username` (and follow the steps to create a reNgine account)
- You should now be able to access reNgine interface at the following address: `http://127.0.0.1:8090`

Hope it helps.

**Comment by AnonymousWP** [comment]
Uhh, except setting `DJANGO_CELERY_BEAT_TZ_AWARE = False`, how is it different from the current setup?
