### ISSUE TITLE
nginx:alpine can't start

### ISSUE THREAD

**Issue by w4ter** [yogeshojha/rengine#769]
docker :
 nginx:alpine                                              "/docker-entrypoint.…"   59 seconds ago       Restarting (1) 14 seconds ago                                                  rengine-proxy-1

docker logs rengine-proxy-1:
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: IPv6 listen already enabled
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2022/12/23 01:38:21 [emerg] 1#1: SSL_CTX_set1_curves_list("sect571r1:secp521r1:brainpoolP512r1:secp384r1") failed (SSL: error:0A080106:SSL routines::passed invalid argument:group 'sect571r1' cannot be set)
nginx: [emerg] SSL_CTX_set1_curves_list("sect571r1:secp521r1:brainpoolP512r1:secp384r1") failed (SSL: error:0A080106:SSL routines::passed invalid argument:group 'sect571r1' cannot be set)

why?

**Comment by NgoHuy** [comment]
use pull request https://github.com/yogeshojha/rengine/pull/767
please read pull request or other issue before opening the issue
also #768

**Comment by barbixxxa** [comment]
> use pull request #767 please read pull request or other issue before opening the issue also #768

didnt work for me

**Comment by kryptexof** [comment]
I keep getting the same error even though I have made the relevant fixes.

**Comment by paweloque** [comment]
Looks like python3 manage.py collectstatic is not executed to prepare static files.

**Comment by paweloque** [comment]
@w4ter: My proxy is not starting and I only access the service directly via 8000. is your proxy running properly? It looks like 'staticfiles' are served via proxy, so if you're accessing rengine directly, staticfiles (js, css, etc) wont be served properly

**Comment by barbixxxa** [comment]
> @w4ter: My proxy is not starting and I only access the service directly via 8000. is your proxy running properly? It looks like 'staticfiles' are served via proxy, so if you're accessing rengine directly, staticfiles (js, css, etc) wont be served properly

Same here

**Comment by kryptexof** [comment]
> @w4ter: My proxy is not starting and I only access the service directly via 8000. is your proxy running properly? It looks like 'staticfiles' are served via proxy, so if you're accessing rengine directly, staticfiles (js, css, etc) wont be served properly

How can this problem be overcome?

**Comment by paweloque** [comment]
So, I don't have a final solution for this yet, but by setting DEBUG=1 you'll be able to get the static resources served via django. This will at least allow you to see the UI and experiment with it. 

<img width="434" alt="Screenshot 2022-12-26 at 18 26 32" src="https://user-images.githubusercontent.com/1042717/209571600-2d9bb810-0ea2-4b10-a587-014b047bd297.png">

<img width="1792" alt="Screenshot 2022-12-26 at 18 26 57" src="https://user-images.githubusercontent.com/1042717/209571634-0f3a509d-f10c-444e-ba96-2f4785021e0b.png">

**Comment by barbixxxa** [comment]
> So, I don't have a final solution for this yet, but by setting DEBUG=1 you'll be able to get the static resources served via django. This will at least allow you to see the UI and experiment with it.
> 
> <img alt="Screenshot 2022-12-26 at 18 26 32" width="434" src="https://user-images.githubusercontent.com/1042717/209571600-2d9bb810-0ea2-4b10-a587-014b047bd297.png">
> 
> <img alt="Screenshot 2022-12-26 at 18 26 57" width="1792" src="https://user-images.githubusercontent.com/1042717/209571634-0f3a509d-f10c-444e-ba96-2f4785021e0b.png">

Worked here

**Comment by paweloque** [comment]
I've changed the `ssl_ecdh_curve` nginx param to:
```
ssl_ecdh_curve                                  secp384r1:X25519:prime256v1;
```
And set my domain in .env file to the domain via which rengine is served and it all worked fine. Let me know whether that helps?

**Comment by Alumniminium** [comment]
the biggest problem is that rengine comes with a reverse proxy that has  the static assets copied into its container so you can't use an existing reverse proxy without turning on DEBUG.

**Comment by villellasullivan** [comment]
Same issue here. 
I confirm, put DEBUG=1 is a workaround

**Comment by yogeshojha** [comment]
This has now been fixed, thanks to @bin-maker, @carsonchan12345, @paweloque, @opabravo! :heart:
