### ISSUE TITLE
make: *** [Makefile:25: build] Error 17

### ISSUE THREAD

**Issue by f4rh3N** [yogeshojha/rengine#777]
failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 2
make: *** [Makefile:25: build] Error 17
reNgine is installed!!!

#########################################################################
Creating an account
#########################################################################
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python3 manage.py createsuperuser
service "web" is not running container #1
make: *** [Makefile:28: username] Error 1
Thank you for installing reNgine, happy recon!!

**Comment by f4rh3N** [comment]
I am getting this error while executing install.sh script

**Comment by topscoder** [comment]
See https://github.com/yogeshojha/rengine/issues/751 for a workaround

**Comment by Mateus-Veras-Tvirus** [comment]
I have this same problem..

**Comment by topscoder** [comment]
Looks like some packages (or just Nuclei) do require the latest version of Go (1.19.x).

**Comment by DanielAKAOi** [comment]
same probleme here

----

failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 2
make: *** [Makefile:25: build] Error 17
reNgine is installed!!!
                                                                                                                                                                                                                                                            
#########################################################################                                                                                                                                                                                   
Creating an account                                                                                                                                                                                                                                         
#########################################################################                                                                                                                                                                                   
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python3 manage.py createsuperuser                                                                                                                                                  
service "web" is not running container #1                                                                                                                                                                                                                   
make: *** [Makefile:28: username] Error 1                                                                                                                                                                                                                   
Thank you for installing reNgine, happy recon!!             


----

**Comment by hassan-elshoraa** [comment]
same error 

failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 2
make: *** [Makefile:25: build] Error 17

service "web" is not running container #1
make: *** [Makefile:28: username] Error 1

**Comment by 7onez** [comment]
See this introduction: https://rengine.wiki/install/detailed/#rengine-installation - I followed this and it helps.

**Comment by whoami-anoint** [comment]
It looks like there might be some issues with the installation or setup of reNgine. Here are a few potential troubleshooting steps that you could try:

    Check the log output: If there are any error messages or other useful information in the log output, they may help you identify the cause of the issue. You can view the log output by running docker logs <container name>, where <container name> is the name of the container that is experiencing the issue.

    Check the dependencies: Make sure that you have all of the required dependencies installed and configured correctly. This may include specific versions of programming languages, libraries, or other tools that are needed for reNgine to run.

    Check the configuration: Make sure that you have followed all of the necessary steps to configure reNgine properly. This may include setting up the database, creating the necessary directories, and setting up any necessary environment variables.

    Check for updates: If you are using an older version of reNgine, there may be updates available that fix bugs or add new features. You can check for updates by visiting the reNgine project's homepage or by contacting the developers directly.

I hope these suggestions are helpful! Let me know if you have any other questions or if you need more assistance.

**Comment by whoami-anoint** [comment]
It looks like there might be some issues with the installation or setup of reNgine. Here are a few potential troubleshooting steps that you could try:

    Check the log output: If there are any error messages or other useful information in the log output, they may help you identify the cause of the issue. You can view the log output by running docker logs <container name>, where <container name> is the name of the container that is experiencing the issue.

    Check the dependencies: Make sure that you have all of the required dependencies installed and configured correctly. This may include specific versions of programming languages, libraries, or other tools that are needed for reNgine to run.

    Check the configuration: Make sure that you have followed all of the necessary steps to configure reNgine properly. This may include setting up the database, creating the necessary directories, and setting up any necessary environment variables.

    Check for updates: If you are using an older version of reNgine, there may be updates available that fix bugs or add new features. You can check for updates by visiting the reNgine project's homepage or by contacting the developers directly.

I hope these suggestions are helpful! Let me know if you have any other questions or if you need more assistance.

**Comment by hassan-elshoraa** [comment]
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 6/8
 ⠿ Network rengine_rengine_network  Created                                                                      0.3s
 ⠿ Container rengine-db-1           Starting                                                                    18.2s
 ⠿ Container rengine-redis-1        Starting                                                                    18.2s
 ⠿ Container rengine-celery-1       Recreated                                                                    3.5s
 ⠿ Container rengine-celery-beat-1  Recreated                                                                    1.7s
 ⠿ Container rengine-web-1          Recreated                                                                    2.3s
 ⠿ Container rengine-proxy-1        Recreated                                                                    5.5s
 ⠿ Container rengine-tor-1          Recreated                                                                    5.4s
Error response from daemon: network 2d0b92fefc181eb81da1f6752fb1cfbc84d51a32d3f523570be5b3739eb46fff not found
make: *** [Makefile:22: up] Error 1
reNgine is installed!!!

**Comment by topscoder** [comment]
The problem is that Nuclei (now) requires Go 1.19, but Go 1.18 is installed (see web/Dockerfile). So either way rengine should install Go 1.19 or rengine should stick to a previous version of nuclei for now.

**Comment by hassan-elshoraa** [comment]
@topscoder 
i dont think that the issue, i have tried everything,  i deleted neclei line from docker
go version                                 
go version go1.19.4 linux/amd64

**Comment by MikJagger** [comment]
As a workaround, change to @latest to earlier Nuclei version:

#edit file from root rengine folder web/Dockerfile
sudo vim web/Dockerfile

#change line:
RUN GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@
to
RUN GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@b355b76afdcc3a2216ff71988636bc206713935c

#Save change (vim = :wq! ENTER)
sudo make build

#when build finished
sudo make up

**Comment by DanielAKAOi** [comment]
sed -i 's/go1.18.2.linux-amd64.tar.gz/go1.19.4.linux-amd64.tar.gz/g' $PATH/rengine/web/Dockerfile

**Comment by themoonbaba** [comment]
> sed -i 's/go1.18.2.linux-amd64.tar.gz/go1.19.4.linux-amd64.tar.gz/g' $PATH/rengine/web/Dockerfile

THANKS THIS WORKS

**Comment by TofuWand** [comment]
> I am getting this error while executing install.sh script

I get this while doing the ./install.sh script:
failed to solve: executor failed running [/bin/sh -c go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 1
make: *** [Makefile:25: build] Error 17
