### ISSUE TITLE
When I was executing the install.sh file, the following error occurred

### ISSUE THREAD

**Issue by wkend** [yogeshojha/rengine#779]
![image](https://user-images.githubusercontent.com/37563697/210331619-0d50e25c-77ed-499f-b269-3313fe530788.png)

**Comment by DanielAKAOi** [comment]
try ->  sed -i 's/go1.18.2.linux-amd64.tar.gz/go1.19.4.linux-amd64.tar.gz/g' $PATH/rengine/web/Dockerfile
