### ISSUE TITLE
Can't install rengine in Parrot OS.

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#781]
Hi all.

Get this error with 
sudo make up 
"failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest]: exit code: 2
make: *** [Makefile:22: up] Error 17"

What to do?

Thanks.

**Comment by DanielAKAOi** [comment]
sed -i 's/go1.18.2.linux-amd64.tar.gz/go1.19.4.linux-amd64.tar.gz/g' $PATH/rengine/web/Dockerfile

**Comment by zinwelzl** [comment]
From where should I run this?
I get error whatever I do?

BTW, thanks.
