### ISSUE TITLE
Bug - Database crash

### ISSUE THREAD

**Issue by villellasullivan** [yogeshojha/rengine#782]
### Issue Summary

Sometimes i'm facing database crashes. 
It's happened randomly when starting an analysis on big targets. 

### Technical details

When the database is crashed, I got this logs : 

`rengine-db-1           | 2023-01-03 22:27:57.616 UTC [99255] FATAL:  password authentication failed for user "postgres"
rengine-db-1           | 2023-01-03 22:27:57.616 UTC [99255] DETAIL:  Role "postgres" does not exist.
rengine-db-1           | 	Connection matched pg_hba.conf line 95: "host all all all md5"`

The workaround is to restart reNgine with 'make restart' and then restart the scan from 0.

reNgine is hosted on Digital Ocean. 

Tell me if you need more infos. 

Best regards

**Comment by abdulb4s1t-2** [comment]
I'm having the same issue

**Comment by MantisSTS** [comment]
Yeah same here. Any workaround/fix for this?

**Comment by MantisSTS** [comment]
So I fixed the issue by replacing the postgres-alpine image for the standard postgres image in the docker-compose.yml file as the 12.3-alpine version is outdated (although still supported from what I can see on https://www.postgresql.org/support/versioning/). I have only tested this short term and cannot guarantee the long-term affects but it seems to have fixed the issue for me. 

```
    image: "postgres:12.3-alpine"
```

to just

```
    image: "postgres"
```
https://github.com/yogeshojha/rengine/blob/master/docker-compose.yml#L6

However, I did encounter some errors when running `docker-compose up` as the environment variables weren't working correctly. So I just set the db host in the .env file to be the IP of the docker container. There's definitely a better way than that but this was a quick fix:

```
#
# Database configurations
#
POSTGRES_DB=rengine
POSTGRES_USER=<REDACTED>
POSTGRES_PASSWORD=<REDACTED>
POSTGRES_PORT=5432
POSTGRES_HOST=10.131.0.2

```

**Comment by MantisSTS** [comment]
> So I fixed the issue by replacing the postgres-alpine image for the standard postgres image in the docker-compose.yml file as the 12.3-alpine version is outdated (although still supported from what I can see on https://www.postgresql.org/support/versioning/). I have only tested this short term and cannot guarantee the long-term affects but it seems to have fixed the issue for me.
> 
> ```
>     image: "postgres:12.3-alpine"
> ```
> 
> to just
> 
> ```
>     image: "postgres"
> ```
> 
> https://github.com/yogeshojha/rengine/blob/master/docker-compose.yml#L6
> 
> However, I did encounter some errors when running `docker-compose up` as the environment variables weren't working correctly. So I just set the db host in the .env file to be the IP of the docker container. There's definitely a better way than that but this was a quick fix:
> 
> ```
> #
> # Database configurations
> #
> POSTGRES_DB=rengine
> POSTGRES_USER=<REDACTED>
> POSTGRES_PASSWORD=<REDACTED>
> POSTGRES_PORT=5432
> POSTGRES_HOST=10.131.0.2
> ```

Scrap that. It crashed after 3 days

**Comment by Squirlld** [comment]
Agreed. Issue still exists.
