### ISSUE TITLE
Bug - Issues In Vulnerability Scanning

### ISSUE THREAD

**Issue by understand0practice** [yogeshojha/rengine#783]
### Issue Summary

Whenever a scan is initated the scan runs however after completing nuclei the scan says failed with "template" error.

### Steps to Reproduce

1. When I am scanning the domains, this happens

I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes)

### Technical details

I have also restarted the system and reinstalled everything again still this persists.
![template_failed](https://user-images.githubusercontent.com/121931028/210513382-26a72301-e9c1-4b76-b4c1-00fa2b353eb2.png)

**Comment by understand0practice** [comment]
celery_1       | [2023-01-04 08:22:23,511: INFO/ForkPoolWorker-4] Creating Endpoint...
celery_1       | [2023-01-04 08:22:23,513: INFO/ForkPoolWorker-4] Endpoint https://ssss.vvvvv.com/signin created!
celery_1       | [2023-01-04 08:22:23,646: ERROR/ForkPoolWorker-4] 'template'
celery_1       | [2023-01-04 08:22:23,648: ERROR/ForkPoolWorker-4] 'template'
celery_1       | [2023-01-04 08:22:23,668: INFO/ForkPoolWorker-4] Task reNgine.tasks.initiate_scan[854a30e0-57bd-406c-b2de-313017   085015] succeeded in 1095.5136760219902s: {'status': True}

**Comment by MikJagger** [comment]
I am experiencing the same issue based on:

rengine 1.3.5 running with earlier Nuclei version 'github.com/projectdiscovery/nuclei/v2/cmd/nuclei@b355b76afdcc3a2216ff71988636bc206713935c' because of issue #777

**Comment by MikJagger** [comment]
The error is fixed by using the method mentioned in comments of #777   [https://github.com/yogeshojha/rengine/issues/777#issuecomment-1370159151](url) instead of my earlier comment changing to Nuclei version.

by changing the Go version within the web/Dockerfile
go1.18.2.linux-amd64.tar.gz to go1.19.4.linux-amd64.tar.gz in file web/Dockerfile
