### ISSUE TITLE
CANNOT INSTALL

### ISSUE THREAD

**Issue by VinzelOps** [yogeshojha/rengine#785]
=> ERROR [redacted_celery 21/31] RUN GO111MODULE=on go install -v gith  30.4s
------
 > [redacted_celery 21/31] RUN GO111MODULE=on go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest:
#0 30.30 go: github.com/projectdiscovery/httpx/cmd/httpx@latest: module github.com/projectdiscovery/httpx/cmd/httpx: Get "https://proxy.golang.org/github.com/projectdiscovery/httpx/cmd/httpx/@v/list": dial tcp: lookup proxy.golang.org: i/o timeout
------
failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest]: exit code: 1
make: *** [Makefile:25: build] Error 17
reNgine is installed!!!

#########################################################################
Creating an account
#########################################################################
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml exec web python3 manage.py createsuperuser
service "web" is not running container #1
make: *** [Makefile:28: username] Error 1

Please for help

**Comment by x24thkk** [comment]
> did you find any solution ? i have the same problem, what version of go do you have maybe it's the problem mine is 1.19.4

please upgrade go to go1.19.4

**Comment by Alganad** [comment]
> please upgrade go to go1.19.4

it was already 1.19.4 and now it's 1.19.5 and still the same problem :(

**Comment by x24thkk** [comment]
> > please upgrade go to go1.19.4
> 
> it was already 1.19.4 and now it's 1.19.5 and still the same problem :(

Are you sure you are upgrading go in the container?
Please edit rengine/web/Dockerfile 45-47 line

**Comment by Alganad** [comment]
Thank you a lot, i changed the Dockfile's go version as you said and it worked, but I couldn't migrate the manage.py file, and when I try runserver this error appear :


ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

i didn't know how to start the virtual environment 

> > > please upgrade go to go1.19.4
> > 
> > 
> > it was already 1.19.4 and now it's 1.19.5 and still the same problem :(
> 
> Are you sure you are upgrading go in the container? Please edit rengine/web/Dockerfile 45-47 line

**Comment by Alganad** [comment]
> > > please upgrade go to go1.19.4
> > 
> > 
> > it was already 1.19.4 and now it's 1.19.5 and still the same problem :(
> 
> Are you sure you are upgrading go in the container? Please edit rengine/web/Dockerfile 45-47 line

Thank you a lot, i changed the Dockfile's go version as you said and it worked, but I couldn't migrate the manage.py file, and when I try runserver this error appear :

ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?

i didn't know how to start the virtual environment

**Comment by x24thkk** [comment]
> 

I don't know under what circumstances this error occurs, can you give some details of the error message?

I think you should read the installation manual carefully, it might be helpful for you.  [install link](https://rengine.wiki/install/detailed/)

**Comment by Alganad** [comment]
> > 
> 
> I don't know under what circumstances this error occurs, can you give some details of the error message?
> 
> I think you should read the installation manual carefully, it might be helpful for you. [install link](https://rengine.wiki/install/detailed/)

Yes, the first thing I did was search in the installation manual but they didn't mention anything about this. 

the error occurred when i finished the reNgine download there was a red line that said that I need to migrate 35 python etc..............., and if didn't do that, reNgine will not work properly and it said i should use the command  "**python manage.py migrate**" but when i use it in ~/rengine/web/manage.py this error occurs 

python manage.py migrate
  File "manage.py", line 20
    ) from exc
         ^
SyntaxError: invalid syntax

**Comment by Alganad** [comment]
> please
> 
> > > > 
> > > 
> > > 
> > > I don't know under what circumstances this error occurs, can you give some details of the error message?
> > > I think you should read the installation manual carefully, it might be helpful for you. [install link](https://rengine.wiki/install/detailed/)
> > 
> > 
> > Yes, the first thing I did was search in the installation manual but they didn't mention anything about this.
> > the error occurred when i finished the reNgine download there was a red line that said that I need to migrate 35 python etc..............., and if didn't do that, reNgine will not work properly and it said i should use the command "**python manage.py migrate**" but when i use it in ~/rengine/web/manage.py this error occurs
> > python manage.py migrate File "manage.py", line 20 ) from exc ^ SyntaxError: invalid syntax
> 
> pease use python3

I used it and tried multiple I installed Django from pip also most of the requremnt.txt and this the error that occurs 

Traceback (most recent call last):
  File "/home/ahmed/rengine/web/reNgine/init.py", line 24, in first_run
    secret = open(secret_file, 'w')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/secret'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ahmed/rengine/web/manage.py", line 25, in <module>
    main()
  File "/home/ahmed/rengine/web/manage.py", line 21, in main
    execute_from_command_line(sys.argv)
  File "/home/ahmed/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/home/ahmed/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 363, in execute
    settings.INSTALLED_APPS
  File "/home/ahmed/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 82, in __getattr__
    self._setup(name)
  File "/home/ahmed/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 69, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/ahmed/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 170, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ahmed/rengine/web/reNgine/settings.py", line 14, in <module>
    SECRET_KEY = first_run(SECRET_FILE, BASE_DIR)
  File "/home/ahmed/rengine/web/reNgine/init.py", line 28, in first_run
    raise Exception('Secret file generation failed' % secret_file)
TypeError: not all arguments converted during string formatting

**Comment by x24thkk** [comment]
> > please
> > > > > 
> > > > 
> > > > 
> > > > I don't know under what circumstances this error occurs, can you give some details of the error message?
> > > > I think you should read the installation manual carefully, it might be helpful for you. [install link](https://rengine.wiki/install/detailed/)
> > > 
> > > 
> > > Yes, the first thing I did was search in the installation manual but they didn't mention anything about this.
> > > the error occurred when i finished the reNgine download there was a red line that said that I need to migrate 35 python etc..............., and if didn't do that, reNgine will not work properly and it said i should use the command "**python manage.py migrate**" but when i use it in ~/rengine/web/manage.py this error occurs
> > > python manage.py migrate File "manage.py", line 20 ) from exc ^ SyntaxError: invalid syntax
> > 
> > 
> > pease use python3
> 
> I used it and tried multiple I installed Django from pip also most of the requremnt.txt and this the error that occurs
> 
> Traceback (most recent call last): File "/home/ahmed/rengine/web/reNgine/init.py", line 24, in first_run secret = open(secret_file, 'w') FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/app/secret'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/ahmed/rengine/web/manage.py", line 25, in main() File "/home/ahmed/rengine/web/manage.py", line 21, in main execute_from_command_line(sys.argv) File "/home/ahmed/.local/lib/python3.9/site-packages/django/core/management/**init**.py", line 419, in execute_from_command_line utility.execute() File "/home/ahmed/.local/lib/python3.9/site-packages/django/core/management/**init**.py", line 363, in execute settings.INSTALLED_APPS File "/home/ahmed/.local/lib/python3.9/site-packages/django/conf/**init**.py", line 82, in **getattr** self._setup(name) File "/home/ahmed/.local/lib/python3.9/site-packages/django/conf/**init**.py", line 69, in _setup self._wrapped = Settings(settings_module) File "/home/ahmed/.local/lib/python3.9/site-packages/django/conf/**init**.py", line 170, in **init** mod = importlib.import_module(self.SETTINGS_MODULE) File "/usr/lib/python3.9/importlib/**init**.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 1030, in _gcd_import File "", line 1007, in _find_and_load File "", line 986, in _find_and_load_unlocked File "", line 680, in _load_unlocked File "", line 790, in exec_module File "", line 228, in _call_with_frames_removed File "/home/ahmed/rengine/web/reNgine/settings.py", line 14, in SECRET_KEY = first_run(SECRET_FILE, BASE_DIR) File "/home/ahmed/rengine/web/reNgine/init.py", line 28, in first_run raise Exception('Secret file generation failed' % secret_file) TypeError: not all arguments converted during string formatting

You should use this command in the container, not the current machine, and I think you should check the installation wiki

**Comment by x24thkk** [comment]
Please read  rengine document.
