### ISSUE TITLE
Feature - Ability to mark vulns false positives

### ISSUE THREAD

**Issue by shorefall** [yogeshojha/rengine#790]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when a finding is actually just a false positive so would be nice to be able to delete or mark one as FP

**Comment by roisec** [comment]
+1

**Comment by SeanOverton** [comment]
would this be a simple button in the "vulnerabilities" page where you can just "mark as false positive"?

**Comment by psyray** [comment]
> would this be a simple button in the "vulnerabilities" page where you can just "mark as false positive"?

Yes it could be that.
But we need also to filter out this false positive to not have them in report.
Maybe we could simply propose to delete the vulnerability ?

**Comment by psyray** [comment]
you're right
