### ISSUE TITLE
celery failed to build

### ISSUE THREAD

**Issue by iso1983** [yogeshojha/rengine#791]
Hi,
When I install the latest version of rengine on Ubuntu, I get:
**The command '/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest' returned a non-zero code: 2
ERROR: Service 'celery' failed to build : Build failed
make: *** [Makefile:25: build] Error 1**

It is not related to go , or go environment setup ,go is setup properly on my system.This is something to do with httpx of projectdiscovery I guess or celery, How to fix this?

**Comment by dhavz** [comment]
Hi @iso1983, I have found a workaround. The httpx latest version requires at least go1.19. 
The default configuration downloads and install go version 1.18 or something. 

You can fix the issue by modifying reEngine/web/Dockerfile with the following contents,

Line Number: 44

# Download and install go 1.18
RUN wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz
RUN tar -xvf go1.19.5.linux-amd64.tar.gz
RUN rm go1.19.5.linux-amd64.tar.gz
RUN mv go /usr/local
