### ISSUE TITLE
Integration of aiodnsbrute

### ISSUE THREAD

**Issue by sebmichel1983** [yogeshojha/rengine#792]
It woud be nice if you can integrate aiodnsbrute to the default toolchain.

https://github.com/blark/aiodnsbrute

It is a really really fast subdomain bruteforcing tool.

**Comment by psyray** [comment]
Project seems to be old (2019 !)
I think we will focus on chaos and PureDNS, more up to date projects
https://github.com/yogeshojha/rengine/issues/173
https://github.com/yogeshojha/rengine/issues/249
