### ISSUE TITLE
Bug - Assetfinder results not created with subprocess.Popen

### ISSUE THREAD

**Issue by serrapa** [yogeshojha/rengine#802]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

If you launch a sudomain discovery with only Assetfinder as tool, it will work well, it actually finds subdomains but the output will not be written in the from_assetfinder.txt file. The > bash  operator does not work with subprocess.Popen. 

### Steps to Reproduce

1. Launch a "only subdomain discovery" scan with a scan engine where the uses_tools = [ assefinder ]
2. See there are no results. 

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

**Comment by psyray** [comment]
assetfinder has been removed in v2
