### ISSUE TITLE
failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest]: exit code: 2

### ISSUE THREAD

**Issue by CSPGhostDelta** [yogeshojha/rengine#803]
I was updating the rEngine using the "make down && git pull && make build && make up" command, and then I got this error. How to fix this?

**Comment by MustafaBilgici** [comment]
if u change /rengine/web/Dockefile  from old to like that it will be solve
line 44
``
RUN wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz

RUN tar -xvf go1.19.5.linux-amd64.tar.gz

RUN rm go1.19.5.linux-amd64.tar.gz

RUN mv go /usr/local
``

**Comment by Ca1mly** [comment]
thanks

**Comment by vsidharth2001** [comment]
anyone please help me for resolve this issue

**Comment by MustafaBilgici** [comment]
u can follow this steps
if u change /rengine/web/Dockefile from old to like that it will be solve
line 44

``
RUN wget https://go.dev/dl/go1.19.5.linux-amd64.tar.gz

RUN tar -xvf go1.19.5.linux-amd64.tar.gz

RUN rm go1.19.5.linux-amd64.tar.gz

RUN mv go /usr/local
``

> anyone please help me for resolve this issue



> anyone please help me for resolve this issue
