### ISSUE TITLE
Fix ERROR: Service 'celery' failed to build : Build failed error

### ISSUE THREAD

**Issue by CATx003** [yogeshojha/rengine#809]
Hi, if you have problems to build like this:

```
The command '/bin/sh -c pip3 install --upgrade setuptools pip &&     pip3 install -r /tmp/requirements.txt' returned a non-zero code: 2       
ERROR: Service 'celery' failed to build : Build failed
make: *** [Makefile:22: up] Error 1
```

Update the rengine/web/requirements.txt and upgrade the celery version to 5.1.2
like this:
```
└─$ cat requirements.txt 
argh
beautifulsoup4==4.9.3
celery==5.1.2     # <<<<<<<<<<<<<<<<<<<<<<<
degoogle==1.0.1
discord-webhook==0.14.0
Django==3.2.4
django-ace==1.0.11
django-celery-beat==2.2.1
django-login-required-middleware==0.6.1
django-mathfilters==1.0.0
django-timezone-field==4.1.2
djangorestframework==3.12.4
djangorestframework-datatables==0.6.0
dotted-dict==1.1.3
drf-yasg
emailfinder==0.2.3b0
fuzzywuzzy==0.18.0
gunicorn==20.1.0
Markdown==3.3.4
metafinder==1.1
netaddr==0.8.0
PyYAML==5.4.1
PySocks
psycopg2==2.9.1
python-Levenshtein==0.12.2
PyVirtualDisplay==2.2
redis==3.5.3
requests==2.25.1
selenium==3.141.0
tldextract==3.1.0
validators==0.18.2
watchdog
whatportis==0.8.2
weasyprint==53.3
wafw00f
asyncwhois
```

After this just run make build and lets go.

**Comment by foozzi** [comment]
@CATx003 requirements.txt has already celery 5.1.2

**Comment by gustavorobertux** [comment]
You can momentarily fix the problems as follows:

Add these lines at the beginning of your install script or issue these commands before running your install script

```sh
sed -i 's/celery==5.1.2/celery==5.2.7/' web/requirements.txt
sed -i 's/# Download and install go 1.18/# Download and install go 1.19/' web/Dockerfile
sed -i 's/go1.18.2.linux-amd64.tar.gz/go1.19.5.linux-amd64.tar.gz/' web/Dockerfile
```

**Comment by haphuoctinh0303** [comment]
![Screenshot 2023-03-02 122037](https://user-images.githubusercontent.com/73652765/222338143-260074b0-a07c-4d37-a52d-e9977f5d018c.png)

I updated it as follows, but still the same error

**Comment by gustavorobertux** [comment]
> ![Screenshot 2023-03-02 122037](https://user-images.githubusercontent.com/73652765/222338143-260074b0-a07c-4d37-a52d-e9977f5d018c.png)
> 
> I updated it as follows, but still the same error

Show the error screen, please, so it's easier to help. ;)

**Comment by haphuoctinh0303** [comment]
> > ![Screenshot 2023-03-02 122037](https://user-images.githubusercontent.com/73652765/222338143-260074b0-a07c-4d37-a52d-e9977f5d018c.png)
> > I updated it as follows, but still the same error
> 
> Show the error screen, please, so it's easier to help. ;)

hiii, am fixed ^^

**Comment by gustavorobertux** [comment]
> 

Nice !

**Comment by haphuoctinh0303** [comment]
@gustavorobertux i begin see this error :D 
![image](https://user-images.githubusercontent.com/73652765/222418100-c661b18b-d237-4a91-83ef-8fd324fcb7d2.png)
![image](https://user-images.githubusercontent.com/73652765/222418200-626e992d-2596-4c67-9707-8a188f43bbc0.png)

**Comment by haphuoctinh0303** [comment]
> > 
> 
> Nice !

help me for my question below :((

**Comment by haphuoctinh0303** [comment]
> > 
> 
> Nice !

![image](https://user-images.githubusercontent.com/73652765/222423047-eadf9420-be5d-4edd-8853-322647699c32.png)
