### ISSUE TITLE
 Problem Install - Make build

### ISSUE THREAD

**Issue by felipemor** [yogeshojha/rengine#811]
Steps To Reproduce:

Example: steps to reproduce the behavior:

    Run 'make build..'
    See error... 'failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest]: exit code: 2'

**Comment by amine1996** [comment]
Hey, this can be fixed by changing the go version in the `web/Dockerfile` to 1.20 instead of 1.18.2.

**Comment by felipemor** [comment]
Solved !
