### ISSUE TITLE
Bug for install reNgine

### ISSUE THREAD

**Issue by felipemor** [yogeshojha/rengine#812]
=> ERROR [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 28/31] RUN pip3 install --upgrade setuptools pip &&     pip3 install -r /tmp/requirements.txt

**Comment by ancodesh** [comment]
i have same problem

**Comment by sasaga** [comment]
The error seems to come from the installation of **celery==5.1.2**, edit the file ./web/requirements.txt change the line **#celery==5.1.2** to **celery** and it will let you continue.

**Comment by felipemor** [comment]
Thanks @sasaga ! But now show a new error 

![image](https://user-images.githubusercontent.com/77069159/217920515-209958bb-eb56-44cd-b201-9164678afc39.png)

Do you know the solution ?
