### ISSUE TITLE
If the results returned during the directory scan are similar, just ignore them

### ISSUE THREAD

**Issue by invoke888** [yogeshojha/rengine#821]
![1](https://user-images.githubusercontent.com/70275727/219899553-b0a73f43-4004-48bd-af13-eebc91f5cf0f.png)
There will be many same and meaningless directory results

**Comment by psyray** [comment]
Fixed by https://github.com/yogeshojha/rengine/pull/963 with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200

Endpoints duplication is checked
