### ISSUE TITLE
Feature - Add number of found items on directory search results

### ISSUE THREAD

**Issue by iwm911** [yogeshojha/rengine#822]
**Is your feature request related to a problem? Please describe.**
its sometimes slow to load a large set of results (which are generated from a wildcard response )

**Describe the solution you'd like**
add the number of records found to the directory scan metadata in the Scan Findings --> Directories page
![image](https://user-images.githubusercontent.com/2302032/220043614-04c6268d-6191-4c0a-8551-1cf1e146c903.png)

**Comment by psyray** [comment]
Fixed with #1050
