### ISSUE TITLE
Bug - make build error

### ISSUE THREAD

**Issue by geekjy** [yogeshojha/rengine#823]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

A summary of the issue.

#0 51.57 github.com/projectdiscovery/httpx/common/hashes/jarm
#0 51.72 github.com/projectdiscovery/httpx/common/httpx
#0 51.83 github.com/projectdiscovery/httpx/common/customports
------
failed to solve: executor failed running [/bin/sh -c GO111MODULE=on go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest]: exit code: 2
make: *** [Makefile:25: build] Error 17

### Steps to Reproduce

1. When I am scanning the domains, this happens
2. ...make build error
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)

### Technical details

Please list out any technical details such as operating environment.

**Comment by SugiB3o** [comment]
Update Dockerfile - go language to 1.19 and command update below
https://github.com/SugiB3o/Rengine/blob/master/web/Dockerfile
