### ISSUE TITLE
Vulnerability scanning gets stuck at 75% always. WHOis is not working

### ISSUE THREAD

**Issue by iowuraku** [yogeshojha/rengine#825]
Hi there Im using the default configs to run a vulnerability scan and it doesnt work it always get stuck on 75% is there a workaround this. I asked the discord group aided some in installing but no feedback on my issue :(

**Comment by psyray** [comment]
Fixed by https://github.com/yogeshojha/rengine/pull/963 with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
