### ISSUE TITLE
Feature - Handling Authentication. How can I auth in Webapp? And can I somewhere put session cookie?

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#826]
Hi.

How can I auth in Webapp with username/password? 

About feature request.
And can I somewhere put session cookie I copy from web browser?
Or can you add this feature to rengine.

Thanks for great project!

**Comment by psyray** [comment]
Use custom header in Scan Engine YAML for that
![image](https://github.com/yogeshojha/rengine/assets/1230954/06177d54-de9a-44a7-b1fb-66320257b174)

With that you could auth to a lot of UI (Auth basic etc..)
https://developer.mozilla.org/fr/docs/Web/HTTP/Headers/Authorization

And for the sessions cookie, set it in the Cookie header

Not all tools use custom header

Tools that use it
- FFUF
- Nuclei
- Hakrawler
- Katana
- Gospider
- Dalfox
- CRLFuzz
- HTTPx

It's a good coverage to launch scan in whitebox
