### ISSUE TITLE
Changing the port of Rengine

### ISSUE THREAD

**Issue by komradz86** [yogeshojha/rengine#828]
Hi,

I was wondering if I could change the port of rengine,

it duplicates with something running on 443, 
even that I changed a port in config/nginx/rengine.conf 
still get the error message.
 any help would be appreciated

**Comment by psyray** [comment]
Edit the docker-compose.yml, change here
![image](https://github.com/yogeshojha/rengine/assets/1230954/51806e93-cda3-40c4-b8e0-3ba141a8d4b7)
And run
```sh
make down
make up
```
