### ISSUE TITLE
Image gets loaded in the same page directly.

### ISSUE THREAD

**Issue by haxormad** [yogeshojha/rengine#83]
It would be great if Screnshots pops up and then can easily go back to where I was. It gets loaded directly in the same page and when I go back via browser back button, it leaves where I was previously.

**Comment by yogeshojha** [comment]
Hi @haxormad,
You are right. I will work on this! How about hover? Hover to load the image inside the page itself. Will it do any better?

Thanks for creating this issue.

**Comment by haxormad** [comment]
Rather than Hover, I guess Click gonna be better to open it fully popped out as sometimes mistakenly pointer could reach the Screenshot place.  And hover to show lil bit larger image in size than normally it shows without click/hover would be an additional awesome feature to have. So that I could know which asset is interesting enough to look at.

**Comment by yogeshojha** [comment]
Great @haxormad , I will work on this!

**Comment by yogeshojha** [comment]
Hi @haxormad,

I just fixed this, can you please verify this, if it works as expected, I will then merge into master. 

`git clone https://github.com/yogeshojha/rengine --branch fix/imageload`

**Comment by yogeshojha** [comment]
Fixed
