### ISSUE TITLE
Directory scan error reported

### ISSUE THREAD

**Issue by testoiubvtc** [yogeshojha/rengine#838]
Directory scan error reported
Scan failed due to ERROR: A string literal cannot contain NUL (0x00) characters.Bug - Title of Bug
[](url)
![111](https://user-images.githubusercontent.com/100524176/225798847-1d327ea4-5ebe-4875-96e5-1c8c210d4b22.png)

**Comment by psyray** [comment]
Check it in v2 and if it persists open a new issue
