### ISSUE TITLE
Dashboard not rendering properly

### ISSUE THREAD

**Issue by plavanabond** [yogeshojha/rengine#848]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

A summary of the issue.
After updating and installing latest rengine, the dashboard or the login page is not rendering properly. Previously it was rendering properly. After the update the login page and dashboard not rendering properly in browser. The port previously was on port 80 or 443. Now the port also changed to 8000.

### Steps to Reproduce

1. After installing rengine, go to browser and access the login page. 
2. Rengine failing to render properly.

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
* yes
![rengine](https://user-images.githubusercontent.com/115732259/227759082-a0e31a90-f266-4e43-a83a-a23398bed971.png)

### Technical details

Please list out any technical details such as operating environment.

**Comment by 4val0v** [comment]
I just installed it and encountered the same issue
port: 443
<img width="817" alt="image" src="https://user-images.githubusercontent.com/11297476/228107173-58b0ea7c-fc37-4066-9156-cc5b47d469a2.png">
port: 8000
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/11297476/228107483-1957bfa0-b79b-430e-ab40-231437e01260.png">
docker ps:
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/11297476/228108049-d4275f46-470e-4a82-ace8-07ddface64fa.png">

**Comment by 4val0v** [comment]
@plavanabond this solution solved my issue - https://github.com/yogeshojha/rengine/issues/853#issuecomment-1486585368

**Comment by plavanabond** [comment]
thanks @4val0v for the solution. Worked for me.

**Comment by ayushbhetwal** [comment]
Hello i tried the above solution by adding lines in docker-compose.yml but still the page is not rendering.

**Comment by ayushbhetwal** [comment]
![image](https://user-images.githubusercontent.com/120379432/229040861-0bf9ac7f-ef48-4b01-8930-8f6377fa44f4.png)

**Comment by sohilstha7** [comment]
(https://user-images.githubusercontent.com/50328924/229382930-a47f3d51-b5bc-46bb-865c-a37cb53fcd57.png)

**Comment by sohilstha7** [comment]
Change DEBUG=0 to 1 and it will render (file => docker-compose.yml)
![1](https://user-images.githubusercontent.com/50328924/229382996-701c45d3-0f29-4034-ae75-98e51673b2c5.png)
![Screenshot 2023-04-03 041934](https://user-images.githubusercontent.com/50328924/229382998-1a99ace4-7392-4ea8-a059-e25a2edaf582.png)

**Comment by yogeshojha** [comment]
Hi @plavanabond , you are supposed to access dashboard via https://127.0.0.1 and not via port 8000 unless you are using it for dev or debug purpose.
