### ISSUE TITLE
Bug - Title of Bug

### ISSUE THREAD

**Issue by kunshdeep2812** [yogeshojha/rengine#852]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

A summary of the issue.
After successful installation the rengine GUI  not render to 443 port on vps, its running on default docker port i.e., 8000. I tried to change the port manually also but didn't work.

### Steps to Reproduce

1. Create vps on digital ocean
2. install all pre-requisites as per installation instruction(s)
3. Then run ./install.sh and wait to finish the installation
4. open VPS IP address (https://IP) but not working its work on (http:ip:8000) and GUI not properly rendered

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

Please list out any technical details such as operating environment.
![image](https://user-images.githubusercontent.com/40362096/228170989-835b7822-5397-4bd0-9af2-2d5e9a81a0c7.png)
![image](https://user-images.githubusercontent.com/40362096/228172334-781c5342-9e84-4abb-9a86-f388eeb1598c.png)

**Comment by 4val0v** [comment]
This issue is described earlier - https://github.com/yogeshojha/rengine/issues/848
@yogeshojha can you research this issue ?

**Comment by kunshdeep2812** [comment]
As per this article "https://github.com/yogeshojha/rengine/issues/853" recommendation temporary issue gets fixed at my side
