### ISSUE TITLE
Error when updating by running make down && git pull && make build && make up

### ISSUE THREAD

**Issue by CSPGhostDelta** [yogeshojha/rengine#854]
COMPOSE_DOCKER_CLI_BUILD=1 docker-compose -f docker-compose.yml down
[+] Running 1/0
 ⠿ rengine  Warning: No resource found to remove                                                                                                                         0.0s
error: Pulling is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit.
fatal: Exiting because of an unresolved conflict

how to fix this

**Comment by psyray** [comment]
Check it in v2 and if it persists open a new issue
