### ISSUE TITLE
failed to solve: process "/bin/sh -c go install -v github.com/OWASP/Amass/v3/...@latest" did not complete successfully:

### ISSUE THREAD

**Issue by giuseppeputzolu** [yogeshojha/rengine#855]
During the quick installation on Ubuntu 22.04 LTS and Kali Linux appears this error: 

=> ERROR [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 15/31] RUN go install -v github.com/OWASP/Amass/v3/...@latest                                                       2.3s
------
 > [docker.pkg.github.com/yogeshojha/rengine/rengine:latest 15/31] RUN go install -v github.com/OWASP/Amass/v3/...@latest:
#0 0.886 go: downloading github.com/OWASP/Amass/v3 v3.23.1
#0 1.056 go: downloading github.com/OWASP/Amass v2.6.0+incompatible
#0 2.264 go: github.com/OWASP/Amass/v3/...@latest: github.com/OWASP/Amass/v3@v3.23.1: parsing go.mod:
#0 2.264        module declares its path as: github.com/owasp-amass/amass/v3
#0 2.264                but was required as: github.com/OWASP/Amass/v3
------
failed to solve: process "/bin/sh -c go install -v github.com/OWASP/Amass/v3/...@latest" did not complete successfully: exit code: 1
make: *** [Makefile:25: build] Error 17

reNgine installation failed!!

**Comment by thistehneisen** [comment]
```
```

**Comment by dontclickthelink** [comment]
Try changing line 78 in rengine/web/Dockerfile to:
RUN go install -v github.com/owasp-amass/amass/v3/...@master

**Comment by yahyatoubali** [comment]
> Try changing line 78 in rengine/web/Dockerfile to: RUN go install -v github.com/owasp-amass/amass/v3/...@master

or
RUN go install -v github.com/owasp-amass/amass/v3/...@latest

**Comment by giuseppeputzolu** [comment]
> Try changing line 78 in rengine/web/Dockerfile to: RUN go install -v github.com/owasp-amass/amass/v3/...@master

Thankyou very much. It works fine! :)
