### ISSUE TITLE
I have installed follwing instuctions but I cannot access web dashboad. Please help me

### ISSUE THREAD

**Issue by why-always-me-mta** [yogeshojha/rengine#859]
![image](https://user-images.githubusercontent.com/74256315/229278444-43995676-52b5-43bd-a53d-b07044d3d65f.png)

![image](https://user-images.githubusercontent.com/74256315/229278334-86ff59d6-4e1d-4f91-94b9-ad43d7c088cf.png)
![image](https://user-images.githubusercontent.com/74256315/229278349-7c37544d-2ec3-43ff-8c45-bb4b67364ef5.png)

**Comment by Denis-Germano** [comment]
Same problem here. The port that opens is 8000, but if you access that port, the staticfiles are not loaded.

**Comment by why-always-me-mta** [comment]
> 

thank you very much

**Comment by yuling456654** [comment]
May I ask how you run successfully ?
```
go: github.com/hakluke/hakrawler@latest: module github.com/hakluke/hakrawler: Get "https://proxy.golang.org/github.com/hakluke/hakrawler/@v/list": dial tcp 172.217.160.81:443: i/o timeout
The command '/bin/sh -c go install -v github.com/hakluke/hakrawler@latest' returned a non-zero code: 1
ERROR: Service 'celery' failed to build : Build failed
make: *** [Makefile:25: build] Error 1
```
my error

**Comment by CSPGhostDelta** [comment]
I have the same issue. Just reinstalled the rEngine and then I got this error.

**Comment by why-always-me-mta** [comment]
> May I ask how you run successfully ?
> 
> ```
> go: github.com/hakluke/hakrawler@latest: module github.com/hakluke/hakrawler: Get "https://proxy.golang.org/github.com/hakluke/hakrawler/@v/list": dial tcp 172.217.160.81:443: i/o timeout
> The command '/bin/sh -c go install -v github.com/hakluke/hakrawler@latest' returned a non-zero code: 1
> ERROR: Service 'celery' failed to build : Build failed
> make: *** [Makefile:25: build] Error 1
> ```
> 
> my error

check your network when installing. Then I kill port 443 and I can continue building

**Comment by why-always-me-mta** [comment]
> I have the same issue. Just reinstalled the rEngine and then can't access the dashboard

firstly, i installed on ubuntu 22.04 but it is not successful. Then i installed on ubuntu 20.04

**Comment by yuling456654** [comment]
Thank you so much.
But there is another problem, the page is not displayed normally after login, as follows:
![b5f0dc77f220d27e7dcecaf2229ef8f3](https://user-images.githubusercontent.com/55023542/229333554-0c880040-2323-4a06-b939-ad02ee3f721e.png)

What is the problem, Excuse?

**Comment by why-always-me-mta** [comment]
> Thank you so much. But there is another problem, the page is not displayed normally after login, as follows: ![b5f0dc77f220d27e7dcecaf2229ef8f3](https://user-images.githubusercontent.com/55023542/229333554-0c880040-2323-4a06-b939-ad02ee3f721e.png)
> 
> What is the problem, Excuse?
https://github.com/yogeshojha/rengine/issues/859#issuecomment-1493040020  
i fixed my problem following it

**Comment by yuling456654** [comment]
> > Thank you so much. But there is another problem, the page is not displayed normally after login, as follows: ![b5f0dc77f220d27e7dcecaf2229ef8f3](https://user-images.githubusercontent.com/55023542/229333554-0c880040-2323-4a06-b939-ad02ee3f721e.png)
> > What is the problem, Excuse?
> > [#859 (comment)](https://github.com/yogeshojha/rengine/issues/859#issuecomment-1493040020)
> > i fixed my problem following it

Thank you for your help.

**Comment by Denis-Germano** [comment]
@yuling456654 
I solved the problem by reading other error threads here on github.
To resolve this issue, you have to edit the **Docker-compose.yml** file.
Adding on line 116 the following:

`networks:
      rengine_network:
        aliases:
          - rengine`
