### ISSUE TITLE
502 Bad Gateway - Please help me

### ISSUE THREAD

**Issue by Giova200** [yogeshojha/rengine#861]
When i try to acces https://IP it gives me 502 Bad Gateway. Help me please.
![Screenshot (219)](https://user-images.githubusercontent.com/118677894/229359390-9f447e68-c8ce-4188-b4bf-f18bd1e54ea5.png)

**Comment by AnonymousWP** [comment]
Tried `sudo make down && sudo make up`?

**Comment by 4val0v** [comment]
@Giova200 Try https://github.com/yogeshojha/rengine/pull/850

**Comment by jaykumarjp** [comment]
keep system configuration high, my is 8 core cpu and 16 gb ram. 
previously i faced 502 many times, always i has to down and up again. but after higher specs not faced 502
