### ISSUE TITLE
BUG - Vulnerability scan not working Please help me

### ISSUE THREAD

**Issue by Giova200** [yogeshojha/rengine#864]
When i start a scan(FULL or Reccomended) all go right but the vulnerability scan end instantly and don't give any output/vulnerability.

Kali 2023.1
Please help

**Comment by 4val0v** [comment]
I have the same issue :(
@AnonymousWP the tor used by default for the vulnerability scanner ?
I see only https://github.com/yogeshojha/rengine/blob/master/web/reNgine/tasks.py#L2633 where the tor is hard-coded

**Comment by 4val0v** [comment]
@AnonymousWP need to fix the following lines https://github.com/yogeshojha/rengine/blob/master/web/reNgine/tasks.py#L1790,L1794
