### ISSUE TITLE
Feature - implement TOR bridge

### ISSUE THREAD

**Issue by AnonymousWP** [yogeshojha/rengine#867]
**Is your feature request related to a problem? Please describe.**

Yes, some firewalls block TOR traffic, which results in an endless loop of TOR warnings (resulting in the fact that no scans are being performed):

```
tor_1          | Apr 04 09:30:15.000 [warn] 134 connections have failed:
tor_1          | Apr 04 09:30:15.000 [warn]  134 connections died in state connect()ing with SSL state (No SSL object)
tor_1          | Apr 04 09:30:20.000 [notice] Tried for 120 seconds to get a connection to [scrubbed]:443. Giving up. (waiting for rendezvous desc)
tor_1          | Apr 04 09:30:25.000 [warn] Problem bootstrapping. Stuck at 45% (requesting_descriptors): Asking for relay descriptors. (Operation timed out; TIMEOUT; count 136; recommendation warn; host <redacted> at <redacted>)
```

**Describe the solution you'd like**

Implement something like a TOR bridge, which can solve the issue: https://bridges.torproject.org/

**Describe alternatives you've considered**

Give users the option to disable TOR and use reNgine without it.

**Comment by psyray** [comment]
@AnonymousWP TOR has benn removed from v2 does your issue still relevant ?

**Comment by AnonymousWP** [comment]
No, as TOR is no longer being used in V2, then this issue is indeed irrelevant now. Closing.
