### ISSUE TITLE
ERROR [rengine_celery 15/31] RUN go install -v github.com/OWASP/Amass/v3/...@latest

### ISSUE THREAD

**Issue by irshadpathan** [yogeshojha/rengine#868]
I try to 10 time more then install reengine vpc

i try Ubuntu 20*,22
 and also debian 10,11 version but same issue facing please help what is the problem 

how to resolve this issue 

` => ERROR [rengine_celery 15/31] RUN go install -v github.com/OWASP/Amass/v3/...@latest                                                        2.4s 
------                                                                                                                                              
 > [rengine_celery 15/31] RUN go install -v github.com/OWASP/Amass/v3/...@latest:
#0 0.960 go: downloading github.com/OWASP/Amass/v3 v3.23.1
#0 1.092 go: downloading github.com/OWASP/Amass v2.6.0+incompatible
#0 2.287 go: github.com/OWASP/Amass/v3/...@latest: github.com/OWASP/Amass/v3@v3.23.1: parsing go.mod:
#0 2.287        module declares its path as: github.com/owasp-amass/amass/v3
#0 2.287                but was required as: github.com/OWASP/Amass/v3
------
failed to solve: process "/bin/sh -c go install -v github.com/OWASP/Amass/v3/...@latest" did not complete successfully: exit code: 1
make: *** [Makefile:25: build] Error 17
`

**Comment by 4val0v** [comment]
@irshadpathan try https://github.com/yogeshojha/rengine/pull/827/commits/e649735bdb4ef7049e5d600dc0056a1fbce73d3f

**Comment by AnonymousWP** [comment]
Pull the latest changes from the repo, it has been fixed: https://github.com/yogeshojha/rengine/commit/95807a952d25c5e5786051ccc898944d4046c55f. You can close the issue if it got fixed for you.

**Comment by hporterr** [comment]
I think this may be a similar issue as the original #868 issue. Trying to run ./install.sh but running into the below issue. is this a GO version incompatibility issue? @AnonymousWP      as of 05/03/2023
-------------------------------------------------------------------------------------------------------------------------------------------

ERROR [rengine_celery-beat 12/31] RUN go install -v github.com/hakluke/hakrawler@latest          0.9s 

failed to solve: process "/bin/sh -c go install -v github.com/hakluke/hakrawler@latest" did not complete successfully: exit code: 2
make: *** [Makefile:25: build] Error 17

**Comment by cyb3rzest** [comment]
OWASP-AMASS installation directory is changed.
go install -v github.com/owasp-amass/amass/v3/...@master

**Comment by chinpchan8** [comment]
I face the same issue:

failed to solve: process "/bin/sh -c go install -v github.com/hakluke/hakrawler@latest" did not complete successfully: exit code: 2
make: *** [Makefile:22: up] Error 17

Even if i run below commend: 
go install -v github.com/owasp-amass/amass/v3/...@master
go: warning: "github.com/owasp-amass/amass/v3/...@master" matched no packages

What can i do?

**Comment by cyb3rzest** [comment]
Firstly, remove the installed go version in your system/vps.
Then, install the latest version by downloading the package using the website download link.

Then install amass and all tools

**Comment by sitanshuforever** [comment]
> I face the same issue:
> 
> failed to solve: process "/bin/sh -c go install -v github.com/hakluke/hakrawler@latest" did not complete successfully: exit code: 2 make: *** [Makefile:22: up] Error 17
> 
> Even if i run below commend: go install -v github.com/owasp-amass/amass/v3/...@master go: warning: "github.com/owasp-amass/amass/v3/...@master" matched no packages
> 
> What can i do?

I had the same issue in my Docker installation after updating.  There was problem regarding go version. Make sure your web/Dockerfile is identical to the one in repository. specifically where the go is getting installed.

**Comment by psyray** [comment]
Check it in v2 and if it persists open a new issue
