### ISSUE TITLE
Bug - Scan History Page Doesn't Load

### ISSUE THREAD

**Issue by ubaidahmedIN** [yogeshojha/rengine#871]
### Issue Summary

My rEngine instance has discovered 790 targets, 52,645 subdomains and 521,246 endpoints. Now, I am unable to access the Scan History > Scan History page. I can see the content when I try to access other pages like SubScan History, Scheduled Scan, All Subdomains and All Endpoints. The issue is only with the Scan History page. 

I am using version 1.3.6

### Technical details

I have done the setup on Digital Ocean's droplet.

**Comment by psyray** [comment]
Check it in v2 and if it persists open a new issue

If it persists upgrade your environment.
