### ISSUE TITLE
Scan stack after short time

### ISSUE THREAD

**Issue by roysG** [yogeshojha/rengine#875]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Steps to Reproduce

1. When i start scan 
2.  After some time the loading is stack..
3. 

I wait for 7 hours and still the same

### Technical details

Please list out any technical details such as operating environment.

**Comment by AnonymousWP** [comment]
Why are you closing an issue you're facing without it being solved or even answered?

It's a regression that has been introduced when I opened a PR. Update reNgine from my repo where it's fixed: https://github.com/AnonymousWP/rengine/tree/fix-scan-issues. So, `git pull https://github.com/AnonymousWP/rengine.git fix-scan-issues`.
