### ISSUE TITLE
Feature: Grep using gf and gf-pattern

### ISSUE THREAD

**Issue by RAVE-V** [yogeshojha/rengine#88]
Optional Grepping the output after fetching the endpoints from gau and hakwaler.
Showing possibility of open redirect or other vulns using gf and gf patterns.

**Comment by yogeshojha** [comment]
Hi @RAVE-V 
Thanks for your suggestions, I will implement this as well. 

🚀

**Comment by yogeshojha** [comment]
Finally done 🚀  

![Screenshot 2021-05-16 at 12 51 56 AM](https://user-images.githubusercontent.com/17223002/118375690-ed17e500-b5e0-11eb-9211-223ce0652700.png)

Also, you get this badge on urls
![Screenshot 2021-05-16 at 12 53 03 AM](https://user-images.githubusercontent.com/17223002/118375712-146eb200-b5e1-11eb-934b-f62b75b34f5f.png)


Can't wait to release.

**Comment by yogeshojha** [comment]
Released in 1.0, Thanks
