### ISSUE TITLE
Connecting to golang.org failed: Network is unreachable.

### ISSUE THREAD

**Issue by En0t5** [yogeshojha/rengine#889]
Step 6/42 : RUN apt update -y && apt install -y  --no-install-recommends     build-                 essential     cmake     firefox     gcc     git     libpq-dev     libpq-dev     lib                 pcap-dev     netcat     postgresql     python3     python3-dev     python3-pip                      python3-netaddr     wget     x11-utils     xvfb     python3-cffi     python3-brotli                      libpango-1.0-0     libpangoft2-1.0-0     geoip-bin     geoip-database
 ---> Using cache
 ---> 70e32d4a4ddf
Step 7/42 : RUN wget https://golang.org/dl/go1.20.linux-amd64.tar.gz
 ---> Running in f50f2d5175d4
--2023-04-18 15:41:20--  https://golang.org/dl/go1.20.linux-amd64.tar.gz
Resolving golang.org (golang.org)... 172.217.163.49, 2404:6800:4012:4::2011
Connecting to golang.org (golang.org)|172.217.163.49|:443... failed: Connection ref                 used.
Connecting to golang.org (golang.org)|2404:6800:4012:4::2011|:443... failed: Networ                 k is unreachable.
The command '/bin/sh -c wget https://golang.org/dl/go1.20.linux-amd64.tar.gz' retur                 ned a non-zero code: 4
ERROR: Service 'celery' failed to build : Build failed

I found that

curl https://golang.org/dl/go1.20.linux-amd64.tar.gz

https://go.dev/dl/go1.20.linux-amd64.tar.gz  Moved Permanently

**Comment by AnonymousWP** [comment]
Have you updated reNgine from the repo? Try again. Works fine for me.

**Comment by En0t5** [comment]
Yes , I'm using the latest repo.I have solved the problem.

Modify web/Dockefile
https://golang.org/dl/go1.20.linux-amd64.tar.gz

to
https://dl.google.com/go/go1.20.linux-amd64.tar.gz

**Comment by 1205747671** [comment]
> https://dl.google.com/go/go1.20.linux-amd64.tar.gz

thanks！

**Comment by AnonymousWP** [comment]
> Yes , I'm using the latest version.I have solved the problem.
> 
> Modify web/Dockefile
> https://golang.org/dl/go1.20.linux-amd64.tar.gz
> 
> to
> https://dl.google.com/go/go1.20.linux-amd64.tar.gz
> 
> 

Then why does the first link work fine for me?
