### ISSUE TITLE
Explain to me, please

### ISSUE THREAD

**Issue by liverpool-is-the-best** [yogeshojha/rengine#891]
I can't add target from localhost, can you explain to me

**Comment by AnonymousWP** [comment]
Define "I can't add target". You should explain your issue in more detail. Post logs etc.

**Comment by zinwelzl** [comment]
http://127.0.0.1:8080
"Invalid Domain or IP"

**Comment by AnonymousWP** [comment]
Mate, how do you expect anyone to help you if you give such little information?

**Comment by zinwelzl** [comment]
Targets - Add Target - http://127.0.0.1:8080/ - "http://127.0.0.1:8080/ is not a valid domain Name"
or
Quick Add - Target - http://127.0.0.1:8080/ - "Invalid Domain or IP"

**Comment by ViperBlackSkull** [comment]
Try adding a domain name i.e github.com, it should work.

**Comment by psyray** [comment]
Check in v2 and if it still persists open a new issue
