### ISSUE TITLE
Directory fuzzing failed with error 

### ISSUE THREAD

**Issue by jaykumarjp** [yogeshojha/rengine#892]
Error a-string-literal-cannot-contain-nul-0x00-characters

### Issue Summary
got an error when directorry guzzing
a-string-literal-cannot-contain-nul-0x00-characters
Ref: 
https://stackoverflow.com/questions/57371164/django-postgres-a-string-literal-cannot-contain-nul-0x00-characters

### Steps to Reproduce

1. Just add target and do full scan
2. check scan progress and see fuzzing failed with error

**Comment by jaykumarjp** [comment]
in iis server tested

**Comment by rhamaa** [comment]
i also faced this issue on my local
![image](https://user-images.githubusercontent.com/26088039/235600953-b33de6af-e5ac-4aa7-ba20-0ac9df2c5b36.png)

Version : 1.3.6

**Comment by jaykumarjp** [comment]
> i also faced this issue on my local ![image](https://user-images.githubusercontent.com/26088039/235600953-b33de6af-e5ac-4aa7-ba20-0ac9df2c5b36.png)
> 
> Version : 1.3.6

do you also testing on iis server ?

**Comment by rhamaa** [comment]
> > i also faced this issue on my local ![image](https://user-images.githubusercontent.com/26088039/235600953-b33de6af-e5ac-4aa7-ba20-0ac9df2c5b36.png)
> > Version : 1.3.6
> 
> do you also testing on iis server ?

no i tested in MacOS - Docker instalation

**Comment by jaykumarjp** [comment]
looks dev team busy, this happening whenver i testing iis product (website), noodejs and php websites working fine

**Comment by psyray** [comment]
Check in v2 and if it still persists open a new issue
Anyway directory search has some problem for the moment, fix is on his way
