### ISSUE TITLE
Bug - Resolve IP Address to domain 500 error

### ISSUE THREAD

**Issue by rhamaa** [yogeshojha/rengine#896]
### Issue Summary
Error occur when calling `api/tools/ip_to_domain/?format=json&ip_address=<IP>`, when debug is enabled, it shows this error
![image](https://user-images.githubusercontent.com/26088039/236011932-f4c7222d-d2c6-4b92-80b9-e7756d0f201f.png)

### Steps to Reproduce

1. Go to Target Menu -> Add Target -> Add IP Address
2. Input IP Address
3. Click Resolve IP Address

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: yes

### Technical details

OS : MacOS Ventura 13.3.1 (22E261)
Docker Compose version v2.17.2
Docker version 20.10.24, build 297e128
reEngine 1.3.6

**Comment by psyray** [comment]
Check in v2 and if it still persists open a new issue
