### ISSUE TITLE
Scan breaks at subdomain enumuration

### ISSUE THREAD

**Issue by Meetzanonymous** [yogeshojha/rengine#900]
I started scanning `6` days prior and it is still collecting the subdomains. Seems like it is broken.

![image](https://github.com/yogeshojha/rengine/assets/30690468/e2995468-7246-4338-86cb-0123c2447efd)

**Comment by Meetzanonymous** [comment]
Thanks for the suggestion, but I have already tried it still it gets broke!

**Comment by AnonymousWP** [comment]
Weird, which scan engine/type? All works fine for me. Try my repo instead, contains various fixes.

**Comment by psyray** [comment]
Check in v2 and if it still persists open a new issue
