### ISSUE TITLE
Rengine 2.0.x Jasper - Feature requests

### ISSUE THREAD

**Issue by IOCsec** [yogeshojha/rengine#906]
**1. OpenVAS scanner** - The Open Source variant of the premium scanner Nessus from Tenable (very powerful into identify vulns).

 **2. Nikto scanner**

**3. All vulnerability scanners: Option to have/save different scan options per URL/Endpoint/Asset**
**Example:** Use Nuclei to scan 1 Endpoint only with specific templeate.
**So:** Choose Scanner > Select Templeate (or command) > Select URL (Endpoint) > Scan.

**4. Rengine > Scan History: Filter by what is already scanned / not scanned (subdomains)** 

**5. Option to download as .txt: IPs, Ports, Technologies.**

**6. Vulnerabilities: Option to select 1 vulnerability and "Mark as resolved OR reported"**
And filter Vulnerabilities by **All, Resolved** and **Reported** **- time saving**
The Vulnerability menu should be rebuilt from scratch. It is the most cluttered menu, it has a table that does not fit on a full laptop screen (vertical scroll), you cannot change Status etc.
Add click to copy CURL command. Now curl command is displayed on 4-8 lines (the display does not have enough space). And some commands don't work in the terminal after you copy them because of copying >  paste.

You through your actions have given and are giving the opportunity to some hard working people to have jobs they otherwise might not have had.

Respect & Thank you for everything!

**Comment by psyray** [comment]
Thanks.
Feel free to help if you can
