### ISSUE TITLE
Bug- Api to fetch api is not working

### ISSUE THREAD

**Issue by samsaksham** [yogeshojha/rengine#914]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

A summary of the issue.

### Steps to Reproduce

1. When tried to used remgine api not able to fetch ips alscanned it is showing in depub mode no Ip is defined
2. ...
3. ...

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)

### Technical details

Please list out any technical details such as operating environment.

**Comment by AnonymousWP** [comment]
Your bug report is everything but clear.

**Comment by psyray** [comment]
Not clear, closing
