### ISSUE TITLE
Rengine 2.0 Jasper - Feature requests :  "show only new findings" in rescan mode

### ISSUE THREAD

**Issue by atolac** [yogeshojha/rengine#915]
Problem:
 When you rescan a target, you get the same results as before

Solution: 
Implement a tab or page in the UI to filter for the new findings for a new scan

Alternative:
 Provide a CLI solution which, given 2 scans, lists only the findings available in the second scan
 
Context:
This is important when targets are changing quickly or for blue-teamers who want to use it for regular (daily / weekly) scans

**Comment by psyray** [comment]
In v2 you could :

- Use logs
![image](https://github.com/yogeshojha/rengine/assets/1230954/dcff3212-0be1-444b-9d56-225790a60bf6)

- Scan history
![image](https://github.com/yogeshojha/rengine/assets/1230954/6c5e4b67-9475-4218-855b-94df5e28d8f5)
