### ISSUE TITLE
Feature Request: Grouping Domains for a Particular asset

### ISSUE THREAD

**Issue by CowlingBanana** [yogeshojha/rengine#92]
Issue: Right now, all targets are separately placed and as such it is difficult to figure out who owns what and which one does a particular domain belong to.

Fix: Creating a grouping function where a group of targets can be listed under a single group body wherein targets of an asset can be easily located and tasks can be applied simultaneously.

TLDR: Grouping domains of a particular asset would be great as it would help organize the recon workflow and cause less headaches!

**Comment by yogeshojha** [comment]
Awesome feature request, I will definitely work on this.

Thank you once again for the feature request.

**Comment by yogeshojha** [comment]
This will be worked upon using something like tags.

**Comment by uBadRequest** [comment]
> This will be worked upon using something like tags.

Could we configure scheduled scans based on tags?

**Comment by yogeshojha** [comment]
This is done, you can tag targets to an organization!
![organization](https://user-images.githubusercontent.com/17223002/129470488-04ee490d-4ad1-47a6-a9d0-0fea7bc5aa61.gif)

**Comment by yogeshojha** [comment]
You can also initiate scan for an entire organization as well. More: https://rengine.wiki/usage/organization/
