### ISSUE TITLE
Transfer ports.json to httpx

### ISSUE THREAD

**Issue by ipsecc** [yogeshojha/rengine#921]
Hi guys, this is a feature request:
Transfer naabu's port scan results to httpx, which will make httpx discover more endpoints than just 80 and 443.

**Comment by AnonymousWP** [comment]
Specify why you closed this.

**Comment by ipsecc** [comment]
In rengine 2.0, you can enable this function by setting 'enable_http_crawl': true
![image](https://github.com/yogeshojha/rengine/assets/40918024/c71af26c-e454-4711-b775-90ad94602017)
