### ISSUE TITLE
IP Range Scanning - Host Discovery

### ISSUE THREAD

**Issue by UncleJ4ck** [yogeshojha/rengine#925]
I was trying to initialize a scan using rengine and i wanted to scan a range of IPs and i couldn't find any option to do it beside uploading the list of IPs or resolving ASNs

**Comment by psyray** [comment]
Fixed by https://github.com/yogeshojha/rengine/pull/963 with @ocervell PR https://github.com/yogeshojha/rengine/pull/742
https://rengine.wiki/changelog/#200
