### ISSUE TITLE
Installation problem in amass

### ISSUE THREAD

**Issue by mojtaba13133** [yogeshojha/rengine#930]
In line 78 of the file
https://github.com/yogeshojha/rengine/blob/master/web/Dockerfile The command to install the amass tool as
_RUN go install -v github.com/owasp-amass/amass/v3/...@latest_
It has come that it is old and according to the change of direction of this tool, it should be
_RUN go install -v [github.com/owasp-amass/amass](url)/v4/...@master_
change so that the installation process is not disturbed

**Comment by psyray** [comment]
Check in v2 and open a new issue if it persists
