### ISSUE TITLE
Feature - AI, Can you also add HuggingChat?

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#931]
Can you also add HuggingChat, an open source chatbot assembled by Hugging Face.

https://huggingface.co
https://huggingface.co/chat/

Huggingface have huge number of free and opensource LLM for use.

**Comment by yogeshojha** [comment]
Hi @zinwelzl rengine 2.0 is integrated with openapi gpt. 

Thank you for this feature request though.
