### ISSUE TITLE
Bug -  Version 2.0 cant add and get list target

### ISSUE THREAD

**Issue by hungnt612** [yogeshojha/rengine#933]
### Issue Summary
Branch code: release/2.0.0
Error show error "DataTables warning: table id=list_target_table - Ajax error. For more information about this error, please see http://datatables.net/tn/7" when reload target page or add target.

![Screen Shot 2023-08-08 at 12 48 54](https://github.com/yogeshojha/rengine/assets/44539667/9c5fdac5-73de-4f88-9d52-e6eb4f4cc5ab)

**Comment by psyray** [comment]
A lot of bugs have been fixed in 2.0.1, so update and check again, open a new issue if it persists
