### ISSUE TITLE
How can I do burpsuite integration?

### ISSUE THREAD

**Issue by taygun08** [yogeshojha/rengine#934]
I want to add burp suite as vulnerability scanner. Any ways you can think of?

The only solution I can think of
Using a project like burp-cli-scan or writing a script that outputs in a format rengine can use
https://github.com/matmar-91/burp-cli-scan/tree/master

**Comment by psyray** [comment]
This project is really old, and Burp Suite have notably evolved since 2017.
It could be a good feature to use Burp, but I doubt that this project works in 2023.
Feel free to test it and open a new feature request
