### ISSUE TITLE
Getting Server Error (500) while starting the scan

### ISSUE THREAD

**Issue by AlishahMughal123** [yogeshojha/rengine#936]
<img width="1186" alt="Screenshot 2023-08-16 at 6 20 17 PM" src="https://github.com/yogeshojha/rengine/assets/52525188/5ec60a50-1d6b-4f5a-b4e1-fb07d2382464">
I'm getting above error, whenever I click on start for scan on my VPS.

@yogeshojha

**Comment by psyray** [comment]
Can't help you with so much informations
Get more infos and reopened an issue if it persists
Also activate debug to have stacktrace
https://github.com/yogeshojha/rengine/pull/994
