### ISSUE TITLE
Bug - Facing issue while running the scan

### ISSUE THREAD

**Issue by smurugaiyan** [yogeshojha/rengine#938]
While scanning my website, scan getting filed

Scan Failed due to: 'int' object is not subscriptable

![image](https://github.com/yogeshojha/rengine/assets/143489407/8be44ec2-1d06-4c06-ad66-b3abea37b3a6)

**Comment by AnonymousWP** [comment]
Try using my fork until 2.0 is out. It has quite a lot of fixes implemented.
