### ISSUE TITLE
Scan failed due to ERROR: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by tire-fire** [yogeshojha/rengine#939]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

Scan failed due to ERROR: 'int' object is not subscriptable

### Steps to Reproduce

I ran a Full scan against a domain. I added two subdomains. I initiated the scan. I came back 30minutes later and I get the error message:

Any other relevant information. For example, why do you consider this a bug and what did you expect to happen instead?

![msrdc_vj02saerYC](https://github.com/yogeshojha/rengine/assets/84106878/6c455574-d456-47a9-91df-a18d78205be2)

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: (yes / no)
yes

### Technical details
I ran it again viewing the output from docker compose and I found this:
```
rengine-celery-1       | [2023-08-29 19:49:16,711: ERROR/ForkPoolWorker-4] 'int' object is not subscriptable
rengine-celery-1       | [2023-08-29 19:49:16,719: ERROR/ForkPoolWorker-4] 'int' object is not subscriptable
rengine-celery-1       | [2023-08-29 19:49:30,490: ERROR/ForkPoolWorker-4] Expecting value: line 1 column 1 (char 0)
rengine-celery-1       | Traceback (most recent call last):
rengine-celery-1       |   File "theHarvester.py", line 6, in <module>
rengine-celery-1       |     from theHarvester import __main__
rengine-celery-1       |   File "/usr/src/github/theHarvester/theHarvester/__main__.py", line 16, in <module>
rengine-celery-1       |     from theHarvester.discovery import (
rengine-celery-1       |   File "/usr/src/github/theHarvester/theHarvester/discovery/securitytrailssearch.py", line 6, in <module>
rengine-celery-1       |     from theHarvester.parsers import securitytrailsparser
rengine-celery-1       |   File "/usr/src/github/theHarvester/theHarvester/parsers/securitytrailsparser.py", line 4, in <module>
rengine-celery-1       |     class Parser:
rengine-celery-1       |   File "/usr/src/github/theHarvester/theHarvester/parsers/securitytrailsparser.py", line 11, in Parser
rengine-celery-1       |     async def parse_text(self) -> tuple[set, set]:
rengine-celery-1       | TypeError: 'type' object is not subscriptable
```

**Comment by davdl92** [comment]
> Try my fork instead; it contains a lot of fixes.

Hello AnonymousWP,
first of all, many thanks for your work ! reNgine comes as huge opportunity for security analysts and your contribution to improve the current release version is awesome.

I'm having the same exact issue while performing a Port Scan activity and it seems this is not solved even after I git cloned your repo and did a fresh install using the .sh script. Are you able to test this and maybe point out the line of code that you focused on for the resolution ? I guess this is related to naabu tool...

**Comment by Squirlld** [comment]
Change line 1180 (in my example anyway) in web/reNgine/tasks.py, remove "['Port´]¨. The error is due to a change in naabu. 

Should be all good. :)

![image](https://github.com/yogeshojha/rengine/assets/103267953/1f358a4d-7f71-42e8-bcec-35b8dfcbd0a1)

**Comment by davdl92** [comment]
> Change line 1180 (in my example anyway) in web/reNgine/tasks.py, remove "['Port´]¨. The error is due to a change in naabu.
> 
> Should be all good. :)
> 
> ![image](https://user-images.githubusercontent.com/103267953/266037665-1f358a4d-7f71-42e8-bcec-35b8dfcbd0a1.png)

Confirming this worked like a charm ! Thank you :)

**Comment by AnonymousWP** [comment]
You guys are right; I could reproduce the issue on my fork, so sorry for assuming my fork wasn't the problem. I'll shortly push the fix @Squirlld suggested (thanks for that btw).

**Comment by AnonymousWP** [comment]
Uhh, after making this change I only get 502 errors and this:

![image](https://github.com/yogeshojha/rengine/assets/50231698/93f33eed-e366-472d-b6ea-6e938cb88e75)

**Comment by qanzhi111** [comment]
THANK YOU !!!

**Comment by ludbaziza** [comment]
> Change line 1180 (in my example anyway) in web/reNgine/tasks.py, remove "['Port´]¨. The error is due to a change in naabu.
> 
> Should be all good. :)
> 
> ![image](https://user-images.githubusercontent.com/103267953/266037665-1f358a4d-7f71-42e8-bcec-35b8dfcbd0a1.png)

Hello How to open task.py? i dont understand. By the way i have same issue
