### ISSUE TITLE
ginandjuice.shop scan with version 2 never end, version 1.3.6 end in 15 minutes

### ISSUE THREAD

**Issue by zinwelzl** [yogeshojha/rengine#946]
Hi.

Version 2 scan ginandjuice.shop never end, almost 24 hours now, portscan error, other scans just hang.

Old version 1.3.6 end in 15 minutes and with all jobs.

Can you try it and see.
https://portswigger.net/blog/gin-and-juice-shop-put-your-scanner-to-the-test
https://ginandjuice.shop/vulnerabilities

**Comment by psyray** [comment]
A lot of bugs have been fixed in 2.0.1, so update and check again, open a new issue if it persists
Ginandjuice.shop scan works well for me on v2.0.1
![image](https://github.com/yogeshojha/rengine/assets/1230954/d27dcfcb-bfb0-456e-956a-69d03d5b05c5)
