### ISSUE TITLE
Feature - Schedule reoccurring scans and identify changes

### ISSUE THREAD

**Issue by uBadRequest** [yogeshojha/rengine#95]
**Is your feature request related to a problem? Please describe.**
Unable to detect changes in a target over a period of time and schedule reoccurring scans.

**Describe the solution you'd like**
Schedule new scans, weekly/monthly, and then detecting if there were any changes in the title, status code, new subdomains for a target, or a previous subdomain that wasn't active has became active.

The notification feature would come in handy along with this feature. Imagine getting notifications after a scan has detected changes in a target, allowing you to act quickly.

**Comment by yogeshojha** [comment]
Thanks @uBadRequest for the feature request. This feature is certainly coming in the coming versions. I will keep you updated.

**Comment by yogeshojha** [comment]
Yay, this is available V0.4. 🎉
