### ISSUE TITLE
celery-beat_1  | Error: No nodes replied within time constraint

### ISSUE THREAD

**Issue by ancodesh** [yogeshojha/rengine#953]
![image](https://github.com/yogeshojha/rengine/assets/99588219/74cac56f-f1cf-4802-ae9f-e2ba0ac01169)

**Comment by psyray** [comment]
Check if all the docker are started, if not restart it all `docker-compose restart` from rengine folder
Also look at the `make logs` for further information about your error
I think the celery or redis docker are not started

**Comment by psyray** [comment]
Check in v2 and open a new issue if it persists
