### ISSUE TITLE
Bug - Depreciated Selenium methods API IPToDomain

### ISSUE THREAD

**Issue by fish-not-phish** [yogeshojha/rengine#959]
Found a bug? Please fill out the sections below. 👍 Please do not use this to raise any support requests, instead [join our discord channel #support](https://discord.gg/azv6fzhNCE) for support requests.

### Issue Summary

Rengine is using depreciated Selenium functions.

Within the IPToDomain function inside of the API application, the developer is utilizing methods called "find_elements_by_xpath" and "find_element_by_xpath". These methods were deprecated by Selenium and was replaced with:

find_elements("xpath", "path_needed")
find_element("xpath", "path_needed")

Because of this, the web application produces a 500 server error due to using non-existent Selenium methods. This API function still does not work (for unknown reasons to me), but I wanted to point out that these methods should be updated within the source code and this function should likely be reviewed. I tested in an isolated environment with the old depreciated methods "find_elements_by_xpath" and "find_element_by_xpath" and Selenium will not run. However, replacing it works when replaced with the newer methods.

### Steps to Reproduce

1. Add Targets
2. Specifically, add an IP or IP block
3. Submit
4. Server 500 error is returned

* I have confirmed that this issue can be reproduced as described on a latest version/pull of reNgine: Yes

### Technical details

Tested in a clean install of Kali as well as a clean install of Ubuntu.

I would be happy to troubleshoot this if I could be directed on how to produce logging output. The API does not appear to be an app in the INSTALLED_APPS, so I cannot make a logger for it within Django. How might I setup a logger or a form of output to troubleshoot this myself. All my attempts to add loggers resulted in crashing the application.

**Comment by psyray** [comment]
Check in v2 and open a new issue if it persists
This part has been completely rewritten
