### ISSUE TITLE
Default Credentia

### ISSUE THREAD

**Issue by d1pakda5** [yogeshojha/rengine#96]
Hi 
kindly provide or update in the readme the default credential for 1st time login.

**Comment by yogeshojha** [comment]
Hi @d1pakda5 

Did you clone the feature/customiseYamlScan branch?

If so, please consider cloning master branch only. I am yet to work on the yaml customisation branch.



If you are looking for /admin password then, you need to create for yourself

Here is how you can do,

docker exec -it rengine_web_1 python manage.py createsuperuser
