### ISSUE TITLE
feat: CSV Option in report export

### ISSUE THREAD

**Issue by Redteamer0101** [yogeshojha/rengine#967]
### Is there an existing feature or issue for this?

- [X] I have searched the existing issues

### Expected feature

Is there any way to export whole report in csv format? I have searched but only subdomains you can export as csv nothing apart of it. is there any option or can you add one? I think every one needs this feature while working in organization.

**Comment by AnonymousWP** [comment]
You apparently didn't even search for existing issues, because literally the previous issue is about that: https://github.com/yogeshojha/rengine/issues/966
