### ISSUE TITLE
Version 2.0 Naabu Scan Port Identification No Service

### ISSUE THREAD

**Issue by testoiubvtc** [yogeshojha/rengine#969]
Naabu Scan Port Identification No Service
![123123](https://github.com/yogeshojha/rengine/assets/100524176/b3fc9231-ab74-4cf5-a750-ea257262bb6a)

**Comment by AnonymousWP** [comment]
For me it's completely empty on the dashboard lol. Which page are you looking at?

![image](https://github.com/yogeshojha/rengine/assets/50231698/91bedc4c-9e35-4969-a9fe-a9ae00f38253)

**Comment by psyray** [comment]
Empty on Home Dashboard
But not on the Target & Scan findings dashboard.
I will investigate
![image](https://github.com/yogeshojha/rengine/assets/1230954/9961b1fc-6f05-4f6b-ab5e-231c9ebf9d9f)

**Comment by psyray** [comment]
Not naabu problem
More details on this new issue
https://github.com/yogeshojha/rengine/issues/1122
