### ISSUE TITLE
dir_file_fuzz error

### ISSUE THREAD

**Issue by LionYing** [yogeshojha/rengine#979]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I create a subdomain directory subscan, dir_file_fuzz will not be executed if the subdomain status is 404.

### Expected Behavior

When I create a subscan, the corresponding execution is initiated regardless of the domain name status.

### Steps To Reproduce

1. Scan the target domain name
2. Select the subdomain name with status 404 for dir_file_fuzz
3. The scan ends directly, and the log shows that there is no subdomain name to execute dir_file_fuzz.

### Environment

```markdown
- reNgine: 2.0.0
- OS: Linux
- Python: 
- Docker Engine: 20.10.14
- Docker Compose: v2.16.0
- Browser: Chrome
```

### Anything else?

None

**Comment by LionYing** [comment]
When the sub-scan finishes executing dir_file_fuzz, the background fuff process has ended, and the front-end scanning status is still in progress.

**Comment by AnonymousWP** [comment]
Why did you close this issue @LionYing?
