### ISSUE TITLE
Installation error 

### ISSUE THREAD

**Issue by ASHP-10** [yogeshojha/rengine#985]
### Is there an existing issue for this?

- [X] I have searched the existing issues

#########################################################################
Installing reNgine
#########################################################################
[+] Building 0.0s (0/0)
http: invalid Host header
make: *** [Makefile:16: certs] Error 17

### Expected Behavior

installation should go through. I am trying to setup in my vps.

### Steps To Reproduce

Just do normal install 
sudo  ./install.sh

### Environment

```markdown
- reNgine: v2.0.0
- OS: Ubuntu
- Python 3.10.12
- Docker version 20.10.24
```

**Comment by psyray** [comment]
Need more info.
Try to help yourself by following this ticket
https://github.com/docker/cli/issues/4437
