### ISSUE TITLE
Bug - HTTP Crawler No result

### ISSUE THREAD

**Issue by d1pakda5** [yogeshojha/rengine#99]
Found a bug? Please fill out the sections below. 👍

HTTP Crawler  not working

A summary of the issue.
I tried with 4-5 target but the HTTP Crawler result is zero always

### Steps to Reproduce

1. For a quick verification i created scan engine with Fetch All URLs only
2. scanned 4-5 targets
3. scan completed but no result 

<img width="928" alt="Screenshot_39" src="https://user-images.githubusercontent.com/17035598/88057161-49f06d80-cb7f-11ea-82e5-d30e6231723c.png">

**Comment by yogeshojha** [comment]
Oh Uh! this should not have been the case. Do you have logs? I can have a look at it.
